### ISSUE TITLE
Place verifier contract to `contracts` folder instead of `contract`

### ISSUE THREAD

**Issue by signorecello** [noir-lang/noir#1009]
### Problem

Hardhat tipically searches the folder `contracts` for contracts, but `nargo codegen-verifier` places the default verifier into a `contract` folder

### Proposed solution

The easiest solution would be to add this verifier contract to the `contracts` folder

### Alternatives considered

Using the `source` configuration param in hardhat, you can have it search for other folder. However, seems like we would want this to be consistent with the more common `contracts` naming

**Comment by kevaundray** [comment]
@TomAFrench Is it okay to call this folder `contracts` given that we changed the `contract` command?

**Comment by TomAFrench** [comment]
I have a couple of reservations about this:
- It assumes that the noir project will live in the same directory as the hardhat/foundry root. This is unlikely imo.
- The `contracts` package isn't a universal standard as foundry projects tend to use `src`.
- If we have verifiers which don't target smart contract languages then this doesn't make sense.

I'd prefer to add an `out` arg to the `codegen-verifier` which defines which directory to write the generated verifier. We can then have a very generic default directory (e.g. `verifier`) and then add a field in `Nargo.toml` for users to set up specify where they want it send by default:

```
[codegen-verifier]
out = "../hardhat_project/contracts/verifier`
```

**Comment by TomAFrench** [comment]
Marking this as a good first issue as it should be fairly achievable for without a ton of context on the internals of the Nargo/Noir. That said it's a feature of a pretty decent size.

**Comment by kevaundray** [comment]
@TomAFrench whats the status of this issue?
