### ISSUE TITLE
Add primitive oracle functions for aztec 3

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#1016]
### Problem

Currently the (WIP) aztec 3 abi encoding in noir relies on several oracle primitives to work, which are not yet implemented. Examples of these can be seen here:

- `get` function for notes: https://github.com/noir-lang/noir-aztec3/blob/main/src/set.nr#L46
- `rand` function for randomness: https://github.com/noir-lang/noir-aztec3/blob/main/src/note.nr#L15
- `get_secret_key`: https://github.com/noir-lang/noir-aztec3/blob/main/src/note.nr#L43

### Proposed solution

Ideally we add these functions or equivalent functionality into Noir. It seems that these features may likely require support within the compiler itself rather than being implemented via a separate library.

**Comment by kevaundray** [comment]
This is no longer relevant, so closing
