### ISSUE TITLE
Add a way to use storage slots within Noir code

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#1020]
### Problem

Once storage slots are added from #1018, users will need some way of accessing them to write libraries.

### Proposed solution

Add some builtin function to access the storage slot of a global.

This function should ideally still handle the case where the global is passed into another function as a parameter, which is then used as an argument for this new builtin function.

**Comment by kevaundray** [comment]
@jfecher Is this completed?

**Comment by jfecher** [comment]
@kevaundray we manually store storage slots in fields of globals right now so we don't need a builtin function to access them. I'm going to close this issue since it is unneeded and we can open a new one if our design changes.
