### ISSUE TITLE
Allow entry_point in WASM compile

### ISSUE THREAD

**Issue by kobyhallx** [noir-lang/noir#1025]
### Problem

As a Developer 
I would like to specify entry_point as a compilation option
so that the default noir-source-resolver could be used on NodeJS 

### Proposed solution

Allow entry_point parameter to compilation options.

### Alternatives considered

Relying on specifying source resolver each time allows resolving sources from different locations.

**Comment by jfecher** [comment]
We could also consider a `#[entry_point]` directive to specify this in the source code if applicable
