### ISSUE TITLE
Support oracle opcode when invoking circuits via nargo

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#1052]
### Problem

Circuits containing oracle opcodes are not compatible with either `nargo execute` or `nargo test`. Addressing this first requires us to decide on a minimal acceptable DX for providing answers to oracle calls.

### Proposed solution

Possibilities:
- Show a stdout prompt that awaits an oracle answer via stdin before continuing
- Log missing oracles answers, prompting the dev to fill them in via Prover.toml or some other file

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by sirasistant** [comment]
We'll try to implement this as a JSON-RPC resolver for oracles in nargo

**Comment by TomAFrench** [comment]
> JSON-RPC resolver for oracles

Can you go into some more detail on what you're picturing on this? I'm not sure its been written down anywhere since Istanbul. Is is just we allow nargo to point at some url at which we expect some process to be running which will handle all of these?

**Comment by sirasistant** [comment]
The idea is that nargo execute and nargo test have an optional parameter that is a resolver URL. This is propagated to the foreign call resolver, so when a foreign call is issued that nargo doesn't know about, if the resolver URL was passed it'll use it to fetch the foreign call results (passing the foreign call parameters). We also evaluated gRPC but it's less suitable for our use case!

**Comment by sirasistant** [comment]
I'll start working in this direction tomorrow
