### ISSUE TITLE
Oracles invoked even when on the "untrodden" execution path

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#1055]
### Aim

Prevent unwanted side effects when oracle opcodes are used in conjunction with if statements.

### Expected behavior

Oracle callbacks shouldn't be invoked when they occur within an "untrodden" path.

### Bug

The currently representation on the oracle opcode doesn't handle predicates.

```
#[oracle(foo)]
fn foo(_x: Field) -> Field {}

fn main(cond : bool, input: Field) -> pub Field {
    if (cond) {
        foo(input)
    } else {
        42
    }
}
```

In the above example, callback `foo` would be invoked regardless of whether `cond` is `true` of `false`. Worse, it is not possible for developer to infer the validity of the argument give to `foo`.

### To reproduce

1. Theoretical: Attempt to solve an intermediate witness for the above sample

### Installation method

None

### Additional context

Note that the above still be an issue once oracles have been wrapped in the unconstrained VM. The unwanted side effects would just be performed by the VM instead.

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kevaundray** [comment]
Closing as oracles have changed behavior since when the issue was opened and now we have a predicate that gets passed to Brillig
