### ISSUE TITLE
Oracle JS integration testing rig

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#1060]
### Problem

We currently have no facility for performing integration tests via JS. An example of a test that particularly benefits from being executed in JS is oracle callbacks. The result of an orcale depends on its inputs, and thus no need a scriptable testing environment for defining/customising how an oracle output is calculated.

### Proposed solution

Add an JS integration testing rig to whether the spiritual successor to noir_wasm is going to live.

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by joss-aztec** [comment]
And example circuit with oracles for testing:

```
#[oracle(foo)]
fn foo(_x: Field) -> Field {}

fn main(cond : bool, input: Field) -> pub Field {
    if (cond) {
        foo(input)
    } else {
        42
    }
}
```

The above should be tested with both `cond` equal to `true` then `false` such that we can check that the oracle callback is invoked conditionally.

**Comment by kevaundray** [comment]
@joss-aztec pinging on this, we now have acvm-simulator [here](https://github.com/TomAFrench/acvm-simulator/tree/master/src) please work on getting oracle support onto Noir master

**Comment by kevaundray** [comment]
Closing as not planned, we now use acvm-simulator
