### ISSUE TITLE
Installing from source

### ISSUE THREAD

**Issue by Ethan-000** [noir-lang/noir#1072]
### Aim

Due to https://github.com/noir-lang/noir/pull/1065, I think `nargo` now needs to be installed with 

`cargo install --locked --path=crates/nargo_cli`

maybe consider modify it to allow 

`cargo install --locked --path=crates/nargo`

or update the book

### Expected behavior

install nargo with

`cargo install --locked --path=crates/nargo`

### Bug

same as above

### To reproduce

1.
2.
3.
4.

### Installation method

None

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by Globallager** [comment]
Should probably be an `noirup` Issue rather than Book Issue? Wdyt @TomAFrench

**Comment by phated** [comment]
Book is updated and noirup works with any version
