### ISSUE TITLE
setup_generic_prover_and_verifier fails with an error

### ISSUE THREAD

**Issue by wighawag** [noir-lang/noir#1076]
### Aim

To test noir in js/ts

### Expected behavior

TO be able to compile, generate proofs and verify all in js

### Bug

```
getting acir...
setup prover/verifier pair...
panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `gates`", line: 1, column: 1351)', src/lib.rs:81:28

Stack:

Error
    at module.exports.__wbg_new_693216e109162396 (/home/wighawag/dev/github/bug-reproduction/noir-test/node_modules/.pnpm/@noir-lang+aztec_backend@0.11.0/node_modules/@noir-lang/aztec_backend/aztec_backend.js:443:17)
    at wasm://wasm/01424da6:wasm-function[519]:0xba204
    at wasm://wasm/01424da6:wasm-function[1543]:0xe00b0
    at wasm://wasm/01424da6:wasm-function[887]:0xd4761
    at wasm://wasm/01424da6:wasm-function[943]:0xd6d7d
    at wasm://wasm/01424da6:wasm-function[1306]:0xdec21
    at wasm://wasm/01424da6:wasm-function[1135]:0xdc0dd
    at wasm://wasm/01424da6:wasm-function[1252]:0xde1a8
    at wasm://wasm/01424da6:wasm-function[986]:0xd8580
    at wasm://wasm/01424da6:wasm-function[209]:0x8568d


wasm://wasm/01424da6:1


RuntimeError: unreachable
    at wasm://wasm/01424da6:wasm-function[887]:0xd479b
    at wasm://wasm/01424da6:wasm-function[943]:0xd6d7d
    at wasm://wasm/01424da6:wasm-function[1306]:0xdec21
    at wasm://wasm/01424da6:wasm-function[1135]:0xdc0dd
    at wasm://wasm/01424da6:wasm-function[1252]:0xde1a8
    at wasm://wasm/01424da6:wasm-function[986]:0xd8580
    at wasm://wasm/01424da6:wasm-function[209]:0x8568d
    at wasm://wasm/01424da6:wasm-function[1028]:0xd97c0
    at module.exports.serialise_acir_to_barrtenberg_circuit (/home/wighawag/dev/github/bug-reproduction/noir-test/node_modules/.pnpm/@noir-lang+aztec_backend@0.11.0/node_modules/@noir-lang/aztec_backend/aztec_backend.js:308:14)
    at setup_generic_prover_and_verifier (/home/wighawag/dev/github/bug-reproduction/noir-test/node_modules/.pnpm/@noir-lang+barretenberg@2.19.0/node_modules/@noir-lang/barretenberg/src/client_proofs/generic_proof/index.ts:29:30)
```

### To reproduce

(see repo : https://github.com/bug-reproduction/noir-test)

1. execute the following

```
git clone git@github.com:bug-reproduction/noir-test.git
cd noir-test
pnpm i
nargo compile circuit 
pnpm test
```

2. see error

Note that compiling in js is commented out because it fails too

### Installation method

Binary

### Nargo version

nargo 0.3.2 (git version hash: 91bd47190402f0fe567dbfb6fcfa17b97c129905, is dirty: false)

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by signorecello** [comment]
Hey @wighawag I believe this is due to a known issue with some `npm` packages being outdated. Also, I believe using the latest packages, the typescript usage is different as it allows for compilation and, generally, doing the whole workflow in TS altogether. Refer to the [zCaptcha](https://github.com/signorecello/zcaptcha) example, which should be OK for a starter

Also check the new docs as they are updated with the latest typescript usage

**Comment by wighawag** [comment]
Hey @signorecello I was using the latest doc and I think I found what cause the problem

it seems some of the library do not support the `pnpm` package manager

when I use npm it seems to work

so I guess it is related to file path (where pnpm differs from npm) might be worth checking to not make assumption on location of node_modules, especially if we are in a monorepo setup

**Comment by kevaundray** [comment]
@signorecello can this be closed?

**Comment by kevaundray** [comment]
Since this pertains to proving in the browser, I'll tentatively close as the status of this has changed drastically since when the issue was opened

**Comment by signorecello** [comment]
Sorry I didn’t see your message. Yes this is terribly outdated
