### ISSUE TITLE
Add a test to check that a program is in SSA form

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1078]
### Problem

Currently there is no test to check that our programs are correctly in SSA form

### Proposed solution

Add a test to check that our functions are in SSA form

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kevaundray** [comment]
@jfecher and @guipublic can you review whether we should keep this issue open? It was originally meant for the old SSA, but might also be useful for the new.

If so, then it will be assigned to @guipublic

**Comment by jfecher** [comment]
@kevaundray I think we can close it. It is a bit vague but mostly covered by the various unit tests in the new ssa. The mem2reg tests may be closest to what we desired in this issue. We can also add more tests as they make sense later.
