### ISSUE TITLE
Add convenience structure for sparse merkle trees

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1080]
### Problem

We currently have a method for checking membership, however it is not intuitive as to how one would check for non-membership using it. 

**More details:**

A merkle tree is mainly used for set membership proofs. So with it i will be able to tell you if an element x was a part of a set in an efficient way within circuits.

For example, if your set is `S = {1,2,3,4}`  and `x=5` then `check_membership(S, x)` would return false.

If `x=2` then `check_membership(S, x)`  would return true.

**Regular merkle tree**

A regular merkle tree is allowed to have a set that looks like this `SA = {200,8,1,1,2,3,4,5,6,7,8,8,8,8,}`

Notice that there are duplicates. This is called an append-only merkle tree, because you can just keep on adding any element you want into the tree. More importantly, notice that an element does not have a "rightful place" in the set.

If I do `check_membership(SA, 1)` this will return true though there are multiple values of 1 in SA so I could reference any one.

**Non-membership**

Since each element does not have a "rightful place" and duplicates are allowed, I cannot prove that an element is not in the set, without looking at every element in the set. This is very in-efficient, and grows with the number of elements in the set.

**Sparse merkle tree**

The set for a sparse merkle tree on the other hand will look like this: `SS = {1, empty_2, 3, empty_4, empty_5, empty_6, empty_7, 8}`
I can also do `check_membership(SS, 1)` and this will return true, but there is only one place that the number 1  can be in. This is just a property of a sparse merkle tree data structure, Hence there are no other 1's  in this set since that is how we have chosen to insert data in the underlying database.

I can additionally prove that an element is not in the set quite easily. Lets say I want to show that the number 2 is not in the set. I just need to do  `check_membership(SS, empty_2)` . If that spot is empty, then I know that 2 is not in the set because the underlying data structure will not insert 2  in any other place.

**Noir**

Notice that in Noir, we don't have a separate function for each of these trees. We still only use check_membership . The catch here is that we need to know what the default value is when something is not in the set. Its usually 0 but in the proposed solution, the user can set it to whatever value they see fit.

### Proposed solution

Using pseudo-code I propose we make a struct:

```rust
struct SparseMerkleTree {
 default_value : Field,
}

impl SparseMerkleTree {
 fn update(self) {}
 fn delete(self) {}
 fn insert(self) {}
}
```

### Additional context

I think we can have a helper standalone update method in the stdlib that gives a merkle update proof.

This would shows that some value `v1` was in the tree with root `R1` , then when I update `v1` to `v2` , the root becomes `R2`

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kevaundray** [comment]
@signorecello noted that the same can be done for AppendOnly merkle trees and other high level structs

**Comment by joss-aztec** [comment]
What's the use case for `SparseMerkleTree::update`? Doesn't `delete`/`insert` already cover it? The usage of sparse trees that I'm familiar with is to take a nullifer as a leaf index, and then a leaf takes one of two values to represent included or not included. Are you suggesting that we should also allow for leaves to take on arbitrary values?

**Comment by joss-aztec** [comment]
I perhaps you simply meant for `update` to select between `delete`/`insert`?

**Comment by joss-aztec** [comment]
@kevaundray, I've implemented a first pass. Needs testing etc. Just wanted to check it's along the lines that you were expecting. Tbh, I don't think this helper does a whole lot to take the burden of managing trees off the developer. They still need to calculate roots and hash paths. Do we perhaps want to add a typescript helper for computing these things?

**Comment by kevaundray** [comment]
The implementation of this will no longer live in the Noir repository and instead will live in some external repo
