### ISSUE TITLE
`noir_wasm` expects padded hex number, but js/ts doesn't work that way

### ISSUE THREAD

**Issue by signorecello** [noir-lang/noir#1083]
### Aim

Tried to pass a single digit to `noir_wasm`, like "1" or "2" using typescript.

### Expected behavior

Expected the proof to be generated as usual.

### Bug

If I pass a number in typescript, it won't be padded with a leading 0. For example:

```js
const i = 1;
i.toString(16) // returns "1", not "01"
```

However, `noir_wasm` apparently expects a number to be padded with 0, probably because it's reading bytes and expects a full byte

### To reproduce

1. Compile a circuit that expects a number in its input (like constrain x == y where x and y are u8)
2. Pass a single digit hex number in typescript (example `create_proof(acir, abi, { x = "1", y = "2" }`
3. Get the error "expected hex string" even though you passed a hex string

A workaround is to pad the hex number with leading zeros, [example](https://github.com/signorecello/noir-starter/blob/0c90df129f40161f3e28f746be79df63d7fa940d/utils/prover.ts#L12)

### Installation method

None

### @noir-lang/noir_wasm version

0.3.2-bcdfd526

### @noir-lang/barretenberg version

github:noir-lang/barretenberg#39a1547875f941ef6640217a42d8f34972425c97

### @noir-lang/aztec_backend version

^0.1.0-0c3b2f2

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by TomAFrench** [comment]
This is common behaviour in a lot of hex libraries so we're unlikely going to accept odd-length hex strings, I think the best solution is to ensure padding in TS.

**Comment by TomAFrench** [comment]
Closing as expected behaviour
