### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by iAmMichaelConnor** [noir-lang/noir#1089]
### Aim

<img width="292" alt="image" src="https://user-images.githubusercontent.com/42943676/229607372-486178b7-5dc1-427e-a424-675938193ec2.png">

(Separately, we should probably add a category of issue to the options which isn't 'bug' or 'new feature', but is 'boring doc change', because this isn't a real bug)

### Expected behavior

I expect the link to work.

### Bug

404 error

### To reproduce

1. Click the link
2.
3.
4.

### Installation method

None

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kevaundray** [comment]
Thanks for opening this up! 

PR #1090 now points the user to https://noir-lang.org/nargo/nargo_installation/

>(Separately, we should probably add a category of issue to the options which isn't 'bug' or 'new feature', but is 'boring doc change', because this isn't a real bug)

I'd class this as a bug :)

**Comment by iAmMichaelConnor** [comment]
@kevaundray this link's broken again :)
