### ISSUE TITLE
[Nargo] Usable Foreign / UltraPlonk Keccak256

### ISSUE THREAD

**Issue by Globallager** [noir-lang/noir#1096]
Tracking issue for exposing the foreign Keccak256 implementation within proving backend (UltraPlonk barretenberg as first target) in Nargo.

```[tasklist]
### Tasklist
- [ ] https://github.com/noir-lang/acvm/issues/90
- [ ] https://github.com/noir-lang/noir/issues/991
- [ ] https://github.com/noir-lang/noir/issues/1189
```

**Comment by TomAFrench** [comment]
We already have a [keccak256 opcode](https://github.com/noir-lang/acvm/blob/4360d6c3c587b1403d459423b9e73471bd208044/acir/src/circuit/black_box_functions.rs#L24) in ACIR.

One thing we're missing however afaict is a stdlib function to call keccak256 in order to use this opcode

**Comment by kevaundray** [comment]
> We already have a [keccak256 opcode](https://github.com/noir-lang/acvm/blob/4360d6c3c587b1403d459423b9e73471bd208044/acir/src/circuit/black_box_functions.rs#L24) in ACIR.
> 
> 
> 
> One thing we're missing however afaict is a stdlib function to call keccak256 in order to use this opcode

That's correct -- the compiler won't process the keccak opcode so that also needs to be fixed

**Comment by Globallager** [comment]
From @vezenovm on Slack re how the function signature could look like:

> I think there were some efficiency benefits to using a `[u64]` however a byte slice is more intuitive and perhaps we can add helper methods to convert between different array types
