### ISSUE TITLE
Pseudo-randomness

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#1099]
This is non-trivial as it requires quite a few changes on the backend/proving system. This can have a pronounced effect on Noir usage but not sure we have the resources to justify pursuing it right now.

[Generating secure randomness on Ethereum using SNARKs | Paradigm](https://www.paradigm.xyz/2023/01/eth-rng#block-hash-oracle-contract-via-snarks)

**Comment by kevaundray** [comment]
Closing this as it requires quite a bit of work from the backend to enable it -- we ca re-open in the future if a backend supports it
