### ISSUE TITLE
Remove all Unstructured error types for fixed variants

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#11]

**Comment by kevaundray** [comment]
Blocked by #87

**Comment by kevaundray** [comment]
Leaving this open until we can check that it has been checked

**Comment by kevaundray** [comment]
@f01dab1e heres a good issue to take on!

**Comment by f01dab1e** [comment]
can this be closed?

**Comment by jfecher** [comment]
@f01dab1e I can't find any more cases of `Unstructured` so I'd say yes. Thanks for the PRs!
