### ISSUE TITLE
Add EdDSA verification to standard library

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1109]
### Problem

Signature verification is an important building block for many protocols. The most popular in this domain being EcDSA. One problem with EcDSA is that it is not deterministic and so it is not suitable for usecases where one would want to use the signature as a nullifier.

### Proposed solution

EdDSA is a suitable alternative for this, moreover it is the alternative is the circomlib that many folks who are using circom will default to.

A link to EdDSA is here: https://github.com/iden3/circomlib/blob/master/circuits/eddsaposeidon.circom

Since we already have poseidon and Twisted edwards curve logic in our stdlib, we can implement the above by composing those two algorithms like in the circom library.

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by joss-aztec** [comment]
So if I understand, any group element in this expression should be multiplied by 8 to map it into the sub group. Why isn't the pub key also multiplied by 8 before it is hashed?

**Comment by kevaundray** [comment]
> So if I understand, any group element in this expression should be multiplied by 8 to map it into the sub group. Why isn't the pub key also multiplied by 8 before it is hashed?

The rationale should be in the [specs](https://www.rfc-editor.org/rfc/rfc8032#section-5.1.7) -- For now, lets just re-implement this in Noir so that it is interopable.

**Comment by joss-aztec** [comment]
This work is being parked due to the following blockers:

- The circuit is huge
  - A single stdlib ec mul currently costs 240K constraints (two muls are required)
  - Our solution needs to be ~24K
- We still need a working solution for checking the signature is less than subgroup order
  - Calling `x.to_le_bytes(32)` hits the compiler error:
  
```
The application panicked (crashed).
Message:  assertion failed: max < FieldElement::modulus()
Location: crates/noirc_evaluator/src/ssa/acir_gen/constraints.rs:414
```

**Comment by joss-aztec** [comment]
Broken impl for reference: https://github.com/noir-lang/noir/pull/1136

**Comment by shuklaayush** [comment]
I was able to reduce the circuit size of a single ec mul to 20k by using the builtin `to_bits` functions. 
Here are the changes:
https://github.com/noir-lang/noir/compare/master...shuklaayush:noir:fix/eddsa

Also fixed some bugs along the way in the `to_bits` and `to_bytes` opcodes to make everything work properly (see https://github.com/noir-lang/noir/compare/master...shuklaayush:noir:fix/to-bits)

Let me know what's the best way to get this merged. Should I just open a PR?
