### ISSUE TITLE
Upgrade acvm to v0.9.0

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1115]
### Problem

Version 0.9 of acvm has been released here: https://github.com/noir-lang/acvm/pull/182

### Proposed solution

Upgrade to v0.9 

This is blocked by backends being updated to v0.9. See https://github.com/noir-lang/aztec_backend/issues/104

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by phated** [comment]
This has to happen with UP so I'm assigning to me.
