### ISSUE TITLE
Add dominator Tree 

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1116]
### Problem

Dominator trees store the dominance relation between basic blocks in a function.

A dominance tree allows us to quickly compute:

- The dominance frontier
- Immediate dominators for a node

The dominator tree is very useful in figuring out which nodes are not dominated by the entry block and for example, can be used for reachability analysis.

### Proposed solution

Implement a dominator tree in a modular way with comments and tests 

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by guipublic** [comment]
For the record, we already have the dominator tree implemented in the BasicBlock structure where blocks reference their direct dominator.
