### ISSUE TITLE
Add mapping data structures

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1118]
### Problem

A common strategy that wil be present in our SSA module is:

```rust
pub struct Data;

pub struct DataId
```

Where data gets stored in some Arena/Map and the `DataId` is the reference to get the `Data` from the Arena/Map.

### Proposed solution

Implement a common data structure to abstract away this information. Cranelift uses PrimaryMap and SecondaryMap.

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kevaundray** [comment]
One can look at the Cranelift datastructures to figure out what the API should look like. An alternative is to use petgraph

**Comment by guipublic** [comment]
For the record this is exactly the strategy we already have in the SSA module where data is stored in an Arena and referenced by its id being the index of the arena.
