### ISSUE TITLE
Build dependency graph between variables in name resolution

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#1122]
### Aim

Trying to write a program
```rs
struct ShouldError {
    uses_nested_arrays: [Array; 2],
}

struct Array {
    array: [Field; 3],
}
```

### Expected behavior

Noir should issue an error that nested arrays are currently unimplemented

### Bug

The error is only issued sometimes when the program is compiled. This is because on some runs `Array` is resolved first and when `ShouldError` is subsequently resolved, it can see all the fields of `Array` and will error that nested arrays are used. On other runs however, `ShouldError` is resolved first and sees only an empty struct for `Array` and thus does not issue an error. In this case, the program continues until monomorphization where it fails with an unreachable assert.

### To reproduce

1.
2.
3.
4.

### Installation method

None

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kevaundray** [comment]
@jfecher what is the status of this issue?

**Comment by kevaundray** [comment]
Lowest hanging fruit to attempt to fix would be replacing suspicious usages of hashmap with something like indexmap

**Comment by kevaundray** [comment]
@jfecher - "The above is not enough, we would need a dependency tree of structures, we could also use this in places where globals depend on other globals"

**Comment by kevaundray** [comment]
Spoke with Jake; he says, ideally name resolution is split into smaller components and we build this dependency tree at the last step to be used in later passes.

**Comment by jfecher** [comment]
Can we re-tag this E-HIGH? I think it'd require a large rewrite of name resolution to first create the graph then follow its nodes to resolve names in that order.

**Comment by Savio-Sou** [comment]
> precise difference is between Large and X-Large

Choice is all good as long as it feels right. The Size field is used just as a subjective reference for now.
