### ISSUE TITLE
Move tests from nargo/test/test_data to nargo_cli

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1124]
### Problem

Tests were moved to nargo_cli, however there are two poseidon tests in the nargo/tests

### Proposed solution

Move tests to nargo_cli/tests

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by phated** [comment]
I done this in #1114 because I wanted to make sure **all** tests were passing. Note that the directory structure might exist on your computer if you've cloned the project before because the Verifier.toml files are gitignored.

**Comment by kevaundray** [comment]
The poseidon tests are not passing -- they seemed like they were before because we moved tests to nargo_cli and they stopped running since they were located in nargo/test_data

**Comment by phated** [comment]
Due to the above ☝️ I've backed out the changes in 1114 as this will need to be a bigger fix.

**Comment by joss-aztec** [comment]
In the case of the test `poseidonperm_x5_254`, it's the usage of `pow_32` in `permute` that results in barretenberg emitting the `linear_eval is not 0.` error that's been seen on other broken proofs issues:
#1134
#1045
