### ISSUE TITLE
Add ABI functionality

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#113]
Add ABI functionality to tell the witness generator, how to generate the witnesses, including witnesses that involve state

**Comment by kevaundray** [comment]
A part of this involves removing explicit hashpaths and allowing them to be inferred from some stateful component

**Comment by kevaundray** [comment]
One idea is to make the partial witness generator stateful, it would be initialised with a set of merkle trees and using the root and index, we can fetch the merkle path that is needed

**Comment by TomAFrench** [comment]
This seems to be targetting something different from our current ABI but I'd wager it's moot at this point so I'm going to close this issue.
