### ISSUE TITLE
merkle proof error: linear_eval is not 0.

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#1134]
### Aim

Successful merkle inclusion proof on a constructed root. This bug blocks https://github.com/noir-lang/noir/pull/1108.

### Expected behavior

Produces a valid proof

### Bug

The follow circuit produces a proof that can't verified, and logs an error from barretenberg while proving:
```
linear_eval is not 0.
```
(Also seen on #1045)

```rs
use dep::std;
use dep::std::hash;
use dep::std::merkle;

fn main(
    leaf_index: Field,
) -> pub Field {
    let default_value = 0xdead;
    let hash_low = hash::pedersen([default_value, default_value])[0];
    let hash_mid = hash::pedersen([hash_low, hash_low])[0];
    let hash_high = hash::pedersen([hash_mid, hash_mid])[0];
    let empty_root = hash::pedersen([hash_high, hash_high])[0];
    // let empty_root = 1982756624023369989027739444041418271699168211804446939220881676795116478748;
    // Possible clue: if you swap the above empty_root definitions to use the
    // hardcoded version, the circuit doesn't even make it as far as failing to
    // prove and instead hits a compiler error:
    //   The application panicked (crashed).
    //   Message:  invalid input
    //   Location: crates/noirc_evaluator/src/ssa/acir_gen/operations/intrinsics.rs:184

    let hash_path = [default_value, hash_low, hash_mid, hash_high];

    constrain merkle::check_membership(
        empty_root,
        default_value,
        leaf_index,
        hash_path,
    ) == 1;
    empty_root
}
```

### To reproduce

1. `nargo prove` the above circuit

### Installation method

Compiled from source

### Nargo version

nargo 0.3.2 (git version hash: 41e00207b0eeae4d0285c617acac72c780cb0900, is dirty: true)

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by Globallager** [comment]
(Possibly will disappear after UltraPlonk integration, to be revisited then.)

**Comment by kevaundray** [comment]
The error itself did indeed disappear, but we are getting verified false

**Comment by kevaundray** [comment]
Tracking issue : https://github.com/noir-lang/noir/issues/1252

**Comment by TomAFrench** [comment]
Opened an issue for compiler error in #1345
