### ISSUE TITLE
Nargo crashes upon compilation of circuit with certain size

### ISSUE THREAD

**Issue by Philogy** [noir-lang/noir#1137]
### Aim

Compile a Noir circuit.

### Expected behavior

I expected the compiler to take a while and then successfully finish compiling. `nargo check` and `nargo gates` both execute successfully but `nargo compile main` and `nargo codegen-verifier` both fail.

### Bug

When I try to compile my code with `nargo compile main` or `nargo codegen-verifier` it fails with the following error:
```
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: RuntimeError { source: Trap(UnreachableCodeReached), wasm_trace: [], native_trace:    0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
 }
Location: /Users/runner/.cargo/git/checkouts/aztec_backend-a697fb631cbad807/2cb523d/barretenberg_wasm/src/lib.rs:93

This is a bug. Consider opening an issue at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml
```

The code I tried to compile is the following:
```noir
use dep::smt;

global TX_SIZE: Field = 4;

fn main(
  start_null_root: pub Field,
  nullifiers: pub [Field; TX_SIZE],
  // Use multiple arrays as arrays-of-arrays not supported in Noir yet :'(
  null_proof0: [Field; smt::SMT_SIZE],
  null_proof1: [Field; smt::SMT_SIZE],
  null_proof2: [Field; smt::SMT_SIZE],
  null_proof3: [Field; smt::SMT_SIZE]
) -> pub Field {
  let mut null_root: Field = start_null_root;
  null_root = smt::insert(null_root, nullifiers[0], null_proof0);
  null_root = smt::insert(null_root, nullifiers[1], null_proof1);
  null_root = smt::insert(null_root, nullifiers[2], null_proof2);
  null_root = smt::insert(null_root, nullifiers[3], null_proof3);
  null_root
}
```

You can find the sparse-merkle-tree library (`smt`) that I'm using [here](https://github.com/philogy/noir-smt). It's included in the project with the following `Nargo.toml` file:

```toml
[package]
authors = [""]
compiler_version = "0.1"

[dependencies]
smt = { tag = "main", git = "https://github.com/philogy/noir-smt" }
```

### To reproduce

1. Create project with `nargo new project-name`
2. Insert above code in a `main.nr` file
3. Run `nargo check` to ensure syntax is correct
4. Attempt compilation with `nargo compile main`

### Installation method

Binary

### Nargo version

nargo 0.3.2 (git version hash: 29b1f7df4d563849a62e64c533cb62932188135b, is dirty: false)

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by Globallager** [comment]
What's the constraint count you're getting when you run `nargo gates`?

Nargo binaries are WASM-based, hence they're limited with maximum constraint counts per WASM's 4GB memory limit.

For v0.3.2 (i.e. TurboPlonk-based), that should be around 2^18 = 262k constraints based on our [preliminary benchmarks](https://hackmd.io/SqzBl5bWTqGMZmI6o8qIGg?view#Constraint-Count-Benchmarks).

To work with large Noir programs, highly recommend compiling Nargo and backend fully from source (i.e. [Option 2.2 on docs](https://noir-lang.org/getting_started/nargo_installation#option-22-install-executable-with-native-backend)) instead to free yourself from WASM's limits.

**Comment by kevaundray** [comment]
@Ethan-000 can you check the status of this issue?

**Comment by kevaundray** [comment]
Assigning myself as I cannot assign Ethan for some reason

**Comment by kevaundray** [comment]
> hello sir @Philogy 🙂
> 
> do u mind providing the `Prover.toml` file you are using as well

I think since this was not related to the input, we can just out random values here and see if it still fails

**Comment by kevaundray** [comment]
Spoke with Ethan and since its a barretenberg issue, we are closing it. Barretenberg is currently being worked on such that we no longer rely on WASM for native proving, for web we will still need WASM, however in that case barretenberg should give better errors specifying that the memory consumption is too high for particular circuit sizes
