### ISSUE TITLE
Add foreign function for recursion

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1154]
### Problem

Once [recurson is added to acvm](https://github.com/noir-lang/acvm/issues/198) we would want a way to support this feature for users.

### Proposed solution

As usual, we can add a foreign function which will handle this, the proposed function signature is as follows:

```rust
#[foreign(recursion)]
fn verify_proof(proof : [u8], verification_key : [u8], public_inputs : [u8]) -> bool;
```

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by vezenovm** [comment]
As per the discussion in https://github.com/noir-lang/acvm/issues/198 the function signature will be changed to take in an input aggregation object and an output aggregation object:

```
#[foreign(verify_proof)]
fn verify_proof(_verification_key : [Field], _proof : [Field], _public_input : Field, _input_aggregation_object : [Field]) -> [Field] {}
```

**Comment by Savio-Sou** [comment]
Closed by https://github.com/noir-lang/noir/pull/1594

Keyword in stdlib: https://github.com/noir-lang/noir/blob/master/noir_stdlib/src/lib.nr#L19-L20
