### ISSUE TITLE
Add integration test for contract artifact output

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#1159]
The PR #1126 resulted in a regression due to insufficient testing on the contract artifacts being saved to disk. This was fixed in https://github.com/noir-lang/noir/pull/1158 but it was brought up that:

> I wonder if we can have PR artifacts that show what the ABI looks like, or possibly some ABI artifact that gets checked in and the CI checks if they match

_Originally posted by @kevaundray in https://github.com/noir-lang/noir/issues/1158#issuecomment-1511295759_

We should add an integration test which checks the build artifacts from a set Noir project against some checked in examples in order to avoid this happening in future.

**Comment by ameya-deshmukh** [comment]
Would love to take this up @TomAFrench!
