### ISSUE TITLE
Incorrect TOML for arrays in Prover

### ISSUE THREAD

**Issue by SleepingShell** [noir-lang/noir#1173]
### Aim

Correct TOML should be generated in the Prover.toml file when ``nargo check`` is ran.

### Expected behavior

Correct TOML should be generated in the Prover.toml file for arrays. Currently, the output is ``"[]"``, whereas it should be ``[""]``.

### Bug

Simply define an array input into main.

Example:

```rust
use dep::std;
fn main(root : pub Field, leaf : Field, index : Field, hash_path: [Field; 1]) {
    constrain std::merkle::check_membership(root, leaf, index, hash_path) == 1;
}
```

Prover.toml:
```
hash_path = "[]"
index = ""
leaf = ""
root = ""
```

### To reproduce

1. Use the above code, or other code that specifies an array input.
2. Run ``nargo check``
3. See Prover.toml 

### Installation method

Binary

### Nargo version

nargo 0.3.2 (git version hash: 29b1f7df4d563849a62e64c533cb62932188135b, is dirty: false)

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by TomAFrench** [comment]
Hey @SleepingShell,  this is addressed in https://github.com/noir-lang/noir/pull/1104. If you update to v0.4.0 then you'll have this behaviour.
