### ISSUE TITLE
@noir-lang library not compiling v0.4.0-compatible circuits 

### ISSUE THREAD

**Issue by glethuillier** [noir-lang/noir#1175]
### Aim

The Noir TypeScript library is expected to be able to compile circuits that are compatible with v0.4.0, similar to the functionality of the CLI tool `nargo`.

### Expected behavior

[This contract](https://github.com/pierg/noir_zkp/tree/main) can be compiled with `nargo` `0.4.0`.

It should also be compilable with the latest `@noir-lang` library version.

```
const { compile } = require("@noir-lang/noir_wasm");
. . .
try {
  compile(circuitPath);
} catch (e) {
  console.trace(e);
}
. . .
```

### Bug

The contract, compilable with `nargo` `0.4.0`, is not compilable with the latest `@noir-lang` library version. 

The program that uses this library returns the following exception: 

```
Trace: RuntimeError: unreachable
    at wasm://wasm/00a338b6:wasm-function[2495]:0x272def
    at wasm://wasm/00a338b6:wasm-function[1514]:0x259c66
    at wasm://wasm/00a338b6:wasm-function[1732]:0x265732
    at wasm://wasm/00a338b6:wasm-function[450]:0x1b303b
    at wasm://wasm/00a338b6:wasm-function[1671]:0x2626b4
    at wasm://wasm/00a338b6:wasm-function[1212]:0x241d6e
    at module.exports.compile (.../node_modules/.pnpm/@noir-lang+noir_wasm@0.10.0/node_modules/@noir-lang/noir_wasm/noir_wasm.js:123:22)
```

It should be noted that this program successfully compiles other contracts. Also, `nargo` `0.3.2` cannot compile this contract (see below for additional context).

Additionally, I ran the `pnpm update` command to get the most recent version of the library.

### To reproduce

1. `git clone git@github.com:pierg/noir_zkp.git && cd circuits/simple`
2. (Using `nargo` `>= 0.4.0`) `nargo prove p` _(no error)_
3. Programmatically try to generate the contract using `@noir-lang/noir_wasm` `^0.10.0` _(RuntimeError: unreachable)_

### Installation method

Binary

### Nargo version

nargo 0.4.0 (git version hash: a4b196a248fdef9e80bf8c0551d83b1cf23c4a39, is dirty: false)

### @noir-lang/noir_wasm version

0.10.0

### @noir-lang/barretenberg version

2.19.0

### @noir-lang/aztec_backend version

N/A

### Additional context

Using `nargo` `0.3.2`, the compilation of this contract fails:

```
$ nargo prove p
error: Expected a literal but found [
  ┌─ /Users/guillaume/. . . /circuits/simple/src/data.nr:2:28
  │
2 │ global D1_SHAPE: [u8; 2] = [2, 1];
  │                            -

error: Expected a ; but found ,
  ┌─ /Users/guillaume/. . . /circuits/simple/src/data.nr:2:30
  │
2 │ global D1_SHAPE: [u8; 2] = [2, 1];
  │                              -

error: Unexpected ,, expected one of contract, fn, impl, mod, struct, use, attribute, global
  ┌─ /Users/guillaume/. . . /circuits/simple/src/data.nr:2:30
  │
2 │ global D1_SHAPE: [u8; 2] = [2, 1];
  │                              -

error: Expected a literal but found [
  ┌─ /Users/guillaume/. . . /circuits/simple/src/data.nr:5:28
  │
5 │ global D2_SHAPE: [u8; 2] = [2, 1];
  │                            -

error: Expected a ; but found ,
  ┌─ /Users/guillaume/. . . /circuits/simple/src/data.nr:5:30
  │
5 │ global D2_SHAPE: [u8; 2] = [2, 1];
  │                              -

error: Unexpected ,, expected one of contract, fn, impl, mod, struct, use, attribute, global
  ┌─ /Users/guillaume/. . . /circuits/simple/src/data.nr:5:30
  │
5 │ global D2_SHAPE: [u8; 2] = [2, 1];
  │                              -

error: Expected type [u8; 2], found type Field
  ┌─ /Users/guillaume/. . . /circuits/simple/src/data.nr:2:29
  │
2 │ global D1_SHAPE: [u8; 2] = [2, 1];
  │                             -

error: Expected type [u8; 2], found type Field
  ┌─ /Users/guillaume/. . . /circuits/simple/src/data.nr:5:29
  │
5 │ global D2_SHAPE: [u8; 2] = [2, 1];
  │                             -

error: aborting due to 8 previous errors
Error: Failed to compile circuit

Location:
    crates/nargo/src/cli/mod.rs:64:5
```

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kevaundray** [comment]
Closing as the library has changed since 0.4. 

If this issue persists then feel free to re-open this issue
