### ISSUE TITLE
Create Foreign Keccak256 Function

### ISSUE THREAD

**Issue by Globallager** [noir-lang/noir#1189]
### Problem

We [already have the Keccak256 opcode in ACVM](https://github.com/noir-lang/acvm/pull/91), but we're missing a Noir function to actually call it in Noir programs.

### Proposed solution

Create the function in `stdlib`.

### Additional context

From @vezenovm on Slack re how the function signature could look like:

> I think there were some efficiency benefits to using a `[u64]` however a byte slice is more intuitive and perhaps we can add helper methods to convert between different array types

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by colinnielsen** [comment]
Looking forward to this. I wrote an [ECDSA recover-like circuit](https://github.com/colinnielsen/ecrecover-noir/blob/main/src/main), using @TomAFrench's [keccak function signature](https://github.com/colinnielsen/ecrecover-noir/blob/main/src/secp256k1.nr#L25-L37).
I had to manually convert my inputs to `[u64;16]`, then pass the input bits. 

It would be amazing to have a circuit signature of `keccak([u64])` or `keccak([u8])` that handled the `input_length` in bits automatically
