### ISSUE TITLE
Backend does not work for ECDSA signatures over secp256k1

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#12]
The problem seems to be WASM related as tests on the C++ side pass verification and the error is `HeapAccessOutOfBounds`.

This happens in the function call, which indicates that possibly a WASM limit is being hit, or that there may be a bug in the C++ code.

Elaborating, signature verification takes roughly 200K constraints, while the biggest circuit that I have tested is 2^19 . From this it would be reasonable for signature verification to not hit the WASM limit.

**Comment by Globallager** [comment]
Closed by https://github.com/noir-lang/noir/pull/1294.
