### ISSUE TITLE
Refactor circuit_build_path logic

### ISSUE THREAD

**Issue by phated** [noir-lang/noir#1201]
### Problem

The logic for getting a circuit_build_path or recompiling is duplicated many times throughout nargo_cli. This should be refactored.

### Proposed solution

Per @TomAFrench's comment:
> I'd like to add a "context" struct at some point which essentially wraps the `PackageManifest` along with the package's root directory. These sorts of functions would then live as methods on there.

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by vicyyn** [comment]
Hello! would love to work on this issue. is there more context on how I would implement this? Thank you 😄
