### ISSUE TITLE
codegen-verifier does not produce a functional verifier

### ISSUE THREAD

**Issue by jrocco2** [noir-lang/noir#1206]
### Aim

I'm try to create a basic circuit, where I use nargo to create the proof. I also use nargo to create the solidity smart contract via `codegen-verifier`. 

### Expected behavior

I expect to be able to create a simple circuit and then generate a verifier in solidity. This verifier should validate proofs that are generated via Nargo.

### Bug

When I pass a proof from Nargo to the solidity verifier it fails with the following command: 
`VM Exception while processing transaction: reverted with panic code 17`

### To reproduce

Given a very simple circuit: 
`fn main(x : Field) {
    constrain x == x;
}`

I generate a proof using `nargo prove p`. Then I generate a verifier using `nargo codegen-verifier`

I then run the following script via hardhat to deploy the verifier and give it the proof:

```
  const TurboVerifier = await ethers.getContractFactory("TurboVerifier");
  const verifier = await TurboVerifier.deploy();
  await verifier.deployed();

  console.log("TurboVerifier deployed to:", verifier.address);

  console.log("Verifying proof...");
  let proof = fs.readFileSync(path.resolve(__dirname, '../circuits/proofs/p.proof'), 'utf8')
  let tx = await verifier.verify('0x'+proof);

  console.log(tx)
```

### Installation method

Binary

### Nargo version

nargo 0.3.2 (git version hash: 29b1f7df4d563849a62e64c533cb62932188135b, is dirty: false)

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by Globallager** [comment]
Hey there, thanks for submitting the issue.

Would you like to give >v0.5.0 a try? Solidity verifiers generated from v0.5.0 onwards have changed and might have resolved the issue you were facing.

**Comment by kevaundray** [comment]
Closing this as the smart contract code has changed a lot since this issue and since 0.3.2
