### ISSUE TITLE
Execute a Noir program via typescript

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1215]
### Problem

Compiling a Noir program will produce build artefacts that one can use to create a proof.

Creating a proof is comparitively quite expensive, so a user may want to know if their proof will pass given certain inputs. We refer to this as "simulation".

- Now since we allow the compiler to be compiled into a WASM binary and ran from typescript, there should be some ergonomic way to simulate proofs with this workflow. 

- Simulation also creates a map of witness indices that will be used by the proof, this is to say that with our current workflow and APIs, we cannot create a proof without simulation first.

### Proposed solution

Add the ability to supply initial program inputs via the ABI provided and then have nargo return the output values in a JSON file.

### Additional context

This issue may be fleshed out more after we discuss the blockers and @TomAFrench 's vision of how this would play out

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kevaundray** [comment]
sub issue: #1236

**Comment by TomAFrench** [comment]
Completed in https://github.com/noir-lang/acvm-simulator/blob/master/test/execute_circuit.test.ts
