### ISSUE TITLE
Investigate whether we can compile the library to WASM with the C++ FFI

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#122]

**Comment by kobyhallx** [comment]
@kevaundray would you be able to give some pointers on how to go about your recommendation [above](https://github.com/noir-lang/noir/issues/122#issuecomment-951073874) and build for `wasm32-unknown-unknown`.
Naively disabling features would result in compilation errors, starting with `please specify a backend to compile with`.

**Comment by kevaundray** [comment]
Hey, I'm currently working on this, just have not committed the changes. Indeed just disabling things will give a compilation error (We want to compile noir without a backend)

Currently I have compiled the noir compiler to a wasm binary using wasm-bindgen which is being called from typescript. 

Do you want me to ping you when I push the changes?

**Comment by kobyhallx** [comment]
Please do.

**Comment by kevaundray** [comment]
This can now be closed and is now under the responsibility of the tooling team led by @kobyhallx
