### ISSUE TITLE
Add deprecation warning for `constrain`

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1228]
### Problem

As of #1227 we are deprecating `constrain` for `assert`. Since we don't want to break all existing Noir programs, we will for now just add a deprecation warning whenever constrain is used to tell folks to use `assert`.

### Proposed solution

Add deprecation warning 

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by joss-aztec** [comment]
Oh actually that's not true, because they won't encounter the depreciation warning because it's not merged yet 😅. It's just my PR that's blocked since the tests won't pass.
