### ISSUE TITLE
Review parameter semantics in Noir implementation

### ISSUE THREAD

**Issue by guipublic** [noir-lang/noir#123]
In the evaluator, objects representing the variables being evaluated are passed by value to the relevant operators (e.g handle_mul_op). When the object is re-used, for instance if we need to apply several constraints to it, this mean we need to clone it. 
While this is fine most of the time, passing these objects by reference and carefully specifying in the functions signature whether we require a mutable reference or not would make explicit when we are actually required to clone it.

**Comment by kevaundray** [comment]
This has grown stale
