### ISSUE TITLE
Encode ABI inputs to create initial witness inputs in typescript

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1236]
### Problem

Nargo CLI allows you to take input from a TOML file and along with an ABI one is able to encode the values in the TOML file into a witness map.

A small example. 

**TOML file**

```toml
x = "5"
y = "6"
```

**ABI**  (Not the exact layout)

```json
{
 "x" : {
          "type" : "Field",
          "visibility" : "private",
          "witness_index" : "1"
       },
"y" : {
          "type" : "Field",
          "visibility" : "public",
          "witness_index" : "2"
       }
}
```

**WitnessMap**

Using the ABI and the TOML file, we are able to create the witness map, which will map witness indices to values. Observe:

- `x` has a witness index of `1` in the ABI and a value of `5` in the TOML file.
- `y` has a witness index of `2` in the ABI and a value of `6` in the TOML file.

The resulting witness map will then look like:

```json
[
 "1" : "5",
 "2" : "6",
]
```

**Whats the point**

This witness map will be used to then pass to the ACVM which will then further populate thw witness map by iterating through the opcodes in the IR (ACIR). This process may also encounter opcodes which will pause the VM as its not possible to process an opcode without fetching information from outside of the VM. These are called oracles. Once the ACVM is finished we can then call the backend to create a proof based on the populated witness map. 

**Notes**

- This procedure is done both by the prover and the verifier. The verifier however only needs to map the `public` items in the ABI.
- We are able to map composite objects like structs and arrays.

It would be a pain for users to need to re-implement the initial population of the witness map in typescript, so we would like to expose this functionality through WASM.

### Proposed solution

We will assume that the ABI and the inputs/TOML file has been populated.

We therefore only need to expose the following function:

```rs
fn encode_abi(abi : Abi, inputs : TomlFile, is_prover : bool) -> Map
```

### Additional context

bump @TomAFrench for visibility

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kevaundray** [comment]
#1237 allows us to use JSON instead of TOML, its not a blocker but once implemented we probably want this to be the default.

**Comment by TomAFrench** [comment]
Completed in https://github.com/noir-lang/acvm-simulator/blob/master/test/execute_circuit.test.ts
