### ISSUE TITLE
Add possibility to encode JSON input instead of TOML input

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1237]
### Problem

Currently the only way for a user to supply initial input is via a TOML file. 

This can be seen with a Verifier/Prover.toml file.

With issues like #1215 and #1236 where we want to take input from some typescript environment. It would make sense to allow typescript users to supply input via a JSON object.

### Proposed solution

We can split this task into two:

- Add JSON as a way to supply input
- Allow the CLI to choose between JSON and TOML, where TOML is the default.

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kevaundray** [comment]
We may be able to do a quick fix by converting JSON to TOML and then using the TOML parser

**Comment by TomAFrench** [comment]
We don't even have to go that far tbh, serde will happily turn json into `TomlTypes`. I've got a local implementation of https://github.com/noir-lang/noir/issues/1236 which does this.

**Comment by kevaundray** [comment]
> We don't even have to go that far tbh, serde will happily turn json into `TomlTypes`. I've got a local implementation of #1236 which does this.

Yep we commented the same thing :) Can you push the PR for this, so someone can pick it up if needs be?

**Comment by TomAFrench** [comment]
Ah gotcha, I thought you were suggesting turning json into actual toml before feeding it in.

> Can you push the PR for this, so someone can pick it up if needs be?

It's currently in the wrong place unfortunately. I was working off of the `wasm` crate however we want to keep that restricted to just compilation so I'll need to set up a separate repository for this.

**Comment by TomAFrench** [comment]
I've opened this #1359 which suggests that we only accept JSON as a CLI argument rather than allowing `Prover.json`. The current `Prover.toml` system is quite inflexible so wouldn't be used by other programs interacting with Nargo imo.

Happy to close this issue in favour of #1359?

**Comment by TomAFrench** [comment]
Unassigning myself as this is low priority atm as it's unneeded for the ACVM simulator work.
