### ISSUE TITLE
Dependencies in noir wasm don't get std library

### ISSUE THREAD

**Issue by sirasistant** [noir-lang/noir#1244]
### Aim

To compile a dependency with noir_wasm that uses the std library.

### Expected behavior

The dependency should have access to the std library.

### Bug

Instead, the compiler crashes 
```
panicked at 'error reporter: could not find crate std', crates/noirc_frontend/src/hir/resolution/import.rs:199:28

Stack:

Error
    at module.exports.__wbg_new_abda76e883ba8a5f (/mnt/user-data/alvaro/aztec3-packages/yarn-project/node_modules/@noir-lang/noir_wasm/nodejs/noir_wasm.js:212:17)
    at wasm://wasm/00f971da:wasm-function[1910]:0x2c0557
    at wasm://wasm/00f971da:wasm-function[1210]:0x2a05ef
    at wasm://wasm/00f971da:wasm-function[1577]:0x2b8472
    at wasm://wasm/00f971da:wasm-function[235]:0x188092
    at wasm://wasm/00f971da:wasm-function[1478]:0x2ae78e
    at wasm://wasm/00f971da:wasm-function[283]:0x198208
    at wasm://wasm/00f971da:wasm-function[29]:0x6185a
    at wasm://wasm/00f971da:wasm-function[29]:0x5f05c
    at wasm://wasm/00f971da:wasm-function[29]:0x5ef2b
```

### To reproduce

1. write a resolver that allows to resolve dependencies
2. create a library that uses the std lib
3. compiler will crash

### Installation method

None

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kobyhallx** [comment]
still an issue with with this failure
https://github.com/noir-lang/noir/actions/runs/6112943464/job/16591423561?pr=2596#step:18:21
