### ISSUE TITLE
Restrict integers to 128 bits max

### ISSUE THREAD

**Issue by guipublic** [noir-lang/noir#125]
Currently Noir allows to define integers up to 255 bits but depending on the ZKP scheme (and its configuration) the underlying prime number can be less than this (e.g Bulletproofs uses a prime around 2^252).
Furthermore Rust natively supports up to 128 bits integers so it makes sense to implement Integers in Noir up to 128 bits and later on allow for bigger bit size using a dedicated big integer implementation.

**Comment by kevaundray** [comment]
This has been implemented however, we should define somewhere that the minimum field size should be 256 bits for Noir. Note that for acir, we can make it any sized field

**Comment by guipublic** [comment]
I don't think the minimum field size should be 256 bits for Noir, it should work with any reasonable size, i.e at least anything over 60 bits.
