### ISSUE TITLE
Change all tests to use `assert` instead of `constrain`

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1251]
### Problem

Now that we are moving towards `assert` instead of `constrain` . We should modify our examples to use `assert`.

The examples live [here](https://github.com/noir-lang/noir/tree/master/crates/nargo_cli/tests/test_data)

### Proposed solution

In each example, rename `constrain expr` to be `assert(expr)`.

Note: There is an `assert` example which uses the `assert` keyword instead of `constrain.

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kevaundray** [comment]
@ makluganteng This is a good first issue, if you are interested :)

**Comment by kevaundray** [comment]
@makluganteng This is a good first issue, if you are interested :)

**Comment by makluganteng** [comment]
Yup i can take this task

**Comment by makluganteng** [comment]
@kevaundray Hi, i kinda need help on setting up the env so that i could test it out

**Comment by shivamganwani** [comment]
@makluganteng which point are you stuck at?

**Comment by makluganteng** [comment]
when im installing the direnv. nix --extra-experimental-features install nixpkgs#direnv

**Comment by kevaundray** [comment]
Hi @makluganteng , 

Thank you for the willingness to take up this task -- I'm going to re-assign this issue to someone on the team. If you are still having installation problems, please open up an issue for it and flag it on our discourse: https://discourse.aztec.network/c/noir/7
