### ISSUE TITLE
`sha256::digest` and `sha512::digest` do not compile

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#1259]
### Aim

I'm trying to compile code which uses the sha256 and sha512 implementations we have in the standard library as part of #1258 .

The functions are defined here:
https://github.com/noir-lang/noir/blob/master/noir_stdlib/src/sha256.nr
https://github.com/noir-lang/noir/blob/master/noir_stdlib/src/sha512.nr

### Expected behavior

These functions should compile correctly and calculate the sha256 and sha512 hashes respectively.

### Bug

Compilation of these functions fails with the error

```
error: index out of bounds
    ┌─ std/sha256.nr:151:23
    │
151 │             msg_block[i] = 0;
    │                       - out of bounds error, index is 64 but length is 64
```

### To reproduce

1. Run the [`sha2_byte` test case](https://github.com/noir-lang/noir/blob/master/crates/nargo_cli/tests/test_data/sha2_byte/src/main.nr)
2. observe error message

Note that all the test cases related to these functions are excluded from the noir integration tests. We don't run this code in the `sha256` test case as this uses the native implementation from bberg rather than in noir.

### Installation method

Binary

### Nargo version

nargo 0.5.0 (git version hash: 5cf7580a9f475d742136c344dea187bd503486a9, is dirty: false)

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by TomAFrench** [comment]
From the look of the error message this isn't an issue in the actual implementation but in Noir itself. We're trying to write past the end of the array but the surrounding if statement should prevent this.

**Comment by kevaundray** [comment]
Whats the status of this issue @TomFrench ?

**Comment by kevaundray** [comment]
Since #1629 has been fixed in the new ssa, closing. Feel free to open if you find that this issue still persists
