### ISSUE TITLE
Review excluded tests for long running times

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1262]
### Problem

We currently are excluding poseidon and sha2_byte in our tests because they were taking a long time to run.

The poseidon rationale can be seen here: https://github.com/noir-lang/noir/pull/768#issuecomment-1423108006

This is non optimal because these tests are never ran.

### Proposed solution

Review the CI times of these functions when no longer excluded. The poseidon test seems to add an extra 30 minutes to CI times which is not feasible, though as noted in the issue, it was contigent on a certain PR, so this seems to be a compiler problem.

The sha2_byte issue has a lot more unknowns and will require further investigation.

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by TomAFrench** [comment]
Outside of these functions living in the standard library is there any reason to include them in the integration tests for the noir language themselves? One benefit of #1258 is that we can offload these tests into external repositories to run separately.

**Comment by kevaundray** [comment]
> Outside of these functions living in the standard library is there any reason to include them in the integration tests for the noir language itself? One benefit of #1258 is that we can offload these tests into external repositories to run separately.
> 
> 
> 
> Granted we had a bug which surfaced in the poseidon integration test however we have multiple versions of more minimal circuits which would work as regression tests.

Good point -- for Poseidon I don't think there is any reason if we go with a thin stdlib, if we remove black box functions too, we also can remove the sha2 tests

**Comment by kevaundray** [comment]
We should put in some time to figure out why they are so long running though -- as adoption increases we want folks to run CI on large/complicated programs

**Comment by kevaundray** [comment]
@guipublic can you check if we are exlcuding these tests in the case of the new ssa and whether they are still long running?

**Comment by kevaundray** [comment]
Closing this because we no longer exclude any tests
