### ISSUE TITLE
Spike suggestion: egg integration

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#1273]
### Problem

Interleaving optimisation passes is hard. Rerunning passes can be is expensive. Cranelift rolled their own e-graph solution to address this: https://github.com/bytecodealliance/rfcs/blob/main/accepted/cranelift-egraph.md. Building an efficient e-graph solution looks like it would cost significant developer effort.

### Proposed solution

Experiment with egg (https://egraphs-good.github.io/), to see if their generalised e-graph solution is a good fit for us to model optimisations around.

### Alternatives considered

Don't use e-graphs or write own own.

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kevaundray** [comment]
Closing as I think its a fairly substantial change to the architecture and egraphs are still quite unstable
