### ISSUE TITLE
if-else loops are short-circuiting when using variables

### ISSUE THREAD

**Issue by harshnambiar** [noir-lang/noir#1277]
### Aim

in _fn main(x: u32, y: pub u32)_, doing **(x == 2), (x < 2) and (x > 2)** all yield true. This is leading to every if, else part getting executed.

### Expected behavior

This should clearly not be the case. However, constraints are working since constraint (x <= 2) seems to work just fine.

### Bug

Each comparison with x is leading to a true case, which effectively short circuits the conditional statements.

### To reproduce

1. Fork https://github.com/resurgencelabs/rock_paper_scissors_game
2. nargo check
3. nargo prove p --show-output
4. The program prints every scenario possible, which should not happen.

### Installation method

Binary

### Nargo version

nargo 0.5.0

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by vezenovm** [comment]
Using the repo provided in the issue I added printlns inside each conditional:
```
    if (p == 0){
        if (q == 1){
            std::println("Player 2 wins!");
            res = 2;
        }
        if (q == 2){
            std::println("Player 1 wins!");
            res = 1;
        }
    }
    if (p == 1){
        if (q == 0){
            std::println("Player 1 wins!");
            res = 1;  
        }
        if (q == 2){
            std::println("Player 2 wins!");
            res = 2;
        }
    }
    if (p == 2){
        if (q == 0){
            std::println("Player 2 wins!");
            res = 2;
        }
        if (q == 1){
            std::println("It's a draw!");
            res = 1; 
        }
    }
```
When using the new experimental ssa (`nargo prove p --experimental-ssa`) this is only now printing
```
"Player 2 wins!"
"0x02"
```
versus every case being printed with just `nargo prove p --show-output`. 

Marking this issue as resolved
