### ISSUE TITLE
Add first end to end test for new ssa module

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1287]
### Problem

With the SSA generation section of the code complete, we want to have an end to end test added as soon as possible. This will allow us to further parallelilze the work needed since one can add optimizations into the ACIR module and ACIR gen more parts of the SSA IR in parallel.

### Proposed solution

- [ ] Add an experimental flag to enable the new SSA module. This is similar to what we did when we moved from the interpreter to the current SSA code.

- [ ] Minimal program

As a first milestone, lets get the following program running from end to end:

```rust
fn main(x : pub Field) -> pub Field {
  x + 1
}
```

### Additional context

The experimental flag will allow us to make circuit size comparisons easier too.

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kevaundray** [comment]
We won't be able to run the full test suite until all features have been enabled, but we can keep a branch open that simply enables the new SSA and comments out the tests.

I'm usually against long standing branches, though because this branch will only be used to keep track of what features are supported, it is fine

**Comment by joss-aztec** [comment]
Various tests have been added at this point
