### ISSUE TITLE
assertion failed: stack_frame.stack.contains(&replacement)

### ISSUE THREAD

**Issue by ax0** [noir-lang/noir#1299]
### Aim

Test the following code:

```rust
fn f<N>(arr: [Field; N]) -> Field
{
    let mut i = 0;
    let mut out = 1;
    let mut cur = [0; 2];
    
    for a in arr
    {
	cur[i] = a;
	i += 1;

	if i == 2
	{
	    out *= cur[0]*cur[1];
	    cur = [0; 2];
	    i = 0;
	}
    }

    out
}

#[test]
fn f_test()
{
    assert(f([1,2,3]) == 2);
}
```

### Expected behavior

The test passes.

### Bug

We get the following error:
```
Message:  assertion failed: stack_frame.stack.contains(&replacement)
Location: crates/noirc_evaluator/src/ssa/inline.rs:373
```

### To reproduce

1. Place the above code in a Noir project.
2. Run `nargo test`.

### Installation method

Compiled from source

### Nargo version

nargo 0.5.1 (git version hash: 9740f54c28f30ea9367897fa986d8aea1aba79f2, is dirty: false)

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kevaundray** [comment]
@guipublic can you check if this is still the case with the new ssa?
