### ISSUE TITLE
SSA Refactor: Implement array cloning

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#1300]
### Problem

In Noir, arrays are cloned when moved into another variable:
```rs
let mut a = [1, 2, 3];
let b = a;

a[0] = 5;
assert(a[0] == 5);
assert(b[0] == 1);
```
However the SSA refactor currently does not clone them, instead arrays function more as references:
```rs
let mut a = [1, 2, 3];
let b = a;

a[0] = 5;
// Assuming this was compiled with the new ssa refactor this would hold currently
assert(a[0] == 5);
assert(b[0] == 5);
```

### Proposed solution

Add a check when creating new variables to clone arrays.

### Alternatives considered

Alternatively, change arrays to have some immutable representation that does not need to be cloned manually. An example representation would be `im::Vector` which would also allow us to grow these arrays.

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by Savio-Sou** [comment]
@jfecher is this still relevant?

**Comment by jfecher** [comment]
> Alternatively, change arrays to have some immutable representation that does not need to be cloned manually. An example representation would be im::Vector which would also allow us to grow these arrays.

This is done now, we use `im::Vector` for all arrays in SSA.
