### ISSUE TITLE
CI should be caching cargo dependencies

### ISSUE THREAD

**Issue by phated** [noir-lang/noir#1303]
### Problem

It seems that all cargo dependencies are being rebuilt on every CI run. These should be cached and rehydrated to significantly bring down the CI run times.

### Proposed solution

In talking with @kobyhallx, he suggested that maybe this is due to not using "clean sources" within Nix. I believe he has experience with this and will dive in.

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kobyhallx** [comment]
Spent a few hours on this but src filtering does not seem to be an issue. In `buildDepsOnly` stage, the actual `src` is replaced with a dummy one to avoid source changes triggering re-builds.

**Comment by phated** [comment]
This dependency caching was working on my branch, but seems to still be building deps on master. I think this needs further investigation.
