### ISSUE TITLE
Quadratic blowup in constraint count in loops that include equality operators

### ISSUE THREAD

**Issue by zac-williamson** [noir-lang/noir#1305]
### Aim

The following code produces over 40 million gates when running `nargo gates`

The gate cost appears to grow quadratically as `LEN` increases linearly

```
use dep::std;

global LEN : comptime Field = 9044; // 532 * 17
fn decodeTest(input: Field) -> Field
{
    let mut num_fields = input;
    for i in 0..LEN
    {
        num_fields += (i == num_fields) as Field;
    }
    num_fields
}

fn main(input: Field)
{
    let num_fields: Field = decodeTest(input);
    constrain num_fields == 17;
}
```

### Expected behavior

The cost of the above function should be approximately 4-5 gates per iteration (i.e. <50,000 gates not >40,000,000 gates). The gate cost should grow linearly with the loop length.

### Bug

Equality operators nested within loops produce a quadratic blowup in gate count. This also appears to be the case for logical operators.

The above circuit costs  40,919,579  gates. where LEN * LEN / 2 = 40,896,968 

The delta between these 2 numbers is 22,611 which is close to the number of gates I expected for the above circuit.

The bug is also present for the following variants:

```
fn decodeTest(input: Field) -> Field
{
    let mut num_fields = input;
    for i in 0..LEN
    {
        num_fields += ((i as u64) & (num_fields as u64)) as Field;
    }
    num_fields
}

fn decodeTest(input: Field) -> Field
{
    let mut num_fields = input;
    for i in 0..LEN
    {
        num_fields += ((i as u64) > (num_fields as u64)) as Field;
    }
    num_fields
}

fn decodeTest(input: Field) -> Field
{
    let mut num_fields = input;
    for i in 0..LEN
    {
        num_fields += (num_fields as u8) as Field;
        std::println(i); // to get around unused variable compiler error
    }
    num_fields
}
```
### To reproduce

1. Create a Noir program with the above code
2. Run `nargo gates`

### Installation method

Binary

### Nargo version

nargo 0.5.1

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by guipublic** [comment]
The quadratic blow-up is due to the optimiser which 'optimise' the gates for width 3.
Because of the += done in a loop, num_fields keeps increasing its linear count, and the optimiser keeps creating the same intermediate variables again and again to get to width of 3.
