### ISSUE TITLE
Assigning to a tuple member within `if` fails

### ISSUE THREAD

**Issue by iAmMichaelConnor** [noir-lang/noir#1309]
### Aim

```rust
let some_condition = false; // for example's sake
let mut my_tuple: (bool, bool) = (false, false);

if some_condition {
    my_tuple.0 = true;
else {
    my_tuple.0 = false;
}
```

This compilation fails with:

```
error: Expected an expression but found =
...
             my_tuple.0 = true;
```

If I replace the tuple `(bool, bool)` with an array `[bool; 2]` and access via `my_tuple[0]`, it compiles.

Note: My tuple was actually made up of structs, rather than `bool`s, but I distilled it down to this, for simplicity.

I'm using the `aztec3-hacky` branch, so it could be because of that...?

### Expected behavior

Expected it to be able to assign to the element of the tuple.

### Bug

See section above.

### To reproduce

1.
2.
3.
4.

### Installation method

None

### Nargo version

nargo 0.4.0 (git version hash: 22c2234fc72f34e96dff9c35f7f3548cf6062d0c, is dirty: false)

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kevaundray** [comment]
> I'm using the aztec3-hacky branch, so it could be because of that...?

Possibly, it would be good to check that this is a bug on master too

**Comment by iAmMichaelConnor** [comment]
Just checked with v0.4.1:

```
fn main(my_tuple: (bool, bool), some_condition: bool) -> pub (bool, bool) {
    // let some_condition = false; // for example's sake
    // let mut my_tuple: (bool, bool) = (false, false);

    if some_condition {
        my_tuple.0 = true;
    } else {
        my_tuple.0 = false;
    }

    my_tuple
}
```

```
error: Expected an expression but found =
   ┌─ /mnt/user-data/mike/packages/yarn-project/noir-contracts/src/contracts/mike-play/src/main.nr:27:20
   │
27 │         my_tuple.0 = true;
   │                    -

error: Expected an expression but found =
   ┌─ /mnt/user-data/mike/packages/yarn-project/noir-contracts/src/contracts/mike-play/src/main.nr:29:20
   │
29 │         my_tuple.0 = false;
   │                    -

error: aborting due to 2 previous errors
Error: Failed to compile circuit
```

**Comment by jfecher** [comment]
Worth noting this fails without the `if` as well - it seems we don't parse assigning to tuple fields at all.
