### ISSUE TITLE
Perform stable releases of `noirc_abi`

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#1314]
### Problem

ABI encoding/decoding is an important action which users want will want to be able to perform outside of the nargo cli. We don't currently provide a stable version of this crate which is guaranteed to match the logic of a particular version of nargo.  This makes it more difficult than necessary to interact with a circuit's ABI outside of this repository.

### Proposed solution

We should publish stable releases of `noirc_abi` to crates.io with each release of `nargo`.

### Additional context

I'm currently running into this issue with the ACVM simulator project.

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by TomAFrench** [comment]
We agreed to park this pending Nargo being moved out of this repository.

**Comment by kobyhallx** [comment]
Also, we can simulate this by pinning dependency to commit
