### ISSUE TITLE
Add more readable serialisation of `InputValue`s representing boolean values.

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#1324]
### Problem

Currently we allow users to set boolean arguments in the toml files as a `true`/`false` value. However when `noirc_abi` saves them to file, they all get converted to `0x0000000000000000000000000000000000000000000000000000000000000001` or `0x0000000000000000000000000000000000000000000000000000000000000000`.

This isn't particularly readable, ideally we'd preserve the "booleanness" of these args rather than treating them as arbitrary fields.

### Proposed solution

The reason for this issue is that `InputValue` represents all of fields, integers and bools as `InputValue::Field`.

https://github.com/noir-lang/noir/blob/260d87d1ef86069a1fcf0f9b4969589273e381d1/crates/noirc_abi/src/input_parser/mod.rs#L14-L19

We could address this by either adding a `InputValue::Boolean` variant or passing the ABI into the serialisation method similarly to how we do for parsing.

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by chirag-bgh** [comment]
hey! hey! @TomAFrench 
i would like to work on this issue.

**Comment by TomAFrench** [comment]
Awesome! Thanks @chirag-bgh. I've had a little think about which option would be best and I think we should pass the ABI to the serialisation method rather than adding `InputValue::Boolean`. This would have the benefit of catching any booleans which are stored in arrays as well.

I'm going to assign this issue to you and feel free to reach out if you run into troubles.
