### ISSUE TITLE
Support choosing generators for pedersen hashes

### ISSUE THREAD

**Issue by sirasistant** [noir-lang/noir#1341]
### Problem

To preserve collision resistance when hashing with pedersen data of different lengths, we need to be able to choose the set of generators to use for the hash. Right now we are using barretenberg's default generators (hash_index = 0) since we don't allow the user to customize which generators to use when calling pedersen. 

This could lead of users being able to craft collisions when hashing sets of data of different domains (different lengths). By hashing data of a specific domain with specific generators, we can avoid cross-domain collisions.

An example of this usage is Aztec circuits:
https://github.com/AztecProtocol/aztec-packages/blob/master/circuits/cpp/src/aztec3/constants.hpp#L60

You can know more about this issue [here](https://hackmd.io/YBdr8GeoTc-PxvmLLloE7A?view#fn1)

### Proposed solution

Add a domain separator parameter to the Pedersen BlackBoxFunctionCall to pass to the backend, that will be used to select the generator set to use, allowing to hash data of diferent domains using pedersen.

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kevaundray** [comment]
This seems to now be supported, so closing issue
