### ISSUE TITLE
Integration tests are not working on the mainframe

### ISSUE THREAD

**Issue by guipublic** [noir-lang/noir#1342]
### Aim

Run cargo test

### Expected behavior

Integration tests pass

### Bug

Somebody modified the noir integration tests and now I have this error:

`thread 'main' panicked at 'failed to copy test cases to temp directory: Error { kind: InvalidInput, message: "the source path is neither a regular file nor a symlink to a regular file" }', crates/nargo_cli/tests/prove_and_verify.rs:65:14`

### To reproduce

1. Execute cargo test on mainframe
2.
3.
4.

### Installation method

None

### Additional context

I can reproduce the issue on the 'mainframe' which is an ubuntu server on aws:
5.15.0-1033-aws #37~20.04.1-Ubuntu SMP Fri Mar 17 11:39:30 UTC 2023

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kevaundray** [comment]
Since these issues are public, using the term `mainframe` does not mean much, plus the `mainframe's` environment changes over time so specifying more details about your environment would be helpful, plus the things you have tried to fix it.

**Comment by Savio-Sou** [comment]
Is this an issue still? Should we close it?

**Comment by phated** [comment]
I removed the tempdir creation in prove_and_verify so this was actually completed with #1510
