### ISSUE TITLE
Modulo operator is not working

### ISSUE THREAD

**Issue by SleepingShell** [noir-lang/noir#1346]
### Aim

Use the modulo operator

### Expected behavior

The modulo operator to return the correct value

### Bug

The modulo operator always returns 0 no matter what.

```rust
use dep::std;

fn main(x : Field, y : pub Field) {
    constrain x != y;
}

#[test]
fn test_main() {
    let x = 50 as u64;
    let y = 9 as u64;
    let z = x % y;
    std::println(z);
}
```

output:
```
nargo test --show-output
Running 1 test functions...
Testing test_main...
0x
ok
All tests passed
```

### Installation method

None

### Nargo version

nargo 0.4.1 (git version hash: 3d2233de810ab6d4a0f4f83007232133c88a49fe, is dirty: false)

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by SleepingShell** [comment]
@vezenovm opened here as we discussed

**Comment by TomAFrench** [comment]
Potentially related to #774 (although I didn't have it happen outside of for-loops)

**Comment by SleepingShell** [comment]
> Potentially related to #774 (although I didn't have it happen outside of for-loops)

So you have code in which modulo is working?

**Comment by porco-rosso-j** [comment]
I also faced this. Temporarily I added my own modulo func to get it around. 
```
fn modulo(x: u64, y: u64) -> u64 {
    let z: u64 = x - y * (x / y);
    z
}
```
