### ISSUE TITLE
"Expression has too many unknowns" error

### ISSUE THREAD

**Issue by spalladino** [noir-lang/noir#1347]
### Aim

I'm getting a `solver opcode resolution error: cannot solve opcode: expression has too many unknowns %EXPR [ 0 ]%` when running a function using the `aztec3-hacky` branch for an e2e test on the aztec3 repository. Here's the function I'm trying to run:

https://github.com/AztecProtocol/aztec-packages/blob/e96ef4a94e481614f1e6f02f6c966cfc30ddff06/yarn-project/noir-contracts/src/contracts/parent_contract/src/main.nr#L84-L107

Note that there is a very similar function right above, which works fine. Given the error, it'd seem like it's related to the function being too long/complex..?

### Expected behavior

Function should run as expected.

### Bug

`solver opcode resolution error: cannot solve opcode: expression has too many unknowns %EXPR [ 0 ]%`

### To reproduce

1. Checkout the `aztec3-packages` repository in the `palla/public-fns-from-private-2` branch and follow setup instructions
2. Replace `skip` with `only` for the `should mine transactions that enqueue multiple public calls with nested public calls` test in `yarn-project/end-to-end/src/e2e_nested_contract.test.ts`
3. Run anvil in the background
4. Run `yarn test nested` in the ``yarn-project/end-to-end` folder 

### Installation method

Compiled from source

### Nargo version

nargo 0.4.0 (git version hash: 22c2234fc72f34e96dff9c35f7f3548cf6062d0c, is dirty: false)

### @noir-lang/noir_wasm version

No

### @noir-lang/barretenberg version

No

### @noir-lang/aztec_backend version

No

### Additional context

This is on the aztec3-hacky branch of the repository

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by guipublic** [comment]
From this repository: https://github.com/AztecProtocol/aztec-packages/
I cannot find the branch:
```
git checkout palla/public-fns-from-private-2
error: pathspec 'palla/public-fns-from-private-2' did not match any file(s) known to git
```

**Comment by benesjan** [comment]
I've also stumbled upon this issue in [this PR](https://github.com/AztecProtocol/aztec-packages/pull/636). The error was thrown in the [acir simulator test](https://circleci.com/gh/AztecProtocol/aztec-packages/56863).

**Comment by kevaundray** [comment]
Since this is using the hacky branch, there will be a bit of a delay in fixing this
