### ISSUE TITLE
Canonicalise wording for printing to stdout

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#1352]
### Problem

We use inconsistent naming for representing the concept of information that gets sent to stdout. (E.g. in cli flags and the places to which those flags propagate.)

### Proposed solution

Switch to a consistent term, e.g. "emit"

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kobyhallx** [comment]
@joss-aztec please offer specific example ?

**Comment by joss-aztec** [comment]
I was being deliberately vague in order to leave that decision to somebody else >_>

I suppose the core of the problem is that it's confusing to have intermingling terms that refer to logging that happens during compilation, but also logging that happens during circuit execution.

Specifically in the command `nargo compile --show-ssa --show-output`, `show-ssa` will affect stdout during compilation, but `show-output` won't affect stdout until a later `nargo execute`.

 The issue might go away if https://github.com/noir-lang/noir/issues/1497 is first addressed.

**Comment by kobyhallx** [comment]
CLI options to change significantly, closing as not relevant
