### ISSUE TITLE
Cannot instantiate a global array of structs

### ISSUE THREAD

**Issue by SleepingShell** [noir-lang/noir#1357]
### Aim

Create a global array of structs

### Expected behavior

A global array can be created (known at compile time) of struct types.

### Bug

Attempting to create a global array of structs will cause the follow error:

```
The application panicked (crashed).
Message:  no entry found for key
Location: crates/noirc_frontend/src/node_interner.rs:520
```

A local array of structs *can* be created.

### To reproduce

```rust
struct Test {
    v: Field,
}
global VALS: [Test; 1] = [Test { v: 100 }];
```

### Installation method

None

### Nargo version

nargo 0.5.1 (git version hash: 7f6dede414c46790545b1994713d1976c5623711, is dirty: false)

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kevaundray** [comment]
@vezenovm can you check if this is still an issue?

**Comment by vezenovm** [comment]
The same error still persists. At a quick glance this looks to be a bug related to the ordering of name resolution for structs and globals, but will require further investigation.
