### ISSUE TITLE
Add convenience structure for Indexed Merkle Tree

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#1358]
### Problem

Indexed Merkle Tree is an efficient approach to prove non-membership, as when compared with Sparse Merkle Tree, it comes with:
- Smaller tree size for the same number of leafs (as leafs are inserted incrementally, instead of having to cater for all possible leafs variants)
- Support for batched leaf insertion

Hence resulting in more efficient leaf insertions.

Reference: [Indexed Merkle Tree | Aztec Docs](https://docs.aztec.network/aztec/protocol/trees/indexed-merkle-tree)

Further to https://github.com/noir-lang/noir/issues/1080, a convenient function / library for developers to easily prove non-membership in Noir based on Indexed Merkle Trees would be desirable.

### Proposed solution

Implement the reference linked above in Noir.

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by kevaundray** [comment]
Closing this as we likely want this to be done as a external library -- we provide the base primitive for computing the merkle root currently in the stdlib
