### ISSUE TITLE
std::println(arr[0]) is not working

### ISSUE THREAD

**Issue by onurinanc** [noir-lang/noir#1362]
### Problem

Printing an element direcly using arr[0] is not working and causes to panic. We need to define the arr[0] as let x = arr[0], then use std::println(x);

Message:  internal error: entered unreachable code: logging this expression type is not supported
Location: crates/noirc_evaluator/src/ssa/context.rs:1181

### Proposed solution

This might be supported in the following versions

**Comment by SleepingShell** [comment]
This seems to happen with any expression, i.e you can only print variables that have been previously assigned. For example, ``std::println(var1 == var2)`` will also not work.

**Comment by kevaundray** [comment]
@vezenovm pinging for visibility

**Comment by jfecher** [comment]
Fixed after the old SSA code was removed
