### ISSUE TITLE
not yet implemented: Conversion to ObjectType is unimplemented for strings

### ISSUE THREAD

**Issue by onurinanc** [noir-lang/noir#1367]
### Aim

There is an example in the Noir lang documentation: https://noir-lang.org/language_concepts/generics#in-structs

When you run this code, it fails to print the outputs, says: not yet implemented: Conversion to ObjectType is unimplemented for strings

However, there seems no conversion to ObjectType

```
struct RepeatedValue<T> {
    value: T,
    count: comptime Field,
}

impl<T> RepeatedValue<T> {
    fn new(value: T) -> Self {
        Self { value, count: 1 }
    }

    fn increment(mut repeated: Self) -> Self {
        repeated.count += 1;
        repeated
    }

    fn print(self) {
        for _i in 0 .. self.count {
            dep::std::println(self.value);
        }
    }
}

fn main() {
    let mut repeated = RepeatedValue::new("Hello!");
    repeated = repeated.increment();
    repeated.print();
}
```

### Expected behavior

Expecting to print 

### Bug

The application panicked (crashed).
Message:  not yet implemented: Conversion to ObjectType is unimplemented for strings

### To reproduce

1.
2.
3.
4.

### Installation method

None

### Nargo version

nargo 0.5.1 (git version hash: 7f6dede414c46790545b1994713d1976c5623711, is dirty: false)

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by harshnambiar** [comment]
I came here to log this bug today, but since you have done it already two months back, we can just wait and chill here :)

**Comment by kevaundray** [comment]
@vezenovm what is the status of this issue in relation to the new ssa code?

**Comment by jfecher** [comment]
Duplicate issue from https://github.com/noir-lang/noir/issues/1035
