### ISSUE TITLE
Cannot import dependency that is a child-dependency of another

### ISSUE THREAD

**Issue by SleepingShell** [noir-lang/noir#1380]
### Aim

Given library A and library B, B depends on A. A crate should be able to import both A and B.

### Expected behavior

To be able to use both libraries

### Bug

I have tried two scenarios to import library A and B.

1. List both dependencies in ``Nargo.toml``. This leads to an error:
```
The application panicked (crashed).
Message:  ice: the same path was inserted into the file manager twice
Location: crates/fm/src/lib.rs:57
```
2. Attempt to import lib A without listing it in ``Nargo.toml``. This leads to:
```
The application panicked (crashed).
Message:  error reporter: could not find crate libA
Location: crates/noirc_frontend/src/hir/resolution/import.rs:199
```

### Installation method

None

### Nargo version

nargo 0.5.1 (git version hash: 7f6dede414c46790545b1994713d1976c5623711, is dirty: false)

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by TomAFrench** [comment]
Can you provide a repo where we can reproduce this please?

**Comment by SleepingShell** [comment]
> Can you provide a repo where we can reproduce this please?

Yes, please use this subfolder in this repo: https://github.com/SleepingShell/darkforest-noir/tree/main/init

**Comment by kevaundray** [comment]
@TomAFrench what is the status of this issue?

**Comment by TomAFrench** [comment]
Resolved in https://github.com/noir-lang/noir/pull/1034
