### ISSUE TITLE
Update GitHub bug report template wrt new packages

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#1384]
### Problem

Per https://github.com/noir-lang/noir/pull/1368, the GitHub bug report template's TypeScript packages section was replaced with placeholder text informing users to wait for the new package roll out.

### Happy Case

Update the section when the new set of packages is released.

### Additional Context

Pending for finalisation and implementation of the upgraded packages workflow:

```[tasklist]
# Pending
- [ ] https://github.com/noir-lang/noir/issues/2711
```

### Would you like to submit a PR for this Issue?

Yes

**Comment by kevaundray** [comment]
Closing this as we've made changes to this since then. Feel free to re-open if the issue has not been addressed.

**Comment by Savio-Sou** [comment]
Thanks for resurfacing the issue.

It has yet to be addressed (pending for finalisation and implementation of the upgraded packages workflow). Updating and re-opening the issue.
