### ISSUE TITLE
Retrieve `BACKEND_IDENTIFIER` from backend (instead of hardcoding)

### ISSUE THREAD

**Issue by phated** [noir-lang/noir#1388]
### Problem

Currently, we have cases in Nargo where we hardcode the `BACKEND_IDENTIFIER` as `acvm-backend-barretenberg`; however, this doesn't work with alternative backends. 

### Happy Case

Backends should provide an identifier via a function. This could also possibly include their version or other information, such as field, features, etc.

### Additional Context

Work has begun in https://github.com/noir-lang/acvm/issues/196 and https://github.com/noir-lang/acvm-backend-barretenberg/pull/189

### Would you like to submit a PR for this Issue?

No

**Comment by Savio-Sou** [comment]
Unsure if this is still relevant with the latest [`nargo backend` works](https://github.com/noir-lang/docs/issues/369).

Happy to hear thoughts if any, cc @TomAFrench @kevaundray. Might close this as stale otherwise.

**Comment by TomAFrench** [comment]
Yes, this is still relevant as artifacts are tailored for a particular backend.
