### ISSUE TITLE
Implement checksum for cached CRS

### ISSUE THREAD

**Issue by phated** [noir-lang/noir#1390]
### Problem

Binary CRS data is cached to the filesystem by nargo-cli, but we can't be sure the filesystem hasn't corrupted it.

### Happy Case

We should implement checksums when reading cached filesystem data for the CRS.

### Would you like to submit a PR for this Issue?

No

**Comment by kobyhallx** [comment]
Since CRS management becomes the responsibility of a Backend, we won't implement this on the Nargo side
