### ISSUE TITLE
Implement retries upon a CRS generate/update error

### ISSUE THREAD

**Issue by phated** [noir-lang/noir#1391]
### Problem

The CRS functions of a backend are only called once, and the process fails if there is an error. Since these are often network calls, this should have retry logic.

### Happy Case

Retry if an error is returned from `generate_common_reference_string` or `update_common_reference_string`.

### Would you like to submit a PR for this Issue?

No

**Comment by kobyhallx** [comment]
Delegates to a backend responsibility.
