### ISSUE TITLE
Add location information to `AcirGenError::IndexOutOfBounds`

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#1412]
### Problem

If the acir-gen pass for the new SSA IR encounters an index out of bounds error, the offending index will be reported, but users will have no indication where in their code this actually occurred.

### Happy Case

Ideally, we add Locations to this error so that when it is issued users will be able to see a clear error message and can find and fix the issue faster.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@guipublic what is the status of this issue?

**Comment by vezenovm** [comment]
This was resolved here (https://github.com/noir-lang/noir/pull/2389) so closing this issue
