### ISSUE TITLE
Support rust semantics for let statement

### ISSUE THREAD

**Issue by guipublic** [noir-lang/noir#143]
Priv and Const statement have low-level semantic and this can lead to artificial problems. For instance using a Priv variable x in a loop to compute x=y*i; will fail when the iterator is 0 because in that case the result is a constant.
It is better to let the compiler handles witness generation as required by the source code.
We should rather use the let statement to declare variable and use specific type when people wants to use witness directly, e.g:
let x: witness =y+a;  //this declares a witness
let y; //this declares a variable which could generate a witness or a constant depending on how it is assigned.

**Comment by kevaundray** [comment]
@jfecher can this be closed?

**Comment by jfecher** [comment]
Yes, it was completed when `priv` and `const` statements were removed in favor of a single `let`.
