### ISSUE TITLE
Store equality sets in AcirContext

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1431]
### Problem

There are many operations which enforce an equivalence relation between `AcirVar`s, the explicit one being `assert_eq_var`. 

This assert_eq means that we can replace `lhs` with `rhs` wherever we see fit. This is useful in the context, where `lhs` might be an Expression whereas `rhs` is a Witness and instead of creating an extra gate to convert lhs to a Witness, we can instead use `rhs`

### Happy Case

Create a Map in AcirContext to store equivalence relations. As noted above the obvious case is `assert_eq_var` however, whenever a constrain is called there is opportunity to capture an equivalnce relation and whenever `get_or_create_witness` is called, there is an opportunity to capture an equivalence relation.

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
This is partially resolved in #2378 but doesn't account for transitive equivalences.
