### ISSUE TITLE
Consider having the frontend disallow `as u{FieldElement::max_num_bits()}` conversions

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1443]
### Problem

As noted in this comment [here](https://github.com/noir-lang/noir/pull/1432/files#r1210103371) we can push the FieldElement check to the frontend.

Its not necessary, but keeping this as tracking issue.

### Happy Case

.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
This should also be solved with https://github.com/noir-lang/noir/pull/1433#discussion_r1208621796

**Comment by kevaundray** [comment]
@guipublic can you check the status of this issue?

**Comment by guipublic** [comment]
The check is still not on the frontend side

**Comment by guipublic** [comment]
I checked again and now bit size >= FieldElement::max_num_bits() are matched in the frontend (in the Lexer). I am closing the issue then.
