### ISSUE TITLE
Address GtEq extra opcodes

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#1444]
### Problem

New ACIR gen effectively constrains `Lt` as not `GtEq`. However, the new SSA IR has no `GtEq` op, and represents it as not `Lt`. Therefore a program containing `>=` effectively constrains it as not not `GtEq`.

### Happy Case

Either optimise away the redundant ACIR expressions, or avoid their creation by adding `GtEq` to the SSA IR.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
Related to this @jfecher noted we can switch the arguments instead of flipping the results: https://github.com/noir-lang/noir/pull/1433#discussion_r1210397148

**Comment by jfecher** [comment]
That comment was a mistake, see https://github.com/noir-lang/noir/pull/1433#discussion_r1210412307, we cannot just swap the arguments, we do need a not operation.

**Comment by TomAFrench** [comment]
We now simplify double nots to just refer to the original value.
