### ISSUE TITLE
Add range constraints for bounded integer params to main

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#1446]
### Problem

Params to main that aren't unbounded field elements need to have range constraints applied consistent with their bit widths.

### Happy Case

This can be done via casting

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@guipublic can you check that this is completed?

**Comment by guipublic** [comment]
I am closing this issue, range constraints are added for main parameters when handling block parameters in acir_gen.
