### ISSUE TITLE
Confirm whether instructions should handle all results from a function call

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1447]
### Problem

See comment [here](https://github.com/noir-lang/noir/pull/1436#discussion_r1210289611)

### Happy Case

We can check back on this once intrinsics are implemented

### Would you like to submit a PR for this Issue?

No

**Comment by joss-aztec** [comment]
`acir_gen/mod` does indeed handle all results of a function call.

**Comment by jfecher** [comment]
The `Vec`s in question were removed as well
