### ISSUE TITLE
Define uninitialised array element access

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#1458]
### Problem

During ACIR gen the current implementation of memory ([once merged](https://github.com/noir-lang/noir/pull/1455)) will throw an error when encountering a load instruction for an array element that hasn't been initialised.

### Happy Case

The current behaviour is probably the safest approach, but its nonetheless worth revisiting further down the road once we better understand the requirements of dynamic arrays.

### Would you like to submit a PR for this Issue?

No

**Comment by joss-aztec** [comment]
Backlink: https://github.com/noir-lang/noir/pull/1455/files#r1210854107

**Comment by kevaundray** [comment]
@guipublic since dynamic arrays have been implemented, can you revisit this?

**Comment by guipublic** [comment]
All arrays are initialised in noir, when they are declared. So loading an initialised part of an array is only possible for out-of-bounds indices, which cannot be avoided when we have witness indices.
However, in that case the prover will not be able to generate the proof and we will report an error.
We could add a range-check before any array access to prevent out-of-bound errors on the prover and then report better errors to the user.

**Comment by jfecher** [comment]
Closing this issue since I think we have a good answer for it. Arrays themselves can never be uninitialized but out of bounds accesses are still possible. For these cases we issue a compiler error.
