### ISSUE TITLE
Prover.toml doesn't handle arrays of structs

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#1459]
### Aim

Arrays of structs should handled

### Expected Behavior

Given the program
```rs
struct Foo {
    bar: Field,
    baz: Field,
}

fn main(foos: [Foo; 3]) -> pub Field {
    foos[2].bar + foos[2].baz
}
```
And the Prover.toml
```
[[foos]]
bar = 0
baz = 0

[[foos]]
bar = 0
baz = 0

[[foos]]
bar = 0
baz = 1
```
nargo should be able to prove

### Bug

Instead you encounter:
```
Error: input file is badly formed, could not parse, TOML parse error at line 3, column 1
  |
3 | [[foos]]
  | ^^^^^^^^
data did not match any variant of untagged enum TomlTypes
```

### To Reproduce

1. prove the above program and input

### Installation Method

Compiled from source

### Nargo Version

nargo 0.6.0 (git version hash: b695faa9127e12ea8adb2b4d46e19fd72a56051d, is dirty: true)

### Would you like to submit a PR for this Issue?

No

**Comment by goblinoats** [comment]
FYI, currently working around this by munging data in the circuit.
