### ISSUE TITLE
Carefully consider range optimizations in ssa pass as the black box function calls relies on them

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1467]
### Problem

Link to comment is [here](https://github.com/noir-lang/noir/pull/1437#discussion_r1210826388).

The crux of the issue being that intrinsic methods rely on the type to figure out how many bits to take from a field element. If these are optimized out in SSA, then we get an incorrect program. The reason to optimize these out is because a cast which maps to a range constraint will cost one opcode each.

### Happy Case

The below will be me copy/pasting paraphrasing Jake's comments/solution.

>We could consider removing the actual cast instruction and reinterpreting the type of x without inserting an extra, unnecessary range constraint. So I think there are ways to keep this optimization and work around this problem, but it is also not the most important optimization so it is just something to keep in mind for the future.

Two example programs to illustrate a simple solution:

```
fn main(x: Field) -> pub u64 {
    let y = x as u32;
    y as u64 // easy to optimize out range constraint for widening here
}
```

The above program will create one cast to a u32 and another widening cast to a u64. The widening cast would not require a range constraint.

```
fn main(x: Field) -> pub u64 {
    let _y = x as u32;
    x as u64 // more difficult to optimize out range constraint here
}
```

The above program will generate two casts if we use a simple analysis. Twice for `x`, with bit width u32 and u64. In the future, we can have a more complicated analysis which figures out that `x` can be widened to a u64.

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
These range constraints should be optimized out now.
