### ISSUE TITLE
Extend left shifts operator to handle non-constant shifts

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1478]
### Problem

When the following code is written: `lhs << rhs`.

In Noir, we convert the code to the following `lhs * 2^{rhs}`. At the moment, we only allow the rhs to be a constant so that we can compute 2^rhs in the compiler, however it is possible to make this non-constant by doing a sqaure-and-multiply algorithm.

Ideally this algorithm is implemented in the Noir source code and then used in the compiler somehow, but having a builtin initially is also fine. The reason for wanting it to be in the Noir source code is mainly because it involves conditionals and we would be eating our own dog food. 

### Happy Case

.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
This is related to https://github.com/noir-lang/noir/issues/1265

**Comment by kevaundray** [comment]
Important: Completion of this task involves copying over the bit shift runtime end to end test

**Comment by TomAFrench** [comment]
Looks like it was removed in https://github.com/noir-lang/noir/pull/2044/files#diff-5f9d36a0db26fcae53924b92ae5b7e0b4fc595b0764dad759d689264d1584877

**Comment by guipublic** [comment]
Closing the issue as fixed by #2072
