### ISSUE TITLE
(bb.js): Incorporate dummy backend to nargo that can interop with bb.js

### ISSUE THREAD

**Issue by vezenovm** [noir-lang/noir#1489]
### Problem

With barretenberg's move to `bb.js` there is a divergence in how the new binary expects a circuit to be serialized and the barretenberg structures it expects (`bb.js` has recursion while acvm-backend-barretenberg) does not. We need a backend that has the structures `bb.js` expects and the respective serialization. 

### Happy Case

The previous way of building nargo with `acvm-backend-barretenberg` should remain the same. If some wishes to compile Noir into the format that `bb.js` expects they should build nargo using `cargo install --path=crates/nargo_cli --no-default-features --features=bb_js`. This will be an advanced user feature until `bb.js` is integrated into `nargo`. A user should then be able to do `nargo compile <CIRCUIT_NAME>` and `nargo execute witness` to interop with `bb.js` which expects a circuit json file and a witness file. 

The tech debt from this dummy backend should be minimal and easy to reverse.

### Alternatives Considered

We will eventually move to incorporating `bb.js` into nargo and then to a final solution once dynamic backends are fully ready. This is a temporary solution to get `bb.js` (which included the low-memory prover and recursion) integrated with Noir, and will be moved away from. 

The current dummy backend also does not handle methods that require simulation such as `pedersen`. This will most likely only come once we have a clean way for nargo to interop with `bb.js`.

### Would you like to submit a PR for this Issue?

Yes

**Comment by Savio-Sou** [comment]
Superseded by https://github.com/noir-lang/noir/issues/1569?

**Comment by kevaundray** [comment]
> Superseded by #1569?

Yep

**Comment by vezenovm** [comment]
This PR https://github.com/noir-lang/noir/pull/1876 when used with this serialization tool https://github.com/vezenovm/acir-to-bberg-circuit should get Noir master in line with bb.js
