### ISSUE TITLE
Make `--show-output` a feature of execution rather than compilation

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#1497]
### Problem

By default log directives aren't compiled into the ACIR unless the `--show-output` flag is used.

### Happy Case

The decision whether or not to show print statements should probably be determined at the time of simulation rather than at the time of compilation.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
Superceded by https://github.com/noir-lang/noir/issues/1971
