### ISSUE TITLE
Remove generational arenas

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#15]
For the use-case it is possible to opt for a simpler arena implementation like la-arena. Which also allows you to tag your data structure.

**Comment by kevaundray** [comment]
@f01dab1e please give this a try when you are free!

**Comment by kevaundray** [comment]
la-arena is here: https://docs.rs/la-arena/latest/la_arena/ fyi

**Comment by jfecher** [comment]
We never free these items so we can just use `Vec`
