### ISSUE TITLE
Cannot parse empty constructor expressions

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#152]
Constructor expressions like `MyStruct { field1: 3, field2: 5, ... }` currently must be non-empty to avoid parsing conflicts when parsing an expression followed by an empty block. For example, in both `if a {}` and `for i in 0..a {}` we would otherwise end up being over-eager when parsing the expression, resulting in us parsing `Constructor(name: a, fields: [])` as the expression rather than just `a`.

It may need to be the case that if we parse an empty constructor expression we also need to check the token after it to make sure it continues the expression or is a terminator that is not`{` (such as `=`, `;`, or keywords like `let`, `fn` in the case of error recovery of a missing semicolon).

**Comment by kevaundray** [comment]
@jfecher whats the status on this?

**Comment by jfecher** [comment]
Still open, I haven't worked on it.

**Comment by kevaundray** [comment]
Closed by #1916
