### ISSUE TITLE
Expand documentation on how the `truncate` instruction is ensuring that `b = lhs mod 2^rhs`

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1522]
### Problem

This instruction was introduced in #1518 -- We should add more documentation on how the constraints are being laid out in `generated_acir.rs`

### Happy Case

.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@guipublic what is the status of this?

**Comment by guipublic** [comment]
Since truncate is using division, it is now obvious. I have added a small comment to explain in PR #2082
