### ISSUE TITLE
Move printing errors to nargo_cli

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1537]
### Problem

Currently errors are printed in noirc_driver to stdout, which is counter-intuitive for a crate that should be a library.

### Happy Case

We can move the printing of errors to `nargo_cli` instead

### Would you like to submit a PR for this Issue?

No

**Comment by f01dab1e** [comment]
I will take care of it. Do I need to remove the printing from those places, right?

https://github.com/noir-lang/noir/blob/ae7ac21a796171e8e6c28b3184cc744788d9ecaa/crates/noirc_driver/src/lib.rs#L194-L200
https://github.com/noir-lang/noir/blob/ae7ac21a796171e8e6c28b3184cc744788d9ecaa/crates/noirc_driver/src/lib.rs#L313-L314

Try introducing a new error type.

**Comment by kevaundray** [comment]
@f01dab1e 

> I will take care of it. Do I need to remove the printing from those places, right?

Those print lines can stay for now, its mostly just about removing the error printing in noirc_driver and having the caller do the printing.

>Try introducing a new error type.

Yeah I think we need to think about the Diagnostic and CustomDiagnostic types and whether the caller needs to have a FileManager.
