### ISSUE TITLE
Discussion around whether the 0 constant should be seen as `Unit` or `Field 0`

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1541]
### Problem

Link to relevant comment which also links the section in the code: https://github.com/noir-lang/noir/pull/1530#discussion_r1217804760

### Happy Case

.

### Would you like to submit a PR for this Issue?

No

**Comment by joss-aztec** [comment]
I think the question is upside down - shouldn't it be possible to have as many type variants of a given constant as is necessary?

The only gotcha I can think of is in tracking bit size. Arguably the bit size should just only be large enough to hold the constant's value. Whether or not that happens in the SSA IR of acir gen is probably another discussion. (Relates to GH-1529)

**Comment by jfecher** [comment]
Constants have a type that can be used to determine their bitsize. I agree with @joss-aztec that a given number like 0 may have different types depending on the context (unit, u8, u32, ...).

I think the unit type does not serve much purpose in the SSA IR and should ideally be removed. The main issue is that it is needed in the SSA-gen pass and after experimenting with it a bit, it is not a trivial change to remove it. For example, SSA-gen would need its own `Type` enumeration that includes `Unit` if it were to be removed from the type enumeration that the rest of SSA uses.

**Comment by kevaundray** [comment]
We've removed 0 being seen as the unit type, so closing this issue
