### ISSUE TITLE
Refactor nix flake file to build noir_wasm using external .sh files

### ISSUE THREAD

**Issue by jonybur** [noir-lang/noir#1544]

**Comment by jonybur** [comment]
Tried to refactor this, but seems like the solution is non-trivial. Got a second opinion from @phated about it, the reason why the flake is not allowing for external .sh files to be loaded up is not obvious. I tried adding a .sh filter to the srcFilter on the flake with no success.

**Comment by kevaundray** [comment]
@jonybur whats the status of this?

**Comment by jonybur** [comment]
This has been done and merged. I'll close this.
