### ISSUE TITLE
Generate Brillig code to handle foreign calls

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1557]
### Problem

This also needs to be specified a bit further, following the fact that we have moved foreign calls into Brillig whereas before they were a concept separate from Brillig.

### Happy Case

.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
Going to leave this open as we do not currently generate Brillig code for a foreign function call yet

**Comment by ludamad** [comment]
Can this be closed?

**Comment by ludamad** [comment]
Enacting "ask forgiveness not permission" :D
