### ISSUE TITLE
Investigate  when the span's starting range is more than the end range

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#156]
## Problem 

[Here](https://github.com/noir-lang/noir/blob/0647dbfda437fcc4c0cf3b4717ad7dae39096e41/crates/noirc_errors/src/position.rs#L62) we check if range.start > range.end . This is quite unusual and @jfecher mentioned that it's possibly a bug in the parser combinator we use.

## Suggested Fix

Investigate and confirm the reason for this and write a comment above the function explaining it

**Comment by kevaundray** [comment]
Link to comment in PR: https://github.com/noir-lang/noir/pull/153#discussion_r798768557

**Comment by kevaundray** [comment]
@jfecher what's the status on this?

**Comment by jfecher** [comment]
I'll look into it again. I believe it was an issue with a specific commit in chumsky that may have been fixed since.

**Comment by TomAFrench** [comment]
This is fixed as far as I remember.
