### ISSUE TITLE
Add unconstrained tag to functions when printing out SSA IR

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1562]
### Problem

Consider the following program:

```
fn main(x : Field)  {
    assert(x == identity(x));
}

unconstrained fn identity(x : Field) -> Field {
  x
}
```

It will output the following SSA:

```
fn identity f1 {
  b0(v0: Field):
    return v0
}
fn main f2 {
  b0(v0: Field):
    v2 = call f1(v0)
    v3 = eq v0, v2
    constrain v3
    return unit 0
}
```

Its not immediately clear that `identity` is an unconstrained function.

### Happy Case

Add unconstrained label to the function when debugging

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@sirasistant I vaguely remember you doing something like this during debugging. What are your thoughts on this? Please close the issue if you think it is not worthwhile

**Comment by sirasistant** [comment]
It was done in an unrelated PR https://github.com/noir-lang/noir/blob/master/crates/noirc_evaluator/src/ssa_refactor/ir/printer.rs#L18. Closing this.
