### ISSUE TITLE
Enable full nargo <-> bb.js interop

### ISSUE THREAD

**Issue by vezenovm** [noir-lang/noir#1569]
### Problem

The current dummy backend in [this PR](https://github.com/noir-lang/noir/pull/1491) currently only enables someone working with the `bb.js` backend (found here: https://www.npmjs.com/package/@aztec/bb.js), to compile their circuit and execute a witness into the format that bb.js expects. The current workflow to work with `bb.js` is to run nargo compile and nargo execute, but then use a global `bb.js` executable for any proving and verification. 

In order to enable using `bb.js` with nargo we need to add a communication layer for this to be possible. This communication layer is also necessary for us to enable ACVM simulation for black box funcs that need to communicate with the backend (such as pedersen, schnorr, etc.)

### Happy Case

`nargo` should work with `bb.js` as it does for our `plonk_bn254` and `plonk_bn254_wasm` backends. 

### Additional Context

With `bb.js` now including recursion we will have to expose this feature while it will not be supported by our other backends. 

### Would you like to submit a PR for this Issue?

No

**Comment by Savio-Sou** [comment]
The [kh-nargo-abackend](https://github.com/noir-lang/noir/tree/kh-nargo-abackend) branch enables Nargo <> bb.js interop, works as a transitionary solution to this intermediate issue.

Long term barretenberg and any other proving backends should be packaged into standalone executables with minimum dependencies (versus e.g. bb.js that requires Node.js to run in CLI) and interface with Nargo.

**Comment by kevaundray** [comment]
Related https://github.com/noir-lang/noir/issues/595

**Comment by Savio-Sou** [comment]
@TomAFrench / @kobyhallx can we consider this to be superseded by https://github.com/noir-lang/noir/issues/2164?

**Comment by Savio-Sou** [comment]
Superseded by https://github.com/noir-lang/acvm-backend-barretenberg/issues/245, where Noir now interops with bb binary (instead of bb.js).
