### ISSUE TITLE
Handle arrays in SSA form

### ISSUE THREAD

**Issue by guipublic** [noir-lang/noir#157]
Arrays are not compatible with SSA because any assignment would invalidate the whole array. So we need to handle specifically arrays in the SSA form. In particular we need to:
1. during parsing (of the AST); generate relevant `store` and `load` instructions to access memory locations
2. during optimisation phase; remove redundant memory access
3. inside overflow strategy; handle static memory access and compute max values
4. during acir generation; generate constraints for dynamic access (permutation proof and consistency checks) or use appropriate backend gate if available
5. during solving phase; load proper array values using info from previous steps.

**Comment by kevaundray** [comment]
@guipublic can this be closed?

**Comment by jfecher** [comment]
Closing this issue, arrays are already handled in ssa
