### ISSUE TITLE
Generate RecursiveAggregation AcirOpcode in SSA refactor

### ISSUE THREAD

**Issue by vezenovm** [noir-lang/noir#1570]
### Problem

The SSA refactor currently does not handle calling the RecursiveAggregation black box func. This should be included to enable compilation of `verify_proof` to match the current SSA pass.

### Happy Case

We should be able to successfully generate a `BlackBoxFuncCall::RecursiveAggregation` ACIR opcode that can then be accepted by a prover (currently only `bb.js` to generate recursive proofs).

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@vezenovm what is the status of this?

**Comment by vezenovm** [comment]
@kevaundray still todo. I will add this when I'm back next week
