### ISSUE TITLE
Nargo: Provide formatting subcommand

### ISSUE THREAD

**Issue by phated** [noir-lang/noir#1580]
### Problem

Nargo should provide a `nargo format` command that will format files and write them back to a filesystem.

### Happy Case

A user can write code in whatever format they want, but running `nargo format` will always produce the same output.

### Additional Context

See also:
- prettier
- cargo fmt
- grain format

### Would you like to submit a PR for this Issue?

No

**Comment by hhamud** [comment]
Any idea when this will be prioritized?
