### ISSUE TITLE
Generate Brillig code to handle modulo/truncate/cast operation

### ISSUE THREAD

**Issue by sirasistant** [noir-lang/noir#1589]
### Problem

Brillig doesn't have a modulo opcode, however it can be emulated with simple instructions. When the Brillig codegen from SSA is more consolidated, we should decide where is best to apply this emulation.

### Happy Case

```rust
unconstrained fn add_int(x : u32, y : u32) -> u32 {
 x % y
}
```

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
This has been merged into our ssa refactor branch, but leaving it open to handle truncate and cast which use modulo
