### ISSUE TITLE
Fix SSA value substitution

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#1592]
### Aim

Fix bugs present in the [ssa printer](https://github.com/noir-lang/noir/issues/1451) and [ACIR gen](https://github.com/noir-lang/noir/pull/1535#issuecomment-1580848584)

### Expected Behavior

During SSA passes (namely mem2reg), we should substitute `ValueId`s at their point of use instead of changing a `ValueId`'s underlying `Value`.

### Bug

-

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@jfecher whats the status of this?

**Comment by jfecher** [comment]
This was fixed when we added the `replaced_value_ids` map
