### ISSUE TITLE
Generalize implementation of `extern` functions

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#160]
Extern functions are meant as mechanisms for users to allow noir code to call into external C code - for example to provide a database call that supplies extra parameters to a function. The difficulty implementing the "call into C code from the noir compiler" side stems from needing to know the type of the function called at compile time so that it can be casted into a function pointer. For example, if we were to use libloading:
```rs
let lib = libloading::Library::new("/path/to/liblibrary.so")?;
let func: libloading::Symbol<unsafe extern fn() -> u32> = lib.get(b"my_func")?;
func()
```

Getting this `unsafe extern fn() -> u32` type known at compile-time for all extern functions noir may call into implies either us limiting the set of possible functions to call into, or standardizing the signatures on the C side into some combination of type-erased `void*`s. With this in mind, I see 4 main ways of implementing the "call into C code" functionality of extern from the rust compiler:

1. Have a limited number of extern functions in noir that are all builtin - the user can't define their own. This way we can just match over the name and cast to the corresponding type in each branch.
2. Allow users to define their own extern functions, but limit their maximum number of parameters. This way, we can match over the Noir function type to gradually build up the actual function type. This match will be exponentially uglier the more parameters that are allowed however. It would require `1 + M^N` match branches if we want to allow functions with a maximum of `N` parameters to use `M` available noir types. Even if we only allow 4 primitive noir types to be used for functions up to 4 parameters, implementing this would still require `1 + 4^4 = 257` match branches, making it impractical.
3. Allow users to define their own extern functions, but standardize things on the C side, so that noir always expects to call a C function with the signature noir_value my_extern_fn(noir_args args); where noir_args and noir_value are both presumably typedefs for `void**` or `void*`. This would rely on the user to do any argument checking they want/need. It may also require we provide a small C header for managing `noir_args`. Example:
```c
noir_value my_extern_fn(noir_args args) {
    assert(noir_args_len(args) == 2);
    int first = noir_int(noir_args_get(args, 0));
    noir_field second = noir_field(noir_args_get(args, 1));
    ...
    return noir_make_int(5);
}
```
4. Hybrid of 2 and 3 in which the C functions take in each argument as a `void*` but still have separate arguments compared to `3` where they are all packed into a single `void**`. Compared to option 3, this would require less casting and checking on the users part, and compared to 2 our implementation would still be limited to a finite number of parameters, but matching on the size would grow linearly (N+1 cases for N parameters) rather than exponentially.
```c
typedef void* noir_value;

noir_value my_extern_fn(noir_value param1, noir_value param2) {
    int first = *(int*)param1;
    noir_field second = *(noir_field*)param2;
    ...
    // open question: do we require this return value to be owned so we may free it?
    int* ret = malloc(sizeof(int));
    *ret = 5;
    return ret;
}
```
This last option also allows a slightly simpler version since the different pointer types are binary compatible:
```c
int* my_extern_fn(int* param1, noir_field* param2) {
    int first = *param1;
    noir_field second = *param2;
    ...
    return ret;
}
```

**Comment by kevaundray** [comment]
We went with a different strategy after-all for this where users can define foreign functions in brillig in order to do things like database calls. This ultimately allows us to abstract away the fact that C code is being used etc
