### ISSUE TITLE
Rationalise properties of `Truncate` instruction

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#1604]
### Problem

Some properties of the current `Truncate` instruction are potentially not beneficial to the SSA passes planned to operate of them, and are possibly leaking an implementation detail from ACIR-gen.

### Happy Case

Create a clearer separation between the truncation information required for the SSA passes, and the truncation information that ACIR-gen can conveniently infer itself.

This may involve removing properties from the instruction, or perhaps even removing the instruction is favour of encoding it as a property on binary operator.

### Would you like to submit a PR for this Issue?

No

**Comment by joss-aztec** [comment]
Backlink: https://github.com/noir-lang/noir/pull/1568#discussion_r1222091428

**Comment by kevaundray** [comment]
In normal euclidean division, q is not explicitly bounded, so we should provide a rationale as to why we do it here

**Comment by guipublic** [comment]
I am closing the issue since the integer division is now correct.
