### ISSUE TITLE
Generate Brillig code to handle normal calls to other brillig functions and constrained functions

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1608]
### Problem

Generate Brillig for the following code:

```rust
fn constrained_identity_func(y : u32) -> u32 {
  y
}

unconstrained fn inner(x : u32, y : u32) -> u32 {
 x + y
}

// Calls a constrained function and then calls an unconstrained function
unconstrained fn outer(x : u32, y : u32) -> u32 {
   let z = constrained_identity_func(y); 
   inner(x, z)
}

```

### Happy Case

.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
Internally in slack it was mentioned that we want to split this issue into sub issues:

- unconstrained calling unconstrained
- constrained calling unconstrained (This is already tested)
- unconstrained calling constrained

@guipublic assigning `unconstrained calling unconstrained` task to you

**Comment by kevaundray** [comment]
@sirasistant what is the status of this issue?

**Comment by sirasistant** [comment]
Resolved by https://github.com/noir-lang/noir/pull/1919
