### ISSUE TITLE
Handle floating point operations in Noir

### ISSUE THREAD

**Issue by guipublic** [noir-lang/noir#161]
Float data types and floating points operations are not supported in Noir. However, floating point operations can enable a wide range of applications, for instance in finance or data science.
To support them we would need to:
1. add float data types into Noir frontend
2. map float objects to field elements in the backend
3. translate floating point operations into field operations
4. provide helper functions for standard computations (e.g. sqrt, sin?)

**Comment by kevaundray** [comment]
@Savio-Sou Here is an old issue detailing floating points, its probably not something we need to add into the compiler and is super low priority

**Comment by Savio-Sou** [comment]
Thanks Kev! Agree that floats won't be an immediate priority

Given how fairly frequently it's brought up in the community on Discord / Twitter however, it'd be nice to get it in the medium-term (e.g. Q1 2024) as a nice-to-have if no one commits to building a library for it before then.

Let's revisit and talk details at a later date.

**Comment by kevaundray** [comment]
Closing this as not applicable since most users can just do quanitization
