### ISSUE TITLE
Schnorr verify blackbox fails

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#1623]
### Aim

The integration test named `schnorr` should pass

### Expected Behavior

^

### Bug

It compiles but fails with the following error:
```
Error: failed to solve blackbox function: schnorr_verify, reason: sig_s should be 32 bytes long, found only 2 bytes
```

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by joss-aztec** [comment]
The only visible difference in the ACIRs printed for the old SSA and the new is that the final arithmetic expression is inverted. This seems inconsequential, so it could be that the printed ACIR omits logging some problematic property.

**Comment by guipublic** [comment]
Closing the issue as the test is now working fine.
