### ISSUE TITLE
Array equality

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#1625]
### Problem

Array equality isn't implemented in the ssa refactor's acir gen. Currently binary ops only support numerics, and not arrays.

### Happy Case

The following program should compile (taken from `array_neq` test):
```nr
// Simple example of checking where two arrays are different
fn main(a: [Field; 32], b: [Field; 32]) {
     assert(a != b);
}
```

### Would you like to submit a PR for this Issue?

No

**Comment by joss-aztec** [comment]
Also affects integration test `7`

**Comment by joss-aztec** [comment]
Test named `generics` affected.

**Comment by joss-aztec** [comment]
Test named `8_integration` affected.

**Comment by joss-aztec** [comment]
Affects test named `global_consts`

**Comment by joss-aztec** [comment]
`7_function`

**Comment by joss-aztec** [comment]
Also affects integration test `6`

**Comment by joss-aztec** [comment]
`struct_inputs`

**Comment by jfecher** [comment]
I'd be in favor of replacing the array equality `a1 == a2` in each of these tests with 

```rs
fn array_eq<T, N>(a1: [T; N], a2: [T; N], elem_eq: fn(T, T) -> bool) -> bool {
    let mut result = true;
    for i in 0 .. a1.len() {
        result &= elem_eq(a1[i], a2[i]);
    }
    result
}
```

Supporting `==` for all `[T]` regardless of `T` as we have now is a type soundness issue anyway.

**Comment by joss-aztec** [comment]
Affects test named `keccak256`

**Comment by joss-aztec** [comment]
Affects `sha256`
