### ISSUE TITLE
Generate Brillig for array inputs and outputs 

### ISSUE THREAD

**Issue by vezenovm** [noir-lang/noir#1627]
### Problem

We currently only support the `Numeric` SSA type when converting SSA block params to Brillig, thus, we cannot use arrays in our inputs to unconstrained functions. Our `convert_ssa_value` function also only currently supports singular SSA values and not `Value::Array`. 

### Happy Case

We should be able to pass arrays into unconstrained functions and also output them

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@vezenovm what is the status of this issue?

**Comment by vezenovm** [comment]
Completed in #1630
