### ISSUE TITLE
codegen test fail

### ISSUE THREAD

**Issue by Ethan-000** [noir-lang/noir#1634]
### Aim

run `cargo test`

### Expected Behavior

codegen test pass

### Bug

codegen test didn't pass

### To Reproduce

1. install `nix` `direnv` as the instructions
2. run `cargo test`
3.
4.

### Installation Method

Compiled from source

### Additional Context

<img width="327" alt="codegen" src="https://github.com/noir-lang/noir/assets/70556667/cb2222e1-610a-4e7a-8bbb-8b5fc7aba06e">

### Would you like to submit a PR for this Issue?

Maybe

### Support Needs

wondering if this is specific to my setup.  `simple_verifier_codegen` seems to be failing when running `cargo test`

**Comment by yordanmadzhunkov** [comment]
@Ethan-000 

I have the same problem on two of my machines with latest master

simple_verifier_codegen fails

**Comment by yordanmadzhunkov** [comment]
can you provide example command how to that for people that will find this issue in the future
