### ISSUE TITLE
Test `struct_inputs` doesn't compile

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#1637]
### Aim

Test name `struct_inputs` should compile under SSA refactor.

### Expected Behavior

^

### Bug

Panics with:
```
The application panicked (crashed).
Message:  internal error: entered unreachable code: ICE: Params to the program should only contains numbers and arrays
Location: crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs:124
```

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by ludamad** [comment]
This seems to have been fixed at some point

**Comment by jfecher** [comment]
I'm not exactly sure when, but as this is no longer occurring on master, it looks like this has been fixed. We can re-open this or a new issue if a similar crash is later found again.
