### ISSUE TITLE
Brillig linking could result in code segments being overwritten

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1638]
### Problem

See [here](https://github.com/noir-lang/noir/blob/5ea79e6ea480a717dfbafd4bffa288c1b634063e/crates/noirc_evaluator/src/brillig/brillig_ir/artifact.rs#L68)

When we are linking two independent artifacts, it could be the case that their labels collide and one artifact overwrites the labels in another artifact.

A traditional linker may error here or in some cases just issue a warning. 

### Happy Case

We should provide an error here and in order to ensure that the labels are unique, we can add the function ID and possibly the name to the label, instead of just the basic block ID

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
This may be more helpful if it was stateful, ie when we are in a particular block, and we add a label, it will automatically prepend the function id and block. Then when you exit the block, you "pop off" that block from the label stack

**Comment by kevaundray** [comment]
@sirasistant what is the status of this issue?

**Comment by sirasistant** [comment]
It was done in https://github.com/noir-lang/noir/pull/1652, It didn't auto close because it was merged to a branch that we used as a  batch merge to master. Closing this!
