### ISSUE TITLE
Refactor ForeignCall instruction

### ISSUE THREAD

**Issue by vezenovm** [noir-lang/noir#1643]
### Problem

See comment here (https://github.com/noir-lang/noir/pull/1600#discussion_r1226746738).

We should be able to create a new Value type and follow the same flow as intrinsics rather than having a separate ForeignCall instruction.

### Happy Case

Remove ForeignCall instruction and maintain same foreign call functionality 

### Alternatives Considered

The existing work is an alternative as foreign calls work as expected. The solution in this issue will enable us to remove an instruction. 

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@vezenovm can this be closed?

**Comment by vezenovm** [comment]
Yes closed by #1644
