### ISSUE TITLE
Closures are unsupported in the ssa refactor

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#1662]
### Problem

SSA refactor has no support for high order functions

### Happy Case

(Issue opened for tracking - suggestions to be documented later.)

### Would you like to submit a PR for this Issue?

No

**Comment by joss-aztec** [comment]
Affected integration test: `higher_order_functions`

**Comment by jfecher** [comment]
I don't think this is correct, the ssa refactor should support higher order functions. It is just that closures require a separate closure conversion pass before SSA, see #1254
