### ISSUE TITLE
`2_div` compiles to unsolvable circuit

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#1695]
### Aim

Test name `2_div` should compile and execute

### Expected Behavior

^

### Bug

```
Error: could not satisfy all constraints
```

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by guipublic** [comment]
Closing the issue as the test is now working fine.
