### ISSUE TITLE
Consider removing `Instruction::{ Allocate, Load, Store }` in the Ssa refactor

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#1703]
### Problem

The existence of allocate, load, and store instructions in the Ssa refactor necessitates we have a separate pass (mem2reg) to later convert our IR into proper SSA form. This can mean any pass before mem2reg may not be able to handle mutable values as well since they will not be able to see what is stored within them.

### Happy Case

We can remove these instructions and the need for an extra pass if we represent mutable variables as block arguments instead. Using block arguments over allocations does come with a decrease in expressiveness, however, if we are no longer considering adding first-class references and limit ourselves to only second-class references (see #1702), we won't need the extra expressiveness allowed by allocations anyway.

As for the issue of passes before mem2reg not being able to see into mutable values, this can be alleviated somewhat by switching to block arguments. Values that are still control flow dependent still won't be able to be peeked into as they will be `Value::Param`s, but subsequent mutations within the same block will be known if there is no branching. For example:
```rs
let mut x = 0;
x = 1;
x = 2;
x == 2
```
Will currently produce the IR (before optimizations):
```
v0 = allocate
store Field 0 in v0
store Field 1 in v0
store Field 2 in v0
v1 = load v0
v2 = eq v1, Field 2
```
With block arguments the IR (without optimization passes) would be completely empty as the entirety would be constant folded to `true`. To achieve this, we'd need to keep track of the most recent value a variable is assigned in each block. This is the job of the `Variable` struct in cranelift for example.

### Alternatives Considered

It is worth noting we can do the same tracking of most recent value assigned in a block with our current allocates and stores. This would give us a similar final IR of:

```
v0 = allocate
store Field 0 in v0
store Field 1 in v0
store Field 2 in v0
```

Where only the final two instructions are folded away and known to be true. Doing this tracking with stores is a bit messier since the allocations and stores are left within the program and need to be removed by the mem2reg pass still.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@jfecher I imagine we want to do this sooner rather than later, if we plan to do it at all. What would be blocking a decision on this?

**Comment by jfecher** [comment]
We have added first class mutable references now which require these instructions. It was only when mutability was only on the "outside" of a variable that we could remove these instructions. So they are required now.
