### ISSUE TITLE
Assertion `(op.access_type == 0)' failed

### ISSUE THREAD

**Issue by ax0** [noir-lang/noir#1706]
### Aim

Try to generate a proof for [this code](https://github.com/aragonzkresearch/noir-trie-proofs/tree/main/tests/depth_8).

### Expected Behavior

A proof should be generated.

### Bug

We get the following error:
```
nargo: /build/cpp/src/barretenberg/dsl/acir_format/block_constraint.cpp:41: void acir_format::create_block_constraints(acir_format::Composer &, const acir_format::BlockConstraint, bool): Assertion `(op.access_type == 0)' failed.
```

### To Reproduce

1. Clone [this repo](https://github.com/aragonzkresearch/noir-trie-proofs).
2. Navigate to `tests/depth_8`.
3. Run `nargo prove`.

### Installation Method

Compiled from source

### Nargo Version

nargo 0.6.0 (git version hash: 242f07b513c0f7141c0c661e6c7913db04eeccef, is dirty: false)

### Would you like to submit a PR for this Issue?

No

**Comment by Savio-Sou** [comment]
Copying Ahmad's extra context here:

> Here's a slightly simpler example (assuming you include my repo as a dependency):
> ```rust
> use dep::trie;
> use dep::trie::{get_fixed32, key_as_nibbles, KEY_LENGTH, NIBBLE_LENGTH, TrieProof32};
> 
> global N = 2;
> 
> fn main(root_hash: pub [u8; 32], trie_proof: trie::TrieProof32<100>) {
>     let _r = root_hash;
>     
>     let key = trie_proof.key;
>    
>     let key_nibbles: [u4; NIBBLE_LENGTH] = key_as_nibbles(key);
>     
>     let mut key_offset = 0;
> 
>     let path = trie_proof.proof; // Proof path
> 
>     let depth = trie_proof.depth; // Depth of proof path
> 
>     for i in 0..N
>     {
> 	    if (i as u8) < (depth as u8)
> 	    {
>  	        let _lookup = get_fixed32(key_nibbles, key_offset, path); // Follow node
> 	    }
>     }
> }
> ```
> The error goes away if `N = 1`. (`get_fixed32` is called in `one_level` and the error does not occur there.)
