### ISSUE TITLE
Epic: Noir Debugger

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#1723]
# Noir Language Debugger

# Goals

# Requirements
- ACVM needs to support stepping through execution. (Currently it proceeds until execution is complete or stalled on foreign call)

https://code.visualstudio.com/api/extension-guides/debugger-extension
```[tasklist]
### Tasks
- [ ] https://github.com/noir-lang/acvm/issues/382
- [ ] https://github.com/noir-lang/noir/issues/2247
```

**Comment by Savio-Sou** [comment]
Closing as I assume https://github.com/noir-lang/noir/issues/3015 supersedes this. Feel free to reopen if not.
