### ISSUE TITLE
Optimistically assume that Mac runner will pass

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1743]
### Problem

Currently MacOS takes quite a long time, though for most PRs, if ubuntu passes, then Mac passes too.

### Happy Case

We can:

- Add ability to add a label to run MacOS on a particular PR
- Always run MacOS on masters

The label is due to the fact that certain changes will likely need to be tested with MacOS before merging due to the high likely hood of them failing. For example, if the barretenberg dependency is updated or if CI is updated.

The second ensures that we don't neglect MacOS and coupled with the merge queue, we can amortize the MacOS runner over multiple PRs in the queue since the merge queue can merge together multiple PRs before trying to merge to master.

### Would you like to submit a PR for this Issue?

No

**Comment by phated** [comment]
You currently can't have required checks for MQ but not for the branch; you'd have to have a run "skip with success" but that makes debugging failures very confusing when they only happen in the MQ.

**Comment by kevaundray** [comment]
@guipublic suggested running execute on Mac and prove and verify on linux
