### ISSUE TITLE
Replace directives with brillig opcodes

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1772]
### Problem

Brillig is a more general version of directives. 

We can now start to replace usage of directives with Brillig opcodes in the compiler.

### Happy Case

All directives are replaced.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
This issue which needs the sorting directive will be superceded by this once we implement it as brillig bytecode: https://github.com/noir-lang/noir/issues/1687

**Comment by TomAFrench** [comment]
Not suggesting that we should do this immediately but once we've migrated all directives to brillig, I think it may be useful to push some of this down to a "brillig stdlib" in similarly to how we have `acvm_stdlib`.

**Comment by kevaundray** [comment]
> Not suggesting that we should do this immediately but once we've migrated all directives to brillig, I think it may be useful to push some of this down to a "brillig stdlib" in similarly to how we have `acvm_stdlib`.

That makes sense -- we have a generated_acir folder in ssa_refactor which has components that could also be migrated to acvm_stdlib -- it essentially just deals with acir construction
