### ISSUE TITLE
A way to access other (and my own) contract's portal addresses 

### ISSUE THREAD

**Issue by rahul-kothari** [noir-lang/noir#1777]
### Problem

Can't access portal addresses of my contract or even someone else's - so need to pass in more args which isn't good dev ex

### Happy Case

perhaps `context.l1PortalAddress` for my own and an oracle call to determine someone else' portal address (given an L2 contract address).

### Additional Context

Comes from https://github.com/AztecProtocol/aztec-packages/blob/923013a9bbab3999d1489983298ef9b50238320f/yarn-project/noir-contracts/src/contracts/uniswap_contract/src/main.nr#L17 where we are using L2 funds to swap on Uniswap on L1 via a uniswap portal contract on Aztec

### Would you like to submit a PR for this Issue?

No

**Comment by Savio-Sou** [comment]
@kevaundray should we close this as won't fix?
