### ISSUE TITLE
account abstraction using its own "custom" constants instead of using shared constants...

### ISSUE THREAD

**Issue by rahul-kothari** [noir-lang/noir#1779]
### Problem

Consider `abi.nr` where we store `MAX_ARGS`. If I want to change this, I need to manually find all places where this is used and update there too since I can't read the MAX ARGS slot like in  [entrypoint.nr](https://github.com/AztecProtocol/aztec-packages/blob/923013a9bbab3999d1489983298ef9b50238320f/yarn-project/noir-contracts/src/contracts/noir-aztec3/src/entrypoint.nr#L30) - notice how because we can't do math or refer other storage slots, we have to manually update the counts everywhere. 

When updating MAX_ARGS, I actually didn't know where else it had to be updated (because relevant comments weren't there) so everything broke temporarily (ty @sirasistant for your help btw!)

### Happy Case

Instead of 
```
// MAX_ARGS * (ACCOUNT_MAX_PUBLIC_CALLS + ACCOUNT_MAX_PRIVATE_CALLS)
global ACCOUNT_FLATTENED_ARGS_SIZE: comptime Field = 32;
```

have:
```
global ACCOUNT_FLATTENED_ARGS_SIZE: comptime Field = abi::MAX_ARGS * (....)
```

this would also prevent the number of vars that need to be passed in!

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
This looks like a potential duplicate of https://github.com/noir-lang/noir/issues/1734. Can you confirm if allowing globals to reference other globals would solve your issue?

**Comment by rahul-kothari** [comment]
yup is a duplicate my bad!
