### ISSUE TITLE
Cannot call method on returned generic type.

### ISSUE THREAD

**Issue by LeilaWang** [noir-lang/noir#1784]
### Aim

The compiler complains when I tried calling a method on a generic type returned from a function.

### Expected Behavior

It should work.

### Bug

An example:

```rust
struct Item {
    id: Field,
}

impl Item {
    fn log(self) {
        let id = self.id;
        std::println(id);
    }
}

fn create<V>(something: V) -> V {
    something
}
```

I can access the id:

```rust
let a = Item { id: 1 };
let b = create(a);
let id = b.id;
std::println(id);
b.log();
```

But it failed on calling the `log` method:

```
error: No method named 'log' found for type 'Item'
    │
114 │     b.log();
    │
```

It worked if I specified the type:

```rust
let a = Item { id: 1 };
let b: Item = create(a);
b.log();
```

But it gets ugly when lots of code depend on generics.

### Installation Method

None

### Nargo Version

nargo 0.6.0 (git version hash: 0181813203a9e3e46c6d8c3169ad5d25971d4282, is dirty: false)

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
PR #1785 has been merged which should fix this issue
