### ISSUE TITLE
`Self` doesn't resolve when calling static struct methods as `Self::f`

### ISSUE THREAD

**Issue by shuklaayush** [noir-lang/noir#1791]
### Aim

I was trying to use the `Self` keyword as a path to call the static `one()` method in noir

```rust
struct S { }

impl S {
    fn one() -> Field {
        1
    }

    fn two() -> Field {
        Self::one() + Self::one()
        // This compiles
        // S::one() + S::one()
    }
}

fn main() { }
```

### Expected Behavior

`Self` keyword should be resolved in the path, allowing for the method to be called, just as it would be in Rust.

### Bug

When attempting to use the `Self` keyword in noir, the following error is thrown: 
```
error: Could not resolve 'Self' in path.
```

### To Reproduce

1. Copy the code above
2. Run `nargo compile --allow-warnings`

### Installation Method

Compiled from source

### Nargo Version

nargo 0.6.0 (git version hash: 0181813203a9e3e46c6d8c3169ad5d25971d4282, is dirty: false)

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@jfecher is this still an issue?

**Comment by michaeljklein** [comment]
Just ran into this:

```rust
struct Foo { }

impl Foo {
    fn foo() { }

    fn bar() {
        Self::foo()
    }
}
```
