### ISSUE TITLE
Add distinct keyword

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1796]
### Problem

Original issue for this is: https://github.com/noir-lang/noir/issues/1183

### Happy Case

We want to add this into the new SSA code

### Would you like to submit a PR for this Issue?

No

**Comment by ludamad** [comment]
Just curious, why a keyword and not an ABI passed when running Noir?

**Comment by kevaundray** [comment]
> why a keyword and not an ABI passed when running Noir? 

What would that look like ser?

>Will non-main functions use this keyword?

Good question, this will only have effect on the entry point function(s) -- I use plural here because contracts have multiple entry point functions

**Comment by kevaundray** [comment]
Closing as the distinct keyword has been merged
