### ISSUE TITLE
Cannot solve opcode: missing assignment for witness index 100

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#1799]
### Aim

Tried to prove `sha2_blocks` or `sha2_bytes`

### Expected Behavior

The programs to prove and verify

### Bug

Instead the program errors with `Error: cannot solve opcode: missing assignment for witness index 100` while proving.

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
update: An MVP of the sha2_byte example seems to be:


```
fn digest() -> [u8; 3] {
    let mut out_h: [u8; 3] = [0; 3];
    let mut i = 0;


    for _i in 0..3 {
        i += 1;
        if i == 0 {
            out_h[i] = 0;
        } 
        else if i < 3 {
            out_h[0] = 0; 
        }
    }


    out_h
}
```

**Comment by kevaundray** [comment]
Re-opening since this example is still broken

**Comment by kevaundray** [comment]
Debugging with @jfecher and we found a minimal example:


```
use dep::std;

fn main(x : Field) {
	
	digest();

}
// SHA-256 hash function
fn digest(){
    let mut msg_block: [u8; 4] = [0; 4];
    let mut i = 0; // Message byte pointer


    for _i in 0..4 {
        if i < 2 {
            msg_block[i] = 1;
            i = i + 1;
        } else if i < 4 {
        	msg_block[i] = 2;  
            i += 1;
        }
    }


std::println(msg_block);
}
```

We found that changing from:

```
  if i < 2 {
            msg_block[i] = 1;
            i = i + 1;
        } else if i < 4 {
        	msg_block[i] = 2;  
            i += 1;
        }
```

to 

```
  if i < 2 {
            msg_block[i] = 1;
            i = i + 1;
        } ;
        if i < 4 {
        	msg_block[i] = 2;  
            i += 1;
        }

```

would print the correct answer

**Comment by jfecher** [comment]
> Re-opening since this example is still broken

I don't think we should re-open this since the bug in this issue is still fixed, it is just the example is running into a different error now with satisfying constraints. I made a note of it in #1800

**Comment by kevaundray** [comment]
That's a good point, closing it now
