### ISSUE TITLE
Could not satisfy all constraints for `regression` test

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#1800]
### Aim

Tried to prove and verify the `regression` test

### Expected Behavior

The test should produce a valid proof

### Bug

The test fails to prove and verify, outputtting the message: `Could not satisfy all constraints`

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
After #1815, this also affects `sha2_byte` and `sha2_blocks`

**Comment by kevaundray** [comment]
Minimal example:

```
fn main(input: u8, length: Field) -> pub Field
{
    if input != 1 {}
    else
    {
     let cond = (0 as u64) < (length as u64) - 1;
     if cond{}
    }

    input as Field
}
```

```
// Prover.toml
input = 0x3f
length = 3
```

Note, input does not equal 1, so the then branch should be getting triggered, however we are getting constrained failed on the else branch. Changing `input != 1` to `input == 1` will produce a passing program

**Comment by kevaundray** [comment]
<img width="784" alt="Screenshot 2023-07-18 at 23 44 41" src="https://github.com/noir-lang/noir/assets/37423678/e5a18123-55b8-41fc-9eda-1a29af397eb6">

Error for reference ^

**Comment by kevaundray** [comment]
This error seems to stem from the fact that we are not multiplying the predicate by the expression which constrains the quotient directive, we therefore account for all cases except for when q ==0 and r ==0
