### ISSUE TITLE
Bigint lib

### ISSUE THREAD

**Issue by merfymerf** [noir-lang/noir#1822]
### Problem

a bigint library for noir

### Happy Case

a bigint library for noir

### Additional Context

developer feedback collected during all hands 

### Would you like to submit a PR for this Issue?

No

**Comment by Savio-Sou** [comment]
@shuklaayush is working on one 👀 https://github.com/shuklaayush/noir-bigint

**Comment by Savio-Sou** [comment]
Refer to https://github.com/shuklaayush/noir-bigint#installation for how to install the library. Cheers!
