### ISSUE TITLE
Unchecked maths mod the max int

### ISSUE THREAD

**Issue by merfymerf** [noir-lang/noir#1824]
### Problem

Unchecked maths mod the max int

### Happy Case

ability to interact with field elements where any sort of overflow works mod the field 

### Additional Context

Developer feedback from all hands 

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
This will likely be put under the "bigint" umbrella

**Comment by TomAFrench** [comment]
The problem here isn't clear so I'm going to close this.
