### ISSUE TITLE
Serialization of input types 

### ISSUE THREAD

**Issue by merfymerf** [noir-lang/noir#1825]
### Problem

Serialization of input types 

### Happy Case

something that is friendly to play with when generating from toml;  (JSON inputs or others from prover tool).

### Additional Context

Developer feedback from all hands 

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
It isn't really clear to me what this issue is asking for. Can you give more details?

**Comment by TomAFrench** [comment]
@merfymerf

**Comment by Savio-Sou** [comment]
I assume it meant serializing compilation artifacts into more standardized formats, e.g. JSON, so tool building upon them would be more accessible.

This is already achievable with `nargo compile`. Closing this as completed and feel free to reopen it if I have misinterpreted the suggestion.
