### ISSUE TITLE
Scalar multiplication is broken in at least >0.5.1

### ISSUE THREAD

**Issue by signorecello** [noir-lang/noir#1830]
### Aim

Trying to use `std::scalar_mul::fixed_base` in this snippet:

```
use dep::std;

fn main(priv_key: Field) {
    std::scalar_mul::fixed_base(priv_key);
}

#[test]
fn test_main() {
    main(0x1929ea3ab8d9106a899386883d9428f8256cfedb3c4f6b66bf4aa4d28a79988f)
}
```

### Expected Behavior

Expected the operation to perform normally

### Bug

Test fails with:

```
Running 1 test functions...
Testing test_main...
The application panicked (crashed).
Message:  not yet implemented
Location: crates/noirc_evaluator/src/ssa/optimizations.rs:162
```

A workaround (thanks @jfecher) is to run `nargo test --experimental-ssa` instead. Only works if using nightly version (>0.7.0)

### To Reproduce

1. Write a circuit with scalar multiplication
2. Write a test
3. Run `nargo test`

### Installation Method

Binary

### Nargo Version

nargo 0.7.1 (git version hash: fa9be1d255cb10fafcf81c92bd02488f366eaf23, is dirty: false)

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
> A workaround (thanks @jfecher) is to run nargo test --experimental-ssa instead. Only works if using nightly version (>0.7.0)

Closing as this is now the default.
