### ISSUE TITLE
LSP: Support codelens

### ISSUE THREAD

**Issue by phated** [noir-lang/noir#1834]
### Problem

The LSP should support codelenses following https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_codeLens

The first iteration will show `> Run Test` above tests inside of noir source code and follow up work can add `> Prove` and `Verify` above main functions.

### Happy Case

A user should see codelenses in their source code while using a LSP client that will allow them to take some action against the code they are writing.

### Would you like to submit a PR for this Issue?

Yes

**Comment by kevaundray** [comment]
Might be better to have execute instead of prove and verify initially -- the former is faster and would not rely on a backend
