### ISSUE TITLE
Nargo runs all tests with the same name

### ISSUE THREAD

**Issue by phated** [noir-lang/noir#1836]
### Aim

The `nargo test` command should be able to run exactly one test in a specific file.

### Expected Behavior

Currently, if you have multiple test functions with the same name (e.g. in different files in your project), the `nargo test <TEST_NAME>` command will run all those tests.

### Bug

There should be a way to run exactly one test in a specific file, otherwise running `nargo test <TEST_NAME>` via the LSP might run multiple tests.

### To Reproduce

1. Create a project with 2 files that have tests with the same name
2. Use `> Run Test` as provided by #1835 
3. Notice that the output says 2 tests ran:
<img width="635" alt="Screenshot 2023-06-28 at 4 05 47 PM" src="https://github.com/noir-lang/noir/assets/992373/f6fbc019-6256-4118-b436-0f50160724d5">

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
I think we should copy rust testing workflow here and do module scopes in the regex to pinpoint a file.

Leaving the bug label because test names need to be named properly in that case

**Comment by kevaundray** [comment]
@f01dab1e do you want to take this on?

**Comment by f01dab1e** [comment]
I'll take this task
