### ISSUE TITLE
Add const generics 

### ISSUE THREAD

**Issue by shuklaayush** [noir-lang/noir#1837]
### Problem

The type system treats generic arguments as a [`NamedGeneric`](https://github.com/noir-lang/noir/blob/5d64f8a175ea087ed980e20041dc525eb799ba95/crates/noirc_frontend/src/hir_def/types.rs#L66-L68) irrespective of whether they're normal types or numerical constants. 

It would be great if you could explicitly declare generic types as `comptime` (analogous to rust's [const generics](https://practice.rs/generics-traits/const-generics.html)) and be able to do something like the following:
```rust
global M: comptime Field = 2;

fn f<N: comptime Field>() -> [Field; M + N] {
    ...
}
```

The `N` here would be treated as a [`Constant`](https://github.com/noir-lang/noir/blob/5d64f8a175ea087ed980e20041dc525eb799ba95/crates/noirc_frontend/src/hir_def/types.rs#L85-L87) instead of a `NamedGeneric` and thus we'd be allowed to do operations over it.

### Happy Case

Make something like this work:

```rust
global M: comptime Field = 2;

fn f<N: comptime Field>() -> [Field; M + N] {
    ...
}
```

### Alternatives Considered

Declare `N` as a global constant instead

```rust
global M: comptime Field = 2;
global N: comptime Field = 1;

fn f() -> [Field; M + N] {
    ...
}
```

### Would you like to submit a PR for this Issue?

Maybe

### Support Needs

I'm happy to help out if this is useful and not too difficult to implement.

**Comment by kevaundray** [comment]
Noting that #2178 removes the concept of comptime

**Comment by vezenovm** [comment]
Going to close this issue now that https://github.com/noir-lang/noir/pull/5155 is merged.
