### ISSUE TITLE
Making the App Crashed Messages more descriptive

### ISSUE THREAD

**Issue by harshnambiar** [noir-lang/noir#1843]
### Problem

Whenever there is a line in the code that does not break during nargo check (syntactic), but does during nargo prove, the error message is something like:

_The application panicked (crashed)._
_Message:  internal error: entered unreachable code: logging this expression type is not supported_
_Location: crates/noirc_evaluator/src/ssa/context.rs:1181_

_This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/._
_If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml_

If this could be made more descriptive, it would surely help the devs in the ecosystem.

### Happy Case

A message along the lines:

_This error is caused because Noir doesn't allow tuple elements to be used in an std::println statement. This is a bug that has not yet been corrected in the latest version. The issue is already logged as an issue on the Noir GitHub._

or something like that would help avoid duplicate bug logging, as well as keep newer devs updated on the progress.

### Alternatives Considered

Even if the message just mentions if something has been corrected in any version so far at all would be quite helpful.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
Assigning this to you @f01dab1e

**Comment by TomAFrench** [comment]
I'm not sure what's actionable here other than just generally replacing panics in the evaluator with `RunTimeError`s.

The described panic no longer exists and I think the happy case is "E-HIGH" as we'd need nargo to be able to diagnose arbitrary panics (as if we knew in advance that could be a panic then we'd turn it into an error), look these up against some external registry which would need to be maintained, etc.

**Comment by kevaundray** [comment]
> I'm not sure what's actionable here other than just generally replacing panics in the evaluator with `RunTimeError`s.
> 
> The described panic no longer exists and I think the happy case is "E-HIGH" as we'd need nargo to be able to diagnose arbitrary panics (as if we knew in advance that could be a panic then we'd turn it into an error), look these up against some external registry which would need to be maintained, etc.

I was mainly looking at this part of the error message:

> This error is caused because Noir doesn't allow tuple elements to be used in an std::println statement

Which was a lot more user friendly to read.

Agreed that it would be E-HIGH if we needed to specify whether the issue has already been solved; we don't want to do this, thanks for pointing that out!
