### ISSUE TITLE
LSP reports constructor problems at type location

### ISSUE THREAD

**Issue by ludamad** [noir-lang/noir#1845]
### Aim

EDIT: Not entirely sure if this is reproducible on second thought, will try again later
I wanted to see which constructor sites were wrong for a type. Instead, the errors were located at the type itself.

### Expected Behavior

The red squiggles would be at the constructor.

### Bug

<img width="335" alt="Screenshot 2023-06-30 at 5 38 33 PM" src="https://github.com/noir-lang/noir/assets/163993/aace5253-686a-4bf1-ac85-f8810c51d786">

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
Can you give the full snippet of code, or at least the portion with the constructor as well? I'm assuming it is the one on line 8 but cannot see what type of error it is specifically from the screenshot alone.

**Comment by ludamad** [comment]
Closing for now, probably more related to debug info
