### ISSUE TITLE
`nargo check` doesn't rewrite Prover.toml and Verifier.toml

### ISSUE THREAD

**Issue by curryrasul** [noir-lang/noir#1851]
### Aim

I was trying to use `nargo check` to generate Prover.toml and Verifier.toml files to be able to fill in witness and public inputs.

### Expected Behavior

`nargo check` should recreate/rewrite generated files (Prover.toml and Verifier.toml)

### Bug

I created new nargo/noir project and after `nargo check` there were two files generated - Prover.toml and Verifier.toml; Prover.toml contained witness input format for default nargo/noir circuit. 
When I changed the circuit and ran `nargo check` again - it didn't change the files.

### To Reproduce

1. Create new nargo project (`nargo new example`)
2. Run `nargo check`
3. Change the circuit , so it has different variables set as an input 
4. Run `nargo check` again and generated files not changed

### Installation Method

Binary

### Nargo Version

nargo 0.6.0 (git version hash: 0181813203a9e3e46c6d8c3169ad5d25971d4282, is dirty: false)

### Would you like to submit a PR for this Issue?

Maybe

**Comment by TomAFrench** [comment]
I think an important thing to keep in mind for this issue is that `nargo check` shouldn't delete info from the user's `Prover.toml`. i.e. If I remove an argument then it should still exist in the `Prover.toml` file but if I add a new one then it can create a skeleton value for it.
