### ISSUE TITLE
Implement returning tuples from main/circuits

### ISSUE THREAD

**Issue by signorecello** [noir-lang/noir#1855]
### Problem

It would be useful to have support for returning tuples from noir circuits

### Happy Case

My circuit returns a tuple like `pub (u32, u32)` and the circuit compiles correctly

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@vezenovm what is the status of this?

**Comment by vezenovm** [comment]
@kevaundray still open. Working on #1889 right now as it is higher priority then will get to this issue

**Comment by kevaundray** [comment]
@vezenovm can this be closed?

**Comment by vezenovm** [comment]
Yes closed per https://github.com/noir-lang/noir/pull/2899
