### ISSUE TITLE
MacOS runner always misses nix cache

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#1874]
CI times on mac are 5x that of ubuntu, compare a recent run on [ubuntu](https://github.com/noir-lang/noir/actions/runs/5475443115/jobs/9971551175) with [mac](https://github.com/noir-lang/noir/actions/runs/5475443115/jobs/9971551364) 

This is due to the fact that the macOS nix cache always misses. The action reports that artifacts are written to the cache but on subsequent CI runs it will report that the key does not exist.

**Comment by TomAFrench** [comment]
@phated @kobyhallx fyi

**Comment by phated** [comment]
Most of the run time seems to be building barretenberg. I believe the commit that things are pinned to has been updated and so we probably don't have that version in cachix because nix only runs on bb master branch.

**Comment by phated** [comment]
In the meantime, I performed a manual run at https://github.com/AztecProtocol/barretenberg/actions/runs/5478921793/jobs/9980058360 and hope that cachix added the commit to the cache

**Comment by kevaundray** [comment]
Closing as we do not need barretenberg for testing anymore
