### ISSUE TITLE
TypeVariable(Field) does not behave like Field when being cast

### ISSUE THREAD

**Issue by ludamad** [noir-lang/noir#1875]
### Aim

Had to cast a Field to a u32, but it ultimately came from generics, minimal reproducer:

<img width="746" alt="Screenshot 2023-07-06 at 3 23 10 PM" src="https://github.com/noir-lang/noir/assets/163993/ddbb6a5a-ce6a-433d-baf1-3f519c8585cc">

Viable workaround: First assigning this to a let x: Field. Low priority as a result.

### Expected Behavior

This cast should be allowed

### Bug

This seems to be due to this technically being a TypeVariable in the compiler, but should act the same for the user.

### To Reproduce

See above screenshot.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@jfecher what is the status of this issue?
