### ISSUE TITLE
`Prover.toml` & `Verifier.toml` should go into `Nargo.toml`

### ISSUE THREAD

**Issue by merfymerf** [noir-lang/noir#1883]
### Problem

Feedback from Noir User Testing: `Prover.toml` & `Verifier.toml` should go into `Nargo.toml`

### Happy Case

`Prover.toml` & `Verifier.toml` should go into `Nargo.toml`

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
I don't think that we should be specifying circuit inputs inside `Nargo.toml`. `Nargo.toml` is a static definition of the project and shouldn't need to be modified to create/verify proofs.

This is analogous to having to write program arguments for a Rust program inside `Cargo.toml`
