### ISSUE TITLE
Consolidate all outputs into one `out` folder

### ISSUE THREAD

**Issue by merfymerf** [noir-lang/noir#1884]
### Problem

Currently artifacts compiled with Nargo are "scattered" into multiple folders (i.e. `contract`, `target`), which might be slightly confusing to some.

### Happy Case

Consolidate all artifacts into one e.g. `out` folder instead. Naming suggestions welcome.

### Additional Context

Suggestion was collected from Noir User Testing Session 1.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@TomAFrench thoughts?

**Comment by phated** [comment]
I think this is bad because you often want to check in some artifacts and not others. For example, Dark Forest checked in the smart contracts but not the PK or VK.

**Comment by kevaundray** [comment]
> I think this is bad because you often want to check in some artifacts and not others. For example, Dark Forest checked in the smart contracts but not the PK or VK.

Closing as "not planned" then
