### ISSUE TITLE
Calling a nested method does not mutate the struct field

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#1887]
### Aim

Tried to prove and verify the following with `--experimental-ssa`:
```rs
struct Foo { bar: Bar }

struct Bar { x: Field }

impl Bar {
    fn mutate(&mut self) {
        self.x = 32;
    }
}

fn main() {
    let foo = &mut Foo { bar: Bar { x: 0 } };
    foo.bar.mutate();
    assert(foo.bar.x == 32);
}
```

### Expected Behavior

Expected the code to prove and verify with `foo.bar.x` now equal to 32.

### Bug

Due to `.` automatically dereferencing, the call to `mutate` is equivalent to 
```rs
mutate(&mut (*foo).bar);
```
which mutates a copy of foo.bar rather than the original. So `foo.bar.x` would still equal 0 after the call to mutate, thus failing the assert.

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@jfecher what's the status of this issue?

**Comment by jfecher** [comment]
@kevaundray still open
