### ISSUE TITLE
Spread array syntax for building arrays

### ISSUE THREAD

**Issue by spalladino** [noir-lang/noir#1920]
### Problem

In Aztec3 we often need to assemble an array as the concatenation of smaller arrays, such as when preparing the inputs to a hash function. We often use the BoundedVec wrapper for that, but it's still somewhat verbose. As an example:

```noir
fn entrypoint(
        inputs: pub PrivateContextInputs,
        payload: pub EntrypointPayload,
        owner: pub [u8;64], 
        signature: pub [Field;3],
        partialContractAddress: pub Field,
    ) {
        let mut args: BoundedVec<Field, 75> = BoundedVec::new(0);
        args = args.push_array(payload.serialize());
        for byte in owner {
            args = args.push(byte as Field);
        }
        args = args.push_array(signature);
        args = args.push(partialContractAddress);

        let args_hash = abi::hash_args(args.storage);
```

### Happy Case

It'd be a lot more ergonomic if we could use array spread syntax for composing the array of inputs. Continuing with the example above:

```noir
fn entrypoint(
        inputs: pub PrivateContextInputs,
        payload: pub EntrypointPayload,
        owner: pub [u8;64], 
        signature: pub [Field;3],
        partialContractAddress: pub Field,
    ) {
        let args = [...payload.serialize(), ...owner as [Field;64], ...signature, partialContractAddress];
        let args_hash = abi::hash_args(args);
```

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
Discussed internally that it would since we want to follow Rust syntax, we would rather have iterators and use `chain` and `flatten` to get the desired effect.

Feel free to open again if this is not an accurate description!
