### ISSUE TITLE
Investigate Ubuntu CI failing on nightly

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#193]
As of merging the methods PR, the rust-nightly CI running Ubuntu latest stable (20.04) is still failing during linking for unknown reasons. Master has since been updated to use macos-latest which succeeds without warnings. Going forward it'd be ideal to have CI working on all platforms and configurations.

**Comment by kevaundray** [comment]
@jfecher can this be closed?

**Comment by jfecher** [comment]
Yes, we've switched back onto ubuntu for a while now.
