### ISSUE TITLE
Keccak256 preimage proof cannot be verified

### ISSUE THREAD

**Issue by ax0** [noir-lang/noir#1934]
### Aim

Generate and verify a proof for the program

```
use dep::std::hash::keccak256;

fn main(x: [u8; 3], len: Field) -> pub [u8; 32] {
    let len_u32 = len as u32;
    keccak256(x, len_u32)
}
```

with `Prover.toml` given by

```
x = [1,2,3]
len = 2
```

### Expected Behavior

A proof may be generated and verified.

### Bug

A proof may be generated but verification fails.

### To Reproduce

1. Create a new Nargo project and populate `main.nr` and `Prover.toml` with the above snippets.
2. Run `nargo prove p`.
3. Run `nargo verify p`.

### Installation Method

Compiled from source

### Nargo Version

nargo 0.8.0 (git version hash: 1056ba1b8048ec817137a16e0b343f5e7bf15139, is dirty: false)

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
Is this ran with the experimental-ssa or the old ssa? cc @guipublic for visibility

**Comment by ax0** [comment]
Just checked and passing `--experimental-ssa` yields the same result, so both.

**Comment by kevaundray** [comment]
@guipublic are there any blockers on diagnosing this issue?

**Comment by guipublic** [comment]
> @guipublic are there any blockers on diagnosing this issue?

no, had to work around barretenberg but now I have a repro there and I am experimenting a fix.

**Comment by kevaundray** [comment]
Update on this: @guipublic will create a unit test that is failing on the barretenberg side

**Comment by guipublic** [comment]
Fixed by https://github.com/AztecProtocol/barretenberg/pull/632

**Comment by guipublic** [comment]
The fix has now been integrated into noir with the last backend update. I am closing the issue.
