### ISSUE TITLE
Split up 9_conditional and 8_integration

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#1938]
### Problem

These are two tests in the end to end test folders. However they contain many edge cases and the program is generally large, making it hard to pinpoint a particular regression or edge case.

### Happy Case

We split up the tests to only test one edge case at a time. We may need to rethink the purpose of this folder;

- Some examples are showing off simple functionality
- Some examples are regression tests

We could possibly have a folder just for regression tests and one for example programs, and or possibly have a separate examples repo that the compiler runs over to test a large corpus of programs.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@guipublic assigning this to you -- this should also speed up tests, the more cores the machine has. 

Note: the main reason we can do this is because we do not do proving anymore. Moreover, some of these regression end to end tests will likely move to be unit tests in the future, so having them split up will make it easier to transition

**Comment by guipublic** [comment]
8_integration will be difficult to split. However, since It was based on sha256, and since we have a sha256 unit test, I think we can simply remove it.
