### ISSUE TITLE
Mutable references bug? I can't cook my potatoes!!!

### ISSUE THREAD

**Issue by iAmMichaelConnor** [noir-lang/noir#1946]
### Aim

A potato themed snippet for you, today!

```rust
struct Potato {
    fried: bool,
    mashed: bool,
    boiled: bool,
    baked: bool,
}

impl Potato {
    fn raw() -> Self {
        Potato {
            fried: false,
            mashed: false,
            boiled: false,
            baked: false
        }
    }

    fn boil(&mut self) {
        self.boiled = true;
    }

    fn mash(&mut self) {
        self.mashed = true;
    }

    fn fry(&mut self) {
        self.fried = true;
    }

    fn boil_then_mash(&mut self) {
    
    // Attempt 1:
        // No method named 'boil' found for type '&mut Potato'
        // self.boil(); // nope
        // self.mash(); // nope
    
    // Attempt 2:
        // No method named 'boil' found for type '&mut Potato'
        // *self.boil(); // nope
        // *self.mash(); // nope

        Potato::boil(self); // yep
        Potato::mash(self); // yep
    }

    fn fry_my_potato(potato: &mut Potato) {
    // Attempt 1:
        // No method named 'fry' found for type '&mut Potato'
        // potato.fry(); // nope

    // Attempt 2:
        // No method named 'fry' found for type '&mut Potato'
        // *potato.fry(); // nope

        Potato::fry(potato); // yep
    }
}

fn main() {
    let mut potato = Potato::raw();

    potato.boil();

    potato.boil_then_mash();

    Potato::fry_my_potato(&mut potato);
}
```

This will compile. But the commented-out lines (my earlier attempts) do not compile - they give the errors shown. Am I using the syntax wrong?

Using the master branch of Noir, compiled from source.

**Comment by jfecher** [comment]
This is a method resolution bug brought up by @vezenovm earlier. Thank you for the issue though, I cannot seem to find an existing issue for it and had forgotten about the bug.

It's a relatively dumb bug that should be easy to fix. The type checker usually looks up methods by looking at the object's struct type and looking at the methods stored for that struct type. For mutable references it just sees a mutable referenced around some type and says "not a struct!" and claims there are no methods for it.

Your syntax is mostly correct, although the `*self.mash();` would have fixed it but your precedence is wrong - methods bind more tightly than `*` so `(*self).mash();` would have refered to the correct method (but would have given a type error that it expected a mutable reference but received a Potato).
