### ISSUE TITLE
Show println on nargo tests

### ISSUE THREAD

**Issue by signorecello** [noir-lang/noir#1968]
### Problem

If you're running tests, we get no output from `std::println`, which would be very handy for debugging

### Happy Case

When I run `nargo test`, I want my `println` statements to log to my console

### Alternatives Considered

Running `nargo execute` or other command that actually prints the output. This is considerably slower than `nargo test`

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
This can be done with `nargo test --show-output`.

**Comment by jfecher** [comment]
To elaborate, the default behavior of `nargo test` hiding printlns was chosen to match the behavior of `cargo test` which does the same.
