### ISSUE TITLE
Remove `predicate: Option<AcirVar>` in acir-gen

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#1972]
### Problem

Currently several functions in acir-gen accept a `predicate: Option<AcirVar>` parameter for passing the predicate specified by the `enable_side_effects` instruction.

### Happy Case

This can be removed and replaced with a non-optional version - or replaced with `context.current_side_effects_enabled_var`.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@Ethan-000 Feel free to pick this up too!
