### ISSUE TITLE
The compiler issues field comparisons for loops at the SSA level

### ISSUE THREAD

**Issue by sirasistant** [noir-lang/noir#1979]
### Aim

Consider the following code:
```
fn main() -> pub Field {
    let mut x = 0;
    for i in 0..10 {
        x += i;
    }
    x
}
```

### Expected Behavior

The compiler is generating a comparison of i with the range 0..10 as can be seen in the following SSA:
```
Initial SSA:
acir fn main f0 {
  b0():
    v1 = allocate
    store Field 0 at v1
    jmp b1(Field 0)
  b1(v2: Field):
    v4 = lt v2, Field 10
    jmpif v4 then: b2, else: b3
  b2():
    v5 = load v1
    v6 = add v5, v2
    store v6 at v1
    v8 = add v2, Field 1
    jmp b1(v8)
  b3():
    v9 = load v1
    return v9
}

```
Which is a comparison with field operands, but the compiler does not allow the user to perform a similar kind of comparison themselves:
```
error: Comparisons are invalid on Field types. Try casting the operands to a sized integer type first
  ┌─ src/main.nr:5:12
  │
5 │         if i > 1 {
  │            -----

```

### Bug

Since loops are unrolled for ACIR, this field comparison never reaches ACIR gen and is simplified away before. But for brillig, loops are runtime and the field comparison reaches brillig gen. This makes brillig having to handle Field comparisons generated by the compiler itself via casting to integer types.

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
Note for when this is fixed, we can remove handling of this in brillig. See https://github.com/noir-lang/noir/pull/1973#discussion_r1268322967

**Comment by kevaundray** [comment]
For reference: This is fixed if:

-  Cast x to an integer
- Allow field comparisons to extend to > and <
- Use a default type which is not a Field

**Comment by kevaundray** [comment]
Have opened #2008 which feeds into this as just allowing Field to have < and > would be a possible fix
