### ISSUE TITLE
App crashes on nargo test --show-output

### ISSUE THREAD

**Issue by harshnambiar** [noir-lang/noir#1982]
### Aim

I tried to run the tests on the phy_vector folder in [this](https://github.com/resurgencelabs/types) repository. But it crashes. 

### Expected Behavior

The crash should not happen

### Bug

The generic "app crashed, this is a bug and might have been resolved in a later release" error message shows up

### To Reproduce

1. Clone above repository
2. cd phy_vector
3. nano main.nr
4. Add these two lines at lines 46 and 47:
    let mm = vsum.j.num;
    std::println(mm);
5. nargo test --show-output 

### Installation Method

Binary

### Nargo Version

0.7.1

### Would you like to submit a PR for this Issue?

No

**Comment by f01dab1e** [comment]
log:
```
Running 4 test functions...
Testing test_sum_vector...
0x1e
ok
Testing test_vector_product_vector...
The application panicked (crashed).
Message:  assertion failed: `(left != right)`
  left: `NodeId(Index { index: 408, generation: 0 })`,
 right: `NodeId(Index { index: 408, generation: 0 })`
Location: crates/noirc_evaluator/src/ssa/optimizations.rs:303

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml
```

**Comment by f01dab1e** [comment]
..it doesn't appear. I had to run a couple of times to repeat https://gist.github.com/f01dab1e/c05a8b78702a3af452593f71c8756f43

**Comment by jfecher** [comment]
Unfortunate. I suppose whatever is making these tests nondeterministic in https://github.com/noir-lang/noir/issues/1986 is also causing this to only sometimes crash.

**Comment by jfecher** [comment]
Alright, I had to run it 10 times but I did replicate the panic

**Comment by jfecher** [comment]
If the panic doesn't occur with `--experimental-ssa`, then I'm closing this issue since we'll be making that the default soon anyway, and the old ssa code will be removed. Until then we're not making any changes to the old ssa code.

**Comment by jfecher** [comment]
Reopening this issue. Since the fix for this relies on using `--experimental-ssa` I think it is better to leave this issue open until the experimental SSA is enabled by default in Noir. I'll link it to the tracking issue for experimental ssa and we can close both when it is merged.

**Comment by jfecher** [comment]
The experimental-ssa is now the default as of 0.9.0, so this is fixed 😄
