### ISSUE TITLE
Replace `Type::TypeVariable`, `Type::PolymorphicInteger`, and all other type variables with one kind

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#1991]
### Problem

As the typechecker grows it can be useful to have different kinds of type variables. E.g. variables that can bind to anything, or only integer types, or integer and field types, etc. However, for these cases we currently have to create an entirely new variant of `Type` each time and implement most cases the same way.

### Happy Case

We should only have `Type::TypeVariable`, and it should contain an internal enumeration `TypeVariableKind` detailing what kind of type variable it is. This will allow us to add and work with type variables more easily without bloating our `Type` representation. Example of this enum:
```rs
enum TypeVariableKind {
    /// Can bind to any type
    Normal,
    /// Can only bind to integer types (not including fields). Used for comparison and bitwise operations
    Integer,
    /// Can bind to integer or field types. Used for most arithmetic operations.
    IntegerOrField,
    /// Can only bind to constant integers e.g. array sizes.
    Constant,
}
```

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@f01dab1e feel free to take this on
