### ISSUE TITLE
More descriptive test failure message when running nargo test

### ISSUE THREAD

**Issue by harshnambiar** [noir-lang/noir#1995]
### Problem

Currently, when a test fails, the only message is Test Failed. It would greatly help in debugging if there was more to it.

### Happy Case

Ideally, if the test is failing because of an assert statement being falsified, if the command could somehow print the LHS and RHS values, it would really help. If it could also print the values of the variables in the failing assert, that would be wonderful too.

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
We do have locations for error messages now but they can still be improved by showing the values of variables when possible. This is not always possible however since assert/constrain can accept any boolean. Here's an example of the current error:
```
error: Unsatisfied constraint
   ┌─ /Users/jakefecher/Code/Noir/noir/short/src/main.nr:30:12
   │
30 │     assert(x[0] == result);
   │            -------------- Constraint failed
```

**Comment by harshnambiar** [comment]
> We do have locations for error messages now but they can still be improved by showing the values of variables when possible. This is not always possible however since assert/constrain can accept any boolean. Here's an example of the current error:
> 
> ```
> error: Unsatisfied constraint
>    ┌─ /Users/jakefecher/Code/Noir/noir/short/src/main.nr:30:12
>    │
> 30 │     assert(x[0] == result);
>    │            -------------- Constraint failed
> ```

You are right. This would be pretty touch to attempt with just an assert. But if there could be an "assert_eq()" function, then maybe this could be done where the LHS and RHS values can be printed in the terminal similar to cargo test in Rust, in case of Test failure.
