### ISSUE TITLE
Release in nixpkgs

### ISSUE THREAD

**Issue by happysalada** [noir-lang/noir#2006]
### Problem

Having a flake is nice, but having a release already available in nixpkgs would be even better :-)

Are you waiting for the api to stabilize before releasing in nixpkgs ? If that is the case, feel free to ping me when you make a PR there, I'd be happy to help get it merged.

### Happy Case

have the binaries available directly in nixpkgs for a smooth dev experience

### Alternatives Considered

doing nothing and leave it as a flake

### Additional Context

I see that there are a couple of dependencies that need to be packaged additionally, since they are all using nix, it shouldn't be too hard.

### Would you like to submit a PR for this Issue?

No

**Comment by kobyhallx** [comment]
agreed, this needs to land in nixpkgs. We're cleaning bunch of other items before.

Today you can use it just the same though, just specify github repo instead of nixpkgs.
