### ISSUE TITLE
Remove the obsolete `flat_witness` feature flag from Nargo

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#2010]
### Problem

The flattened witness format has been adopted as the default approach to formatting witnesses generated.

The [`flat_witness`](https://github.com/noir-lang/noir/blob/5526c5279e2a62be71eb7d80ed5323dabc66ea0c/crates/nargo_cli/Cargo.toml#L64) feature flag seems obsolete in consideration of so.

### Happy Case

Merge-to-master or remove experimental works under the feature flag, and remove the flag.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@vezenovm assigned this to you, please check if we do need this and document what has changed for us to no longer need this.

cc @TomAFrench
