### ISSUE TITLE
Update commit reference for Aztec backend

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#202]
A fix has been made for Macs using the intel chip as of this commit: https://github.com/AztecProtocol/barretenberg/tree/9861b2c230723e73c188865d47b67e161b0371f1

We should update the dependency in the aztec backend crate

**Comment by phated** [comment]
@kevaundray Is this resolved now?

**Comment by kevaundray** [comment]
> @kevaundray Is this resolved now?

Yep we can close this!
