### ISSUE TITLE
Create ACIR + witness artifacts for Barretenberg using `experimental-ssa`

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#2020]
### Problem

Barretenberg uses the committed ACIR and witness files in the `test_data` directory in order to test ACIR proof generation. As we switch over to using the new SSA by default we want to ensure that Barretenberg has test coverage for this.

### Happy Case

We should run the `rebuild.sh` script on the `test_data_ssa_refactor` directory and update Barretenberg to pull these and run its tests on them.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
I think #2013 should be done separately so it doesn't hold us up
