### ISSUE TITLE
Add a JS package to handle ABI encoding/decoding

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#2025]
### Problem

Currently acvm_js assumes that the caller can provide an initial witness with which to execute the circuit.

This is fine for relatively simple programs but it's not a good experience and makes more complex noir programs unwieldy to work with. 

### Happy Case

In order to interact with Noir programs in the browser we need a way to construct the initial witness from a set of inputs similar to what we have in `Prover.toml`.

### Would you like to submit a PR for this Issue?

Yes

**Comment by Savio-Sou** [comment]
> Add a JS package

Is there any value for it to live as a standalone package? Would it make sense to merge it into `noir_wasm` or `acvm_js`?

**Comment by TomAFrench** [comment]
Neither of those two packages are good spots for this functionality to live tbh.

`noir_wasm`: This would require a user to load a complete copy of the noir compiler in order to construct initial witnesses.
`acvm_js`: See https://github.com/noir-lang/acvm-simulator/issues/4

**Comment by Savio-Sou** [comment]
Hmm reasonable.

The need for wrapping everything into [one Noir.js package](https://github.com/noir-lang/Planning/issues/26) as an option seems to be growing. Fiddling with 4+ packages just to get started sounds like a DevEx nightmare.
