### ISSUE TITLE
Add an `assert_eq` function to remove unnecessary constraints from calls to `assert`

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#2031]
### Problem

Our restriction to only have the `assert` function results in suboptimal ACIR generation. Consider the Noir program

```rust
fn main(x: Field) {
    assert(x == 1);
}
```

Note that this circuit can be clearly seen to be equivalent to `EXPR [ (1, _1)  -1 ]`. If we look at what the Noir compiler produces under `experimental-ssa` however we get the ACIR

```
Compiled ACIR for main:
current witness index : 4
public parameters indices : []
return value indices : []
EXPR [ (1, _1) (-1, _2) -1 ]
BRILLIG: inputs: [Single(Expression { mul_terms: [], linear_combinations: [(1, Witness(2))], q_c: 0 })]
outputs: [Simple(Witness(3))]
[JumpIfNot { condition: RegisterIndex(0), location: 3 }, Const { destination: RegisterIndex(1), value: Value { inner: 1 } }, BinaryFieldOp { destination: RegisterIndex(0), op: Div, lhs: RegisterIndex(1), rhs: RegisterIndex(0) }, Stop]

EXPR [ (1, _2, _3) (1, _4) -1 ]
EXPR [ (1, _2, _4) 0 ]
EXPR [ (1, _4) -1 ]
```

(The old SSA produces roughly equivalent code).

You can see that we can solve the circuit backwards from witness 4 to show that witness 2 is 0 and recover the single opcode form of this circuit. All opcodes after the first are unnecessary.

The reason behind why we have all these extra opcodes is that `assert(x == 1)` is split into two tasks.

1. Return a witness which has the value 1 if `x == 1` and 0 if `x != 1`.
2. Constrain this witness to be equal to 1.

In reality we only care about the second task but it's not permitted by the structure of the `assert` function as it only accepts a single input.

### Happy Case

We should define a `assert_eq` function which accepts two variables and enforces equality only.

More concretely, the `Constrain` instruction

https://github.com/noir-lang/noir/blob/2d87c873a286b21741736ad61fbef546b6d42b21/crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs#L307-L310

should be reworked to be implemented as

```
Instruction::Constrain(lhs, rhs) => { 
     let lhs = self.convert_numeric_value(*lhs, dfg); 
     let rhs = self.convert_numeric_value(*rhs, dfg); 
     self.acir_context.assert_eq_var(lhs, rhs)?; 
 }
```

and `assert_eq(lhs, rhs)` appearing in Noir code should result in an `Instruction::Constrain(lhs, rhs) ` instruction only

### Would you like to submit a PR for this Issue?

Maybe

**Comment by kevaundray** [comment]
Another solution, which may not be the most optimal, is to apply the optimizations after the fact, this is what Guillaume's simplifier was attempting to do

**Comment by kevaundray** [comment]
This is related to https://github.com/noir-lang/noir/issues/573

**Comment by TomAFrench** [comment]
I prefer this way as it simplifies the Noir compiler rather than adding extra complexity to ACVM.

**Comment by jfecher** [comment]
I'm fine with an `assert_eq` as long as we don't have both a `constrain`/`assert` and `assert_eq` instructions in the SSA IR. The former can be trivially converted to the later by adding an `== 1`.

**Comment by TomAFrench** [comment]
Agreed, I would suggest converting `assert(x)` into `assert(x, 1)` asap.

**Comment by TomAFrench** [comment]
> Another solution, which may not be the most optimal, is to apply the optimizations after the fact, this is what Guillaume's simplifier was attempting to do

Realised today that this should be much simpler to do now we have the stepwise ACVM.

If all the simplifier was intended to do is catch these small isolated sections of redundant opcodes then we can now clear then in a single pass by iterating backwards. This would ensure that we encounter all of the `witness = constant` constraints before the opcode where they're relevant.

**Comment by TomAFrench** [comment]
> the main blocker on this is the requirement for stdlib functions to be explicitly imported

Added an issue [here](https://github.com/noir-lang/noir/issues/2140)
