### ISSUE TITLE
Remove comptime feature

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#2040]
### Problem

This is a tracking issue to remove comptime from the language.

### Happy Case

.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
Please add issues related to removing comptime here

**Comment by kevaundray** [comment]
Related:

-  https://github.com/noir-lang/noir/issues/280
- https://github.com/noir-lang/noir/issues/1188

**Comment by f01dab1e** [comment]
Related:
#445 
#793

**Comment by jfecher** [comment]
I think `comptime` may actually still be needed for `for` loops. Since in regular constrained code those are still required to terminate. I suppose we can replace it with something else like a more ad-hoc check that the for loop bounds are constant, but this would break existing code.

**Comment by iAmMichaelConnor** [comment]
I just hit a use case where a comptime Field might still be helpful...
I wanted to instantiate an array with length equal to: the sum of the serialised lengths of two structs.
I.e. I have two structs. Each struct has a method which returns the `comptime Field` "length" of the struct (when that struct is serialised into an an array of fields).

```
let struct1_length: comptime Field = Struct1::get_serialised_length();
let struct2_length: comptime Field = Struct2::get_serialised_length();
let combined_length: comptime Field = struct1_length + struct2_length;
let mut combined_arr = [0; combined_length];

let mut insertion_index = 0;
spread(combined_arr, struct1, insertion_index);
insertion_index += struct1_length;

spread(combined_arr, struct2, insertion_index);
```

Isn't the only way to do this with comptime Fields?

**Comment by jfecher** [comment]
I don't believe we support initializing arrays with a `comptime FIeld` size at all currently. It must be an actual constant instead, which is more restrictive.

**Comment by iAmMichaelConnor** [comment]
Oh. Whoops. Can we generate constants from other constants at compile time? That's what this example would need. (I.e. specifying the length of an array at compile time, by doing simple arithmetic on other constants).

**Comment by jfecher** [comment]
Not if they're stored in local variables or parameters, that's the scope of comptime. Constants are limited to the type system, globals, and basic arithmetic on those.

**Comment by iAmMichaelConnor** [comment]
```
struct Foo { }
impl Foo {
    fn get_constant() -> comptime Field { // or constant, or something
        5 // <-- this constant isn't stored in a local variable.
    }
}
```
```
let my_arr_length = Foo::get_constant() + 1;
let my_arr = [0; my_arr_length];
```
^ I was trying something like this.

```
error: Cannot find a global or generic type parameter named `plain::my_arr_length`
```
