### ISSUE TITLE
Casting negative literals to unsigned doesn't work

### ISSUE THREAD

**Issue by shuklaayush** [noir-lang/noir#2045]
### Aim

I use `-1 as u{X}` syntax to get the unsigned max values. This doesn't seem to work in the new ssa.

```rust
use dep::std::println;

#[test]
fn test_cast() {
    let a: u8 = -1 as u8;
    // "0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000000"
    println(a);
    // assert(a == 0xff);
}
```

### Expected Behavior

The above code should print out `0xff` instead of `MODULUS - 1`

### Bug

The test should pass

A workaround for now is to replace `-1 as u8` with `0-1 as u8`

### To Reproduce

1. Copy the code above
2. Run `nargo test`

### Installation Method

Compiled from source

### Nargo Version

nargo 0.9.0 (git version hash: 66cb1fd3b380ecd32c2ec1a8d6031d59d0359d61, is dirty: false)

### Would you like to submit a PR for this Issue?

Maybe

**Comment by kevaundray** [comment]
@Ethan-000 have assigned this to you, if you have questions please ask them in here.

bumping @jfecher for visibility

**Comment by jfecher** [comment]
I would think this should be handled by
https://github.com/noir-lang/noir/blob/master/crates/noirc_evaluator/src/ssa_refactor/ir/instruction.rs#L369-L377 but it seems like it is not
