### ISSUE TITLE
`nargo test` failing with "not yet implemented", where `nargo prove ...` passes

### ISSUE THREAD

**Issue by alexroan** [noir-lang/noir#2058]
### Aim

Testing a circuit in noir, using inputs that pass when running `nargo prove ...`.

Link to repo and commit: https://github.com/alexroan/noir-merkle/tree/2fabbd424d7bb50f25d72717e115e33f696ae0c9

### Expected Behavior

Passing test

### Bug

```sh
Running 1 test functions...
Testing test_main...
The application panicked (crashed).
Message:  not yet implemented
Location: crates/noirc_evaluator/src/ssa/optimizations.rs:169
```

### To Reproduce

1. [Clone this repo](https://github.com/alexroan/noir-merkle)
2. Checkout this commit: `2fabbd424d7bb50f25d72717e115e33f696ae0c9`
3. Run `nargo prove main`
4. Then run `nargo test`

### Installation Method

None

### Nargo Version

nargo 0.9.0 (git version hash: 970c18ee29e37d35e39169005e629deed8b30b6e, is dirty: false)

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
This no longer crashes on master in Noir due to the experimental ssa being the new default. You can enable this in your current version by passing the `--experimental-ssa` flag until it is removed in a later release. Although the test does still fail:
```
error: Unsatisfied constraint
   ┌─ std/field.nr:31:39
   │
31 │             r = (b[32-i] as Field) * (r * self) + (1 - b[32-i] as Field) * r;
   │                                       -------- Constraint failed

Error: could not satisfy all constraints

Location:
    crates/nargo_cli/src/cli/mod.rs:74:5
```
Bit of an odd location to fail though.

**Comment by alexroan** [comment]
Why would it fail here in the test if `nargo prove` passes with that same data?
