### ISSUE TITLE
Apply ssa optimizations to brillig functions

### ISSUE THREAD

**Issue by sirasistant** [noir-lang/noir#2066]
### Problem

Right now brillig is generated before any ssa optimizations are applied. We should generate brillig just before ACIR is generated, after all optimization steps are applied.

### Happy Case

All optimization steps apply succesfully to ssa containing both brillig and acir functions.

### Would you like to submit a PR for this Issue?

No

**Comment by sirasistant** [comment]
I think this issue should be implemented in phases:
 - First, do runtime separation, right now if brillig calls an ACIR function it's targeted as is when it's going to be compiled to brillig. We should, after defunctionalization, find out all acir functions reachable by brillig, clone those as brillig and substitute all calls to the brillig versions. That way subsequent optimization steps can be sure that function.runtime() corresponds to the actual compilation target
 - Then move brillig gen after all optimization passes, we should be able to do it without issue after the previous step...
 - Then start modifiying optimizations to be applicable to brillig. For example, Inlining in brillig makes sense, but stopping at recursion boundaries. Or loop unrolling can make sense for a maximum of compile-time known iterations, etc

**Comment by vezenovm** [comment]
A good starting point for this issue would be the runtime separation pass. An example of reachability analysis for Brillig funcs  is already performed here: https://github.com/noir-lang/noir/blob/master/crates/noirc_evaluator/src/brillig/mod.rs#L59. These  ACIR funcs called from Brillig would then be cloned and replaced with a Brillig runtime.

**Comment by vezenovm** [comment]
This issue would be solved by this being completed as well: https://github.com/noir-lang/noir/issues/2336
