### ISSUE TITLE
Panic message is confusing if dependency is missing a name field in toml

### ISSUE THREAD

**Issue by phated** [noir-lang/noir#2086]
### Problem

Now that we require package names in the Nargo.toml file, we present the user with a descriptive error message if they haven't set it. However, this error message is also surfaced for dependencies but there is no indication on which dependency caused it, which can be very confusing.

### Happy Case

The error message should tell us which file is missing the `name` field.

### Would you like to submit a PR for this Issue?

No

**Comment by iAmMichaelConnor** [comment]
Can confirm. :)
If I hadn't just read this it would have taken me a while to do the same for dependencies.

**Comment by TomAFrench** [comment]
Not sure that we can really address this as we can't pass any information into the `panic_missing_name` function.

**Comment by phated** [comment]
We can actually do better error messages once #1992 is merged because we can relax the toml parser and validate it when converting to a workspace.
