### ISSUE TITLE
ICE: Should have been in cache instruction

### ISSUE THREAD

**Issue by ax0** [noir-lang/noir#2099]
### Aim

Generate a proof for [this program](https://github.com/aragonzkresearch/noir-trie-proofs/tree/main/tests/depth_8_storage_proof).

### Expected Behavior

A proof is successfully generated.

### Bug

We get the following error:
```
Message:  internal error: entered unreachable code: ICE: Should have been in cache v1338 Instruction { instruction: Id(1327), position: 0, typ: Numeric(Unsigned { bit_size: 1 }) }
Location: crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs:720
```

### To Reproduce

1. `git clone https://github.com/aragonzkresearch/noir-trie-proofs`
2. `cd noir-trie-proofs/tests/depth_8_storage_proof`
3. `nargo prove`

### Installation Method

Compiled from source

### Nargo Version

nargo 0.9.0 (git version hash: 9b417da0eef28a29dbe0f339ee19b8dd9859dc4d, is dirty: false)

### Additional Context

[These](https://github.com/aragonzkresearch/noir-trie-proofs/blob/5b33690a2229efd020ac8899780390e8c202ebc9/src/lib.nr#L75-L83) appear to be the offending lines. Commenting them out should result in a failure to satisfy constraints but instead yields a different error:
```
Message:  Should not read uninitialized memory
Location: /home/ax0/.cargo/registry/src/github.com-1ecc6299db9ec823/acvm-0.21.0/src/pwg/memory_op.rs:26
```

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
Potentially related to the issues in #1954?
