### ISSUE TITLE
Remove panic location from error messages

### ISSUE THREAD

**Issue by rahul-kothari** [noir-lang/noir#2104]
### Problem

![image](https://github.com/noir-lang/noir/assets/35169918/6fa261f1-6860-4206-9fef-22b2cb43194b)

The location text underneath is scary and unehlpful
Distracts the dev from the real error (

### Happy Case

Location should be where the error is coming from in my file!

### Would you like to submit a PR for this Issue?

No

**Comment by f01dab1e** [comment]
yes
