### ISSUE TITLE
Better return type error message

### ISSUE THREAD

**Issue by rahul-kothari** [noir-lang/noir#2105]
### Problem

![image](https://github.com/noir-lang/noir/assets/35169918/bc51a32f-b3fc-4b82-a49f-91a574ee18fe)

Happens when I write:
```
fn lotsofRead() -> pub Field {
....
// I return nothing!
}
```

### Happy Case

Could be `Expected return type Field, but a value of type () was actually returned`

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@f01dab1e can you take this on?

**Comment by f01dab1e** [comment]
maybe add an annotation like in Rust:
```
  |
1 | fn lotsofRead() -> usize {
  |    ----------      ^^^^^ expected `usize`, found `()`
  |    |
  |    implicitly returns `()` as its body has no tail or `return` expression
  ```
