### ISSUE TITLE
Gather feedback about solidity verifier output paths

### ISSUE THREAD

**Issue by phated** [noir-lang/noir#2108]
In #1992, we changed the file path locations output by the `codegen-verifier` command to be `<root>/contract/<package_name>/plonk_vk.sol`.

We are seeking feedback on this change. Does this layout make sense? Would something else be better?

**Comment by Savio-Sou** [comment]
cc @critesjosh @signorecello in case if you guys have any thoughts

**Comment by TomAFrench** [comment]
Why do we use the filename `plonk_vk.sol`? Would `<root>/contract/<package_name>.sol` be preferable?

**Comment by phated** [comment]
> Why do we use the filename `plonk_vk.sol`? Would `<root>/contract/<package_name>.sol` be preferable?

Tom and I discussed this a bit over a call and we think the package name should be used for a directory because some verifiers can contain multiple files (such as https://github.com/AztecProtocol/barretenberg/tree/master/sol)

**Comment by TomAFrench** [comment]
That said, `plonk_vk.sol` is a pretty bad name and could be improved imo
