### ISSUE TITLE
Refactor optimizer logic in compile_circuit

### ISSUE THREAD

**Issue by phated** [noir-lang/noir#2110]
### Problem

The `compile_circuit` function in nargo_cli mutates a program with an optimized circuit while updating debugging data. This seems like it could be contained in the optimize function, which could take ownership of the program and return an "optimized program" that we'd use everywhere afterwards.

### Happy Case

Nargo/compiler developers should be able to know whether a program is optimized or not based on the data types in the program.

### Would you like to submit a PR for this Issue?

Maybe

**Comment by TomAFrench** [comment]
This has been completed with the creation of `nargo::ops::optimize`
