### ISSUE TITLE
Closure environments aren't added to a closure's parameters

### ISSUE THREAD

**Issue by alehander92** [noir-lang/noir#2120]
### Aim

Try to assign to a value using a captured mutable reference to it in a closure:

(example by @jfecher  ):

```noir
fn main() {
    let x1 = &mut 42;
    let set_x1 = |y| { *x1 = y; };

    assert(*x1 == 42);
    set_x1(44);
    assert(*x1 == 44);
    set_x1(*x1);
    assert(*x1 == 44);
}
```

run `nargo execute` in this project

### Expected Behavior

assertions pass correctly, no error

### Bug

A lookup ssa ICE:

<details>
<pre>
The application panicked (crashed).
Message:  lookup: variable not defined
Location: crates/noirc_evaluator/src/ssa_refactor/ssa_gen/context.rs:418

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 8 frames hidden ⋮                               
   9: core::panicking::panic_display::h29316b4d8276b58d
      at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:139
  10: core::panicking::panic_str::hdb14547b30ece385
      at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:123
  11: core::option::expect_failed::h1c9d589f6e6349ed
      at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/option.rs:1879
  12: core::option::Option<T>::expect::h4358a8adecd3fa90
      at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/option.rs:741
  13: noirc_evaluator::ssa_refactor::ssa_gen::context::FunctionContext::lookup::h9248c1e85392b3f2
      at /home/al/noir/crates/noirc_evaluator/src/ssa_refactor/ssa_gen/context.rs:418
  14: noirc_evaluator::ssa_refactor::ssa_gen::context::FunctionContext::ident_lvalue::h139e67ba738052c6
      at /home/al/noir/crates/noirc_evaluator/src/ssa_refactor/ssa_gen/context.rs:520
  15: noirc_evaluator::ssa_refactor::ssa_gen::context::FunctionContext::extract_current_value_recursive::hd12835bcfdf47006
      at /home/al/noir/crates/noirc_evaluator/src/ssa_refactor/ssa_gen/context.rs:543
  16: noirc_evaluator::ssa_refactor::ssa_gen::context::FunctionContext::extract_current_value::h98d5aedb18d85c15
      at /home/al/noir/crates/noirc_evaluator/src/ssa_refactor/ssa_gen/context.rs:503
  17: noirc_evaluator::ssa_refactor::ssa_gen::<impl noirc_evaluator::ssa_refactor::ssa_gen::context::FunctionContext>::codegen_assign::h0ae74c0605bce610
      at /home/al/noir/crates/noirc_evaluator/src/ssa_refactor/ssa_gen/mod.rs:433
  18: noirc_evaluator::ssa_refactor::ssa_gen::<impl noirc_evaluator::ssa_refactor::ssa_gen::context::FunctionContext>::codegen_expression::hbed02fe13302f1d6
      at /home/al/noir/crates/noirc_evaluator/src/ssa_refactor/ssa_gen/mod.rs:81
  19: noirc_evaluator::ssa_refactor::ssa_gen::<impl noirc_evaluator::ssa_refactor::ssa_gen::context::FunctionContext>::codegen_block::h1f4442e155ad6e66
      at /home/al/noir/crates/noirc_evaluator/src/ssa_refactor/ssa_gen/mod.rs:178
  20: noirc_evaluator::ssa_refactor::ssa_gen::<impl noirc_evaluator::ssa_refactor::ssa_gen::context::FunctionContext>::codegen_expression::hbed02fe13302f1d6
      at /home/al/noir/crates/noirc_evaluator/src/ssa_refactor/ssa_gen/mod.rs:65
  21: noirc_evaluator::ssa_refactor::ssa_gen::<impl noirc_evaluator::ssa_refactor::ssa_gen::context::FunctionContext>::codegen_function_body::h3a30d7fadb672b15
      at /home/al/noir/crates/noirc_evaluator/src/ssa_refactor/ssa_gen/mod.rs:56
  22: noirc_evaluator::ssa_refactor::ssa_gen::generate_ssa::heca22e4cc66763e8
      at /home/al/noir/crates/noirc_evaluator/src/ssa_refactor/ssa_gen/mod.rs:46
  23: noirc_evaluator::ssa_refactor::optimize_into_acir::hc5b0e6998a74d50a
      at /home/al/noir/crates/noirc_evaluator/src/ssa_refactor.rs:43
  24: noirc_evaluator::ssa_refactor::create_circuit::ha30ce1b0ce7adb30
      at /home/al/noir/crates/noirc_evaluator/src/ssa_refactor.rs:87
  25: noirc_driver::compile_no_check::h6c12ded194d20b7f
      at /home/al/noir/crates/noirc_driver/src/lib.rs:277
  26: noirc_driver::compile_main::he8205448c3365dc5
      at /home/al/noir/crates/noirc_driver/src/lib.rs:166
  27: nargo_cli::cli::compile_cmd::compile_circuit::hfe072f713cdd406f
      at /home/al/noir/crates/nargo_cli/src/cli/compile_cmd.rs:136
  28: nargo_cli::cli::execute_cmd::execute_package::hfc05356ee1f8318e
      at /home/al/noir/crates/nargo_cli/src/cli/execute_cmd.rs:73
  29: nargo_cli::cli::execute_cmd::run::h4995f87b92c6170a
      at /home/al/noir/crates/nargo_cli/src/cli/execute_cmd.rs:51
  30: nargo_cli::cli::start_cli::hed1ec5e662c4cab2
      at /home/al/noir/crates/nargo_cli/src/cli/mod.rs:79
  31: nargo::main::hd4a820dc8ea83d4b
      at /home/al/noir/crates/nargo_cli/src/main.rs:14
  32: core::ops::function::FnOnce::call_once::h341ee90d78f8ccb6
      at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251
                                ⋮ 16 frames hidden ⋮                              
</pre>
</details>

### Installation Method

Compiled from source

### Nargo Version

nargo 0.9.0 (git version hash: 39610af5b3cc8de7e3aa963a2cbff3083179cbf4, is dirty: true)

### Additional Context

originated here https://github.com/noir-lang/noir/pull/1959#issuecomment-1660999172

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
Looking at the lambda from this example in the monomorphized IR:
```
fn lambda$f1(y$l1: Field) -> () {
    *x1$l0 = y$l1
}
```
We can see that the "variable not found" panic is correct since `x1` isn't defined within the lambda at all. It is part of the closure environment but was never added as a parameter to the lambda. I'll keep this issue open to track adding environment parameters to closures, but it is not an SSA or references related issue.

**Comment by jfecher** [comment]
Also, this may help with debugging:

To get the above output I added a `println` of the monomorphized output after the call to `monomorphize` in `crates/noirc_driver/src/lib.rs`
