### ISSUE TITLE
A `not yet implemented: Cast into signed` when trying to use `i32` array and `sort_via`

### ISSUE THREAD

**Issue by alehander92** [noir-lang/noir#2121]
### Aim

write 

```noir
fn main() {
    let myarray: [i32; 3] = [1, 2, 3];
    let descending = myarray.sort_via(|a, b| a > b);
}
```

and build/run with `nargo execute`

### Expected Behavior

build/run without error

### Bug

fails with `not yet implemented: Cast into signed`

<details>
<pre>
The application panicked (crashed).
Message:  not yet implemented: Cast into signed
Location: crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs:902

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 8 frames hidden ⋮                               
   9: noirc_evaluator::ssa_refactor::acir_gen::Context::convert_ssa_cast::h09357460f3960596
      at /home/al/noir/crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs:902
  10: noirc_evaluator::ssa_refactor::acir_gen::Context::convert_ssa_instruction::ha12452e0a9c7e573
      at /home/al/noir/crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs:311
  11: noirc_evaluator::ssa_refactor::acir_gen::Context::convert_acir_main::hd0231e6bf01f6f4d
      at /home/al/noir/crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs:172
  12: noirc_evaluator::ssa_refactor::acir_gen::Context::convert_ssa::hede2e604c9547159
      at /home/al/noir/crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs:155
  13: noirc_evaluator::ssa_refactor::acir_gen::<impl noirc_evaluator::ssa_refactor::ssa_gen::program::Ssa>::into_acir::hc23fca6360b5c572
      at /home/al/noir/crates/noirc_evaluator/src/ssa_refactor/acir_gen/mod.rs:109
  14: noirc_evaluator::ssa_refactor::optimize_into_acir::hc5b0e6998a74d50a
      at /home/al/noir/crates/noirc_evaluator/src/ssa_refactor.rs:66
  15: noirc_evaluator::ssa_refactor::create_circuit::ha30ce1b0ce7adb30
      at /home/al/noir/crates/noirc_evaluator/src/ssa_refactor.rs:87
  16: noirc_driver::compile_no_check::h6c12ded194d20b7f
      at /home/al/noir/crates/noirc_driver/src/lib.rs:277
  17: noirc_driver::compile_main::he8205448c3365dc5
      at /home/al/noir/crates/noirc_driver/src/lib.rs:166
  18: nargo_cli::cli::compile_cmd::compile_circuit::hfe072f713cdd406f
      at /home/al/noir/crates/nargo_cli/src/cli/compile_cmd.rs:136
  19: nargo_cli::cli::execute_cmd::execute_package::hfc05356ee1f8318e
      at /home/al/noir/crates/nargo_cli/src/cli/execute_cmd.rs:73
  20: nargo_cli::cli::execute_cmd::run::h4995f87b92c6170a
      at /home/al/noir/crates/nargo_cli/src/cli/execute_cmd.rs:51
  21: nargo_cli::cli::start_cli::hed1ec5e662c4cab2
      at /home/al/noir/crates/nargo_cli/src/cli/mod.rs:79
  22: nargo::main::hd4a820dc8ea83d4b
      at /home/al/noir/crates/nargo_cli/src/main.rs:14
  23: core::ops::function::FnOnce::call_once::h341ee90d78f8ccb6
      at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251
                                ⋮ 16 frames hidden ⋮                         
                                </pre>
                                </details>
                                

### Installation Method

build from source

### Nargo Version

nargo 0.9.0 (git version hash: 39610af5b3cc8de7e3aa963a2cbff3083179cbf4, is dirty: true)

### Additional Context

Originated here https://github.com/noir-lang/noir/pull/1959#discussion_r1280994476

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
This is a result of signed integers still not being implemented properly in Noir (unfortunately). See #2184. I'm going to close this issue since #2184 is better for tracking it. Additionally, I'll work on #2125 so users aren't confused by this in the future.
