### ISSUE TITLE
Allow usage of some stdlib functions without an explicit import

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#2140]
### Problem

https://github.com/noir-lang/noir/pull/2137 adds an `assert_eq` builtin function which is more efficient than usage of the `assert()` keyword. It isn't very ergonomic for developers however as it must be imported from the stdlib explicitly.

```rust
// Compiles
use dep::std::assert_eq;

fn main(x: Field) {
    assert_eq(x, 3);
}

// Compile error
fn main(x: Field) {
    assert_eq(x, 3);
}
```

### Happy Case

In an ideal situation we would have a list of stdlib functions which are imported into each Noir file by default.

An example list could be:
- `assert_eq`
- `println`

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
The usual way to do this is via a prelude that gets imported automatically to every program. 

First step would be to add a prelude file to stdlib and then have it only import the relevant items, then given that the stdlib is always available, the compiler will automatically include the prelude imports into every module.

**Comment by kevaundray** [comment]
Changed priority to P-low since this is non-blocking and is the current workflow strategy

**Comment by TomAFrench** [comment]
Closing in favour of #2361
