### ISSUE TITLE
Should naitive and wasm proving and verifying tests be added to ci as well 

### ISSUE THREAD

**Issue by Ethan-000** [noir-lang/noir#2143]
### Problem

related to https://github.com/noir-lang/noir/issues/1137

at the moment only build is checked i think but proving and verifying in wasm environment is not checked

### Happy Case

.

### Would you like to submit a PR for this Issue?

Maybe

**Comment by Savio-Sou** [comment]
Related to https://github.com/noir-lang/noir/issues/1229?

**Comment by TomAFrench** [comment]
`noir_wasm` isn't responsible for proving and verifying, it's instead simply an implementation of the Noir compiler. Proving and verifying is a multistep process so it doesn't make sense to bake into a single wasm binary.

```mermaid
flowchart TD
   A -->|ACIR| C
   A -->|ABI| B
   B -->|Initial witness| C
   C -->|Solved witness| E
   D -->|Public inputs| F
   A -->|ACIR| E
   A -->|ACIR| F
   subgraph noir_wasm
     A[Noir source compilation]
   end 
   
   subgraph noirc_abi_wasm
     B[Abi encoding of inputs]
   end 
   
   subgraph acvm_js
     direction TB
     C[Execution of ACIR with initial witness]
     D[Extraction of public inputs]
     
        C -->|Solved witness| D
   end 
   
    subgraph bb.js
     direction TB
     E[Proof generation]
     F[Proof verification]
     
     E -->|Proof| F
   end 
```

The idea being that with a fixed circuit you can remove `noir_wasm` from this graph just as you don't embed solc into the browser when interacting with smart contracts. This also allows us to place each component at the right abstraction layer (acvm_js sits in the ACVM repo) and we can test components in isolation.

#1229 is just related to us adding tests for Noir code to produce identical ACIR when provided to the CLI vs wasm. We should have e2e integration tests for the entire user flow however.

**Comment by kevaundray** [comment]
@Ethan-000 If you are satisfied with the response from Tom, please close the issue or ask for clarification on any points that are not clear!

**Comment by kevaundray** [comment]
> proving and verifying is not tested on naitive as well at the moment i think, only execution is tested

Yep thats correct -- Proving and verifying is tested in the particular backends repository, so barretenberg has acir_tests and another backend will be able to take e2e tests from Noir and run those on their repository
