### ISSUE TITLE
Support functions with optional arguments

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#2145]
### Problem

As described in https://github.com/noir-lang/noir/issues/1939, we want to be able to provide an optional assert message to be displayed in the situation where a constraint is unsatisfied.

`assert` is in the process of being changed into a [built-in function](https://github.com/noir-lang/noir/pull/2137), we then need to be able to have two version of `assert_eq` both with and without the assert message.

### Happy Case

Ideally we'd be able to have an optional argument to `assert_eq` as so

```rust
#[builtin(assert_eq)]
fn assert_eq<T>(lhs: T, rhs: T, msg?: str) {}
```

### Alternatives Considered

We could also allow shadowing of a function name as long as the signature was different.

```rust
fn assert_eq<T>(lhs: T, rhs: T) {
    assert_eq(lhs, rhs, "")
}

#[builtin(assert_eq)]
fn assert_eq<T>(lhs: T, rhs: T, msg?: str) {}
```

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
We could also simply not convert `assert_eq` into a builtin function and keep it as a keyword. Supporting an optional extra message argument is the reason assert is still a keyword for example.

**Comment by kevaundray** [comment]
Changed to P-LOW due to this being a nice to have if we have it as a keyword. The thing that Rust has that we don't which makes it possible in Rust without optional arguments is macro_rules

**Comment by kevaundray** [comment]
Closing this as not actionable, we can re-open if we do decide to have optional arguments
