### ISSUE TITLE
Divide-by-zero is a constraint failure for integers but not for `Field`

### ISSUE THREAD

**Issue by Jurarpereurs** [noir-lang/noir#2149]
### Aim

The proving phase would complain that constraints are unsatisfiable when dividing an unsigned integer by zero:

```rust
let a: u8 = 3 / 0;
```

However, when changing the variable type to Field, the proving phase would not complain:

```rust
let a: Field = 3 / 0;
```

It would be better to make the behavior consistent. Also, the compiler should explicitly detect and give more informative error messages for divide-by-zero.

### Expected Behavior

The compiler should explicitly issue an error message for divide-by-zero.

### Bug

Please see steps to reproduce.

### To Reproduce

Save the following code into `src/main.nr`:

```rust
use dep::std;

fn main() {
    let a: u8 = 3 / 0;
    std::println(a);
}
```

Run the following command:

```bash
nargo prove
```

You would see the following error message:

```bash
error: Unsatisfied constraint
  ┌─ /home/Jurarpereurs/src/main.nr:4:17
  │
4 │     let a: u8 = 3 / 0;
  │                 ----- Constraint failed

Error: could not satisfy all constraints

Location:
    crates/nargo_cli/src/cli/mod.rs:74:5
```

Then change the variable type to Field:

```rust
use dep::std;

fn main() {
    let a: Field = 3 / 0;
    std::println(a);
}
```

Run the following command:

```bash
nargo prove
```

The proving phase would succeed and you would see the following output:

```bash
"0x00"
```

### Installation Method

Binary

### Nargo Version

nargo 0.9.0 (git version hash: 35404ba9b2916cebf35519546eec0f0ae54b5516, is dirty: false)

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
Since its a constraint failed error, this can likely be replicated with `nargo execute`
