### ISSUE TITLE
Better error for misuse of unary operators

### ISSUE THREAD

**Issue by Ethan-000** [noir-lang/noir#2152]
### Problem

small issue i found when experiementing with the language

if we try to do something like 

```rust
fn main() {
    let a = [1,2] | [1,2];
}
```

it will return 
```rust
error: Arrays cannot be used in an infix operation
```

which is good but with

```rust

fn main() {
    let a = -[1,2];
}

```

it will return

```
error: Expected type Field, found type [Field; 2]
```

which is a decent error but could be better with something like

```rust
error: Arrays cannot be applied with an unary operator
```

### Happy Case

.

### Would you like to submit a PR for this Issue?

Maybe

**Comment by kevaundray** [comment]
@Ethan-000 did you want to take this on?
