### ISSUE TITLE
Inconsistent parsing of `CrateName`s from `String`

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#2166]
I noticed that we're currently only performing validation of crate names when using the `FromStr` trait but we have `From<String>` implementations

https://github.com/noir-lang/noir/blob/2232a387177f827d14f7c0b7ac1f3e5bb6d957d9/crates/noirc_frontend/src/graph/mod.rs#L38-L64

This means that we get the unfortunate behaviour

```
// Returns Err()
let crate_name = CrateName::from_str(user_input);

// Returns an invalid crate name
let crate_name = CrateName::from(user_input);
```

We should standardise these so that the `From<String>` becomes `TryFrom<String>` implementations and apply the same check.

**Comment by phated** [comment]
@TomAFrench Is `CrateName::from` implemented the reverse of `String::from(crate_name)`? I used the inverted impl so we'd only have `String::from` but maybe does some sort of double generation for each type?

**Comment by TomAFrench** [comment]
Ahhhh, I just realised I was misreading the linked implementations as `From<String> for CrateName` rather than `From<CrateName> for String`

**Comment by TomAFrench** [comment]
This issue is invalid in this case.

**Comment by TomAFrench** [comment]
Thanks @phated
