### ISSUE TITLE
Are function types supposed to be working

### ISSUE THREAD

**Issue by Ethan-000** [noir-lang/noir#2176]
### Problem

I don't know if these are considered implemented or not but saw functions are parsed as types. is the following suppose to work

```rust
use dep::std;
fn main() {
    let a = 1;
    let c = foo(a, bar);
    std::println(c);
}

fn foo(a: Field, f: Fn(Field) -> Field) -> Field {
    f(a)
}

fn bar(b: Field) -> Field {
    b
}
```

### Happy Case

.

### Would you like to submit a PR for this Issue?

Maybe

**Comment by jfecher** [comment]
Yes, but you have the syntax a bit off. The function type uses a lower-case `fn` like rust's function types. Capital `Fn` is reserved for function traits once traits are implemented. Here's a fixed version of your example:
```rs
use dep::std;
fn main() {
    let a = 1;
    let c = foo(a, bar);
    std::println(c);
}

fn foo(a: Field, f: fn(Field) -> Field) -> Field {
    f(a)
}

fn bar(b: Field) -> Field {
    b
}
```

**Comment by jfecher** [comment]
Ah, I should also note that you can use lambdas as well: `|a, b| a + b`. We're in the process of implementing closures though, so trying to capture variables from the environment is broken at the moment..
