### ISSUE TITLE
Panic when using `nargo new`

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#2182]
### Aim

`nargo new foo`

### Expected Behavior

a new directory to be created

### Bug

```
The application panicked (crashed).
Message:  Command new: Argument names must be unique, but 'name' is in use by more than one argument or group
Location: /Users/.../.cargo/registry/src/github.com-1ecc6299db9ec823/clap_builder-4.3.19/src/builder/debug_asserts.rs:86
```

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by phated** [comment]
This was broken by my rebase. Tom is going to submit a PR shortly

**Comment by TomAFrench** [comment]
I can't reproduce this on 1c991d0f0eac9270eb218b9ad672e36e8af74bc9.

**Comment by jfecher** [comment]
I'm also on 1c991d0f0eac9270eb218b9ad672e36e8af74bc9

**Comment by TomAFrench** [comment]
Ah, this is only an issue on `cargo run -- nargo new` apparently. Fixing now

**Comment by phated** [comment]
When running nargo executable, it was showing duplicate flags in help:
```
Options:
      --name <NAME>  Name of the package [default: package directory name]
      --name <NAME>  Name of the package [default: current directory name]
      --lib          Use a library template
      --bin          Use a binary template [default]
  -h, --help         Print help
```

**Comment by jfecher** [comment]
> Ah, this is only an issue on cargo run -- nargo new apparently. Fixing now

No, it is occurring on plain `nargo new foo` and any `nargo new` command for me

**Comment by phated** [comment]
> No, it is occurring on plain nargo new foo and any nargo new command for me

Doesn't happen on Mac, but we know where the fix is so it doesn't matter.

**Comment by jfecher** [comment]
> Doesn't happen on Mac, but we know where the fix is so it doesn't matter.

I'm on mac

**Comment by jfecher** [comment]
I also can't run `nargo new --help` at all, that yields the same panic

**Comment by phated** [comment]
Cool, so it's just a @jfecher problem. It's okay, fix incoming.
