### ISSUE TITLE
Integrate `noir-lang/build-nargo` into this repository

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#2188]
### Problem

The Nargo release process is currently split off into the `noir-lang/build-nargo` repository which handles building Nargo binaries and adding them to release tags. This separation causes issues as we've had a good number of times where we create a release and it's unable to create binaries due to issues which only occur in the release flow.

### Happy Case

We should integrate those workflows into the CI of this repository. We can then use the built binaries to implement #2013 and also run the full cross-compilation flows on any release-please PR which while block any broken release.

### Alternatives Considered

#1921 uses the output of one of these release flows already so we can start amortising these build times across CI workflows.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@TomAFrench are you taking this on?
