### ISSUE TITLE
Should `const` be renamed?

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#219]
An issue raised by @guipublic is whether we should rename `const` to something more descriptive since it is meant to be a "is known at compile-time" tag moreso than "is not mutated" tag as some may expect. There is precedence for both approaches - in rust a `const fn` is one that is evaluated at compile-time and a `const` variable is one that is a compile-time constant and is substituted for its rhs at each use (this is evident when using Atomics or Mutexes - they will appear as if they never change). In C++ a `constexpr` expression is similarly known at compile-time, but a `const` type is one that is shallowly immutable.

**Comment by kevaundray** [comment]
@jfecher what is the status on this issue?

**Comment by jfecher** [comment]
Closed, we have renamed the old `const` to `comptime` to indicate whether a value should be known at compile-time or not.
