### ISSUE TITLE
`nargo compile --contracts` output gets garbled

### ISSUE THREAD

**Issue by dbanks12** [noir-lang/noir#2203]
### Aim

Read warnings and errors from nargo.

### Expected Behavior

Warnings and errors should be printed normally.

### Bug

This happens when compiling aztec contracts:
![image](https://github.com/noir-lang/noir/assets/47112877/7ad65014-14b8-47fd-bb99-cae22c20f2f3)

### To Reproduce

1. clone and `./bootstrap.sh` aztec-packages repo
2. `cd yarn-projects/noir-contracts`
3. `yarn noir:build:all`

### Installation Method

Compiled from source

### Nargo Version

0.9.0

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
This looks more like a result of you spinning up multiple shells in parallel which are all writing to stdout concurrently.

**Comment by dbanks12** [comment]
Ah that's exactly what's happening: https://github.com/AztecProtocol/aztec-packages/blob/master/yarn-project/noir-contracts/scripts/compile.sh#L57

Thanks @TomAFrench!
