### ISSUE TITLE
Add builtin `serialize` and `deserialize` functions

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#2240]
### Problem

It can be useful for TS tools to have a canonical serialization order for types and a builtin function that automatically converts to this order.

### Happy Case

We should add a `serialize<T>(x: T) -> [Field]` builtin to serialize every type to a canonical serialization order. This will use the user-defined field order for structs and should issue an error message for types that cannot be serialized such as functions.

A pairing `deserialize<T>(fields: [Field]) -> Option<T>` function would also be useful.

### Alternatives Considered

Once traits are added the need for this function isn't entirely obviated since a user-defined `Serialize` impl may not adhere to the canonical serialization order. Can we make this distinction more clear and avoid name conflicts in any way? Or should we not worry about this issue since every type would already be able to be serialized via this builtin and we thus wouldn't need a Serialize trait?

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
Alternative names would be `to_fields` and `from_fields`

**Comment by Savio-Sou** [comment]
Superseded by https://github.com/noir-lang/noir/issues/3379.
