### ISSUE TITLE
Panic when using right shift operator

### ISSUE THREAD

**Issue by shuklaayush** [noir-lang/noir#2250]
### Aim

There's a regression in the newer versions of the compiler where the following code panics with `Message:  attempt to divide by zero`
```rust
fn main() {
    let a: u1 = 1 >> 1;
    let b: u32 = 1 >> 32;
}
```

### Expected Behavior

The code shouldn't panic and return 0

### Bug

I think what's probably happening is that the bit shift is getting optimized to a division and the divisor is getting truncated to the type of the dividend. So `>> 1` becomes `/ (2^1 as u1)` which is 0 and hence the panic.

### To Reproduce

1. Copy the code above
2. Run `nargo execute main`

### Installation Method

Compiled from source

### Nargo Version

nargo 0.9.0 (git version hash: 90c5d182b578b6d512e4b5dc2c07810e6815f31e, is dirty: false)

### Would you like to submit a PR for this Issue?

Maybe

**Comment by TomAFrench** [comment]
Thanks, I can reproduce this
