### ISSUE TITLE
Epic: bb.js end to end testing

### ISSUE THREAD

**Issue by jonybur** [noir-lang/noir#2251]
```[tasklist]  
- [ ] https://github.com/noir-lang/noir/issues/2252
- [ ] https://github.com/noir-lang/noir/issues/2253
```

![Image](https://user-images.githubusercontent.com/11148144/259756072-cdac17a3-4381-4a6a-ae60-799d8e575855.png)

**Comment by Savio-Sou** [comment]
@kobyhallx @jonybur is this completed?

**Comment by jonybur** [comment]
@Savio-Sou The work on this got superseded by Charlie's bb.js refactor PR

**Comment by Savio-Sou** [comment]
Thanks! Link to the PR for future readers' reference: https://github.com/AztecProtocol/aztec-packages/pull/1855.
