### ISSUE TITLE
Testing: proving with bb.js and noir

### ISSUE THREAD

**Issue by jonybur** [noir-lang/noir#2252]
Description:
Ensure that the provided ACIR and the solved witness are provable by bb.js. In the case of bb.js, this should be inclusive of both browser and node versions.

Acceptance Criteria:

- bb.js (browser & node) should correctly generate proof based on a provided ACIR and witness.
- a GitHub workflow should be added that verifies the output of both modules and checks that it matches.

**Comment by Savio-Sou** [comment]
> bb.js (browser & node) and noir should both correctly generate proof...

What do you mean by noir should generate a proof?

**Comment by Savio-Sou** [comment]
Link to current Noir tests in the barretenberg repo in case if it's helpful: https://github.com/AztecProtocol/barretenberg/blob/master/acir_tests/run_acir_tests.sh

**Comment by Savio-Sou** [comment]
Works superseded by https://github.com/AztecProtocol/aztec-packages/pull/1855.
