### ISSUE TITLE
Testing: bb.js output should be verifiable against solidity

### ISSUE THREAD

**Issue by jonybur** [noir-lang/noir#2253]
Description:
Utilize the `verify()` method of bb.js and integrate its results with the Solidity verifier to enable verification and ensure compatibility with Ethereum smart contracts.

Acceptance Criteria:

- The `verify()` method in bb.js should work as expected.
- Integration with Solidity verifier should be smooth and without inconsistencies.

**Comment by kevaundray** [comment]
Is this a Noir issue or something that can be placed into the barretenberg?

**Comment by Savio-Sou** [comment]
Works superseded by https://github.com/AztecProtocol/aztec-packages/pull/1855.
