### ISSUE TITLE
linker error cannot find -lstdc++

### ISSUE THREAD

**Issue by themighty1** [noir-lang/noir#226]
Just wanted to note that I was getting an error 
> = note: /usr/bin/ld: cannot find -lstdc++
          collect2: error: ld returned 1 exit status

I had libstdc++-8-dev libstdc++-9-dev libstdc++-10-dev installed on the system
Only when I installed libstdc++-7-dev, the error went away.

**Comment by kevaundray** [comment]
We've come a long way from this issue and most of our c++ issues are now being logged on the c++ repo. 

This seems to be fixed and if not we can reopen on that repo.

Thank you for your patience and trying out Noir!
