### ISSUE TITLE
Simplify the release acceptance tests

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#2262]
In #2211 we've pulled across the release acceptance tests from `noir-lang/build-nargo` verbatim. Now they're here we can start reworking them in the context of this repository.

See related comments for context:
https://github.com/noir-lang/noir/pull/2211#discussion_r1287680206

https://github.com/noir-lang/noir/pull/2211#discussion_r1290519861

https://github.com/noir-lang/noir/pull/2211#discussion_r1290522712

**Comment by Savio-Sou** [comment]
Were these completed?
