### ISSUE TITLE
Release acceptance testing suite doesn't report errors on windows.

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#2270]
See test report for latest commit on windows: https://github.com/noir-lang/build-nargo/actions/runs/4388080749/jobs/7684151837#step:9:40

This is the error currently being reported at https://github.com/noir-lang/noir/issues/981 but it's not being raised as an issue by our test suite.

**Comment by Savio-Sou** [comment]
Assigning `P-LOW` as we don't officially support Windows.
