### ISSUE TITLE
`CrateName` does not reject empty strings

### ISSUE THREAD

**Issue by critesjosh** [noir-lang/noir#2287]
### Aim

`nargo compile` shouldn't produce an empty target dir when the artifact (target.json) is placed in the project root.

### Expected Behavior

see above.

### Bug

no error messages.

### To Reproduce

1. run `nargo compile`. see output described above

### Installation Method

None

### Nargo Version

nargo 0.9.0 (git version hash: 3d1b2522c8d9a0acebff102f9f877c44178c5db5, is dirty: false)

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
Can you give more concrete reproduction steps? This isn't very clear to me.

**Comment by critesjosh** [comment]
Sorry, I left out an important detail. This only happens when `name = ""` in Nargo.toml.

You can create a new noir project with `nargo init`. Make the name an empty string. then run `nargo compile`

**Comment by TomAFrench** [comment]
Ok, looks like we're not doing enough validation there.
