### ISSUE TITLE
nargo prove fails due to command arg conflict

### ISSUE THREAD

**Issue by alexvitkov** [noir-lang/noir#2299]
### Aim

The recently added `--program-name` conflicts with the `--prover-name` argument of `nargo prove`, and `nargo prove` panics with the following error:

```Message:  Command prove: Short option names must be unique for each argument, but '-p' is in use by both 'prover_name' and 'program_dir'```

### Expected Behavior

nargo prove doesn't panic

### Bug

it panics

### To Reproduce

1. nargo prove
2. panic

### Installation Method

Compiled from source

### Would you like to submit a PR for this Issue?

Yes

**Comment by alexvitkov** [comment]
Fix: https://github.com/noir-lang/noir/pull/2300

**Comment by phated** [comment]
Solved by #2300 - thanks @alexvitkov!
