### ISSUE TITLE
Remove `dep` keyword for importing from dependencies

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#2307]
### Problem

Importing from libraries in Noir differs from rust in that you must add a `dep::` prefix to each path in the dependency. This is unnecessary since you can already tell by the crate name in the path that it is a different crate.

### Happy Case

The `dep::` prefix is removed.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@jfecher did you start working on this? If not, then I think we can assign it to someone else to reduce context switch and since its E-LOW
