### ISSUE TITLE
Ssa warn for constraints that will always succeed/fail

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#231]
It is possible that code like `constrain a != 0` can be known to always fail if the ssa pass evaluates `a` to 0, resulting in `constrain 0 != 0`. Before, the ssa code would crash with a failed assert that a != b, but PR #223 removed most of these in favor of having the code fail to verify instead.

Can we give better warning messages here that points users to the correct location in the source code?

**Comment by kevaundray** [comment]
The new ssa code contains source location information, so closing this. We can open a new issue if we need the new SSA to improve in its current functionality
