### ISSUE TITLE
Noir-wasm nodeJs testing

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#2326]
### Problem

Currently it does not seem possible to run tests of noir-wasm using nodeJs

### Happy Case

We can run tests using NodeJs aswell as the browser

### Would you like to submit a PR for this Issue?

No

**Comment by Savio-Sou** [comment]
What do you mean it's not possible 🤔

We had https://github.com/noir-lang/noir/pull/1921 that introduced Node.js-based tests. Did something break?

Headless browser tests are something we plan to tackle next (after bb.js tests): https://github.com/noir-lang/noir/issues/2163

**Comment by kevaundray** [comment]
> Could you elaborate a bit on what does "not possible" mean?
> 
> We had #1921 that introduced Node.js-based tests. Did something break?
> 
> Headless browser tests are something we plan to tackle next (after bb.js tests): #2163

Hmm where are the node JS tests in that? I only see browser tests being called
