### ISSUE TITLE
Save nightly build in github releases with date tags

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#2332]
### Problem

Similar to Rust, it would be great to be able to do something like `noirup -v nightly-2023-08-3`

Our current workflow is that each night, we overwrite the nightly tag, so there is no convenient way to get the nightly release from two or three days ago. 

This is mainly a problem for project whom don't want to build from source, and don't want to wait for a release but they want to use the latest features.

### Happy Case

Each night when CI makes a release, it should tag the release artifacts with the date. It should also tag the latest release artifact with `nightly` so users can do `noirup -v nightly` to get the latest nightly version.

Note: we only need to store nighty versions for as long as our release schedule is. So if we release every two weeks, we only need to store nightlies for 2 weeks. We could perhaps just round it to 30 days so folks have time to switch their CI from nightly to stable.

### Would you like to submit a PR for this Issue?

No

**Comment by phated** [comment]
> Note: we only need to store nighty versions for as long as our release schedule is. So if we release every two weeks, we only need to store nightlies for 2 weeks. We could perhaps just round it to 30 days so folks have time to switch their CI from nightly to stable.

This is incorrect, we'd need to store them forever to avoid breaking anyone's workflow that has these values hardcoded.

**Comment by kevaundray** [comment]
I don't think we should make that guarantee with nightly builds -- users should not be trying to get stability with nightly builds, for that they should rely on a stable release version which does live forever.

I'm okay with increasing the retention period to something longer barring Github's storage limits
