### ISSUE TITLE
Change `constrain` to take any boolean expression

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#235]
Currently the constrain construct includes a binary operator as part of its syntax: `constrain <expr1> <binop> <expr2>` where `<binop>` is a boolean operator like `==`.  This seems to be a relic from before these operators where implemented elsewhere in the language.

Proposed change is to generalize to `constrain <expr>` where `<expr>` is any boolean-returning expression.

**Comment by kevaundray** [comment]
@jfecher can this be closed?

**Comment by jfecher** [comment]
Indeed, this has been implemented in #236
