### ISSUE TITLE
(fuzzer) - The parser does not allow parenthesizing in two type locations

### ISSUE THREAD

**Issue by pczarn** [noir-lang/noir#2375]
### Aim

I tried to compile types with parentheses in two locations:
* `str<(Foo)>` - string type with a parethesized argument
* `[Foo; (Bar)]` - array type with a parenthesized length

### Expected Behavior

Expected the types to compile with at most a warning.

### Bug

This is inconsistent with other type expressions in Noir, and with the Rust parser which gives a warning (I know we differ from Rust grammar, but still).

### To Reproduce

Compile:
```rust
fn foo<Bar>(bar: [Bar; (123)]) {}
```
-> Error: `Expression is invalid in an array-length type: 'Error'. Only unsigned integer constants, globals, generics, +, -, *, /, and % may be used in this context.`
```rust
fn foo<Foo>(bar: str<(Foo)>) {}
```
-> ???

### Installation Method

Compiled from source

### Additional Context

Bug found with the parser-fuzzer tool.

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
@f01dab1e want to take this one on?
