### ISSUE TITLE
Add return statement in the Frontend

### ISSUE THREAD

**Issue by guipublic** [noir-lang/noir#238]
The frontend should put return statements in the AST to indicate what is returned from a function.

**Comment by kevaundray** [comment]
@jfecher and @guipublic from internal talks, we decided to not go for this right?

**Comment by guipublic** [comment]
I don't see how you can support early returns without this, so I still think having a return statement in the AST is the most elegant pattern.

**Comment by jfecher** [comment]
If we were to add early returns we would likely need to do this. I'm not sure what our decision on early returns was previously but I'm also open to moving that to a more specific discussion issue on whether early returns should be added.

**Comment by kevaundray** [comment]
Closing this for now, lets open it up with a more detailed rationale when/if we decide to do it
