### ISSUE TITLE
Documenting commutativity on constrain statements

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#2381]
### Problem

It may come as a surprise to users if ‘assert a == b’ and ‘assert b == a’ both compile to different circuits.

This is the case with Circom for example, which is acceptable since it’s a low level language.

### Happy Case

Clearly document if we don’t plan to support both asserts being compiled to the same circuit.

### Would you like to submit a PR for this Issue?

No

**Comment by Savio-Sou** [comment]
Pardon the stupid question, but would switching `assert a == b` to `assert b == a` in other languages, e.g. Rust, compile into different bytecode / binaries?

**Comment by kevaundray** [comment]
> Pardon the stupid question, but would switching `assert a == b` to `assert b == a` in other languages, e.g. Rust, compile into different bytecode / binaries?

Thats a great question, in Rust it would be slightly different bytecode, you can see on the right [here](https://godbolt.org/z/v5oYjWeq6). In the context of _running a binary_, I don't think it matters much because both programs are equivalent and no-one really checks the binary or saves the binary anywhere.

In the context of verifying a program, if two programs are equivalent, then you don't need to re-generate the verification key, which in some cases like the blockchain are saved on-chain.

I'm not fully convinced by my own logic, so I can see a strong reason to just document it and maybe do a best effort if it doesn't increase complexity

**Comment by Savio-Sou** [comment]
> if two programs are equivalent, then you don't need to re-generate the verification key, which in some cases like the blockchain are saved on-chain

Ah makes sense.

I wasn't even sure if devs would find it troubling to begin with for different behaviors from "different code, same logic", so yeah documenting rather than fixing it sounds good.

Was this originated from an actual question from the community, or something we assumed the community might find troubling?

**Comment by TomAFrench** [comment]
I think we should generally not guarantee that a semantically equivalent Noir program will compile down an identical circuit. There's too many ways that users can insert a noop in such a way that it stops a compiler optimisation from working, etc.

**Comment by jfecher** [comment]
> I think we should generally not guarantee that a semantically equivalent Noir program will compile down an identical circuit. 

Agreed, there are plenty of ways to fool the optimizer

**Comment by TomAFrench** [comment]
Gonna close this as this is not a generally expected feature of a language.
