### ISSUE TITLE
Compile code lens displays twice

### ISSUE THREAD

**Issue by kobyhallx** [noir-lang/noir#2396]
### Aim

"Get" `Compile | Execute` Code Lens in VSCode while editing Noir src.

### Expected Behavior

`Compile | Execute` Code Lens in VSCode displayed properly

### Bug

`Compile` displays twice.

<img width="183" alt="image" src="https://github.com/noir-lang/noir/assets/102518238/f95acefc-6dc0-47d0-b61a-021015e3ae41">

### To Reproduce

1.
2.
3.
4.

### Installation Method

Binary

### Nargo Version

nargo 0.10.3 (git version hash: 2db759f43971c57e2f1f8284c82943e31a555d0c, is dirty: false)

### Additional Context

Related to #1579 

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
I also see this.

**Comment by phated** [comment]
@TomAFrench @kobyhallx please provide reproduction steps.
