### ISSUE TITLE
feat: Add parser support for trait as parameter to function or as a return type

### ISSUE THREAD

**Issue by yordanmadzhunkov** [noir-lang/noir#2397]
### Problem

```
fn tralala(a: impl TraitName) {
}
```

```
fn tralala2(a:Field) -> impl TraitName {
  ...
}
```

### Happy Case

If we want to make Traits similar to rust we should implement this as well

### Alternatives Considered

Do not support this

### Would you like to submit a PR for this Issue?

Later, we will

related to implementing traits to https://github.com/noir-lang/noir/issues/527

**Comment by kevaundray** [comment]
Can you link all traits related issues to #527 ?

**Comment by jfecher** [comment]
This would be very nice to have, although I worry it may be difficult to implement since we have no real way of type erasure. Lets only consider implementing it once our base implementation for traits is completely finished.

**Comment by TomAFrench** [comment]
This can be closed right @jfecher

**Comment by jfecher** [comment]
@TomAFrench Yes, we have impl trait as a return type but not as a parameter still since it is low priority. This issue is superseded by: https://github.com/noir-lang/noir/issues/4540
