### ISSUE TITLE
Integers should be printed as normal integers instead of fields

### ISSUE THREAD

**Issue by phated** [noir-lang/noir#2401]
### Problem

Currently, when printing an integer, it is converted to a string via `format_field_string` even though we track it as an integer in the program boundary. These should be printed as normal integers.

### Happy Case

Using `println(f"{}", 1)` should print `1` instead of `0x01`.

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
I'd like for us to do this for fields as well to be honest. If users want a hex representation we should represent this through the string formatting options.

**Comment by Savio-Sou** [comment]
cc @tsujp as you might find this interesting given the [prettify print bash script](https://github.com/tsujp/tikan/blob/master/circuit/lib/test.sh) you've already put together!

**Comment by tsujp** [comment]
> cc @tsujp as you might find this interesting given the [prettify print bash script](https://github.com/tsujp/tikan/blob/master/circuit/lib/test.sh) you've already put together!

When I get a tiny bit more bandwidth (trying to stay laser focused on ZK Fog of War Chess and EPF right now) I'll have a crack at a PR for this, may be 1 or 2 weeks until I _start_ having said crack though.

It'd probably be useful to have other format specifiers too e.g. integer to ASCII as in my script.
