### ISSUE TITLE
Usage of nested arrays throws unhelpful ICE error

### ISSUE THREAD

**Issue by 0xPhaze** [noir-lang/noir#2410]
### Aim

Trying to compile the following circuit.

`main.nr`:

```rust
use dep::std;

global DEPTH: Field = 4;

fn hash(left: [u8; 32], right: [u8; 32]) -> [u8; 32] {
  let mut concat: [u8; 64] = [0; 64];

  for i in 0..32 {
    concat[i] = left[i];
  }

  for i in 0..32 {
    concat[i + 32] = right[i];
  }

  std::hash::keccak256(concat, 64)
}

fn computeRoot(key: [u8; 32], leaf: [u8; 32], nodes: [[u8; 32]; DEPTH]) -> [u8; 32] {
  // Start with the `leaf` node.
  let mut root: [u8; 32] = leaf;

  for i in 0..DEPTH {
      // Either hash current node with right zero subtree `zeros(i)`
      // of depth `i` or with left provided node `nodes[i]`.
      root = if (key[31 - i] == 0) { // Read `key`s i-th least-significant bit.
          hash(root, zeros(i))
        } else {
          hash(nodes[i], root)
        };
  }

  root
}

/// Main circuit.
fn main(
  receiver: pub Field,
  key: [u8; 32],
  nullifier: pub [u8; 32],
  secret: [u8; 32],
  nodes: [[u8; 32]; DEPTH],
  root: pub [u8; 32],
) {
  // Compute `leaf` using `nullifier` and `secret`.
  let leaf: [u8; 32] = hash(nullifier, secret);

  // Ensure `leaf` is included in the merkle tree.
  assert(computeRoot(key, leaf, nodes) == root);

  // Tie `receiver` into proof.
  assert(receiver != 0);

  // std::println(f"receiver: {receiver}");
  // std::println(f"key: {key}");
  // std::println(f"nullifier: {nullifier}");
  // std::println(f"secret: {secret}");
  // std::println(f"leaf: {leaf}");
  // std::println(f"nodes: {nodes}");
  // std::println(f"root: {root}");

}


fn zeros(level: Field) -> [u8; 32] {
  let mut out: [u8; 32] = [0; 32];

  if level == 0 {
    out = [0xad,0x32,0x28,0xb6,0x76,0xf7,0xd3,0xcd,0x42,0x84,0xa5,0x44,0x3f,0x17,0xf1,0x96,0x2b,0x36,0xe4,0x91,0xb3,0x0a,0x40,0xb2,0x40,0x58,0x49,0xe5,0x97,0xba,0x5f,0xb5];
  }
  if level == 1 {
    out = [0xb4,0xc1,0x19,0x51,0x95,0x7c,0x6f,0x8f,0x64,0x2c,0x4a,0xf6,0x1c,0xd6,0xb2,0x46,0x40,0xfe,0xc6,0xdc,0x7f,0xc6,0x07,0xee,0x82,0x06,0xa9,0x9e,0x92,0x41,0x0d,0x30];
  }
  if level == 2 {
    out = [0x21,0xdd,0xb9,0xa3,0x56,0x81,0x5c,0x3f,0xac,0x10,0x26,0xb6,0xde,0xc5,0xdf,0x31,0x24,0xaf,0xba,0xdb,0x48,0x5c,0x9b,0xa5,0xa3,0xe3,0x39,0x8a,0x04,0xb7,0xba,0x85];
  }
  if level == 3 {
    out = [0xe5,0x87,0x69,0xb3,0x2a,0x1b,0xea,0xf1,0xea,0x27,0x37,0x5a,0x44,0x09,0x5a,0x0d,0x1f,0xb6,0x64,0xce,0x2d,0xd3,0x58,0xe7,0xfc,0xbf,0xb7,0x8c,0x26,0xa1,0x93,0x44];
  }
  if level == 4 {
    out = [0x0e,0xb0,0x1e,0xbf,0xc9,0xed,0x27,0x50,0x0c,0xd4,0xdf,0xc9,0x79,0x27,0x2d,0x1f,0x09,0x13,0xcc,0x9f,0x66,0x54,0x0d,0x7e,0x80,0x05,0x81,0x11,0x09,0xe1,0xcf,0x2d];
  }

  out
}
```

### Expected Behavior

Should compile

### Bug

```
nargo compile
error: Internal Consistency Evaluators Errors: 
 
                    This is likely a bug. Consider Opening an issue at https://github.com/noir-lang/noir/issues
  ┌─ /Users/lain/git/zkcamp/cashcash/circuits/src/main.nr:1:1
  │
1 │ use dep::std;
  │ -
  │

Error: Aborting due to 1 previous error

Location:
    crates/nargo_cli/src/cli/mod.rs:79:5
```

### To Reproduce

1. `noirup -n`
2. `nargo compile`

### Installation Method

Binary

### Nargo Version

nargo 0.10.3 (git version hash: 707685cbb339f4ea83f88a1df6d3955acef5a125, is dirty: false)

### Would you like to submit a PR for this Issue?

No

**Comment by 0xPhaze** [comment]
After playing around a bit with different versions, I'm seeing this other error message:
```
internal error: entered unreachable code: Nested arrays and arrays of strings are not supported
```

Maybe the message could be more verbose like before.

**Comment by TomAFrench** [comment]
This looks to be a result of you having a nested array for `nodes: [[u8; 32]; DEPTH]`. We don't currently support nested arrays afaik but this should throw a clearer errors message rather than causing an ICE.

**Comment by TomAFrench** [comment]
Btw, Noir actually perform any hashes of constant inputs at compile time so you can replace your `zeros` function with

```
fn zeros(n: Field) -> [u8; 32] {
    if n == 0 {
        std::hash::keccak256([0;64], 64)
    } else {
        let hash = keccak_zeros(n-1);
        let mut concat = [0; 64];
        for i in 0..32 {
           concat[i] = hash[i];
           concat[i+32] = hash[i];
        }
        std::hash::keccak256(concat, 64)
    }
}
```

and as long as you call it with a constant value for `n` then you'll get the correct hash without needing to precompute it.

**Comment by 0xPhaze** [comment]
Ah interesting, I tried using `zeros` with a for loop on `n`, but had some compile error about not knowing the loop number at compile time. Didn't know that could be circumvented via recursion. But I had written an `unconstrained` zeros function which worked

```rust
unconstrained fn zeros_unconstrained(level: Field) -> [u8; 32] {
  let mut out: [u8; 32] = [0; 32];

  for _ in 0..(level + 1) {
    out = hash(out, out);
  }

  out
}
```

but then I wasn't sure about proof manipulation, so I just went back to the hardcoded version. Thanks for your help!

**Comment by TomAFrench** [comment]
> Ah interesting, I tried using zeros with a for loop on n, but had some compile error about not knowing the loop number at compile time. Didn't know that could be circumvented via recursion.

There's nothing really special about recursion, your version should work as well (and is cleaner). I can compile yours with the same behaviour so I think you may have been calling it with a non-constant input.

I'm not sure if this is in a release yet but you can add the `assert_constant` function to check to make sure you're calling with a constant input.
```rust
fn zeros(level: Field) -> [u8; 32] {
  std::assert_constant(level)
  let mut out: [u8; 32] = [0; 32];

  for _ in 0..(level + 1) {
    out = hash(out, out);
  }
```

**Comment by 0xPhaze** [comment]
You are right, weird, maybe the error was pointing to something else and I misinterpreted it.

**Comment by jfecher** [comment]
It looks like this example works as-is now - excepting for a constraint failure I have since I don't know the correct inputs to main. I'm closing this issue now since support for nested arrays was added a little while back.
