### ISSUE TITLE
Unary minus generates wrong SSA

### ISSUE THREAD

**Issue by alexvitkov** [noir-lang/noir#2412]
### Aim

The following assert fails:
```rust
fn main() {
    let x: i32 = -1;
    assert(1 - 2 == x);
}
```

Here's the generated SSA -- as far as I can see the issue is a missing truncate after the first sub:
```
    v2 = sub i32 0, i32 1
    v4 = sub i32 1, i32 2
    v5 = truncate v4 to 32 bits, max_bit_size: 33
    v6 = eq v5, v2
    constrain v6
    return
```

Note that this example succeeds (explicitly state 0-1 instead of -1):
```Rust
fn main() {
    let x: i32 = 0-1;
    assert(1 - 2 == x);
}
```

and here's its SSA:
```
Initial SSA:
acir fn main f0 {
  b0():
    v2 = sub i32 0, i32 1
    v3 = truncate v2 to 32 bits, max_bit_size: 33
    v5 = sub i32 1, i32 2
    v6 = truncate v5 to 32 bits, max_bit_size: 33
    v7 = eq v6, v3
    constrain v7
    return
}
```

### Expected Behavior

assert passes

### Bug

it doesn't

### Installation Method

None

### Would you like to submit a PR for this Issue?

Yes

**Comment by alexvitkov** [comment]
I've submitted a fix: https://github.com/noir-lang/noir/pull/2413

**Comment by vezenovm** [comment]
Resolved by https://github.com/noir-lang/noir/pull/2413 so closing
