### ISSUE TITLE
Dynamic indices for non-homogenous array

### ISSUE THREAD

**Issue by vezenovm** [noir-lang/noir#2461]
### Problem

Reference this `unimplemented` macro in ACIR gen (https://github.com/noir-lang/noir/blob/93726c4b4938512db6e36de47dc6ad77487c1acb/crates/noirc_evaluator/src/ssa/acir_gen/mod.rs#L575).

With the introduction of dynamic indices for slices as well in this PR (https://github.com/noir-lang/noir/pull/2446) enabling dynamic indices for arrays of complex types is necessary to avoid inconsistencies in our array/slice implementations. 

### Happy Case

Non-const indices should be fully supported just like const indices for both arrays and slices. 

### Alternatives Considered

N/A, there is no reasonable alternative

### Would you like to submit a PR for this Issue?

No

**Comment by Savio-Sou** [comment]
What does "non-homogenous array" here mean?

Aren't arrays in Noir strictly required to be homogeneous, as in all elements in a Noir array must be of the same type?

(Or is this referring to Rust arrays in ACIR?)

**Comment by vezenovm** [comment]
"Non-homogenous array" means an array of structs basically, technically if we had a struct like such:
```
struct Bar {
    inner: [Field; 3],
}
struct Foo {
    a: Field,
    b: [Field; 3],
    bar: Bar,
}
```
and an array `x : [Foo; 4]` the array is homogenous for the `Foo` type. But we flatten structs into its internal type structure so it is in fact an array with the types `Field, [Field; 3], [Field; 3]`, thus being non-homogenous.
