### ISSUE TITLE
Remove base64 encoding from acir artifacts

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#2469]
### Problem

The acir artifacts are currently being base4 encoded because they are included in the ABI.json file.

For backend end to end tests, they don't need to have a base64 encoded file since they just get the raw bytecode and not the json file.

### Happy Case

base64 decode file before saving it in .bytecode

### Would you like to submit a PR for this Issue?

No

**Comment by Savio-Sou** [comment]
cc Tooling @kobyhallx @TomAFrench @jonybur @phated

**Comment by TomAFrench** [comment]
Nope, we're passing just the circuit rather than the full JSON artifact so we can pass binary.
