### ISSUE TITLE
Optimize `update_acir`

### ISSUE THREAD

**Issue by Ethan-000** [noir-lang/noir#2474]
### Problem

currently `update_acir` is taking a lot of times in some programs eg. `eddsa` and `sha2_blocks` execution

eddsa:

![eddsa_flamegraph](https://github.com/noir-lang/noir/assets/70556667/902f80c9-a334-42e2-93ed-b63862f915ce)

sha2_blocks:

![sha2_blocks_flamegraph](https://github.com/noir-lang/noir/assets/70556667/165fb988-5ffc-4957-9c56-7cbc71d830fc)

did some changes it seems these can be avoided

### Happy Case

optimize this to

eddsa:

![eddsa_no_update](https://github.com/noir-lang/noir/assets/70556667/d9fdb1d5-b151-4c62-b377-98b2f02c1974)

sha2_blocks:

![sha2_blocks_optimized_flamegraph](https://github.com/noir-lang/noir/assets/70556667/e1c9602d-d86d-4a2d-90bb-c47693b03d7d)

### Would you like to submit a PR for this Issue?

Maybe

**Comment by kevaundray** [comment]
Nice! Can you explain the changes you made and quantify the difference in terms of percentage improvements?

**Comment by kevaundray** [comment]
> eddsa execution after optimization:
> 
> <img alt="optimized" width="796" src="https://user-images.githubusercontent.com/70556667/264059426-2e8c6f21-2eaf-44ef-9f0a-e6dfb54ba044.png">
> eddsa execution before optimization:
> 
> <img alt="master" width="797" src="https://user-images.githubusercontent.com/70556667/264059558-ad1ad318-a2c7-4930-a478-32f1872b36a7.png">
> sha2block didn't change much based on criterion results it seems
> 
> after optmization
> 
> <img alt="sha2blocksoptimized" width="466" src="https://user-images.githubusercontent.com/70556667/264060198-17db0316-4aff-4ae4-bdc9-2d376a61891d.png">
> before optimization
> 
> <img alt="sha2blocksbeforeoptimized" width="531" src="https://user-images.githubusercontent.com/70556667/264060328-9bc2f42c-22a7-4550-b581-2840ad6928a8.png">

Ah thanks for the numbers -- yeah this might become more pronounced the larger the program
