### ISSUE TITLE
Better handling of arrays of references in mem2reg when an array element is unknown

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#2477]
### Aim

Comes from a TODO in the mem2reg pass:
```rs
// TODO: This should be a unification of each alias set
// If any are empty, the whole should be as well.
```
where each element of an array is iterated and we call `try_add_alias` on each.

### Expected Behavior

`try_add_alias` should mark the entire array unknown which references it holds if any single reference is unknown

### Bug

`try_add_alias` uses `if let Some(..) = ...` guards instead, without `else` branches so it incorrectly does nothing if any element is unknown.

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by Savio-Sou** [comment]
Has this been resolved?

**Comment by jfecher** [comment]
@Savio-Sou I think so, yes! `try_add_alias` is completely removed and the cases in `set_value` that used `if let` guards have been removed.
