### ISSUE TITLE
Replace `Hashmaps` with `FxHashmaps` or another data structure

### ISSUE THREAD

**Issue by Ethan-000** [noir-lang/noir#2487]
### Problem

In some programs hashmaps is taking a lot of time

below is the flamegraph of the [tally circuit](https://github.com/aragonzkresearch/nouns-anonymous-voting/tree/main/circuits/tally)

<img width="1434" alt="1" src="https://github.com/noir-lang/noir/assets/70556667/1c49a1c0-00d9-4075-aa7a-d06384c5aeff">

### Happy Case

[FxHashmaps](https://github.com/cbreeden/fxhash) is what the rust compiler uses internally, which should speed it up

### Alternatives Considered

or another datastructure

### Would you like to submit a PR for this Issue?

Maybe

**Comment by jfecher** [comment]
It's a bit of an improvement still I suppose, and probably not hard to implement. Did you replace the HashMaps of that one function or all through SSA / the compiler?

(edit: there's a PR now)

**Comment by kevaundray** [comment]
We don't have a tracking issue for benchmarks so putting it here: I wonder how much time we are spending in the arena, here: https://github.com/noir-lang/noir/blob/df9f09eda62b7d09ed8ade8cad907453ea91d3e2/crates/arena/src/lib.rs#L7

If its a lot, we could replace that with something simpler like la-arena which _should_ be faster as we are not using the generational component of generational-arena

**Comment by jfecher** [comment]
We can just replace the arenas with Vecs honestly. We never delete elements anyway
