### ISSUE TITLE
Trouble compiling from source

### ISSUE THREAD

**Issue by jtfirek** [noir-lang/noir#2499]
### Aim

Set up my development environment using these steps:
https://noir-lang.org/getting_started/nargo_installation/#option-4-compile-from-source 

### Expected Behavior

I was trying to install the native dependencies after running `direnv allow`

### Bug

This is the error that occurred when running `direnv allow` on my mac with m2 chip

<img width="1334" alt="Screenshot 2023-08-30 at 7 38 40 PM" src="https://github.com/noir-lang/noir/assets/106350168/0825b834-ed7f-45f2-b393-0b282e10c18b">

### To Reproduce

1. Machine with M2 chip
2. https://noir-lang.org/getting_started/nargo_installation/#option-4-compile-from-source 

### Installation Method

Compiled from source

### Additional Context

Sorry if this is the wrong place for this.

### Would you like to submit a PR for this Issue?

No

**Comment by Savio-Sou** [comment]
Hey there! Which repo were you compiling?

If it's just Nargo you could give [Option 3](https://noir-lang.org/getting_started/nargo_installation/#option-3-install-via-nix) a spin, it's also compiling from source.

**Comment by jtfirek** [comment]
Hey @Savio-Sou, Thanks for the reply sorry it took me so long to get back to you. I am trying to compile the noir library so I can start contributing to the library. I didn't think that option 3 would be helpful in this case as I am trying to set up my development environment not just install Nargo.

**Comment by jtfirek** [comment]
Also from the current master branch I am getting a similar error that has to do "bad CPU in executable" when I run `cd crates/nargo_cli && cargo test`
![Screenshot 2023-09-02 at 9 36 58 PM](https://github.com/noir-lang/noir/assets/106350168/03aa6874-4625-4882-89c9-563d24a780a0)

**Comment by Savio-Sou** [comment]
Thanks for the reply @jtfirek!

Which crate(s) were you attempting to compile from source? Let me check if I can reproduce the error on our M2 Mac.

**Comment by jtfirek** [comment]
Hey @Savio-Sou thanks for helping me so much with this! Once I get up and going I feel like I can bring a lot of valuable contributions! 

- With the first error I mentioned, I was setting up my development environment. I was working in the root directory of the projecting running `direnv allow` so I was not compiling any specific crates.
- With the second error I mentioned, I was compiling the `nargo_cli` crate which actually compiles just fine, it just throws an error when I try to run the tests. I have done some more digging and I am pretty sure that the test is failing because I don't have the dev environment set up so their is no baretenberg backend.
```
error: Failed to download srs: Unable to open file: /Users/jacobfirek/.nargo/backends/acvm-backend-barretenberg/g1.dat 
```
