### ISSUE TITLE
Test passing in 0.7.0 freezes in 0.10.3 using nargo test

### ISSUE THREAD

**Issue by harshnambiar** [noir-lang/noir#2500]
### Aim

The test case was passing earlier 

### Expected Behavior

The test case should continue to pass irrespective of new version update

### Bug

The test is not failing but it is freezing up. I have waited for up to 5 minutes, and it neither passes, nor fails, nor skips.

### To Reproduce

1. clone [this](https://github.com/resurgencelabs/types)
2. cd types/fraction
3. nargo test --show-output
4. the tests test_sin() and test_cos() should hang

### Installation Method

Binary

### Nargo Version

0.10.3

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
On current master (commit cb2f2ebf5d8d78d54ebdb18db3c4f72b1031d9a9) this takes roughly 15s to pass for me

**Comment by harshnambiar** [comment]
> On current master (commit [cb2f2eb](https://github.com/noir-lang/noir/commit/cb2f2ebf5d8d78d54ebdb18db3c4f72b1031d9a9)) this takes roughly 15s to pass for me

I did a "noirup --version 0.10.3" roughly 23 hrs back, and for me those two tests never pass (nor fail), but remain in limbo forever. I mean not really forever, I cancelled it at 15 mins. Am I doing something wrong? Should I upgrade to something higher than 0.10.3 or is it possible the issue is with my processing?

**Comment by harshnambiar** [comment]
Further Update: I upgraded to 0.10.4 and now not only does it freeze at those tests, the terminal and even chrome crash :|

**Comment by Savio-Sou** [comment]
Just did a quick check with v0.10.5, seems that everything ran fine:
```
% nargo test --show-output
(warnings...)
[types_fraction] Running 9 test functions
[types_fraction] Testing test_add2... ok
[types_fraction] Testing test_split... ok
[types_fraction] Testing test_mul_large2... ok
[types_fraction] Testing test_sin... 0x00
0x058f
0x2710
ok
[types_fraction] Testing test_cos... 0x00
0x0afb
0x2710
ok
[types_fraction] Testing test_add... ok
[types_fraction] Testing test_add_large2... 0x27bc86a5
0x64
ok
[types_fraction] Testing test_mul2... ok
[types_fraction] Testing test_split2... ok
[types_fraction] All tests passed
```

> even chrome crash

Might be a system-wide issue with your machine than something to do with Nargo perhaps? 🤔

**Comment by harshnambiar** [comment]
> Just did a quick check with v0.10.5, seems that everything ran fine:
> 
> ```
> % nargo test --show-output
> (warnings...)
> [types_fraction] Running 9 test functions
> [types_fraction] Testing test_add2... ok
> [types_fraction] Testing test_split... ok
> [types_fraction] Testing test_mul_large2... ok
> [types_fraction] Testing test_sin... 0x00
> 0x058f
> 0x2710
> ok
> [types_fraction] Testing test_cos... 0x00
> 0x0afb
> 0x2710
> ok
> [types_fraction] Testing test_add... ok
> [types_fraction] Testing test_add_large2... 0x27bc86a5
> 0x64
> ok
> [types_fraction] Testing test_mul2... ok
> [types_fraction] Testing test_split2... ok
> [types_fraction] All tests passed
> ```
> 
> > even chrome crash
> 
> Might be a system-wide issue with your machine than something to do with Nargo perhaps? 🤔

Did you guys recently increase the minimum hardware requirements for running Noir? I'm on an i5 device and using Ubuntu 22

**Comment by harshnambiar** [comment]
A couple of findings: 
1. The app doesn't crash if the loop is rewritten to _for i in 0..6_
2. The crash is probably due to excess and repeated arithmetic on larger numbers
3. After rewriting the functions as in the latest commit, the crash stops from happening, but this is only treating the effect of the issue, not the cause. It might still happen for other functions in the future, on other machines.

As discussed with Josh, keeping this one open in case someone can find out what changed between 0.9.0 and 0.10.3 that caused working functions to now cause crashes.
