### ISSUE TITLE
Solidity verifier should not need optimizations

### ISSUE THREAD

**Issue by phated** [noir-lang/noir#2509]
### Problem

The solidity verifier that we generate doesn't work without optimizations.

Tracking issue for https://github.com/AztecProtocol/aztec-verifier-contracts/issues/19

### Proposed solution

Fix it upstream and then reflect the contract changes here. Interim, we're just going to document that the optimizer must be turned on

### Submission Checklist

- [ ] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by Savio-Sou** [comment]
Is this still relevant? The issue linked seems to suggest https://github.com/AztecProtocol/aztec-verifier-contracts/pull/12 resolved the issue.

**Comment by Savio-Sou** [comment]
Closing as resolved. Please comment below if anyone reading is still experiencing this as an issue.
