### ISSUE TITLE
Inject comment containing package version into verifier contract

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#2510]
### Problem

I think it would be useful to inject the version of `acvm-backend-barretenberg` which was used to generate a smart contract verifier.

This would allow us to trace it back to a commit in https://github.com/AztecProtocol/aztec-verifier-contracts more easily in case there are reported issues (however the contract could be modified post-generation)

### Proposed solution

We can inject a comment such as the below into the generated contract.

```
// Automatically generated using `acvm-backend-barretenberg` v0.1.0
// https://github.com/noir-lang/acvm-backend-barretenberg
```

### Submission Checklist

- [x] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by Savio-Sou** [comment]
@TomAFrench is this still relevant?

If it is, what priority and effort labels would you consider appropriate for this Issue?
