### ISSUE TITLE
nargo prove crashes with an ICE on master on NixOS

### ISSUE THREAD

**Issue by alexvitkov** [noir-lang/noir#2524]
### Aim

Currently on master `nargo prove` fails with an ICE, I believe this is a NixOS specific issue
```
Message:  Failed to execute command: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Location: crates/acvm_backend_barretenberg/src/bb/prove.rs:42

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml

  10: core::result::Result<T,E>::expect::h8d19846cb72c1b46
      at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:1070
  11: acvm_backend_barretenberg::bb::prove::ProveCommand::run::h0042deee1b1f3810
      at /home/vitkov/code/repos/metacraft-labs/noir/crates/acvm_backend_barretenberg/src/bb/prove.rs:42
  12: acvm_backend_barretenberg::proof_system::<impl acvm_backend_barretenberg::Backend>::prove::h79e36b3847a81579
      at /home/vitkov/code/repos/metacraft-labs/noir/crates/acvm_backend_barretenberg/src/proof_system.rs:89
  13: nargo::cli::prove_cmd::prove_package::he5f3248023075b29
      at /home/vitkov/code/repos/metacraft-labs/noir/crates/nargo_cli/src/cli/prove_cmd.rs:127
  14: nargo::cli::prove_cmd::run::h2822f40aa387439b
      at /home/vitkov/code/repos/metacraft-labs/noir/crates/nargo_cli/src/cli/prove_cmd.rs:66
  15: nargo::cli::start_cli::h2563fda0a3b6295f
      at /home/vitkov/code/repos/metacraft-labs/noir/crates/nargo_cli/src/cli/mod.rs:85
  16: nargo::main::he2b59468db18932c
      at /home/vitkov/code/repos/metacraft-labs/noir/crates/nargo_cli/src/main.rs:24
  17: core::ops::function::FnOnce::call_once::h8ca7b2e002e5ab57
      at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251
```

This is on an empty program:
```rust
fn main() {
}
```

The latest working commit for me is 336396b11f295870bb83

**Comment by alexvitkov** [comment]
I'm looking over the recent changes, it seems that the way the backend executable is called has changed.

Here's the line that nargo prove attempts to execute:

`/home/vitkov/.nargo/backends/acvm-backend-barretenberg/backend_binary "prove" "-c" "/tmp/nix-shell.ct21bR
/.tmpNsCqqs" "-b" "/tmp/nix-shell.ct21bR/.tmpNsCqqs/circuit.bytecode" "-w" "/tmp/nix-shell.ct21bR/.tmpNsCqqs/witness.tr" "-o" "/tmp/nix-shell.ct21bR/.tmpNsCqqs/proof.proof" "-v"`

The path to the executable is valid, so it probably executes it fine and the `"No such file or directory"`comes from `backend_binary` rather than `nargo` itself.

**Comment by alexvitkov** [comment]
If I exec `backend_binary` from the shell with the args nargo passes it, it segfaults:
```
/home/vitkov/.nargo/backends/acvm-backend-barretenberg/backend_binary "prove" "-c" "/tmp/nix-shell.kZASYw/.tmpoXs74B/" "-b" "/tmp/nix-shell.kZASYw/.tmpoXs74B/circuit.bytecode" "-w" "/tmp/nix-shell.kZASYw/.tmpoXs74B/witness.tr" "-o" /tmp/nix-shell.kZASYw/.tmpoXs74B/proof.proof "-v"
fish: Job 1, '/home/vitkov/.nargo/backends/ac…' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by kevaundray** [comment]
I think you would need to patch the bb binary using patchelf for now and in the future, the bb binary would either include libstdc++(its one not great option) or produce versions which work with nixOS. The code to patch looks roughly like:

```
            patchelf --set-rpath "${stdenv.cc.cc.lib}/lib:${pkgs.gcc.cc.lib}/lib" ~/.nargo/.../backend_binary
            patchelf --set-interpreter ${stdenv.cc.libc}/lib/ld-linux-x86-64.so.2 ~/.nargo/.../backend_binary
```

**Comment by nickysn** [comment]
Are there any plans to fix this, or are NixOS users expected to just manually patch the binary by themselves? Where does this binary come from? Is it compiled from source?

**Comment by nickysn** [comment]
Another question: is there a Linux distro that is always guaranteed to work with Noir? E.g. Ubuntu, Fedora, etc? And which version?

**Comment by kevaundray** [comment]
> Are there any plans to fix this, or are NixOS users expected to just manually patch the binary by themselves? Where does this binary come from? Is it compiled from source?

The binary comes from the repo containing barretenberg [here](https://github.com/AztecProtocol/aztec-packages/blob/3a8e7026ea10aa8564bdcc127efd4213ebd526de/circuits/cpp/barretenberg/.github/workflows/publish.yml#L24) so its never compiled in the Noir repo, other proving backends will follow a similar strategy.

Whether barretenberg supports nixOS is an issue that we can open in barretenberg, another option you could try in the interim is `nix-shell -p gcc --run "/backend_binary"`. I'm not on nixOS, so have not tried it myself. The above command could probably be put in a bash script and it could be denoted as the nix linux version which means that proving systems would only need to compile for traditional linux.

**Comment by kevaundray** [comment]
> Another question: is there a Linux distro that is always guaranteed to work with Noir? E.g. Ubuntu, Fedora, etc? And which version?

We use github actions which uses ubuntu 22.04 , the barretenberg binary uses ubuntu 20 so using ubuntu 22.04 should be guaranteed to work with Noir and the barretenberg binary (backend_binary) 

For Noir builds on linux, see [here](https://github.com/noir-lang/noir/blob/0dc73a1b4eba3db2799177fe530bb7bf795e42c3/.github/workflows/publish.yml#L111)

**Comment by nickysn** [comment]
Using `nix-shell -p gcc --run "~/.nargo/backends/acvm-backend-barretenberg/backend_binary"` doesn't help, unfortunately :( Still getting the same error.

**Comment by nickysn** [comment]
I tried compiling barretenberg version 0.4.6 on NixOS. I get a backend binary that starts and reports "No command provided.", which is to be expected. However, when I try 'nargo codegen-verifier' (the test in tests/codegen_verifier.rs), it invokes the backend and the backend crashes with 'Segmentation fault (core dumped)'.

**Comment by kevaundray** [comment]
This seems to be a barretenberg issue, which does not use nix, since we have essentially separated from barretenberg, we can open up this nix specific issue in barretenberg instead
