### ISSUE TITLE
Nargo uses exhausts all memory and crashes on larger circuits

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#2571]
### Aim

I've been trying to compile https://github.com/SetProtocol/noir-rsa to experiment on reducing the number of constraints in the circuit.

### Expected Behavior

The circuit should compile successfully

### Bug

The circuit fails to compile at all. Looking at the task manager, I can see that Nargo takes more and more memory until it's at 100% utilisation (at which point Nargo is using > 30GB) and then crashes.

Comparing with the 0.10.5 release shows that this is a relatively recent issue as this reaches a constant amount of memory, although the compilation time is extremely long ()

### To Reproduce

1. `noirup -n`
2. clone https://github.com/SetProtocol/noir-rsa
3. `nargo info --package dkim`
4. `noirup -v 0.10.5`
5. `nargo info --package dkim`

### Installation Method

Binary

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
After adding `examples/dkim` to the workspace, this crate does not run without using `--package` , @phated can you look into getting this fixed?

**Comment by Savio-Sou** [comment]
Possibly related: https://github.com/noir-lang/noir/issues/2500
