### ISSUE TITLE
Negative integer literals are not supported for unsigned types

### ISSUE THREAD

**Issue by Jurarpereurs** [noir-lang/noir#2583]
### Aim

Noir throws an error saying that "u32 cannot be used in a unary operation" when directly assigning a negative integer literal to an unsigned integer type.

```rust
let a: u32 = -1;
```

However, if you do some operations on the negative integer literal, the error is not thrown.

```rust
let a: u32 = -1 - 1;
```

### Expected Behavior

Noir should not throw an error when directly assigning a negative integer literal to an unsigned integer type.

### Bug

Create a new Noir project with the following command:

```bash
noir new neg
```

Save the following code into `src/main.noir`:

```rust
fn main() {
    let a: u32 = -1;
}
```

Run `nargo prove` and observe the following error:

```text
warning: unused variable a
  ┌─ /home/Jurarpereurs/neg/src/main.nr:2:9
  │
2 │     let a: u32 = -1;
  │         - unused variable
  │

error: u32 cannot be used in a unary operation
  ┌─ /home/Jurarpereurs/neg/src/main.nr:2:18
  │
2 │     let a: u32 = -1;
  │                  --
  │

Error: Aborting due to 1 previous error

Location:
    crates/nargo_cli/src/cli/mod.rs:79:5
```

To see that the error is not thrown when doing some operations on the negative integer literal, save the following code into `src/main.noir`:

```rust
fn main() {
    let a: u32 = -1 - 1;
}
```

Run `nargo prove` and observe that the error is not thrown.

### To Reproduce

1. Create a new Noir project with the following command:

    ```bash
    noir new neg
    ```

2. Save the following code into `src/main.noir`:

    ```rust
    fn main() {
        let a: u32 = -1;
    }
    ```

3. Run `nargo prove` and observe the error.

### Installation Method

Binary

### Nargo Version

nargo 0.10.5 (git version hash: 9fe4cfd05b46d1d8867bc2583a11da32480366fc, is dirty: false)

### Would you like to submit a PR for this Issue?

No

**Comment by guipublic** [comment]
The issue is not that -1 is forbidden, but rather the fact that -1-1 is allowed. This is because the check we perform is too simple.
We have a similar issue if you assign 300 to u8 vs 300+4 to u8.
Because we are moving toward preventing integer overflows, the solution is to error on overflows also in these cases
