### ISSUE TITLE
Unused divide or modulo by zero passes execution instead of failing

### ISSUE THREAD

**Issue by gladiatorcasino** [noir-lang/noir#2584]
### Aim

Noir does not handle modulus with a zero divisor gracefully. It causes the rustc compiler to crash.

The minimal example is:

```rust
fn main() {
    let x: u32 = 1 % 0;
}
```

It causes the rustc compiler to crash with the following error:

```text
The application panicked (crashed).
Message:  attempt to calculate the remainder with a divisor of zero
Location: /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/num/mod.rs:933

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml
```

Also, note that if the operation is not modulo but division, then no crash occurs. For example, if you change the code to:

```rust
fn main() {
    let x: u32 = 1 / 0;
}
```

The compilation would succeed without any error message when you run `nargo prove`.

### Expected Behavior

Noir should not cause rust compiler to crash. It should instead report a compile-time error.

### Bug

First, create a new noir project:

```bash
nargo new mod_zero
```

Then, edit the `src/main.noir` file to contain the following code:

```rust
fn main() {
    let x: u32 = 1 % 0;
}
```

Then, run the proving phase:

```bash
nargo prove
```

You would observe the following output:

```text
The application panicked (crashed).
Message:  attempt to calculate the remainder with a divisor of zero
Location: /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/num/mod.rs:933

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml
```

### To Reproduce

Please refer to the last section.

### Installation Method

Binary

### Nargo Version

nargo 0.10.5 (git version hash: 293dffcb8a064b44d762a9b5dfde3a9e862ab9a8, is dirty: false)

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
After https://github.com/noir-lang/noir/pull/2578 this no longer crashes, but it does pass instead of failing from the modulo by zero.

(During SSA optimizations the dead instruction elimination pass removes the result since it is unused).
