### ISSUE TITLE
Investigate trait implementations with attributes

### ISSUE THREAD

**Issue by Maddiaa0** [noir-lang/noir#2629]
```[tasklist]
### Soft Prerequisite
- [ ] https://github.com/noir-lang/noir/issues/2568
```

### Problem

While implementing custom / multiple attributes work, it did not appear that traits currently had any notion of an attribute. This issue serves as a bookmark to revisit this once traits are more mature.

The relevant code that sparked this thought: 
https://github.com/noir-lang/noir/blob/6db3bdaeaa992da32d0de842325ef2d5f6188974/crates/noirc_frontend/src/hir/def_collector/dc_mod.rs#L216

### Happy Case

-

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
Closing in favour of #3301
