### ISSUE TITLE
Backends should receive `Circuit` rather than verification key when verifying proof

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#2680]
We currently pass (a path to) [the verification key](https://github.com/noir-lang/noir/blob/e2105f762bc631ec7156d9c509e8c311a49fb1e8/tooling/acvm_backend_barretenberg/test-binaries/mock_backend/src/verify_cmd.rs#L13) to backends when verifying a proof.

This is an abstraction leak from the backend which should be in charge of caching its own verification keys. The backend can hash the `Circuit` to act as a key to this cache, alternatively producing a verification key if none exists in the cache.

**Comment by kobyhallx** [comment]
Leaving with lower Priority as this is more relecant for other backends. Barretenberg is fine to receive vk.

**Comment by kevaundray** [comment]
@TomAFrench is this still an issue?

**Comment by TomAFrench** [comment]
Closing this as it causes issues for JS where circuit preprocessing is harder to cache.
