### ISSUE TITLE
Silence nargo output

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#269]
Proving and verifying a noir program via nargo currently looks like:
```
~/noir/crates/nargo/tests/test_data/1_mul>  nargo prove p && nargo verify p
deserialising constraint system : 23125ns ~0seconds
creating crs factory : 416ns ~0seconds
creating circuit with witness : 324584ns ~0seconds
aligned_free : 250ns ~0seconds
creating prover : 8178208ns ~0seconds
creating proof : 248532250ns ~0seconds
total wasm time : 0seconds
proof : 09a1dda81d7140d78134904d704b436f1cbc5f7388f292e98943537fc54a50f90703550bdf6e2084a897daf216d0ba3b22998c89b4306317e12100ed77778bbf28c72014e2a52ce5be7db8d1583f2aba4917d955474c2cc71418be724aad3a2a19eeeada3ced07f6c83e317b18d55701c659d3cb89aa2a8ae4b304fd210a3bc40539a06343cf027727bdb163f4dfcb5b9a75abc97600a4cdf712adc7bebac29504a0b7c1c02cfe798cfebea01b8a247addf4f6bebebc50900bafe9b5f54bdea727dae71c0d4a4d75697e998481212d907cd27bc1e5d88d58b465ee0ad460dce60c84b6cb62b824414b596c052a93434bbc716f54ccde1cee40a30adbcd422d0c13822a69898aaec44dd48b9296b9e3762020b43c72c526b14ee8f5ebb940f4c5130545a4f474b1bf2a91bb7508949a0bdd0ac2db658b74775a376332d7b546361059a408a58ad942066f1a7b6e44a8e10d086f56d060adc6530acaf371a1597629c851392e1b27f6a16692e2d33a0e833dc5d7ac1e00eddd52da16f35c854bd917a577600abb2fd63fd982317873b41bda47427f1703f03c474368b1de78e2162db8fa22d5efcddf2a89ffa1f0f05f495d192de5499444d34090a7a7e8f8765927da3c53aa0f2ffa9ba3d85a854280471668dcf315a68093143ad5325bb7d8ff2110d883ba7a760ff7cb5dc6ec89cf3eae1230b461a240b3bb71b07a46e3b7fa0a64a07ef67a2375b22585079e574fec94821d5c6916c11ebf0cc87ca0434a2f169a9de1d371fb220ed43caa811c4a9c71bb9d452361cce436c53396858290401558158ce15c42dd83b4b28030c4e3412756b83d96a72ff64195e7bd47d762f7218b71b229408027a2725be43779e625da72c0e0a004d9e0ec7eb3e14ff1118e0712bee85500f8ea0ad639d35ec20bc8a6d9d60387482bd8b8816039a5431b6716de1e89ea5621a434dc03886a07941787924710a8278d73605cb551468ac5601b83f15fe17fc78c4a9c5e181f8ef82389b72aaaeba188ccf0ead7f5b73c56120955d57520b8483933444cad523e0a77a960a72a326aa154c0a34bfb6cb4a932065e2fe68cc3995d783480a6d4549ef99952dc9223dd754b371b575f32c2baad0d8b2351e6226d5685ae7de96cc958b4a5f622063c3d6cbd647d97474d78984d02d0b0adc7963d8685b704b3dfe8a96a16c8f0c546f2b9eebd5c0709d5a79b8802d0b0adc7963d8685b704b3dfe8a96a16c8f0c546f2b9eebd5c0709d5a79b8802ebae2444e5ef91d6eaf7b599b10539a2d559def5b2ea4bd8a506f99a98b8e72c1bfcc0c9ebfa7764fe0748822d4326a337f953e19564e27eb92dc56b93bc8b1256d8801fdaae958ce7b68978077229d64b3cccd9e98b2628a87b6939a140b414e4eb848ba5988e4de05664fbaf053fae5d8c2be4ca50f83422451f525945a5254e70836310c03c8cb1b1bcecb78767b716d6cb8102ea8a09e7a35ef030e479090a9fdd869f385bc1e90d3758dfe4f17ad9168c5d7496428219968f8bcbd0c60e3bb387604123f9d3114d3d648d605474b95160c1d5be0e78608f1711e9eb950540faf21c9e96b5b34fbccd65b014bfc3021dc741979937caf4c771865fff31031fed0802e910a5c92d2c2082f645134e0bd3369892d50edff9acd22aab14f615fe14f3c1143d3dad90b45a78b29773268160062267c2acd1c2e834d6e3b244
Proof successfully created and located at proofs/p.proof
Ok("/Users/jakefecher/Code/Noir/noir/crates/nargo/tests/test_data/1_mul/proofs/p.proof")
verifier deserialise : 403166ns ~0seconds
creating verifier : 320372833ns ~0seconds
verifying proof : 45211667ns ~0seconds
Proof verified : true

~/noir/crates/nargo/tests/test_data/1_mul> 
```
Most of this unnecessary debug output is from barretenberg itself, I traced the prove times to originate from the extern C function`composer__new_proof` and I imagine it is a similar story for the verify timings.
I think we can give a cleaner experience for the user by omitting these timings by default (mockup):
```
~/noir/crates/nargo/tests/test_data/1_mul>  nargo prove p && nargo verify p
Proof successfully created and located at proofs/p.proof
Proof verified
~/noir/crates/nargo/tests/test_data/1_mul> 
```
Where:
- I've omitted the long proof hex, we can keep it if it is likely to be needed in most cases versus forcing users to access it in proofs/p.proof
- `Proof verified` would be shown in green when it is verified. Otherwise it would output `Proof failed to verify` in red. I believe this to be better over Proof verified: true/false.
- For programs that take longer to prove or verify we may wish to have a progress bar builtin to the compiler as a very rough estimate to the user of the compiler's progress. This would be shown while compiling and erased afterward.

**Comment by kevaundray** [comment]
- I like the succintness of the mockup. We may want to add in just the time it took to create the proof, something like:

>Proof successfully created and located at proofs/p.proof
> Time taken : 10 seconds

- Yeah I like this. Also good that it changes the text when it fails, so that those who are colour bind can also differentiate.

- We might need to do a bit more planning around this one, as the progress is not dictated by Noir. Some suggestions on what we could do; poll the external backend for how long it has left, or we could have the backend give us harcoded numbers on how long it roughly takes for various program sizes. Out of those two suggestions, I think the latter is easier to eventually add since we do not need to keep talking to the backend. The former will give better/more accurate numbers but it requires more scaffolding from the backend.

**Comment by TomAFrench** [comment]
Closing as the only remaining debug output has been removed in https://github.com/noir-lang/aztec_backend/pull/49 (so will disappear once we update the dependency).
