### ISSUE TITLE
Cache, check and use compiled programs in `nargo prove`

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#2712]
### Problem

Currently, `nargo prove` recompiles Noir programs on every run to avoid users falling into the trap of:
1. `nargo compile`
2. Edit program
3. `nargo prove` (without recompiling)
4. Gets an error

Compilation times could however be significant, especially for large Noir programs. Compiling [nouns-anonymous-voting](https://github.com/aragonzkresearch/nouns-anonymous-voting)'s Noir programs for example cost minutes on decent hardware.

The current `nargo prove` behavior hence lengthens and pollutes `nargo prove` times with compilation times, which in turn causes `nargo prove` to produce worse benchmarking times (compiling + proving times) than what Noir app users are practically expected to experience (proving time only; compilation was performed by developer).

### Happy Case

On `nargo compile` / the first run of `nargo prove`, Nargo should cache:
- The compiled program
- A checksum

Where on subsequent runs of `nargo prove`, Nargo would check the Noir program source code against the checksum:
- If the source code matches what was cached, proceed directly to proving
- If the source code does not match the cache, recompile the Noir program

### Would you like to submit a PR for this Issue?

No

**Comment by Savio-Sou** [comment]
Per https://github.com/noir-lang/noir/issues/2680, should verification keys not be cached on Nargo's end?

**Comment by TomAFrench** [comment]
Yeah, handling of keys is a backend concern so nargo shouldn't be involved. We should cache our own build artifacts however.

**Comment by Savio-Sou** [comment]
Thanks, updated the issue accordingly.

**Comment by TomAFrench** [comment]
One trouble with this:

We can hash the `Program` struct which should allow us to determine whether we need to rebuild the circuit or can reuse the old one, however the debug information could fall out of sync with the current source files which we can't detect/fix easily.

We can rearrange the source code while maintaining the programs AST so if we maintain the `file_map` field on the `CompiledProgram` the source code contained within the `CompiledProgram` will be out of sync with the actual source code. This means that any callstacks generated will point to incorrect line numbers.

I'm not sure that we can correct this without just running ACIR gen again however at which point we're doing the entire compilation again.
