### ISSUE TITLE
Unexpected constraint count bump from v0.10.5 --> v0.11.0

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#2720]
### Aim

Constraint counts (hence proving efforts) of Noir programs should stay roughly the same, if not lower, when updating Nargo from 0.10.5 to ≥0.11.0.

### Expected Behavior

For example, constraint count of [depth_8_storage_proof](https://github.com/aragonzkresearch/noir-trie-proofs/tree/8d254ccf399206090f79d5e8ca19f4d318c940d4/tests/depth_8_storage_proof) on 0.10.5 was:
```
$ nargo --version
nargo 0.10.5 (git version hash: 91efe44d17762ea883d9a576d530049ad20f1393, is dirty: false)
$ nargo info --package depth_8_storage_proof
+-----------------------+------------------------+--------------+----------------------+
| Package               | Language               | ACIR Opcodes | Backend Circuit Size |
+-----------------------+------------------------+--------------+----------------------+
| depth_8_storage_proof | PLONKCSat { width: 3 } | 79955        | 681757               |
+-----------------------+------------------------+--------------+----------------------+
```

Backend circuit size should stay identical or lower on newer Noir versions.

### Bug

Constraint count on 0.11.0 however is:
```
$ nargo --version
nargo 0.11.0 (git version hash: 75638451277cfc27de19c90ca6bb87d0713876fd, is dirty: false)
$ nargo info
+-----------------------+------------------------+--------------+----------------------+
| Package               | Language               | ACIR Opcodes | Backend Circuit Size |
+-----------------------+------------------------+--------------+----------------------+
| depth_8_storage_proof | PLONKCSat { width: 3 } | 79955        | 1708578              |
+-----------------------+------------------------+--------------+----------------------+
```

That is the constraint count >2x from 681,757 to 1,708,578.

### To Reproduce

1. `git clone https://github.com/aragonzkresearch/noir-trie-proofs.git`
2. `cd noir-trie-proofs`
3. `noirup -v 0.10.5`
4. `nargo info --package depth_8_storage_proof`
5. `noirup -v 0.11.0`
6. `nargo info --package depth_8_storage_proof`

### Installation Method

Binary

### Nargo Version

nargo 0.11.0 (git version hash: 75638451277cfc27de19c90ca6bb87d0713876fd, is dirty: false)

### Additional Context

Would be good to debug further which Noir change(s) caused the constraint bump, and supersede this Issue with the further action(s) to be taken.

cc @ax0, thanks for reporting the issue!

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
This provides some more motivation that constraint count changes should be automatically tracked on each PR and release. Testing manually on each release makes it much more difficult to track where the increase comes from and whether or not it was necessary.

**Comment by guipublic** [comment]
I tried to locate the faulty commit, but I could not identify it.
Last working commit is 336396b11f295870bb83da1f48f1d50079418b34 on the 31st of August, using barretenberg 0.4.3 I believe.
Then, with the switch to ACVM 0.23.0 and BB 0.4.5, the test is failing with this error: 
```
not in gzip format
Input is not large enough
```
All subsequent commits fail until the 6th of September, where commit f95ea0990fa266d01dc4dbd910b4581fb30f51e7, using BB 0.5.1, does not error but experiences the constrain bump.

**Comment by guipublic** [comment]
The noir faulty commit is: 146727566 chore!: Update to `acvm-backend-barretenberg` v0.12.0
(on the 31 of August)
It is a big change:
ACVM is updated from 0.22.0 to .0.23.0
acvm-backend-barretenberg from 0.11.0 to 0.12.0
and barretenberg goes from the 8th of July noir acvm-backend-barretenberg branch to v.0.4.3 (8th of August ) in master

However there is no changes internal to noir, and both version send the same 20863 opcodes to barretenberg.
They are translated into 7383 ‘acir format constraints’ in barretenberg.
However, the more recent barretenberg generates 162293 gates vs 46487 with the older one.

**Comment by Savio-Sou** [comment]
I.e. it's a barretenberg change that caused it, rather than a Noir change?

**Comment by guipublic** [comment]
> I.e. it's a barretenberg change that caused it, rather than a Noir change?

Yes, most probably

**Comment by Savio-Sou** [comment]
Thanks @guipublic.

> the memory constrains were not reaching barretenberg with acvm-aztec-backend 0.11

Does that mean programs at that point were underconstrained, where the bump in constraint is reflected from a fix for that?

**Comment by guipublic** [comment]
@Savio-Sou yes, that's correct, it was not literally a fix for an issue but a result of moving deserialisation code from aztec-backend 0.11 into barretenberg which fixed it.

**Comment by guipublic** [comment]
I am closing the issue since it is not an issue.
