### ISSUE TITLE
[Tracking issue] Cleanup CI

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#2724]
## Problem 

Our current CI can be improved, this is a tracking issue to collect all of the items that come to mind.

## Performance

- Some of our workflows are not caching
- We are running the publish nargo workflow on every PR for all platforms

## Maintability

- We use release and publish interchangeably, instead of sticking to one
- Additionally, We can make the workflow files easier to distinguish by following a naming convention like `js-publish-noir-js`, `js-test-source-resolver`,`rs-test-workspace`
- We can merge the PR linting workflows into one file; labeller, pull-request and spellcheck.

## Notes

Another way to organize is to remove the extra on triggers for items with workflow dispatches and create a new workflow for the on triggers that were removed. For example, "Publish Nargo" and "integration test" are workflows that can be triggered by a workflow dispatch or by a scheduled cron job. With this, we would create a yml file called cron_job.yml and it would trigger "Publish Nargo" and "integration test". The same naturally goes for our publishing workflow.

**Comment by TomAFrench** [comment]
> We are running the publish nargo workflow on every PR for all platforms

This workflow is pretty well optimized so generally isn't the blocking workflow run however.

**Comment by kevaundray** [comment]
> > We are running the publish nargo workflow on every PR for all platforms
> 
> This workflow is pretty well optimized so generally isn't the blocking workflow run however.

Yeah I agree, I imagine that the ubuntu test will get faster over time and it will become the bottle-neck -- at that point, I think it would make sense to run this only on master and not on every PR

**Comment by Savio-Sou** [comment]
> We use release and publish interchangeably, instead of sticking to one
Going with "release" rather than "publish" could make sense for alignment with "Releases" on GitHub, NPM, etc.
