### ISSUE TITLE
ECDSA signature verification panics if provided invalid signature/public key

### ISSUE THREAD

**Issue by colinnielsen** [noir-lang/noir#2755]
### Aim

I am trying to wrap up my [dark-safe circuit](https://github.com/colinnielsen/dark-safe/blob/main/circuits/src/main.nr#L26-L42):

I need a variable amount of items in an input array, so I'm using loop with some fixed `MAX_ITERATIONS`, then an `should_calculate` boolean in the input structs as a "no-op" flag.

There is an `if` block within the `for` loop, which looks for a `should_calculate` flag in the struct, and no-ops otherwise.

<img width="497" alt="Screenshot 2023-09-19 at 7 30 11 PM" src="https://github.com/noir-lang/noir/assets/33375223/d3f66dfa-80f7-4c24-a1a9-2b2204d5a76b">

### Expected Behavior

The program should not panic

### Bug

Given a [Prover.toml](https://github.com/colinnielsen/dark-safe/blob/main/circuits/Prover.toml) with 4 valid inputs and with 4 "empty" structs,  running `nargo execute`, I see 4 `println` statements echo the array index, and "computing", then the program crashes at the blackbox-solver file.
<img width="744" alt="Screenshot 2023-09-19 at 7 15 52 PM" src="https://github.com/noir-lang/noir/assets/33375223/a560c3f1-73ed-47b6-a03b-2cb15f0c6737">

Running the `nargo execute -p provers/Prover_full.toml` with a _full_ array [Prover_full.toml](https://github.com/colinnielsen/dark-safe/blob/main/circuits/Prover.toml) works as expected
<img width="522" alt="Screenshot 2023-09-19 at 7 18 16 PM" src="https://github.com/noir-lang/noir/assets/33375223/fa63f5d1-da17-4157-8b24-8593b4a2e57e">

### **NOTE:** 
- If I place the "empty" structs _first_ in the Prover.toml, it will crash on the first iteration in the no-op <img width="386" alt="Screenshot 2023-09-19 at 7 21 16 PM" src="https://github.com/noir-lang/noir/assets/33375223/f96fe756-a058-4d44-9adf-0b7eb86d82e0">
- I have also tried "flipping" the if statement, and putting the computation in the `else` branch. This makes no difference to either above case. The program crashes whenever it hits an empty struct in the loop.
- Interestingly enough, if I _only pass empty_ structs in via `nargo execute`, the program will fail on the first iteration

### To Reproduce

1. `git clone https://github.com/colinnielsen/dark-safe.git && cd dark-safe/circuits`
2. either `nargo execute`, `nargo execute -p provers/Prover_completely_empty.toml`, `nargo execute -p provers/Prover_full.toml`, or `nargo execute -p provers/Prover_empty_first.toml`

If you want to play with your own Prover.toml, (with a valid polynomial and array of signatures) run:
1. `yarn install`
2. `yarn build`
3. follow the cli prompt

### Installation Method

Binary

### Nargo Version

nargo 0.12.0 (git version hash: 13cc23bfe655eff52fa19c3f7e32f1c3cf09bd82, is dirty: false)

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
Thanks for reporting this @colinnielsen. The underlying issue is that [`verify_secp256k1_ecdsa_signature`](https://github.com/noir-lang/acvm/blob/2f503c4b444d68d4b8489eba78e95e6889382c2e/blackbox_solver/src/lib.rs#L101) panics rather than returning false if we provide invalid signatures like you're doing here.

I'll go through and update this function to return false in this case rather than panicking.

**Comment by TomAFrench** [comment]
@colinnielsen I've tested `dark-safe` with the fix in https://github.com/noir-lang/acvm/pull/557 and I now get a failed constraint when asserting the polynomial evaluates to zero rather than a panic.

**Comment by colinnielsen** [comment]
> @colinnielsen I've tested `dark-safe` with the fix in [noir-lang/acvm#557](https://github.com/noir-lang/acvm/pull/557) and I now get a failed constraint when asserting the polynomial evaluates to zero rather than a panic.

Awesome! Thank you, Tom

**Comment by TomAFrench** [comment]
This issue is closed now but Noir isn't currently pulling from the ACVM code in this repository yet.
