### ISSUE TITLE
`[Struct {}, N]` syntax results in a panic due to assigning `LocalId(0)` twice

### ISSUE THREAD

**Issue by bryanwee023** [noir-lang/noir#2786]
### Aim

I'm trying to initialize an array of a user-defined `struct`.

### Expected Behavior

If this is meant to be supported, then my code should run.
If not, then an appropriate error message should be printed.

### Bug

I get the following error output.
```
[noir_playground] Testing test_main... The application panicked (crashed).
Message:  Variable LocalId(0) was defined twice in ssa-gen pass
```

### To Reproduce

1. Define a `struct`
2. Initialize an array of the `struct` in `main`
3. Call `main` in a test and run `nargo test`

```
struct Box {
    x: Field
}

fn main() {
    let boxes = [Box  {x: 1}; 8];
}

#[test]
fn test_main() {
    main();
}
```

### Installation Method

Binary

### Nargo Version

nargo 0.10.5 (git version hash: 91efe44d17762ea883d9a576d530049ad20f1393, is dirty: false)

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
Interesting, thanks for opening this issue @bryanwee023. I've replicated this on current master.

Arrays of structs are supported but it looks like the sugared syntax to create an array filled with the same element doesn't, i.e. `[Box  {x: 1}, Box  {x: 1}, ..., Box  {x: 1}]` will work but `[Box  {x: 1}; 8]` won't.

**Comment by TomAFrench** [comment]
This seems to also require you to initialize the struct inside the array creation. As a workaround, I'd move this outside and use something like the below.

```
fn main() {
    let box = Box {x: 1};
    let boxes = [box; 8];
}
```
