### ISSUE TITLE
`if` block in `for` loop crashes test

### ISSUE THREAD

**Issue by bryanwee023** [noir-lang/noir#2787]
### Aim

I want to achieve something similar to this logic flow:
```rust
let mut v = Vec::new();
let mut skip = true;
for _ in 0..5 {
    if skip {
        v.push(1);
        // Do something to skip here...
    } 
}
```

### Expected Behavior

The block of code to run. Or if the operation is not supported (for some reason), then maybe a more appropriate error message should be printed.

### Bug

I get the following output error:
```
[noir_playground] Testing test_main... The application panicked (crashed).
Message:  Expected array value
```

### To Reproduce

This is the minimal example I managed to find.
```rust
use dep::std::collections::vec::Vec;

fn main() {
    let mut v = Vec::new();

    let mut skip = true;
    for _ in 0..5 {
        if skip {
            v.push(1);
        }
    }
}

#[test]
fn test_main() {
    main();
}
```

Calling `nargo test` will produce the error.
Some things I noted:
1. Removing the vector `v` fixes things
2. Removing the `if` condition fixes things
3. Using a different condition for `if` (e.g., a `bool` declared outside `main` fixes things)

### Installation Method

Binary

### Nargo Version

nargo 0.10.5 (git version hash: 91efe44d17762ea883d9a576d530049ad20f1393, is dirty: false)

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
The error given in your snippet no longer occurs, but we do run into a different "attempt to subtract with underflow" panic. I've made a PR to fix it here: #2796
