### ISSUE TITLE
Track IsConst for `==` and `!=` on arrays

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#280]
Currently if the user writes `array1 == array2` or `array1 != array2` (given both variables are arrays), the result will never be const, even if both arrays have const elements.

In practice, this is only noticeable if the result of this expression is later casted to an integer and used as an array index:
```
let i = (array1 == array2) as Field;
constrain array1[i] == foo; // error: i is not const
```

**Comment by kevaundray** [comment]
@jfecher what is the status of this issue?

**Comment by jfecher** [comment]
Still open. The issue documents a known but fairly unimportant issue as the code to trigger it is possible but fairly contrived.
