### ISSUE TITLE
Engine crash while running an unconstrained function

### ISSUE THREAD

**Issue by 0xddom** [noir-lang/noir#2802]
### Aim

I try to compile and run the following code:

```
struct BitWithCarry {
    value: Field,
    carry: Field
}

unconstrained fn bitAddValue(b1: Field, b2: Field, carry: Field) -> Field {
    (b1 + b2 + carry) % 2
}

unconstrained fn bitAddCarry(b1: Field, b2: Field, carry: Field) -> Field {
    (b1 + b2 + carry) / 2
}

fn weirdBitAdd(b1: Field, b2: Field, carry: Field) -> BitWithCarry {
    let value = bitAddValue(b1, b2, carry);
    let carry = bitAddCarry(b1, b2, carry);

    assert(value * (value - 1) == 0);
    assert(carry * (carry - 1) == 0);

    BitWithCarry {
        value,
        carry
    }
}

fn main(b1: pub Field, b2: pub Field, carry: pub Field) -> pub BitWithCarry {
    weirdBitAdd(b1, b2, carry)
}
```

### Expected Behavior

The circuit compiles and executes correctly

### Bug

When I try to run the circuit I get the following error:

```
$ nargo compile
The application panicked (crashed).
Message:  internal error: entered unreachable code: Field type cannot be used with mod. This should have been caught by the frontend
Location: crates/noirc_evaluator/src/brillig/brillig_gen/brillig_block.rs:1173
```

### To Reproduce

1. Create a Noir project with `nargo`
2. Write the circuit above in `main.nr`
3. Build the circuit with `nargo compile`

### Installation Method

Binary

### Nargo Version

nargo 0.11.0 (git version hash: 75638451277cfc27de19c90ca6bb87d0713876fd, is dirty: false)

### Additional Context

I also tried with nargo 0.12.0

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
@sirasistant do you know why mod for fields is unimplemented in Brillig? It works fine in ACIR.
