### ISSUE TITLE
Must run bootstrap script inside barretenberg after updating commit reference in aztec backend crate

### ISSUE THREAD

**Issue by vezenovm** [noir-lang/noir#282]
When the commit reference to the aztec backend is updated, simply installing nargo by itself currently fails. In this [PR](https://github.com/noir-lang/noir/pull/274) the insert merkle opcode was deleted which required changes to the barretenberg serialization. The commit reference was [updated](https://github.com/noir-lang/noir/pull/274/files#diff-783445433661113a3a3da2d566388eb68952c56418d572ee3a1ec2ec81f2f338L12) to reflect this change. However, when running `cargo install --locked --path=.` inside nargo the backend would fail to build. 

```  --- stderr
  CMake Warning:
    Manually-specified variables were not used by the project:

      CMAKE_ASM_COMPILER
      CMAKE_ASM_FLAGS


  make: warning: -jN forced in submake: disabling jobserver mode.
  CMake Error at /usr/local/Cellar/cmake/3.23.1/share/cmake/Modules/GoogleTestAddTests.cmake:112 (message):
    Error running test executable.

      Path: '/Users/maximvezenov/Documents/dev/noir/target/release/build/barretenberg_wrapper-e5a5dbe1119d7c88/out/build/src/aztec/dsl/dsl_tests'
      Result: Process terminated due to timeout
      Output:
        

  Call Stack (most recent call first):
    /usr/local/Cellar/cmake/3.23.1/share/cmake/Modules/GoogleTestAddTests.cmake:225 (gtest_discover_tests_impl)


  make[2]: *** [src/aztec/dsl/dsl_tests] Error 1
  make[2]: *** Deleting file `src/aztec/dsl/dsl_tests'
  make[1]: *** [src/aztec/dsl/CMakeFiles/dsl_tests.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....
  make: *** [all] Error 2
  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 2

  build script failed, must exit now', /Users/maximvezenov/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.48/src/lib.rs:975:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The build would succeed upon checking out to the relevant commit in barretenberg and running the bootstrap script. I am on an intel so to be specific I ran `./bootstrap.sh APPLE_INTEL`. barretenberg then successfully built and I successfully installed nargo. 

Rerunning `bootstrap.sh` in barretenberg is also needed when trying to install `nargo` after a `cargo clean`

It seems that a developer should be able to build nargo without having to install the barretenberg repo themselves and subsequently run the bootstrap script. I am curious if anyone else has experienced this issue as well.

**Comment by kevaundray** [comment]
@vezenovm can we close this issue or should we keep it open?

**Comment by phated** [comment]
When setting up the project, I didn't need to run the `bootstrap.sh` file. I also think it might conflict with the CMake execution in the `build.rs`

**Comment by kevaundray** [comment]
Oh nice, closing this issue then
