### ISSUE TITLE
Refactoring main export from `noir_js` to aggregate different Noir steps

### ISSUE THREAD

**Issue by signorecello** [noir-lang/noir#2835]
Part of the first `noir_js` review:

I need to import Backend but Backend is literally a copy of noir-starter noir.ts file, plus it’s nested within a test folder.

```js
import { Backend } from '@noir-lang/noir_js/test/backend/barretenberg'
```

I'm suggesting that we:

- [x] Should put Backend in the src folder
- [x] Should export Backend in the package.json file
- [x] The Backend file is what `Noir_js` should be, aggregating circuit compilation, witness generation, and the backend. Currently it is literally just a wrapper on barretenberg. At least witness generation would be necessary to include.

**Comment by kevaundray** [comment]
Closing this as I believe its completed -- if this is incorrect, feel free to reopen
