### ISSUE TITLE
Fix auto rebuild script for acir artifacts

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#2847]
### Aim

The auto rebuild script is failing

### Expected Behavior

.

### Bug

https://github.com/noir-lang/noir/actions/runs/6312167310/job/17137819892

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
Fixed in #2849
