### ISSUE TITLE
Apply backend agnostic ACIR optimization passes separately to backend-specific passes

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#2866]
### Problem

In https://github.com/noir-lang/acvm/pull/88, we made the distinction between optimizers (which are generic between backends) and transformers (which use knowledge about the desired proving backend to make the ACIR compatible with it.

Despite this we currently have a single monolithic `compile` function inside the ACVM which applies both optimizations and transformations.   

### Happy Case

We should expose `optimize` and `transform` (this could be named better) functions to separate these two functions. We could then make use of `optimize` as a final pass within the Noir compiler so that our outputted ACIR represents the most optimized generic ACIR possible.

This means that our backend step is _purely_ a matter of making the ACIR compatible with the backend rather than a mix of two concepts.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
Can this be closed?

**Comment by TomAFrench** [comment]
Yep this was closed by #2979
