### ISSUE TITLE
Make integration tests easier to run locally

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#2880]
### Problem

Currently running the integration tests locally is a bit of a pain as it requires manually copying a number of files around and deploying contracts. We should have shell scripts for this so that the experience can be as simple as opening two shells (one for anvil and another for the javascript tests) and running two commands.

### Happy Case

We should define shell scripts which can be run locally to simplify running these tests locally.

`forge-init.sh`: This should set up the foundry project for the verifier contracts. We should delete any unnecessary files from here as part of this so we're not compiling things we don't need.
https://github.com/noir-lang/noir/blob/4765c8288c583a61a81ff97eea1ef49df13eeca0/.github/workflows/test-integration.yml#L219-L220

`codegen-verifiers.sh`: This should codegen the verifier contracts and pull them into the foundry project.
https://github.com/noir-lang/noir/blob/4765c8288c583a61a81ff97eea1ef49df13eeca0/.github/workflows/test-integration.yml#L222-L233

`deploy-verifiers.sh`: This would start up an anvil instance and deploy the contracts, writing the contract addresses to a json file.
https://github.com/noir-lang/noir/blob/4765c8288c583a61a81ff97eea1ef49df13eeca0/.github/workflows/test-integration.yml#L214-L217
https://github.com/noir-lang/noir/blob/4765c8288c583a61a81ff97eea1ef49df13eeca0/.github/workflows/test-integration.yml#L235-L243

We can also have a overarching script to run all of these in order.

### Alternatives Considered

We'll probably want to have a `yarn` command to rebuild any of the dependencies of the integration tests package.

### Would you like to submit a PR for this Issue?

No

**Comment by kobyhallx** [comment]
Could we isolate solidity to it's own file? This way I can progress with work in more fine grained fashion.
