### ISSUE TITLE
Release new `noir_js` versions on NPM automatically

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#2884]
### Problem

Right now _noir_js_ releases are pushed onto NPM manually. (Or are they expected to be automatic? This would be a bug if that's the case.)

As such, the latest _noir_js_ on NPM is still at v0.12.0 at the moment of creating this issue, in comparison to the latest v0.14.1 Noir / Nargo available.

https://www.npmjs.com/package/@noir-lang/noir_js?activeTab=versions

### Happy Case

A _noir_js_ release should be cut and pushed when a Noir release PR is merged, like how Nargo is released.

### Additional Context

Ideally we would want _noir_js_ releases to be pushed under the "dev" tag when a Noir Pre-release is cut, and updated to the "latest" tag when the corresponding Noir Pre-release is switched into a Release.

This could go into a separate GitHub Issue however if it's considered a scope creep.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
I think there is an issue with the js publishing workflow -- I can check why these are not publishing or @jonybur

**Comment by jonybur** [comment]
@kevaundray Fixing here: https://github.com/noir-lang/noir/pull/2926

**Comment by Savio-Sou** [comment]
Duplicate of https://github.com/noir-lang/noir/issues/2881.
