### ISSUE TITLE
Add fuzzy tests to noir

### ISSUE THREAD

**Issue by jonybur** [noir-lang/noir#2888]
- Create several noir programs for testing purposes.
- Conduct fuzzy testing on created programs.

Working on this repo: https://github.com/jonybur/fuzzy-tester

**Comment by f01dab1e** [comment]
I think it would be interesting to incorporate fuzz testing for the type checker. I came across a resource that might be helpful in this regard: https://hardekbc.github.io/files/dewey15fuzzing.pdf

**Comment by jonybur** [comment]
Getting them fixed as part of this issue: https://github.com/noir-lang/noir/issues/2881
