### ISSUE TITLE
Array of tuple not supported in the main function

### ISSUE THREAD

**Issue by 0xrishabh** [noir-lang/noir#2891]
### Aim

I tried to pass array of tuple to the main function

### Expected Behavior

It should have compiled successfully 

### Bug

```
Message:  not yet implemented: AbiType::from_type not yet implemented for tuple types
Location: tooling/noirc_abi/src/lib.rs:167
```

### To Reproduce

```
global DEPTH: Field = 11;
fn main(x: [(u8, u8, u8); DEPTH], y: u8) {}
```

Compile this

### Installation Method

None

### Would you like to submit a PR for this Issue?

Yes

**Comment by vezenovm** [comment]
This a repeat of https://github.com/noir-lang/noir/issues/1855 except that this issue is talking about inputs to main rather than outputs from main, but both would be implemented at the same time.
