### ISSUE TITLE
Nargo can panic when loading build artifacts from previous versions

### ISSUE THREAD

**Issue by 0xrishabh** [noir-lang/noir#2892]
### Aim

Take a u24 and perform some operation onto it

### Expected Behavior

Compilation should have been succesfull

### Bug

```
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Io(Kind(UnexpectedEof))
Location: /Users/runner/work/noir/noir/acvm-repo/acir/src/circuit/mod.rs:140
```

### To Reproduce

```
use dep::std;
fn main(x: u24) {
   let a = x >> 16 & 0xFF;
   let b = x >> 8 & 0xFF;
   let c = x & 0xFF;
}
```

nargo build

### Installation Method

None

### Nargo Version

v0.15.0

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
This is due to you having a cached build artifact from a different version of nargo which `0.15.0` can't parse. We'll add a proper fix for this but in the meantime delete the `target` directory and you should be fine.
