### ISSUE TITLE
Cannot print array of strings

### ISSUE THREAD

**Issue by vezenovm** [noir-lang/noir#2903]
### Aim

I want to be able to print an array of strings.

For example in this test:
```
#[test]
fn test_print_char_array()
{
    let v : [str<1>; 1] = ["1"; 1];
    dep::std::println(v); // will print [""]

    let a = v[0];
    dep::std::println(a); // will print "1"
}
```

### Expected Behavior

I should get the output of ["1"] for the first println, but instead I get the output of [""]. Extracting the `str<1>` value I successfully print "1" (the strings all printing with quotes is a different issue that can be addressed separately).

### Bug

I get an output of [""] for the first println in the snippet above.

### To Reproduce

1. Copy the test snippet above into a Noir program
2. Run `nargo test --show-output `

### Installation Method

Compiled from source

### Nargo Version

nargo 0.15.0 (git version hash: 9854416f5ac03c9da6538edc6a0a540ccccb4b61, is dirty: true)

### Additional Context

```
    let bytes = [ "a", "b", "c" ];
    dep::std::println(bytes);    
```
will just print `["", "", "]`

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@vezenovm what is the status of this issue?
