### ISSUE TITLE
Do not include quotes when printing values

### ISSUE THREAD

**Issue by vezenovm** [noir-lang/noir#2904]
### Problem

Currently any calls to `println` will print the value to stdout with quotes. This includes strings, integers, etc. 

For example in this snippet:
```
#[test]
fn test_println()
{
    dep::std::println("");   // outputs {""}     instead of { }
    dep::std::println("A");  // outputs {"A"}    instead of {A}
    dep::std::println("\t"); // outputs {"    "} instead of {    }
}
```

### Happy Case

The snippet outlines what should be printed and what happens instead. We do not want quotes around everything we print. The string `"A"` should just be printed as `A`. 

### Alternatives Considered

N/A otherwise it gets confusing with the quotations and makes it less clear to developers who are debugging. Quotations should just be used for encapsulating strings and only included in a print when they are used with escape characters. 

### Would you like to submit a PR for this Issue?

No

**Comment by rahultg1411** [comment]
Hey, I'm Rahul. I would like to work on this issue. Could you please assign it to me?

**Comment by vezenovm** [comment]
Hey thanks for taking this on! @rahultg1411

**Comment by grasshopper47** [comment]
@vezenovm I've fix this with this PR https://github.com/noir-lang/noir/pull/3574
