### ISSUE TITLE
Cannot index access dereferenced mutable array 

### ISSUE THREAD

**Issue by vezenovm** [noir-lang/noir#2907]
### Aim

I should be able to directly access a dereferenced array without having to specify its type. 

For example:
```
#[test]
fn mutable_array_indexing() -> [Field; 2]
{
    let v = &mut [1, 2];
    // dep::std::println((*v)[0]); // error: Expected type Array, found type [Field; 2]

    let v_normal = *v;
    // dep::std::println(v_normal[0]); // error: Expected type Array, found type [Field; 2]
    // let f: Field = v_normal[0]; // error: Expected type Array, found type [Field; 2]

    let mut v : [Field; 2] = *v;
    dep::std::println(v[0]); // works, prints 1

    for i in 0..v.len() { v[i] += 1; }

    dep::std::println(v); // works, prints 2, 3

    let mut v = &mut v;
    *v
}
```

### Expected Behavior

I should be able to access `v_normal[0]` without a type mismatch error. The error no longer occurs when `[Field; 2]` is specified directly. The behavior that occurs 

### Bug

We get `error: Expected type Array, found type [Field; 2]` when we access `v_normal` in the snippet above.

### To Reproduce

1. Copy the test in the issue to a Noir project.
2. Uncomment the lines listed with errors in the snippet.
3. Run `nargo test --show-output`

### Installation Method

Compiled from source

### Nargo Version

nargo 0.15.0 (git version hash: 9854416f5ac03c9da6538edc6a0a540ccccb4b61, is dirty: true)

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
The test listed now passes.
