### ISSUE TITLE
Cleanup Noir.js

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#2910]
### Problem

List of tracking items for cleaning up Noir.js and its related items:

- https://github.com/noir-lang/noir/issues/2895
- https://github.com/noir-lang/noir/pull/2902#discussion_r1341788679
- https://github.com/noir-lang/noir/pull/2902#discussion_r1341789258

### Happy Case

.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
Currently we call this.backend.instantiate when a user calls Noir.init and we also check to see if its called when we generate/verify a proof. 

we should have a single strategy for this, ie always force users to call .init or always lazilly call it when a function needs it

**Comment by signorecello** [comment]
I made some suggestions on it here as well: https://github.com/noir-lang/noir/pull/3044

**Comment by Savio-Sou** [comment]
@kobyhallx safe to close?
