### ISSUE TITLE
Implement print builtin that does not insert a newline

### ISSUE THREAD

**Issue by vezenovm** [noir-lang/noir#2912]
### Problem

We have a `println` builtin function in our standard lib but this restricts developers to have to print with a new line.  

### Happy Case

Developers should be able to call a `print` function that gives the option to print without a newline. Our existing `println` function can then be reimplemented where it calls this new `print` function.

### Alternatives Considered

N/A or else developers will not be able to have a normal print.

### Would you like to submit a PR for this Issue?

No

**Comment by yekxp** [comment]
Hello, my name is Jakub and I am a student of Technical University in Kosice and I would be very happy if I could work on this issue. Could you assign me to it?

**Comment by grasshopper47** [comment]
@vezenovm This can be closed

**Comment by vezenovm** [comment]
https://github.com/noir-lang/noir/pull/3650
