### ISSUE TITLE
Integrate Bors into the CI

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#292]
Link to Bors: https://github.com/bors-ng/bors-ng

**Comment by kevaundray** [comment]
We added this, but it's not being used -- what are your thoughts on this @jfecher ?

**Comment by jfecher** [comment]
I've never had a need to use it. We can check in with the tooling team to see if it'd be desirable to integrate it more closely, if not then I'd suggest removing it.

**Comment by phated** [comment]
It seems that the bors workflow isn't setup as a workflow that runs with an `on` and produces an error constantly in the Actions tab.

I had never heard of bors, so I just skimmed their https://github.com/bors-ng/bors-ng#but-dont-githubs-protected-branches-already-do-this

They call out:
> In addition to the testing requirements, GitHub can also be set to block pull requests that are not "up to date" with the main branch, meaning that problems like this can't show up. This fixes the problem, by requiring that the main branch only contain a snapshot of the code that has passed the tests

I'd rather rely on GitHub features, even if they take a little more time, than extra CI runs, especially knowing that we'll have to keep it up-to-date and trust a third-party action.
