### ISSUE TITLE
Add Noir.Js as a required test

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#2930]
### Aim

For some reason github won't allow us to add Noir.js as a required tests to pass for CI to pass

### Expected Behavior

There should be a dropdown list in settings that says Noir JS.

### Bug

No mention of Noir Js

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
Oh my mistake, its called "test" in the settings list

**Comment by Savio-Sou** [comment]
Closed with https://github.com/noir-lang/noir/pull/2932?

**Comment by kevaundray** [comment]
Yep closing
