### ISSUE TITLE
Switch integration tests to use hardhat over anvil

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#2933]

**Comment by Savio-Sou** [comment]
Can we test both Hardhat and Forge?

They both seems popularly adopted still amongst the Solidity / EVM community.

**Comment by TomAFrench** [comment]
There's no point in using both as we're just checking that we can verify the proofs within the EVM which is common between them. The only difference is that we can avoid having a separate setup script with hardhat compared to using an anvil node.
