### ISSUE TITLE
Enable easy developer iteration with `noir_js` packages

### ISSUE THREAD

**Issue by kobyhallx** [noir-lang/noir#2955]
Provide developer version of noir_js packages which pre-built, ready to be used in demonstrations, CI and experimentations.

**Comment by kobyhallx** [comment]
[noir_js-dev](https://github.com/noir-lang/noir_js-dev) repository will contain all `noir_js` related packages.

**Comment by Savio-Sou** [comment]
@kobyhallx safe to consider this closed?
