### ISSUE TITLE
Different compiled bytecode for ecdsa_account_contract.json on m1 vs x86_64

### ISSUE THREAD

**Issue by dan-aztec** [noir-lang/noir#2959]
### Aim

In the AztecProtocol monorepo, I'm getting different bytecode generated for yarn-project/aztec.js/src/abis/ecdsa_account_contract.json when I compile/build locally on m1 vs mainframe.  

Not sure why this is the only contract where the abi/artifact is different.  

noticed this [on my branch](https://github.com/AztecProtocol/aztec-packages/pull/2635) (which doesnt change the noir source).  

### Expected Behavior

the same bytecode to be produced in `yarn-project/aztec.js/src/abis/ecdsa_account_contract.json` on m1 and x_86

### Bug

just slightly different bytecode in a single aztec contract

### To Reproduce

1. in aztec-packages, checkout dan/test-nargo-12 (or master, as of October 3rd 2023)
2. do top level `./bootstrap.sh` or within `yarn-projects/noir-contracts` do `./boostrap.sh`
3. `git status` will show `yarn-project/aztec.js/src/abis/ecdsa_account_contract.json` has changed on m1

### Installation Method

Binary

### Nargo Version

nargo 0.12.0 (git version hash: 3b43709ddd5feffdbbc1723ba7dbcf63531aae05, is dirty: false)

### Would you like to submit a PR for this Issue?

No

**Comment by guipublic** [comment]
I did the same on my M1 and on the mainframe, from master, and I get the same result.
How can I ensure there were properly generated by the bootstrap?

**Comment by kevaundray** [comment]
Closing as this is not reproducable
