### ISSUE TITLE
Standardise Node setup on workflows

### ISSUE THREAD

**Issue by jonybur** [noir-lang/noir#2960]

**Comment by Savio-Sou** [comment]
Does https://github.com/noir-lang/noir/pull/2989 resolves this?

**Comment by TomAFrench** [comment]
No, that's to do with publishing.

**Comment by Savio-Sou** [comment]
@jonybur not sure if you have created the Issue; would you like to supplement on what's the aim and plan here?

**Comment by jonybur** [comment]
Closing as this was already done with https://github.com/noir-lang/noir/pull/2989
