### ISSUE TITLE
(fuzzer) - should the parser allow constructors in parentheses within `if` condition and `for` range?

### ISSUE THREAD

**Issue by pczarn** [noir-lang/noir#2996]
### Aim

Tried to parse the following code:
```rust
fn foo() {
  let x = Bar  { baz : 1 };
  if (Bar { baz: 1 } == Bar { baz: 2 }) {
    // do something
  }
}
```

### Expected Behavior

I know that constructors appearing directly after `if` and `for ... in` are disallowed, but I expected the code to parse and compile OK because the constructors are surrounded by parentheses.

### Bug

Got parse error `Expected an expression but found {`.

This behavior is inconsistent with Rust lang, which allows the code to compile. Also, it does not quite make sense to disallow such syntax.

Most likely reason for the bug is the second argument to `expression_with_precedence` called from `expression_no_constructors`:

```rust
fn expression_no_constructors() -> impl ExprParser {
    recursive(|expr| {
        expression_with_precedence(Precedence::Lowest, expr.clone(), expr, false, false)
    })
    .labelled(ParsingRuleLabel::Expression)
}
```

### Installation Method

Compiled from source

### Additional Context

Found by the parser-fuzzer tool.

### Would you like to submit a PR for this Issue?

Yes, possible

**Comment by pczarn** [comment]
Seems important because formal grammar is much tougher with two kinds of expression, allowing constructors or not.

**Comment by pczarn** [comment]
I have code that may fix this.

**Comment by jfecher** [comment]
Yes, we should allow it. It was an oversight that it was not already allowed.
