### ISSUE TITLE
Implement slices for function arguments

### ISSUE THREAD

**Issue by guipublic** [noir-lang/noir#301]
Fonctions working on arrays take fixed-length array as input, which is too restrictive.
For instance doing a matrix multiplication requires to define multiple functions for each matrix length.
One possibility to solve this is to support slices in function arguments. We should have a len() method on slices that the user can use and which would be of  'const type'
This would allow the user to write something like this:
```
fn matrix_mul(a: []u32, b: []u32) {
  constrain a.len()==b.len(); 
  for i in 0..a.len()*a.len() 
(...)
}
```
We could also support this syntax for slices and arrays:
`for i in a {...};`

**Comment by jfecher** [comment]
Another option could be to support size parameters, as in futhark: https://futhark-lang.org/examples/size-parameters.html

**Comment by kevaundray** [comment]
This has now grown stale
