### ISSUE TITLE
Cannot parse fieldless structures

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#3018]
### Aim

Parse the following code:

```
struct Foo;
```

### Expected Behavior

Parse successfully.

### Bug

error: Unexpected ;, expected one of <, {
  ┌─ main.nr:5:11
  │
5 │ struct Foo;
  │           -
  │

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by f01dab1e** [comment]
This includes creating structures through simply "let foo = Foo;"?

**Comment by kevaundray** [comment]
Forgot to reply -- this is not necessary for this issue, we can create another issue for it.

In rust, 

`struct Foo;`

can be created by either doing:

`let foo = Foo;`
or
`let foo = Foo{};`
