### ISSUE TITLE
Add a flag to nargo to silence warnings

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#3024]
### Problem

Currently when users run `nargo compile` they can get a lot of warnings without the ability to silence them.

### Happy Case

Add a flag like `nargo compile --silence-warnings` which will silence all of the warnings in the program

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@f01dab1e can you take this issue?

**Comment by f01dab1e** [comment]
okay
