### ISSUE TITLE
Document why OPCODE::ToBits is unreachable in the partial witness generator

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#303]
We should document why the Opcode "ToBits" is unreachable in the partial witness generator.

```
OPCODE::ToBits => unreachable!()
```

**Comment by guipublic** [comment]
"ToBits" is unreachable here because it is not handled by Barretenberg, it is transformed into arithmetic constraints before.
- Should I explain this in a comment?
- Would it make sense to have a Plonk custom gate for this?

**Comment by kevaundray** [comment]
Should it be a builtin noir function instead?

**Comment by guipublic** [comment]
> Should it be a builtin noir function instead?

It is a builtin noir function! cf. std::to_bits(..)

**Comment by kevaundray** [comment]
Adding a note:

We should remove the `ToBits` OPCODE since we want it as a directive. It seems to be getting used in the evaluate_opcode method in SSA. I am not sure why though.

Noting that OPCODES should be used for adding constraints, if it is unreachable then it should not be an opcode.

**Comment by kevaundray** [comment]
This has now been removed and moreover acvm is no longer in this repo
