### ISSUE TITLE
Disallow `pub` outside of main

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#306]
After PR #281 `pub` only has effects on arguments to the main function. It is currently erroneously allowed in other functions, although does not do anything. We should add a check either during parsing or name resolution to warn the user that it does nothing if used outside of main.

**Comment by kevaundray** [comment]
To keep parsing simple, I think it should go into name resolution. 

In the future, it would need to account for the edge case where a user declares a library and has a main function. In that case, pub would not be allowed since its not a binary.
