### ISSUE TITLE
Flaky CI for dynamic backends

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#3060]
### Aim

CI routinely fails with backend encoutered an error. See https://github.com/noir-lang/noir/actions/runs/6460408720/job/17538044190?pr=2978

### Expected Behavior

.

### Bug

.

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
My money is on the `codegen-verifier` and `hello-world` integration tests trying to write the CRS to the same file at the same time.

**Comment by TomAFrench** [comment]
I haven't experienced this in quite some time so I'm going to say this has been resolved. It seems to have been an issue in `bb` rather than nargo code.
