### ISSUE TITLE
nargo fails to verify its own proof on recursive proof example

### ISSUE THREAD

**Issue by jordan-public** [noir-lang/noir#3090]
### Aim

% nargo verify
Failed to verify proof .../noir/tooling/nargo_cli/tests/execution_success/double_verify_proof/proofs/double_verify_proof.proof

### Expected Behavior

% nargo verify
OK

### Bug

Nargo 0.16.0 fails to verify its own generated proof on example double_verify_proof from Noir repo.

### To Reproduce

% noirup -v v0.16.0
% git clone https://github.com/noir-lang/noir.git
% cd noir
% git checkout tags/v0.16.0
% cd tooling/nargo_cli/tests/execution_success/double_verify_proof
% nargo prove
% nargo verify
Failed to verify proof .../noir/tooling/nargo_cli/tests/execution_success/double_verify_proof/proofs/double_verify_proof.proof

### Installation Method

Binary

### Nargo Version

nargo 0.16.0 (git version hash: 3611cfc1cd010ac8b772d8c251bfe8012d911a3f, is dirty: false)

### Would you like to submit a PR for this Issue?

No

**Comment by vezenovm** [comment]
Upon downloading the most recent `nargo` using `noirup`: 
```
nargo version = 0.23.0
noirc version = 0.23.0+5be9f9d7e2f39ca228df10e5a530474af0331704
(git version hash: 5be9f9d7e2f39ca228df10e5a530474af0331704, is dirty: false)
```
the test successfully verifies so I am closing this issue.
