### ISSUE TITLE
The parser ignores lexer errors

### ISSUE THREAD

**Issue by f01dab1e** [noir-lang/noir#3125]
### Aim

```
/*
```

### Expected Behavior

Compilation error

### Bug

Currently, the parser is ignoring lexer errors:
https://github.com/noir-lang/noir/blob/88682da87ffc9e26da5c9e4b5a4d8e62a6ee43c6/compiler/noirc_frontend/src/parser/parser.rs#L57-L61

### To Reproduce

1.
2.
3.
4.

### Installation Method

Compiled from source

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@f01dab1e good catch -- can you pick this up?

This change was made in this PR: https://github.com/noir-lang/noir/pull/2760

Pinging at @jfecher for visibility.

Naively, I would see if we could convert a LexerError into a ParserError so there is no change in the API
