### ISSUE TITLE
Formatter formats `&mut x` into `&mutx` which no longer compiles

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#3152]
### Aim

I'd like to be able for format code which uses mutable references.

### Expected Behavior

```
fn main(mut x: Field) {
    &mut x;
}
```

should be unaffected by the formatter

### Bug

This actually gets formatted into

```
fn main(mut x: Field) {
    &mutx;
}
```

This then no longer compiles

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@f01dab1e can you take a look?
