### ISSUE TITLE
Investigate clap toolkit to enhance CI

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#3159]
### Problem

Clap comes with a lot of tools that we have not looked into in their monorepo, one of these is an automatically generated markdown page for the cli commands available](https://github.com/clap-rs/clap/blob/master/clap_mangen/README.md) another is [auto complete in the shell](https://github.com/clap-rs/clap/blob/master/clap_complete/README.md)

### Happy Case

Investigate Clap CLI features that we can add into nargo_cli to make the user experience better

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@f01dab1e can you pick this up? Lower priority than the other tasks you are currently doing.

This issue will be used to first discuss the feature from clap that we'd like to add before opening up a PR, where each new feature will require a new PR

**Comment by f01dab1e** [comment]
It seems that clap_mangen can only create ROFF format (which can be converted to Markdown via Pandoc), but I've also found a crate that can create Markdown directly. You can find more details at https://docs.rs/clap-markdown/latest/clap_markdown/

**Comment by TomAFrench** [comment]
Closing in favour of #6284 as it's more specific considering that we already have a codegen markdown reference.
