### ISSUE TITLE
Investigate why LSP is slow

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#3160]
### Problem

Compiler currently compiles the whole program and does not allow one to compile a single file without compiling the crate root first.

This may be one of the reasons why the LSP is slow to compile programs. It could also be that it is always generating ACIR, whereas we could make the LSP go only upto typechecking/ssa.

### Happy Case

.

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
> It could also be that it is always generating ACIR, whereas we could make the LSP go only upto typechecking/ssa.

We only go up to typechecking currently.

**Comment by TomAFrench** [comment]
We've gone through a bunch of optimisations e.g. caching of parsing layers, etc. so I'm gonna close this.
