### ISSUE TITLE
Add pub(crate) visibility

### ISSUE THREAD

**Issue by guipublic** [noir-lang/noir#3168]
### Problem

We support the `pub` attribute when defining a function, so that the function is visible everywhere externally and internally.

We could extend it with the `pub(crate)` notation which would allow the function to be used inside the crate, but not in an external crate.

### Happy Case

`pub(crate)` makes a function visible within the current crate.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
Also tagging along pub(crate) and pub for structures, but we may want this in another issue
