### ISSUE TITLE
Benchmark number of ACIR opcodes per PR

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#3182]
### Problem

As surfaced in https://github.com/noir-lang/noir/issues/2720#issuecomment-1723507947, the CI does not currently check for changes in the number of ACVM opcodes generated by a set of benchmark Noir programs.

This leads to the situation where certain PRs could have bumped the number of ACVM opcodes (hence degrade compilation and proving speeds) of certain Noir keywords / language features, where core contributors:
- Would not have noticed until the community reports it
- Would have to go through a painful debugging process to identify the PR that caused the bump

### Happy Case

A set of benchmarking programs should be aligned upon, where the CI should then:
1. Automatically benchmark the number of ACIR opcodes generated by the programs on each PR
2. Highlight programs that came with considerable bumps (e.g. ≥+10%) in number of ACIR opcodes

### Additional Context

A significant portion of the work could be borrowed from Aztec's implementation: https://github.com/AztecProtocol/aztec-packages/pull/2733

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
Aztec's implementation of benchmarking doesn't work us as it's a very different usecase. I have a side-project to benchmark Noir programs which we could use with a couple of days of prioritisation.
