### ISSUE TITLE
Noir to reserve a list of global keywords

### ISSUE THREAD

**Issue by rahul-kothari** [noir-lang/noir#3192]
### Problem

Say I write a noir function `throw()`
I compile my aztec-nr contract and generate a typescript interface.....and the interface blows up because throw() is a TS keyword! 

From @kevaundray - It is also an issue for regular Noir programs -- in the private kernel circuit branch we have a ts-generator program for regular Noir functions which takes a Noir artifact in JSON and creates a typescript wrapper for the function it describes so you can call Noir functions from typescript

 we can reduce the inconvenience by reserving the popular ones and or put it as a warning in the linter  

### Happy Case

linter warns/compiler throws 

### Additional Context
https://aztecprotocol.slack.com/archives/C03P17YHVK8/p1697466151425219
### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
Gonna tentatively close this, feel free to reopen if you think its something that we should fix before 1.0
