### ISSUE TITLE
Add instructions to compile Nargo from specific Noir commits and branches

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#3196]
### Problem

The [current instructions](https://noir-lang.org/dev/getting_started/nargo_installation#option-3-install-via-nix) explains how to compile Nargo from the latest commit of Noir _master_ using Nix.

At times though users might want to compile Nargo from specific commits and/or branches instead, which the current instructions do not shine light on how-to.

### Happy Case

Describe how to compile Nargo from specific Noir commits and branches.

### Additional Context

Reference: https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-profile-install

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
Closing since we are no longer encouraging nix to be used for this, but just noirup which has a way to compile from a commit/branch in its docs

**Comment by Savio-Sou** [comment]
Thanks. Created https://github.com/noir-lang/noir/issues/4055 accordingly.
