### ISSUE TITLE
Clean up std out

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#321]
When running this test for example `noir_integration` we are printing out a lot of unnecessary information like the constraints. We can remove this and later on set a flag to enable it

**Comment by TomAFrench** [comment]
We can probably close this as we're we're down to 5 lines per test, e.g.

```
Running test "8_integration"
ACIR opcodes generated : 6010
Total Proving time (Rust + Static Lib) : 675398541ns ~ 0seconds
Proof successfully created
Proof saved to /tmp/p_and_v_tests.3UcCpXLqhFQZ/pp.proof
```

Timings are being removed in the next backend update so we're really down to 4.
