### ISSUE TITLE
`assert(false);` can hang the compiler

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#3210]
### Aim

`nargo execute` on
```rs
fn main() {
    assert(false);
}
```

### Expected Behavior

The program to run and issue a failed constraint error

### Bug

`nargo execute` hangs without terminating

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
I can't seem to replicate this anymore after making no changes to the example. Perhaps this is related to a network error or slow network when downloading the CRS?

**Comment by guipublic** [comment]
Closing as no-repro
