### ISSUE TITLE
Add a dummy proving system

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#324]
Regarding the slow CI times that I mentioned in the scrum. I think we can somewhat alleviate it for us by moving nargo out of the repo as I think the slow times are from building barretenberg_wrapper.

This is not simple yet though because the compiler needs some way to test if a circuit is satisfiable. The solution I have had in mind for a while is to create a dummy proof system that basically just checks the circuit and the proof is simply a 0 for false or 1 for true.

**Comment by guipublic** [comment]
I made a dummy proving system that always generate a proof and verify anything. It will be commit here: https://github.com/noir-lang/dummy_proof_system
In particular it does not check if the circuit is satisfiable, but I added this feature in PR #338 inside the partial witness generator. So now Noir always checks that a the circuit is satisfiable.
One caveat though is that if you use some custom gates (e.g pedersen), the dummy prover will not compute the correct witnesses so the circuit will not be satisfiable.
