### ISSUE TITLE
Add `nargo fmt` descriptions under `nargo --help`

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#3261]
### Problem

We are [documenting the availability of the `nargo fmt` command](https://github.com/noir-lang/noir/issues/3240) alongside the v0.17.0 stable release, i.e. it's going public.

But the command is currently not listed nor explained under `nargo --help`.

### Happy Case

Add `fmt` to the list of Nargo commands under `nargo --help`.

### Would you like to submit a PR for this Issue?

No

**Comment by Savio-Sou** [comment]
@f01dab1e would you like to take this up?

**Comment by nfurfaro** [comment]
Hello Noir team I love the work you're doing, keep it up!
I just opened a PR here to address this: #3328 
@f01dab1e sorry if you already have WIP on this; if that's the case please disregard my work :)
