### ISSUE TITLE
Expose core functionality (eliminate the need for the compiled service)

### ISSUE THREAD

**Issue by jonas089** [noir-lang/noir#3305]
### Problem

I understand that currently the only supported backend is [barretenberg](https://github.com/AztecProtocol/barretenberg).
However since there are plans to add support for bulletproofs, I would like to ask if prover and verifier logic will be exposed (public). This seems like a major improvement in terms of developer experience, since it'll enable the development of pure Rust services depending on  Noir's lib.

### Happy Case

Ideally it'd look similar to this:

use noir::backend
use noir::{Prover, Verifier}

let backend = backends::Bulletproofs
Prover.prove(..., )
Verifier.verify(...,)

where noir::backends is an enum of all supported pure Rust backends

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
I'm closing this as I'd say that this usecase is enabled by the dynamic backends project.
