### ISSUE TITLE
Make "Publish Nargo" workflow automatically release as a pre-release

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#3316]
### Problem

Currently when we manually publish using a workflow dispatch, it sets that release to be the official release whereas we want it to be a pre-release

### Happy Case

When we fill in the below workflow dispatch

<img width="409" alt="Screenshot 2023-10-27 at 13 41 38" src="https://github.com/noir-lang/noir/assets/37423678/a6826a8c-75ae-41d5-bb22-40d2766bb3c9">

It should release as a pre-release

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
This is now fixed
