### ISSUE TITLE
contract_library_method's should not require a pub return type

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#3344]
### Aim

The following code should compile, since the `contract_library_method` attribute specifies that the method will not be used as an entry point function.

```rust
contract Foo {
    #[contract_library_method]
    fn foo(x : u8) -> u8 {
        x
    }
}
```

### Expected Behavior

.

### Bug

Instead of it passing, we get:

```
error: missing pub keyword on return type of function foo2
   ┌─ main.nr:14:8
   │
14 │     fn foo(x : u8) -> u8 {
   │        ---- missing pub on return type
   │
   = The `pub` keyword is mandatory for the entry-point function return type because the verifier cannot retrieve private witness and thus the function will not be able to return a 'priv' value

Aborting due to 1 previous error
```

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
Also note that `return a 'priv' value` should probably be changed to private(?). `priv` comes from the fact that a long time ago, we used to have the `priv` keyword to mean a private value, instead of `let`

**Comment by jfecher** [comment]
> The following code should compile, since the contract_library_method attribute specifies that the method will not be used as an entry point function.

I still think we should remove `#[contract_library_method]`. No reason for it to exist when it causes bugs and users can place the functions outside the contract instead.
