### ISSUE TITLE
Nargo appears to hang

### ISSUE THREAD

**Issue by signorecello** [noir-lang/noir#3352]
### Aim

Trying to switch nargo versions with, I guess, different backend versions?

### Expected Behavior

I expect to get some kind of output somehow reporting what is happening.

### Bug

I get nothing, just a blank line. I assume it is downloading the backend, but in any case it should say something.

I was on Nargo 0.17.0, moved to 0.15.0 and got some backend errors so I ran `nargo backend uninstall acvm-backend-barretenberg`. And then `nargo prove`, nothing happens. Tried removing the `~/.nargo` folder, didn't work.

 This happened with @catmcgee as well while downloading Nargo v0.17.0

<img width="717" alt="Screenshot 2023-10-30 at 10 16 29" src="https://github.com/noir-lang/noir/assets/20129824/61f49c11-9814-41d5-a9c4-4697f2b03415">

### To Reproduce

1. Install latest nargo with `noirup` (0.17.0 at the time of writing)
2. Run `noirup -v 0.15.0`
3. Run `nargo backend unintall acvm-backend-barretenberg`
4. Run `nargo prove`

### Installation Method

Binary

### Nargo Version

nargo 0.15.0 (git version hash: 7a9983a7371fc99373e5f48dae3a297e9da09523, is dirty: false)

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
Likely duplicate of https://github.com/noir-lang/noir/issues/3210. The old issue was closed due to no repro but thisnew one shows others are running into the same issue as well. We can keep this new issue over the old one since it has more detail.

**Comment by signorecello** [comment]
an update here, deleting _only_ the `~/.nargo/backends` seems to have solved the problem, although removing `~/.nargo` didn't
