### ISSUE TITLE
Apostrophes are not permitted in test attributes

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#3372]
### Aim

```
#[test(should_fail_with = "this can't compile")]
fn test_speech_mark_gets_escaped() {
    assert_eq(0, 1, "this can't compile");
}
```
### Expected Behavior

It to compile the test

### Bug

We get "Malformed function attribute" due to the `'` (apostrophe) being used.

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by sambarnes** [comment]
not too important but i found this is also the case with some of these characters `.!?%^` so i assume its only spaces & alnum supported rn

```
error: Malformed function attribute
   ┌─ /home/sam/dev/noir-by-example/circuits/examples/assert/src/main.nr:18:1
   │
18 │ #[test(should_fail_with = "Must sum to three.")]
   │ ------------------------------------------------  test(should_fail_with = "Must sum to three.") is not a valid attribute
   │

Aborting due to 1 previous error
```

**Comment by kevaundray** [comment]
> not too important but i found this is also the case with some of these characters `.!?%^`
> 
> happy to pr for some of the common punctuation if yall are open to it
> 
> ```
> error: Malformed function attribute
>    ┌─ /home/sam/dev/noir-by-example/circuits/examples/assert/src/main.nr:18:1
>    │
> 18 │ #[test(should_fail_with = "Must sum to three.")]
>    │ ------------------------------------------------  test(should_fail_with = "Must sum to three.") is not a valid attribute
>    │
> 
> Aborting due to 1 previous error
> ```
> 
> edit: im on 0.19.4 currently

Great catch -- Please feel free to make a PR!
