### ISSUE TITLE
Add doc comments to `check_overflow` and `check_signed_overflow`

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#3381]
### Problem

These were introduced in this PR https://github.com/noir-lang/noir/pull/2713 . We should add doc comments to these functions

### Happy Case

.

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
Reopening - #3393 documents overflow in Noir, it does not document the `check_overflow` or `check_signed_overflow` functions within the compiler

**Comment by jfecher** [comment]
Reopening - #3393 documents overflow in Noir, it does not document the `check_overflow` or `check_signed_overflow` functions within the compiler
