### ISSUE TITLE
Define a default `ForeignCallHandler` for NoirJS

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#3388]
### Problem

NoirJS will currently throw an error whenever it encounters a foreign call opcode within a brillig block. This is because the default foreign call handler doesn't know how to process any of these.

This is problematic as `std::println` is a common function which may exist in a circuit if a user is debugging using JS. It would be nicer if we had a handler for this foreign call type so that JS users can print values from their circuits without needing to write it themselves.

### Happy Case

We should write a function in JS to properly format `std::println` calls and `console.log` them.

### Additional Context

https://github.com/noir-lang/noir/pull/3294#discussion_r1372093749

### Would you like to submit a PR for this Issue?

No

**Comment by signorecello** [comment]
Hey @Savio-Sou can we prioritise this a bit? People are hitting this problem a lot with stuff like RSA verification...

**Comment by Savio-Sou** [comment]
NoirJS now skips all `println` as per https://github.com/noir-lang/noir/pull/3764, so the function no longer blocks using programs with it with NoirJS.

A more proper implementation / custom foreign call handler that parses `println` into `console.log` is not available yet.

**Comment by signorecello** [comment]
I believe one can pass that as an oracle function @Savio-Sou so I'm closing this as completed for now
