### ISSUE TITLE
Add Auto-Formatting to noir_lsp 

### ISSUE THREAD

**Issue by f01dab1e** [noir-lang/noir#3400]
### Problem

To add auto-formatting to a language server protocol (LSP) implementation like "noir_lsp" for the "Save" functionality, you would typically want to incorporate a code formatting feature that triggers when a user saves a file. This is a common and useful feature in code editors to ensure that the code is consistently formatted. 

### Happy Case

-

### Additional Context

It seems that there are three events for this: OnTypeFormatting, Formatting, RangeFormatting

### Would you like to submit a PR for this Issue?

No

**Comment by Savio-Sou** [comment]
Duplicate of https://github.com/noir-lang/noir/issues/1581? (I.e. safe to close that?)

**Comment by f01dab1e** [comment]
Apologies for the noise. Couldn't locate the issue, but it seems we might need to open two more issues for two events: RangeFormatting and OnTypeFormatting.

**Comment by Savio-Sou** [comment]
Not at all and thank you for the context!

Will close that issue when the remaining two events are addressed in that case.
