### ISSUE TITLE
Expose `loadVerificationKey` in backend_barretenberg

### ISSUE THREAD

**Issue by signorecello** [noir-lang/noir#3403]
```[tasklist]
### Prerequisite
- [ ] https://github.com/noir-lang/noir/issues/3450
```

### Problem

Sometimes you'd want to actually load an external `verification_key` instead of initializing one from the circuit. For example, one could load it from the output json of `nargo compile --include-keys`.

Reason being that it's just faster than having to compute the vk in case you already have it, or you're storing it somewhere on the browser

### Happy Case

I want to be able to initialize my Backend instance with a precomputed VK. Example:

```js
const backend = new Barretenberg(circuit, { threads: 8, importVk: true })
```

This would call `acirLoadVerificationKey` and load it from the `circuit.verification_key` field in the compiled circuit.

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
Closing this as the only time it would make sense to use is when you're just verifying an externally produced proof, at which point you would use @michaeljklein's work on #3450
