### ISSUE TITLE
Split backend_barretenberg into prover and verifier classes

### ISSUE THREAD

**Issue by signorecello** [noir-lang/noir#3450]
### Problem

Once upon a time, in PR #3322 , there was this comment:

```
// The "real" workflow will involve a prover and a verifier on different systems.
 //
 // We cannot do this in our tests because they will panic with:
 // `unreachable`
 //
 // This happens when we we create a proof with one barretenberg instance and
 // try to verify it with another.
 //
 // If this bug is fixed, we can remove this test and split barretenberg into
 // a prover and verifier class to more accurately reflect what happens in production.
```

Since that PR fixed the bug, seems like we can tackle this now, just as @TomAFrench suggested

### Happy Case

`backend_barretenberg` has two classes, one for proving and one for verification

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
@kevaundray Is this something that we want to pursue? Seems like we're going to end up paying the fixed costs associated with bb.js twice for not much benefit.

**Comment by Savio-Sou** [comment]
Good to first have https://github.com/AztecProtocol/aztec-packages/issues/4188 tackled, if anyone is tackling this.
