### ISSUE TITLE
Example code is missing `pub` keywords in returns

### ISSUE THREAD

**Issue by microbecode** [noir-lang/noir#3452]
### Aim

Many of the examples in the documentation state something like this:
```
fn foo(x : Field, y : pub Field) -> Field {
    x + y
}
```

However, this syntax does not seem to be accepted (anymore). The return value should have the `pub` keyword.

Should this issue be listed as a 'bug' or an 'idea'? Dunno.

### Expected Behavior

I expect the example codes to work.

### Bug

Without the `pub` keyword I get error:
`The `pub` keyword is mandatory for the entry-point function return type because the verifier cannot retrieve private witness and thus the function will not be able to return a 'priv' value`

### To Reproduce

1.
2.
3.
4.

### Installation Method

Binary

### Nargo Version

nargo 0.17 86704bad3af19dd03634cbec0d697ff8159ed683

### Would you like to submit a PR for this Issue?

Yes

**Comment by microbecode** [comment]
Nothing? Nobody interested?

**Comment by TomAFrench** [comment]
Hi @microbecode. The example you've posted is actually valid Noir, `foo` is a non-entrypoint function so its return value isn't required to be public. This is only the case for the function `main` so I expect what's happened is you've renamed the function to `main` which adds the extra restriction. It looks like we don't explicitly flag up this requirement for `main` in the docs however so we could add a section on that.

I've removed the public argument to `foo` in #3643  to help avoid any confusion in future.
