### ISSUE TITLE
Support generic traits

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#3471]
### Problem

While generics on trait methods and trait impls on generic types are working, generics on traits directly are not supported yet.

### Happy Case

The following should execute successfully:
```rs
trait Into<Result> {
    fn into(self) -> Result;
}

impl Into<u32> for Field {
    fn into(self) -> u32 {
        self as u32
    }
}

impl Into<u64> for Field {
    fn into(self) -> u64 {
        self as u64
    }
}
```

### Would you like to submit a PR for this Issue?

No

**Comment by sirasistant** [comment]
This would be especially useful to create a serialize trait:
```rust
trait Serialize<N> {
    fn serialize() -> [Field; N];
}
```
