### ISSUE TITLE
Enable raw string support

### ISSUE THREAD

**Issue by grasshopper47** [noir-lang/noir#3475]
### Problem

To ease working with strings, implement `r#""#` raw-string operator from Rust.

### Happy Case

I can create raw strings like:

```rust
let my_string = r#"{ "my_key" : 1 }"#;
```

### Alternatives Considered

The only alternative is to escape the double-quote character, which leads to a very painful to read code.

### Additional Context

For example, in the context of tests for a JSON or REGEX parser, the tests would be unreadable.

### Would you like to submit a PR for this Issue?

No

**Comment by pczarn** [comment]
Starting work on this task. cc @kevaundray

**Comment by grasshopper47** [comment]
> Starting work on this task. cc @kevaundray

Great timing with a BETA release on the JSON parser lib! :grin:  

This is really needed to parse `"` instead of `'`, which is used now to avoid escaped quote in tests.

**Comment by pczarn** [comment]
@grasshopper47 where can I find the tests for said JSON parser?

**Comment by grasshopper47** [comment]
> @grasshopper47 where can I find the tests for said JSON parser?

https://github.com/RontoSOFT/noir-json-parser-tests

Sent you an invite
