### ISSUE TITLE
`wrapping_mul` incorrectly wraps values

### ISSUE THREAD

**Issue by tsujp** [noir-lang/noir#3482]
### Aim

Experimenting with `wrapping_mul` I noticed that:

```rust
let foo: u8 = wrapping_mul(200, 5);
println(foo);
``` 

Outputs:

```
0xe8
```

Except that should be `0xeb` no?

It looks like it's wrapping by `2 ** 8` (256) when an 8-bit unsigned integer's maximum value is `(2 ** 8) - 1` (255).

```
1000 mod 256 = 232
1000 mod 255 = 235
```

### Expected Behavior

I'd expect `wrapping_mul` to wrap by the range of _values_ its operand can represent and not simply `2 ** N` where `N` is the bit-width of its operand.

### Bug

As described in aim.

### To Reproduce

1. Run code from `aim`.
2. Observe output.

### Installation Method

Compiled from source

### Nargo Version

nargo version = 0.19.0 noirc version = 0.19.0+ff96ba441689e1e04333be0df833b963232d9554 (git version hash: ff96ba441689e1e04333be0df833b963232d9554, is dirty: false)

### Would you like to submit a PR for this Issue?

No

**Comment by guipublic** [comment]
The current behaviour is correct, you can check that rust does the same:
`let foo = 200_u8.wrapping_mul(5);`
