### ISSUE TITLE
Bad CPU type in executable error

### ISSUE THREAD

**Issue by workingdoge** [noir-lang/noir#3483]
### Aim

Following the hello world tutorial, I'm unable to run `nargo verify`

### Expected Behavior

complete the tutorial

### Bug

```shell
❯ nargo verify
Could not determine version of `acvm-backend-barretenberg`. Downloading expected version...
Bad CPU type in executable (os error 86)
```

same error using version 0.17.0, using apple silicon

### Installation Method

Binary

### Nargo Version

nargo version = 0.19.2 (git commit:  47f0130c0d154f1b70eb23f376783beb3f23ad72)

### Would you like to submit a PR for this Issue?

Maybe

**Comment by Savio-Sou** [comment]
This is likely due to the x86 version of barretenberg is being fetched, rather than the ARM one.

```
% ~/.nargo/backends/acvm-backend-barretenberg/backend_binary
backend_binary: Mach-O 64-bit executable x86_64
```

Users could install Rosetta to circumvent the issue until this is fixed.

(Thank you @Maddiaa0 for providing the additional context.)

**Comment by kevaundray** [comment]
Closing this in favour of https://github.com/AztecProtocol/aztec-packages/issues/2518 and https://github.com/AztecProtocol/aztec-packages/issues/1904
