### ISSUE TITLE
nargo compile --include-keys doesn't include keys

### ISSUE THREAD

**Issue by signorecello** [noir-lang/noir#3488]
### Aim

Tried to include verification keys in the compilation of my circuit

### Expected Behavior

For keys to show up in the json file

### Bug

They don't show in the json file

### To Reproduce

1. Install Nargo 0.19.2
2. Run nargo compile --include-keys
3. Confirm that the keys are absent

### Installation Method

Binary

### Nargo Version

nargo version = 0.19.2 noirc version = 0.19.2+47f0130c0d154f1b70eb23f376783beb3f23ad72 (git version hash: 47f0130c0d154f1b70eb23f376783beb3f23ad72, is dirty: false)

### Would you like to submit a PR for this Issue?

No

**Comment by mikirov** [comment]
I ran into this issue trying to use `nargo compile --package <package_name> --include-keys`. Not sure if it's related. Nargo version 0.19.4

**Comment by guipublic** [comment]
In fact keys are not part of the artefacts anymore, cf. #2280 
I will remove the include-keys option then.
