### ISSUE TITLE
feat: Expose Profile information in vscode

### ISSUE THREAD

**Issue by kobyhallx** [noir-lang/noir#3501]
As a Developer
I would like to be able to see opcodes information in my ide (vscode)
so that I can form my code accordingly.

**Comment by kobyhallx** [comment]
<img width="713" alt="image" src="https://github.com/noir-lang/noir/assets/102518238/efded9c9-b6b1-4809-ae76-cbafae26d477">

**Comment by kevaundray** [comment]
Closing as completed
