### ISSUE TITLE
Consider how to incorporate Backend relevant information in wider context

### ISSUE THREAD

**Issue by kobyhallx** [noir-lang/noir#3504]
### Problem

Currently we rely on backend to deliver information about supported opcodes, etc. This is suboptimal as 
1. this information is not always relevant, 
2. we may not need it in dynamic form (ie. interacting with backend)
3. we can deliver it through other means 

### Happy Case

Declare supported opcodes information in static way (ie. through Nargo.toml.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
We no longer rely on the backend to tell us the supported opcodes, going to close this unless it becomes relevant again
