### ISSUE TITLE
Unclear parser error when using a type where a pattern was expected

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#351]
In the following code:

```rs
fn main(a: [Field; 3]) {
    let i = 1;

    // Using a const variable as a parameter should not make it non-const
    let i2 = foo(i);
    let elem1 = a[i];
}
```
We fail with a parser error because the lexer issues incorrect tokens. Namely for `i2` it instead issues a `Int(2)` token, skipping the `i` entirely.

Edit: The above is slightly incorrect, it issues a `IntType(2)` token because `i2` is an integer type by design. The real issue is the unclear parser error issued to the user which does not indicate this:
```
error: Expected a pattern but found i2
  ┌─ /Users/jakefecher/Code/Noir/noir/crates/nargo/tests/test_data/1_mul/src/main.nr:7:9
  │
7 │     let i2 = foo(i);
  │         --

error: Expected a = but found (
  ┌─ /Users/jakefecher/Code/Noir/noir/crates/nargo/tests/test_data/1_mul/src/main.nr:7:17
  │
7 │     let i2 = foo(i);
  │                 -
```

**Comment by TomAFrench** [comment]
Is this fixed? I get the lexer issuing a `Token::IntType(IntType::Signed(2))` for `i2` which is what I would expect in this scenario.

**Comment by jfecher** [comment]
This has not been fixed but also has not been tested since or for any other examples

**Comment by jfecher** [comment]
Looks like the real issue here is that `i2` in this example is not a valid identifier by design: it is a keyword for a 2-bit signed integer type. The relevant errors that the parser issues are (ignoring the unused variable errors):
```
error: Expected a pattern but found i2
  ┌─ /Users/jakefecher/Code/Noir/noir/crates/nargo/tests/test_data/1_mul/src/main.nr:7:9
  │
7 │     let i2 = foo(i);
  │         --

error: Expected a = but found (
  ┌─ /Users/jakefecher/Code/Noir/noir/crates/nargo/tests/test_data/1_mul/src/main.nr:7:17
  │
7 │     let i2 = foo(i);
  │                 -
```
Suggestions:
- The first error should attempt to specify why the invalid portion is not a valid pattern: "expected a pattern but found a type - i2"
- The second error seems to have skipped the `=` token when trying to recover from the previous token. This can likely be fixed.

**Comment by TomAFrench** [comment]
Ah, looks like we talked passed each other slightly.

I thought it was understood that the lexer should treat `i2` as a type, but you were seeing a `2` literal being emitted. The lexer is parsing the function "correctly" but the  errors due to invalid input.

**Comment by kevaundray** [comment]
@jfecher what is the status of this issue?

**Comment by jfecher** [comment]
I haven't worked on it since - I considered it somewhat lower priority since syntax highlighting for noir should ideally highlight `i2` as a type, alluding to the error. The parse error should be improved anyway, though there are a lot of instances we can improve parsing errors in general for.

**Comment by kevaundray** [comment]
@f01dab1e feel free to take a look at this issue
