### ISSUE TITLE
Error message mentions code in a separate file

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#3510]
### Aim

Writing code with a missing struct field

### Expected Behavior

An error message explaining the field is missing and (optional) a link to the original struct definition.

### Bug

In the actual error the location for "BoundedVec" is correct but not meant for the file the error originated in. It was actually defined on the first line in `bounded_vec.nr` (nor is it from the NewContractData being imported on the cited line).
```
error: missing field: empty_value
   ┌─ /../noir-protocol-circuits/src/crates/types/src/utils/arrays.nr:1:9
   │
 1 │ use crate::abis::new_contract_data::NewContractData;
   │         ---------- BoundedVec defined here
   ·
16 │     BoundedVec { storage: array, len }
   │     ----------
   │
```

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@f01dab1e if you have time, can you take a look at this?

**Comment by f01dab1e** [comment]
I'll do it tomorrow

**Comment by kevaundray** [comment]
@jfecher has this been fixed?
