### ISSUE TITLE
Investigate whether we can pull out the aztec macros into a top level directory

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#3517]
### Problem

Currently the aztec macros are embedded in the compiler and the lack of API means that it has access to all of the internals

### Happy Case

We investigate the effort needed to pull out the aztec macros and have it as a seperate modeule using a well defined interface exposed by the compiler

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
Closed by https://github.com/noir-lang/noir/pull/3578
