### ISSUE TITLE
Add `nargo fmt --check` functionality

### ISSUE THREAD

**Issue by benesjan** [noir-lang/noir#3520]
### Problem

We would like to integrate `nargo fmt`  in CI in aztec-packages but to do that we would need to run `nargo fmt` in "check-only mode" (not modifying the files and just throwing instead).

### Happy Case

`nargo fmt --check` exits with exit code 1 when formatting issues are spotted.

### Would you like to submit a PR for this Issue?

No

### Support Needs

_No response_</div>

**Comment by kevaundray** [comment]
@f01dab1e can you take this on?
