### ISSUE TITLE
Tracking issue: nargo format on aztec-packages

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#3521]
This is a tracking issue for the issues that arose when trying to implement `nargo fmt` into aztec-packages.

The PR is [here](https://github.com/AztecProtocol/aztec-packages/pull/3372)

**Comment by LHerskind** [comment]
Adding some of the issues here for clarity:

## Deleting commented lines
In `counter_contract/src/main.nr` I have this case where the end comment is just deleted, which messes with the generated docs.
![image](https://github.com/noir-lang/noir/assets/16536249/54777294-a87c-4826-98aa-7f7e94ae042d)
This happens a few more places when there is closing `}` on both sides of the comment.
Also in:
- `yarn-project/noir-contracts/src/contracts/schnorr_hardcoded_account_contract/src/main.nr`
- 

## Inconsistent linebreak before `{` in function defs
In `docs_example/src/main.nr` we have this linebreak which looks a little weird:
![image](https://github.com/noir-lang/noir/assets/16536249/86a90334-1a9b-4f5e-a17a-89f1ab6c0d1d)
Also happens in:
- `yarn-project/noir-contracts/src/contracts/test_contract/src/main.nr`
- More places 
This might just be my personal pref


If you look at https://github.com/AztecProtocol/aztec-packages/pull/3372, running `nargo fmt` on top of it will delete comments

**Comment by f01dab1e** [comment]
@LHerskind, Seems like there's a slightly different behavior in the master right now. Can you check?

**Comment by f01dab1e** [comment]
Ran it on master, seems like these issues are not present:

* https://github.com/f01dab1e/aztec-packages/blob/1f6d194c2ed25cdafe93bb1af684aa05f05596b5/yarn-project/noir-contracts/src/contracts/counter_contract/src/main.nr#L68-L73

* https://github.com/f01dab1e/aztec-packages/blob/1f6d194c2ed25cdafe93bb1af684aa05f05596b5/yarn-project/noir-contracts/src/contracts/docs_example_contract/src/main.nr#L228-L229

**Comment by LHerskind** [comment]
Still got issues on some of the mains for the `compute_nullifier...` doc line being removed, not sure why.

**Comment by kevaundray** [comment]
closing this and we can open up another issue with specifics, if any issues persist
