### ISSUE TITLE
Swap "Examples" and "NoirJS/Guides" sections in Docs with a link to noir-examples

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#3551]
### Problem

In the Examples section, we currently have one very outdated [Merkle Proof Membership](https://noir-lang.org/examples/merkle-proof) example.

Meanwhile in the NoirJS/Guides section, we also have one easily-outdatable [End-to-end](https://noir-lang.org/noir_js/getting_started/tiny_noir_app) example.

Writing, maintaining and documenting examples at two different places (in noir-examples and in Noir Docs) is error-prone, labor-consuming and perhaps unnecessary.

### Happy Case

1. Remove the Examples and NoirJS/Guides sections
2. Add a [link](https://docusaurus.io/docs/sidebar/items#sidebar-item-link) to [noir-examples](https://github.com/noir-lang/noir-examples/) in the sidebar

### Alternatives Considered

- Leave everything as is, or
- Just remove the sections, but not add the link

### Additional Context

Personal recommendation: external links in general should live as bottommost items on the sidebar to minimize distractions.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@Savio-Sou / @signorecello what is the status of this issue?

**Comment by Savio-Sou** [comment]
@signorecello clarified that noir-examples are not aimed to be fully up-to-date at all times:
> *https://github.com/noir-lang/noir/pull/3711#issuecomment-1851075588:*
> 
> It is not meant to be up-to-date, unless breaking changes show up. By trusting the community to flag when some change goes undetected by devrel (which inevitably happens), we can keep them fairly up-to-date with the latest syntax without depleting all of our time.
So the happy case suggested in this issue does not necessarily address the problem.

As of https://github.com/noir-lang/noir/pull/3711, the examples were moved into "How To Guides" and "Tutorials" sections that are clearly separated from language sections in the sidebar. Reader confusions regarding outdated guides in docs could have been lowered since.

Given such, closing this as not planned for now.

If outdated guides in our docs as is are later found confusing / unhelpful still, we can consider proper approaches to update (e.g. binding examples to CI) or remove them.
