### ISSUE TITLE
Proof verification fails with a simple example

### ISSUE THREAD

**Issue by guipublic** [noir-lang/noir#358]
Noir is not able to verify a proof for this program:
```
fn main(mut x: Field, y: Field) {
     let t = x+1;
    let r2= t*t;
    let r1 = y*t;
constrain r2*t == r1;
}
```
With the prover.toml:
x = "1"
y = "4"

n.b 
- it works if you use x=0 and t=x+2
- the generated circuit and witnesses are correct
- this one gate is failing verification:     1x1*x1 + 2x1 + -1x4 + 1 = 0,

**Comment by kevaundray** [comment]
Tracking issue: https://github.com/noir-lang/noir/issues/1252
