### ISSUE TITLE
`#[contract_library_function]` allows `pub` parameters

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#3632]
### Aim

```rs
contract Foo {
    #[contract_library_method]
    fn foo(x : pub u8) -> u8 {
        x
    }
}
```

### Expected Behavior

An error explaining `pub` is not allowed on non-entry point functions.

### Bug

The function is accepted, except for a `pub` return type error related to https://github.com/noir-lang/noir/issues/3344

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
@guipublic what is the status of this issue?

**Comment by guipublic** [comment]
The issue  is resolved so I close it.
