### ISSUE TITLE
Deserialization to Circuit Results in Invalid Hex

### ISSUE THREAD

**Issue by VrushankGunjur** [noir-lang/noir#3641]
### Aim

Tried to use [https://github.com/visoftsolutions/noir_rs](https://github.com/visoftsolutions/noir_rs) to generate a proof for a circuit and verify it. This works fine for the test provided, but bugs arised when I tried proving more complex circuits.

### Expected Behavior

Running the [code](https://github.com/VrushankGunjur/noir_rust_test) should result in clean verify/prove. Specifically, the circuit a proof is being generated for uses the Noir standard library's BabyJubJub curve implementation to decrypt three elements under the Elgamal encryption scheme.

### Bug

When I tried generating the proof for a more complex circuit (that proves/verifies just fine in nargo cli + solidity verifier), the bincode::deserialize to type Circuit resulted in

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Invalid hex for FieldElement: \u{6}\0\0"'`

Stepping through the debugger, this issue arises from the following call: 

` bincode::deserialize(&acir_buffer_uncompressed).map_err(|e| e.to_string())?;`

The input bytecode is taken directly from the JSON generated by nargo compile

### To Reproduce

1. Write Noir code to verify three decryptions under Elgamal encryption, compile the circuit, and get the bytecode
2. Run the 'main' file at https://github.com/VrushankGunjur/noir_rust_test (the bytecode is included, as well as all the necessary inputs)

### Installation Method

Binary

### Nargo Version

0.19.2

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
Hey,

I think that this is expected since  https://github.com/visoftsolutions/noir_rs does not use the latest version of acvm. Currently it is using a forked version so serialization is not guaranteed to match.

The best plan of action would likely be to ask the maintainer to update the fork to the latest version
