### ISSUE TITLE
Allow specifying the hash function to be used in EDDSA signature verification.

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#3642]
### Problem

Looking at https://github.com/iden3/circomlib/tree/master we can see that they expose multiple different flavours of EDDSA with different hash functions used. If Noir users wish to use a different hash function in their EDDSA algorithm however they would need to vendor the entire EDDSA verification algorithm.

### Happy Case

We should expose a generic EDDSA verification function from the stdlib which allows a custom hash function to be used, `eddsa_verify`.

We can also provide some functions similar to the current `eddsa_poseidon_verify` which specify common hash functions is to be used.

### Alternatives Considered

We could accept this limitation and perform these changes in an external library in pursuit of #1258 

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
This can be done easier now that we have traits
