### ISSUE TITLE
Setting an unsigned type to negative values 

### ISSUE THREAD

**Issue by grasshopper47** [noir-lang/noir#3649]
### Aim

To be able to write:

```rust
let var : u8 = -1; // or global
```

### Expected Behavior

That both examples compile and work in the _exact same_ way.

### Bug

Instead, a compilation error is thrown: `error: u8 cannot be used in a unary operation`

Yet doing:

```rust
let var = -1 as u8;
```

compiles and executes as expected with the previous code.

### To Reproduce

See notes above

### Installation Method

None

### Nargo Version

nargo 0.19.4

### Would you like to submit a PR for this Issue?

No

**Comment by guipublic** [comment]
The first example works as expected because -1 is not a valid u8 number. Rust behaves similarly.

The second example does not work either because execution is failing. However it compiles fine as you indicate.
So the issue here is that the second example compiles.
