### ISSUE TITLE
LSP goto def should error when Ident at Location could not resolve

### ISSUE THREAD

**Issue by kobyhallx** [noir-lang/noir#3659]
### Problem

As we gradually implement LSP and adding features we currently return `None` when something is not implemented for goto definitions feature of LSP.

### Happy Case

This should not happen though - we should always be able to resolve Ident to Location.

### Would you like to submit a PR for this Issue?

No

**Comment by kevaundray** [comment]
Closing this issue would involve figuring out which cases we return None for and whether its a bug in the compiler perhaps

**Comment by asterite** [comment]
I don't think this issue is valid anymore as the code for this changed a lot and I can't find a place where something is returning `None`.
