### ISSUE TITLE
Tests pass but execute and prove fail

### ISSUE THREAD

**Issue by ppoliani** [noir-lang/noir#3701]
### Aim

I've written this circuit [here](https://github.com/Apocentre/zk-auth). Running the main with `nargo test` completes successfully with all assertions passing. However, when I run `nargo prove` the assertions fail. I have double-checked the input values and they are exactly the same.

I've also tried to `nargo execute` but the result is same.

### Expected Behavior

Nargo test and nargo prove (and execute) should have the same result.

### Bug

I cannot create a proof for a circuit which all test pass.

### To Reproduce

1. `git clone https://github.com/Apocentre/zk-auth`
2. `nargo test` passes but `nargo prove` or `nargo execute` fails

### Installation Method

Binary

### Nargo Version

 0.19.3

### Would you like to submit a PR for this Issue?

No

**Comment by signorecello** [comment]
Hey @ppoliani wondering if you could help us by submitting a smaller minimal reproducible example? That would make it much easier to debug so it could be prioritized that way

**Comment by TomAFrench** [comment]
Closing as a suitable repro was not provided.
