### ISSUE TITLE
aztec_noir: (constrained) functions without macro are loosing their first arg when compiling

### ISSUE THREAD

**Issue by drgorillamd** [noir-lang/noir#3712]
### Aim

Omit to declare a public/private macro before a constrained function in an Aztec contract, the first argument of the function is then dropped when compiling (I guess noirc removes `context` for every "non-unconstrained" function, even if no macro inlines it before).

### Expected Behavior

Have the function with the correct signature (ie not loosing the first argument)

### Bug

Snippet:
```Rust
    fn my_fancy_function(foo: Field, bar: [Field; 5]) {}

    #[aztec(public)]
    fn my_fancy_function_public(foo: Field, bar: [Field; 5]) {}

    #[aztec(private)]
    fn my_fancy_function_private(foo: Field, bar: [Field; 5]) {}

    unconstrained fn my_fancy_function_unconstrained(foo: Field, bar: [Field; 5]) {}
```
Resulting target json (`aztec-cli compile .` with noir v0.18.0-aztec.5) (only the relevant part):
```shell
(...)
      "name": "my_fancy_function",
      "functionType": "secret",
      "isInternal": false,
      "parameters": [
        {
          "name": "bar",
          "type": {
            "kind": "array",
            "length": 5,
            "type": {
              "kind": "field"
            }
          },
          "visibility": "private"
        }
      ],
(...)
```

### To Reproduce

Run `aztec-cli compile .` with the above snippet, then use `aztec-cli inspect-contract PathToJson`

### Installation Method

Binary

### Nargo Version

v0.18.0-aztec.5

### Would you like to submit a PR for this Issue?

Maybe

### Support Needs

Happy to give it a try if pointed in the right direction!

**Comment by TomAFrench** [comment]
Looks like this is an issue in how the aztec compiler handled the artifacts rather than Noir.

https://github.com/AztecProtocol/aztec-packages/blob/1696a8fdafd359c58229d27943a05ec3177d3348/yarn-project/noir-compiler/src/contract-interface-gen/abi.ts#L22-L44
