### ISSUE TITLE
Add for-each loop for array elements

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#375]
Currently noir only supports a ranged for loop with integer start and end indices such as the following:
```rs
let start = 0;
let end = 5;
for i in start .. end {
    ...
}
```
(where `i`, `start`, and `end` must all be `const`). Expanding on this, we could also support a special version for arrays:
```rs
for elem in array {
    ...
}
```
Here neither `elem` nor `array` need be const since the actual indices would be known either way.

### Motivation

This feature would not increase noir's expressiveness since the same can always be achieved with indices and extracting array elements manually. It would increase ergonomics somewhat and decrease the barrier for those coming to noir from other languages like rust which allow for-each loops over arrays themselves. 

### Implementation strategy

The easiest way to implement this would likely be as syntactic sugar. For example, the above loop could be automatically expanded into:

```rs
for i in 0 .. std::array::len(array) {
    let elem = array[i];
    ...
}
```
Where `i` is a fresh variable.

**Comment by guipublic** [comment]
This would be very nice indeed

**Comment by TomAFrench** [comment]
I've implemented this as a learning exercise as my experience with compilers is pretty much nil. Can share a PR this weekend with a rough version and questions.
