### ISSUE TITLE
Helpful error message when `fn` is missing

### ISSUE THREAD

**Issue by rahul-kothari** [noir-lang/noir#3768]
### Aim

It would be nice to have a specific error message when using this (wrong) syntax:
```
 #[aztec(private)]
 constructor() {
     (...)
 }
```

Above has the `fn` keyword missing and it throws with a generic parsing error (Expected an end of input but found contract)
https://github.com/AztecProtocol/aztec-packages/issues/3630

**Comment by signorecello** [comment]
Seems like this happen anytime there is a error. Things like missed `,`, `:` instead of `::`... Any parsing error will bring this unhelpful message
