### ISSUE TITLE
Implement `impl Trait` for function parameters

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#3771]
### Problem

Using traits can be somewhat cumbersome when it requires extra ceremony just for a single parameter:
```rs
fn log<T>(x: T) where T: ToString {
    let string = x.to_string();
    println(f"log: {s}");
}
```

### Happy Case

Adopt rust's `impl Trait` syntax for parameters as well (Noir already mostly supports this for return types):
```rs
fn log(x: impl ToString) {
    let string = x.to_string();
    println(f"log: {s}");
}
```

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
Adding "good first issue" here. Whenever we see `impl Trait` in a parameter position we can desugar it to an extra generic and constraint on the function. E.g:
```rs
fn log(x: impl ToString) {
    let string = x.to_string();
    println(f"log: {s}");
}
```
Would get desugared directly to:
```rs
fn log<T>(x: T) where T: ToString {
    let string = x.to_string();
    println(f"log: {s}");
}
```
This'd likely be done during name resolution when we can cleanly create fresh type variables that are guaranteed not to be in scope elsewhere.

**Comment by michaeljklein** [comment]
Newer version of this issue here that's part of an Epic: https://github.com/noir-lang/noir/issues/4540
