### ISSUE TITLE
'internal error: entered unreachable code: Cannot flatten a dynamic array' when adding if

### ISSUE THREAD

**Issue by 0xShaito** [noir-lang/noir#3817]
### Aim

Sometimes adding some if statements leads to more checks needed on notes or it fails compiling with:

'internal error: entered unreachable code: Cannot flatten a dynamic array'.

This is fixed by utilizing the Aztec note ONLY inside an if statement that checks that the note exists:

Works:
```js
    let options = NoteGetterOptions::new().select(1, from.address).set_limit(1);
    let note = stored_set.get_notes(options)[0];
    if (note .is_some()) {
        stored_set.remove(note.unwrap_unchecked()); 
    }
```

Doesn't work:

```js
    let options = NoteGetterOptions::new().select(1, from.address).set_limit(1);
    let note = stored_set.get_notes(options)[0];
    assert(note.is_some());
    stored_set.remove(note.unwrap_unchecked()); 
```

### Expected Behavior

Asserting that the note exists should be the same as using it inside an if statement. 

Even if the note is not asserted, the error should be more expressive into what the actual issue is.

### Bug

Code:

https://github.com/drgorillamd/aztec-big-gist/tree/feat/array-in-struct/src

Error:

'internal error: entered unreachable code: Cannot flatten a dynamic array'

This bug only happens when adding if statements. In the code sent, removing the if from the start of the function makes the contract compile:

```js
        if (from.address != context.msg_sender()) { // commenting out this fixes compilation
            assert_current_call_valid_authwit(&mut context, from);
        } 
```

### To Reproduce

Repo with the reproduction: https://github.com/drgorillamd/aztec-big-gist/tree/feat/array-in-struct/src

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by vezenovm** [comment]
Would you be able to provide a smaller more up-to-date example? We recently had a [fix](https://github.com/noir-lang/noir/pull/4364) that I think is related to this issue but the project is using compiler version `0.18.0` and old versions of `aztec-nr` so it is difficult to reproduce.

**Comment by vezenovm** [comment]
@drgorillamd Thank you for the update! I'm assuming you are using `0.24.0` of `aztec-packages`. The recent fix has not yet been released but it is on master. I can successfully compile the supplied contract with the fix on master. Going to close this issue as it has been fixed but please do re-open it if after the release you are still running into issues.
