### ISSUE TITLE
Profile and optimize the compiler

### ISSUE THREAD

**Issue by pczarn** [noir-lang/noir#3820]
### Problem

`Noirc` is slow when compiling rsa and other programs.

### Happy Case

1. Profile
2. Optimize
3. ???
4. profit

### Alternatives Considered

No alternatives - just profile before optimizing

### Would you like to submit a PR for this Issue?

Yes

### Support Needs

Ideas are welcome

**Comment by pczarn** [comment]
Initial profiling - just debug and not entire compiler run - shows that likely there is plenty of time spent in `Instruction::simplify`

![2023-12-15-153633_628x1058_scrot](https://github.com/noir-lang/noir/assets/3356767/a065c60d-4c2f-4643-87b5-fcf9e4c90281)

**Comment by pczarn** [comment]
I am using valgrind accompanied by the tools callgrind and kcachegrind and unfortunately a debug build of nargo-cli

**Comment by TomAFrench** [comment]
We hugely improved compilation times for noir-rsa in #3815, I'd recommend installing the latest nightly (should be out in 10mins or so)

**Comment by pczarn** [comment]
Okay. Is anyone else still working on improving compilation times?

**Comment by TomAFrench** [comment]
Yep, we're going to keep an eye on compilation times and we're going to need better profiling, etc. going forwards to help with this.
