### ISSUE TITLE
Change constrain key word to assert

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#384]

**Comment by kevaundray** [comment]
If we are going to do this change, it should be sooner rather than later.

My suggestion is to allow constrain and assert for about a year, but change all documentation to use assert. 

This way existing programs are not broken and newer programs are discouraged from using it. A lint would also be good here, to notify existing programs that it is being phased out.

Cc @jfecher @guipublic @vezenovm

**Comment by jfecher** [comment]
I am fine with `constrain` or `assert`. The later would be more familiar to those coming from other languages, but perhaps `constrain` is clearer for those already in the ZKPL space?

The change is fairly trivial to make if we do want to change to `assert`. I'll also suggest we can issue a deprecation warning for `constrain` while in this intermediate period of allowing both.

**Comment by kevaundray** [comment]
pinging @sirasistant for visibility
