### ISSUE TITLE
invalid boolean value

### ISSUE THREAD

**Issue by jonas089** [noir-lang/noir#3852]
### Aim

fn main(x : Field, y : pub Field) {
    assert(x != y);
}

This used to work fine with nargo V0.15.0, but all of a sudden i'm getting a 'invalid boolean' error when trying to prove / verify.

### Expected Behavior

evaluate assertion

### Bug

see "Aim"

### To Reproduce

1. use nargo v 0.15.0 together with my circuit
2. add x = 1 and y = 2 to the Prover
3. run cargo check && cargo prove
4. see output ("invalid boolean" error)

### Installation Method

Binary

### Would you like to submit a PR for this Issue?

No

**Comment by jonas089** [comment]
I tried with the latest version of the nargo binary and it worked. This is odd since the behavior of the old binary has changed for no apparent reason

**Comment by kevaundray** [comment]
0.15 is quite an old version which could have possibly contained a bug. Since it works on the latest stable version, I'll close this issue
