### ISSUE TITLE
Create Poseidon hash function

### ISSUE THREAD

**Issue by critesjosh** [noir-lang/noir#387]
# Problem

Poseidon is a common hash function when writing circuits--add it to the Noir stdlib.

# Solution

Write the Poseidon hash function in Noir.

# Additional context

We will consider giving a [grant](https://www.notion.so/aztecnetwork/6c4d76769a714cbea9fc959a60417b05?v=12c257164ff94a68945a44e4bab54bf4) to do this.

**Comment by critesjosh** [comment]
@kevaundray can you add the noir-stdlib label to this?

**Comment by vaibhavgeek** [comment]
Update: Awaiting vectors / Multi dimensional arrays to be implemented in Noir before further proceeding with the same, basic implementation is completed.

**Comment by vezenovm** [comment]
> Update: Awaiting vectors / Multi dimensional arrays to be implemented in Noir before further proceeding with the same, basic implementation is completed.
> 
> Work currently on standby as communicated with @vezenovm.

@vaibhavgeek From discussions with the team I cannot give an exact timeline when this will be added. This isn't currently a priority for us as multi dimensional arrays can be mocked using 1D arrays at the moment.
