### ISSUE TITLE
Create Keccak hash function

### ISSUE THREAD

**Issue by critesjosh** [noir-lang/noir#388]
# Problem

Keccack is a common hash function when writing circuits--add it to the Noir stdlib.

# Solution

Write the Keccack hash function in Noir.

# Additional context

We will consider giving a [grant](https://www.notion.so/aztecnetwork/6c4d76769a714cbea9fc959a60417b05?v=12c257164ff94a68945a44e4bab54bf4) to do this.

**Comment by TomAFrench** [comment]
FYI for anyone interested in this bounty/grant, I've got an almost complete implementation of the keccak256 algorithm in Noir. I  I could share code to save time implementing the Poseidon hash function (#387) however.

**Comment by AmanGotchuParadigm** [comment]
Hey @TomAFrench! Any status update on this? Would love to pair or help in any way to push it through!

**Comment by TomAFrench** [comment]
Hey @AmanGotchuParadigm, thanks for the offer.

To be honest the majority of the issues I'm running into have been internal to Noir/Nargo and I've been working with the Aztec team to address these. As it stands I'm not sure that adding another engineer will help unblock things.

The code is in a pretty much complete state with all that's remaining:
1. Build out the test suite for internal functions + fix anything that comes up.
2. Get overall circuit compiling once Nargo allows.
3. Optimise for gate count

There's definitely opportunities for optimisation inside keccakf but I want to build out the test suite first to give a "reference implementation".

The repo is public here: https://github.com/TomAFrench/keccak256-noir

**Comment by TomAFrench** [comment]
Closing this as keccak256 is now supported natively in ACVM
