### ISSUE TITLE
Remove `SecondaryAttribute::Event`

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#3885]
### Problem

The enum variant `SecondaryAttribute::Event` is only used in the aztec_macros, we can remove this and use the `is_custom_attribute` function

### Happy Case

.

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
We still have the concept of an event in the main compiler however so it wouldn't be a clean removal.

https://github.com/noir-lang/noir/blob/57eae42080d6a928e8010c6bc77489964a5777ef/compiler/noirc_frontend/src/hir/def_map/mod.rs#L195-L205

**Comment by kevaundray** [comment]
> We still have the concept of an event in the main compiler however so it wouldn't be a clean removal.
> 
> https://github.com/noir-lang/noir/blob/57eae42080d6a928e8010c6bc77489964a5777ef/compiler/noirc_frontend/src/hir/def_map/mod.rs#L195-L205

Yeah I think we'd need to have the concept of a primary attribute that is able to put things in the abi, ie `#[abi(event)]`

**Comment by asterite** [comment]
The attribute doesn't exist anymore so this issue can be closed.
