### ISSUE TITLE
Create SHA512 hash function

### ISSUE THREAD

**Issue by critesjosh** [noir-lang/noir#389]
# Problem

SHA512 is a common hash function when writing circuits--add it to the Noir stdlib.

# Solution

Write the SHA512 hash function in Noir.

# Additional context

We will consider giving a [grant](https://www.notion.so/aztecnetwork/6c4d76769a714cbea9fc959a60417b05?v=12c257164ff94a68945a44e4bab54bf4) to do this.

**Comment by okuyiga** [comment]
I'm interested in working on this. Who should I get in touch with?

**Comment by critesjosh** [comment]
> I'm interested in working on this. Who should I get in touch with?

Awesome! First step is to apply here and we'll be in touch.

https://airtable.com/shr7NALhaRGc6Ouhk
