### ISSUE TITLE
Remove aggregation objects from recursion opcode

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#3908]
### Problem

Once https://github.com/AztecProtocol/aztec-packages/pull/3765/files is merged, the nested_aggregation_object will no longe be needed in the ACIR recursion opcode. 

This along with the input_aggregation_object and the output_aggregation_object can now be safely removed from ACIR

### Happy Case

This is a breaking change. For now, all of our Noir examples should just set these objects to zeroes.

### Would you like to submit a PR for this Issue?

No

**Comment by Savio-Sou** [comment]
@vezenovm / @kevaundray grateful if you could link the Noir PR mirrored from aztec-packages that closes this Issue.
