### ISSUE TITLE
Create ECDSA verify and sign utilities

### ISSUE THREAD

**Issue by critesjosh** [noir-lang/noir#391]
# Problem

ECDSA verify and sign utilities don't currently exist in Noir. Adding these would make it easier to integrate Ethereum account information into circuits.

# Solution

Write ECDSA verify and sign utilities in Noir.

# Additional context

We will consider giving a [grant](https://www.notion.so/aztecnetwork/6c4d76769a714cbea9fc959a60417b05?v=12c257164ff94a68945a44e4bab54bf4) to do this.

**Comment by nfurfaro** [comment]
@critesjosh Has there been any progress on this? I could be interested in working on it if not.

**Comment by critesjosh** [comment]
This is actually cpmplete. You can see how to use it here. https://noir-lang.org/standard_library/cryptographic_primitives/ecdsa_secp256k1
