### ISSUE TITLE
Create EDDSA verify and sign utilities

### ISSUE THREAD

**Issue by critesjosh** [noir-lang/noir#392]
# Problem

EDDSA verify and sign utilities have been requested by Noir users. We currently don't support these.

# Solution

Write EDDSA verify and sign utilities in Noir.

# Additional context

We will consider giving a [grant](https://www.notion.so/aztecnetwork/6c4d76769a714cbea9fc959a60417b05?v=12c257164ff94a68945a44e4bab54bf4) to do this.

**Comment by Savio-Sou** [comment]
https://github.com/noir-lang/noir/blob/a9766c5e9650160bcafc693f2617e441ed47721a/noir_stdlib/src/eddsa.nr
