### ISSUE TITLE
Create Elliptic Curve Arithmetic utilities

### ISSUE THREAD

**Issue by critesjosh** [noir-lang/noir#393]
# Problem

Elliptic curve arithmetic utilities have been requested by Noir users.

# Solution

Write elliptic curve arithmetic utilities in Noir.

# Additional context

Currently blocked. Awaiting bigint support first.

We will consider giving a [grant](https://www.notion.so/aztecnetwork/6c4d76769a714cbea9fc959a60417b05?v=12c257164ff94a68945a44e4bab54bf4) to do this.

**Comment by guipublic** [comment]
Note that elliptic curve arithmetic can easily be implemented on the native field of noir.
Elliptic curve on a different field would require bigint.

**Comment by Globallager** [comment]
https://github.com/noir-lang/noir/pull/964 added some EC arithmetic utilities, but not all that's possible. Re-open for devs to engage with this issue.
