### ISSUE TITLE
nargo fmt: inconsistent formatting with arrays

### ISSUE THREAD

**Issue by LHerskind** [noir-lang/noir#3945]
### Aim

Run fmt on
```rust
dep::std::hash::pedersen_hash_with_separator([
    contract_address.to_field(),
    storage_slot
], GENERATOR_INDEX__PUBLIC_LEAF_INDEX)
```

### Expected Behavior

```rust
dep::std::hash::pedersen_hash_with_separator([
    contract_address.to_field(),
    storage_slot
], GENERATOR_INDEX__PUBLIC_LEAF_INDEX)
```

Or 

```rust
dep::std::hash::pedersen_hash_with_separator(
    [
        contract_address.to_field(),
        storage_slot
    ], 
    GENERATOR_INDEX__PUBLIC_LEAF_INDEX
)
```

### Bug

The formatted code looks like

```rust
dep::std::hash::pedersen_hash_with_separator(
    [
    contract_address.to_field(),
    storage_slot
],
    GENERATOR_INDEX__PUBLIC_LEAF_INDEX
)
```

### To Reproduce

1. Run nargo fmt
2.
3.
4.

### Installation Method

None

### Additional Context

Saw the issue as part of https://github.com/AztecProtocol/aztec-packages/pull/3803/files/c6f4b7b9b9efe9a118e57aec0f28219523812563

### Would you like to submit a PR for this Issue?

No

**Comment by benesjan** [comment]
I tried to use the master branch of noir (version 219423eb87fa12bd8cca2a6fd2ce4c06e308783c) to see if the issues pertain and unfortunately they do.

**Comment by benesjan** [comment]
Another issue I've stumbled upon. When I put 2 spaces after "fn" the formatter leaves it as it is:

`
fn  main(input: PrivateKernelInputsInner) -> distinct pub KernelCircuitPublicInputs {
    input.native_private_kernel_circuit_inner()
}
`

**Comment by benesjan** [comment]
The formatter ignores spaces in struct functions:
<img width="422" alt="image" src="https://github.com/noir-lang/noir/assets/13470840/a74dfa77-09f4-4699-9cc3-ac72caee8e21">

**Comment by kevaundray** [comment]
@f01dab1e can you take this on?

**Comment by f01dab1e** [comment]
I'll have a look on Monday.
