### ISSUE TITLE
Trait bound struct implementations

### ISSUE THREAD

**Issue by sirasistant** [noir-lang/noir#3954]
### Problem

While trying to make Aztec's Map use a trait for keys, we want to bind that the key type implements the trait ToField. 
In Rust, you could do something like this:
```rust
use std::marker::PhantomData;

struct Map<K, V> {
    items: Vec<V>,
    phantom: PhantomData<K>,
}

impl<K, V> Map<K, V>
where
    K: Into<usize>,
{
    fn new() -> Self {
        Self {
            items: Vec::new(),
            phantom: PhantomData,
        }
    }

    fn at(&self, index: K) -> &V {
        let index = index.into();
        &self.items[index]
    }
}

fn main() {
    let _map: Map<u128, u128> = Map::new(); <= complains because u128 is not Into<usize>
}

```
Where you'd trait bind your impl so a map could never be created with a key type that cannot be converted to usize.

In noir, trait binding impls is not working:
```rust
trait ToField {
    fn to_field() -> Field;
}

struct Map<K,V> {
    key: K, // Just an example
    value: V, // Just an example
}

impl<K,V> Map<K,V> where K: ToField { <== fails
    fn new(key: K, value: V) -> Self {
        Self { key, value }
    }
}

```

### Happy Case

Trait binding impls is possible

### Alternatives Considered

You can always make the specific function that needs the IntoField generic but then you'd be able to use a map with different key types, which sounds like a footgun for users.

### Would you like to submit a PR for this Issue?

No

**Comment by asterite** [comment]
It seems the second code snippet complies fine. Maybe this started working once we started checking trait where clauses. But please reopen if this is not the case!
