### ISSUE TITLE
Improve Traits stdlib page in docs with user-oriented elaborations and examples

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#3969]
### Problem

As per https://github.com/noir-lang/noir/pull/3796, the [standard library - traits](https://noir-lang.org/docs/dev/noir/standard_library/traits) page was introduced in the Noir docs.

As it currently stands, it is not fully intuitive how each of the functions are useful and can be used.

### Happy Case

Will defer to assignee of this issue, but one possible way could be turning the current implementation code blocks on the page into minimal examples that demonstrate usage.

### Additional Context

Can refer to Rust's docs for descriptions of similar methods.

### Would you like to submit a PR for this Issue?

No

**Comment by Savio-Sou** [comment]
@signorecello would you like to pair with @jfecher and work on this?

Albeit we are holding off from actively promoting Traits publicly with v0.21.0, we should have all changes in the version properly documented before announcing the release.

**Comment by signorecello** [comment]
Hey indeed I wouldn't block any release with this. @jfecher has done some AMAZING work so far, and better examples will come later when I have the time to get up to speed and add some real use-case examples in a how-to guide or something

**Comment by Savio-Sou** [comment]
Note that this is for the [standard library - traits](https://noir-lang.org/docs/dev/noir/standard_library/traits) page, not the [types - traits](https://noir-lang.org/docs/dev/noir/concepts/traits) (which was beautifully written).

Fine to consider this non-blocking as long as the anticipated risk of support resource drain is sufficiently low 🙌
