### ISSUE TITLE
Document the `#[oracle]` attribute

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#3971]
### Problem

The `#[foreign_call]` attribute has been surfaced in multiple discussions as a feature for fetching information outside of the Noir program, but we don't currently have written explanations of how it is used.

### Happy Case

Document how is `#[foreign_call]` used in the Noir docs with examples.

### Additional Context

Non-exhausive / potentially inaccurate list of reference PRs I came across:
- https://github.com/noir-lang/noir/pull/3294
- https://github.com/noir-lang/noir/pull/3506
- https://github.com/noir-lang/noir/pull/3764
- https://github.com/noir-lang/noir/pull/3902

### Would you like to submit a PR for this Issue?

No

**Comment by Savio-Sou** [comment]
@signorecello would you like to pair with @TomAFrench and @sirasistant to work on this?

**Comment by Savio-Sou** [comment]
Relatedly is `#[oracle]` the same as `#[foreign_call]`? ([example](https://github.com/noir-lang/noir/blob/fbb51ed33e9e4d9105d8946cdfc4ea387c85258e/test_programs/execution_success/brillig_oracle/src/main.nr#L24))
If not we should create a separate issue to also document it.

**Comment by kevaundray** [comment]
`#[foreign]` is a compiler attribute for specifying blackbox functions whereas `#[oracle]` tells the compiler to delegate execution of a function to something outside of Noir

**Comment by Savio-Sou** [comment]
Does that mean Noir devs are intended to use `#[oracle]` but not necessarily `#[foreign_call]`?
(And is `#[foreign_call]` and `#[foreign]` the same?)

**Comment by kevaundray** [comment]
Noir devs should not use any of those I think in most cases -- oracles are for people who want to have their own runtimes like aztec, ie I can't depend on a library that has an oracle in it unless it is an oracle from the Noir runtime, like println

**Comment by Savio-Sou** [comment]
Right, perhaps an advanced rather than general use case but would e.g. https://github.com/orgs/noir-lang/discussions/3767 be where `#[oracle]` could be useful for Noir devs?

**Comment by TomAFrench** [comment]
`#[foreign_call]` doesn't exist. I got those mixed up in an example a while back.

**Comment by TomAFrench** [comment]
> Noir devs should not use any of those I think in most cases -- oracles are for people who want to have their own runtimes like aztec, ie I can't depend on a library that has an oracle in it unless it is an oracle from the Noir runtime, like println

Generally agree although I can see an argument for allowing them in `bin` packages, i.e. as it lives in the package you running then you aren't pulling in this new oracle call unawares so you're more likely to run the package in an environment which supplies a handler for it.

**Comment by signorecello** [comment]
This is where diátaxis framework shines: we don't have to _not document_ something, as it is delegated to reference material. It is still there, but not surfaced as something that works out-of-the-box.

To work, I'll be doing a how-to guide which will come with its own section on the runtime part.

This should be documented in reference, though. I'll try to find a nice place for it, and we can follow the same pattern for future situations like this.
