### ISSUE TITLE
Put `ExpressionWidth` into the circuit definition

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#4012]
### Problem

It is not apparent if a circuit has been reduced or not, just by reading the bytecode

### Happy Case

We can move ExpressionWidth into the ACIR structure to make this apparent.

### Would you like to submit a PR for this Issue?

No

**Comment by vezenovm** [comment]
Closing as resolved by https://github.com/AztecProtocol/aztec-packages/pull/4014
