### ISSUE TITLE
Failing test in the `nargo` crate

### ISSUE THREAD

**Issue by ilitteri** [noir-lang/noir#402]
# Description

## Aim

Run `nargo` tests.

## Expected behavior

All tests should pass.

## Bug

Test fails with the following message

```shell
thread 'tests::noir_integration' panicked at 'range end index 322560156 out of range for slice of length 3585470', library/core/src/slice/index.rs:73:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::noir_integration

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 5.37s
```

# To reproduce

This is assuming #401 is fixed.

1. Clone the repo.
2. `cd crates/nargo`.
3. `cargo t`

# Environment

I'm using this repo's main branch.

- OS: macOS Monterey 12.6

**Comment by jfecher** [comment]
Can you retest this on latest with a fresh clone? These tests are automatically tested an CI and I just verified they pass for me locally as well. on an M1, macOS 13.0.

**Comment by ilitteri** [comment]
Closing this because this test does not fail when running the workspace's tests in the CI.
