### ISSUE TITLE
Add poseidon permutation opcode

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#4037]
### Problem

Poseidon is a popular circuit friendly hash function, currently we do not have an efficient blackbox function for it like keccak, sha256 and blake.

### Happy Case

Add the poseidon permutation opcode

### Additional Context

It would be great if we could make the opcode agnostic to the `t` parameter, this does not seem possible and barretenberg uses a non-standard `t` parameter for efficiency.

Would be good to investigate whether we can add a more fine grained opcode without losing efficiency and still being agnostic to `t`

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
@guipublic Do we really gain much on having the poseidon2 permutation added as a blackbox function rather than in Noir directly? As it's just arithmetic it seems like we'd get all the same benefits from https://github.com/AztecProtocol/aztec-packages/pull/5374?

**Comment by guipublic** [comment]
I think there is some gain as the gates are tailored to the specific Poseidon operations, i.e they are hand-made crafted as opposed to automatically generated in Noir.
Another point is that using a Honk backend will greatly benefit from the blackbox function, and I think having a Honk backend for Noir is something that we want.

n.b: the poseidon2 permutation is already added as a blackbox.
