### ISSUE TITLE
Add big integer opcode

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#4040]
### Problem

These opcodes will allow us to implement big group, which would in turn allow us to implement higher level primitives like ecdsa

### Happy Case

Add BigIntAdd, BigIntNeg, BigIntMul, BigIntInv

### Additional Context

We should be careful about BigIntInv and think about whether we want to just limit the bigint modulus to be prime

### Would you like to submit a PR for this Issue?

No

**Comment by guipublic** [comment]
Should we rather have BigIntDiv instead of BigIntInv?
BigIntDiv works for non prime modulus as well.

**Comment by kevaundray** [comment]
> Should we rather have BigIntDiv instead of BigIntInv?
> BigIntDiv works for non prime modulus as well.

Yep lets go with Div!

**Comment by TomAFrench** [comment]
Reopening as the opcode doesn't have an implementation in ACVM

**Comment by Savio-Sou** [comment]
Closed with https://github.com/AztecProtocol/aztec-packages/pull/4415.
