### ISSUE TITLE
Tried to bind an already bound type variable!

### ISSUE THREAD

**Issue by critesjosh** [noir-lang/noir#4057]
### Aim

Trying to use the LSP with writing Aztec contracts.

### Expected Behavior

The LSP should work automatically, or provide a more helpful error.

### Bug

```
[Info  - 2:08:36 PM] Starting LSP client using command: /home/josh/.nargo/bin/nargo lsp
[31mThe application panicked (crashed).[0m
Message:  [36mTried to bind an already bound type variable![0m
Location: [35mcompiler/noirc_frontend/src/hir_def/types.rs[0m:[35m433[0m

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml
[Error - 2:08:36 PM] Request textDocument/codeLens failed.
  Message: Request handler of textDocument/codeLens panicked: Tried to bind an already bound type variable!
  Code: -32603 
  ```

### To Reproduce

1. clone https://github.com/AztecProtocol/aztec-starter
2. Check the "Noir Language Server" from the drop down in the "Output" tab

### Installation Method

None

### Nargo Version

noirc version = 0.19.4+4d133c50a50f21ca23861a9d1987207bd8783d36

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
> noirc version = 0.19.4+4d133c50a50f21ca23861a9d1987207bd8783d36

Can you test on an up-to-date version of Nargo?

**Comment by jfecher** [comment]
This works on my machine on current master for Nargo

**Comment by critesjosh** [comment]
Yea this is working for me on nightly. Sorry for the oversight.
