### ISSUE TITLE
Monomorphization duplicates some functions

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#4066]
### Aim

Running the `trait_generics` test

### Expected Behavior

Expected 1 instance of `fold` in the resulting SSA (shown with `--show-ssa`), since although there are 2 invocations of the generic function, both have the same generic arguments.

### Bug

`fold` is monomorphized twice for the same types and appears twice in the resulting SSA.

This doesn't affect program correctness since the two functions are equivalent and functions cannot be compared for equality in Noir.

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by michaeljklein** [comment]
Myself and @jfecher were unable to replicate: it appears to be resolved!
