### ISSUE TITLE
Error compiling the `noirc_abi` crate

### ISSUE THREAD

**Issue by ilitteri** [noir-lang/noir#407]
# Description

## Aim

To compile the `noirc_abi` crate.

## Expected behavior

It should compile successfully for both `bn254` and `bls12_381` features (separately).

## Bug

`acvm` is used and there is no way for the user to specify which feature to use causing a compilation error.

`acvm` has two features but none of them is specified in the `Cargo.toml` nor could be specified by the user in the terminal. Also `acvm` has no default feature.

I think that the default feature of `acvm` should be `bn254` as it is in `noir_fields` and `noirc_abi` should inherit both features as well.

# To reproduce

For some crates you have two different features for compilation both related to the elliptic curves used (*bn254*, *bls12381*). In those crates there is no default feature set and you should specify which to use or you are getting a compilation error (saying that you should use a feature). 

1. Clone the repo.
2. `cd crates/noirc_abi`.
3. `cargo c` or `cargo c --features bn254` or `cargo c --features bls12_381`.

# Environment

- OS: macOS Monterey 12.6

**Comment by TomAFrench** [comment]
> acvm is used and there is no way for the user to specify which feature to use causing a compilation error.

Agreed that this is a bit clunky from a DX perspective but if you prefix the feature flag with the dependency name then it applies the flag to the correct dependency.

i.e. `cargo c --features bn254` fails because it's applying the flag to `noirc_abi` whereas `cargo c --features acvm/bn254` succeeds..
