### ISSUE TITLE
Compiler assertion failure in ACIR gen due to compiler converting u8 overflowing as boolean

### ISSUE THREAD

**Issue by pventuzelo** [noir-lang/noir#4080]
### Aim

The compiler panics and crashes when we perform certain operations with overflow values. The reason appears to be that the compiler ends up treating a portion of the operation as a boolean (bit size = 1)

### Expected Behavior

As you can observe in the code comments below, the crash only occurs in very specific cases with specific operands. It is challenging to precisely explain the reason for this crash, but the main factor appears to be in this portion: ((255+1) ^ (255+1)), which the compiler treats as a 1-bit-sized value.

The panic crash occurs with the latest compiler version (0.22.0) as well as with the compiler from the noir git repository. The error message is as follows:

```
The application panicked (crashed).
Message:  assertion failed: `(left == right)`
  left: `Unsigned { bit_size: 1 }`,
 right: `Unsigned { bit_size: 8 }`: lhs and rhs types in Binary { lhs: Id(147), rhs: Id(155), operator: Sub } are not the same
Location: compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs:1629
```

### Bug

The assert panic raised for here: https://github.com/noir-lang/noir/blob/447aa343555cbd5a7cd735876e08f43271ecdd40/compiler/noirc_evaluator/src/ssa/acir_gen/mod.rs#L1629-L1634

## Steps to Reproduce

1. Create a Noir project with the following command: **`nargo new test_issue`**
2. Paste the code below into the file [[main.nr](http://main.nr/)](http://main.nr/)
3. Compile the project using the following command: **`nargo compile`**

```rust
fn main() {

    // (255+1) overflows u8, but both left and right sides are equal to 0 and result in a crash
    let var1: u8 = ((255+1) ^ (255+1)) - ((255+1) - (255+1));

     // Still crashes with other integer types, overflowing u16 due to the sum (65535+1)
    let var2: u16 = ((65535+1) ^ (65535+1)) - ((65535+1) - (65535+1));

    // Doesn't crash if we swap left and right sides
    let var3: u8 = ((255+1) - (255+1)) - ((255+1) ^ (255+1));

    // No crash if the middle operand is anything other than subtraction and division.
    let var4: u8 = ((255+1) ^ (255+1)) + ((255+1) - (255+1));

    // No crash if one part does not cause overflow
    let var5: u8 = ((255+1) ^ (255+1)) - (255 - 255);
    let var6: u8 = (255 ^ 255) - ((255+1) - (255+1));
}
```

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
This is crashing due to this line. https://github.com/noir-lang/noir/blob/447aa343555cbd5a7cd735876e08f43271ecdd40/compiler/noirc_evaluator/src/ssa/ir/instruction.rs#L1005

The compiler is seeing that `(255 + 1) ^ (255 + 1)` can be simplified to zero but choses a boolean type rather than maintaining the operand types.
