### ISSUE TITLE
Document `noir-codegen`

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#4093]
Document [`noir-codegen`](https://github.com/noir-lang/noir/tree/master/tooling/noir_codegen).

Reference: https://github.com/noir-lang/noir/issues/3348

**Comment by TomAFrench** [comment]
See usage here: https://github.com/noir-lang/noir/blob/16d5f18c68cc3da1d11c98e101e3942d2437c3a8/tooling/noir_codegen/package.json#L38

**Comment by jzaki** [comment]
Update to use with with crate and show `export` command working.
Related [4454](https://github.com/noir-lang/noir/pull/4454).
