### ISSUE TITLE
Support restricted bit sizes in noir: just support 1, 8, 32, 64, field

### ISSUE THREAD

**Issue by sirasistant** [noir-lang/noir#4162]

**Comment by Savio-Sou** [comment]
Good to create a separate Issue for providing fallback methods to ease users' migrations.

**Comment by Savio-Sou** [comment]
To go in after the PR that warns users.

**Comment by smanilov** [comment]
What happened to u16? I cannot find a relevant issue which discusses why support for it is removed. It seems like a lot of example code referenced from https://github.com/noir-lang/awesome-noir is using it, e.g. https://github.com/michaelelliot/noir-sha1.

**Comment by smanilov** [comment]
Ah, thanks, I thought that I was missing some reason why there shouldn't be a u16. The linked issue clarifies it :+1:
