### ISSUE TITLE
Add a `noirup` script for easy installation.

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#417]
It's a fairly common complaint in the noir channel that it's difficult to install or update nargo. This could be automated through a script similar to foundry's `foundryup`. This has the benefit of allowing us to check for common issues and flag it up to the user rather than just having the build fail.

I've made a quick and dirty version of this at https://github.com/TomAFrench/nargoup, however people won't (and shouldn't) be comfortable running `curl -L https://raw.githubusercontent.com/TomAFrench/nargoup/main/install | bash` so for trust reasons this would have to be housed in the main Noir repo.

Would a PR adding this script be welcome?

**Comment by kevaundray** [comment]
Yes! 

The team is currently at an offsite, so PR reviewing may not be until Monday. This is extremely appreciated though!
