### ISSUE TITLE
Types of some array functions in the docs are incorrect

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#4172]
### Aim

Looking through the array docs: https://noir-lang.org/docs/noir/syntax/data_types/arrays/#sort

### Expected Behavior

Each function to have the correct type

### Bug

`map`, `fold`, `reduce`, `all`, and `any` are missing their `self` parameters.

Other functions before them also use a more explicit `array: [T; N]` over `self`. This is nice since you can see the object type which you can't with `self`, but confusing because it makes them look like free functions rather than methods. We should decide on a way to distinguish methods from functions in the docs.

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
Probably worth holding off on this and doing as part of the code snippets refactor.

**Comment by jfecher** [comment]
@TomAFrench My impression was that the code snippets refactor was just related to code snippets compared to this which concerns the pseudo-code of function declarations. The syntax is also correct here, the main issue is some of these functions aren't listing their `self` parameters.
