### ISSUE TITLE
Incorrect compiler error when comparing the index of a "for" loop with a non-casted value.

### ISSUE THREAD

**Issue by pventuzelo** [noir-lang/noir#4193]
### Aim

We (@fuzzinglabs) find that the compiler incorrectly raises an error when comparing the index of a "for" loop with a non-casted value.

### Expected Behavior

The compiler should not treat the compared value as a field type but as a u64

### Bug

This error seems to be caused by the compiler treating the compared value as a field type, while the index of a 'for' loop is always treated as a u64, as stated here in the documentation: https://noir-lang.org/docs/noir/syntax/control_flow

As indicated in the code comments, this error doesn't appear with a u64 variable, and it specifically occurs when using the '>'; '<'; ‘≥’; ‘≤’ operators."

The panic crash occurs with the latest compiler version of the main branch. The error message is as follows:

```
error: Comparisons are invalid on Field types. Try casting the operands to a sized integer type first
```

### To Reproduce

1. Create a Noir project with the following command: **`nargo new test_issue`**
2. Paste the code below into the file `main.nr`
3. Compile the project using the following command: **`nargo compile`**

```rust
fn main() {
    // Raises an error because the compiler interprets '1' as a Field and not as a u64.
    for i in 0..10 {
        assert(i > 1);
    }

    // Same issue persists even if the value is stored in a variable.
    for i in 0..10 {
        let val = 1;
        assert(i < val);
    }

    // Error only occurs with '<' '>' '<=' '>=' operators.
    for i in 0..10 {
        assert(i == 1);
    }

    // Error only occurs with the index of a "for" loop, not with every u64.
    let i: u64 = 5;
    assert(i > 1);

    // Casting the value as u64 resolves the problem.
    for i in 0..10 {
        assert(i < 1 as u64);
    }
}
```

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by jfecher** [comment]
Possibly a duplicate of https://github.com/noir-lang/noir/issues/3639

The PR which fixes the duplicate https://github.com/noir-lang/noir/pull/4118 should test this case as well.
