### ISSUE TITLE
Move bounded_vec into the stdlib

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#4198]
### Problem

With the removal of nested slices, the BoundedVec struct which essentially acts as a array where the max size/capacity is given, will become more useful.

### Happy Case

Copy the BoundedVec implementation from https://github.com/AztecProtocol/aztec-packages/blob/1c8ea497fb1d64da64cb240917a60d57bd1efef8/yarn-project/noir-protocol-circuits/src/crates/types/src/utils/bounded_vec.nr#L1

### Would you like to submit a PR for this Issue?

No

**Comment by vezenovm** [comment]
This is a repeat of this issue (https://github.com/noir-lang/noir/issues/4020)

**Comment by vezenovm** [comment]
Closing in favor of the older issue
