### ISSUE TITLE
lsp panics when contract with #[event]

### ISSUE THREAD

**Issue by kobyhallx** [noir-lang/noir#4203]
### Aim

Open noir source file with contract which uses events

### Expected Behavior

LSP to function as usual

### Bug

lsp crashes with
`method not found`

### To Reproduce

1. Open contract source code with `#[event]`
2. Editor reports lsp crash

### Installation Method

Compiled from source

### Nargo Version

nargo version = 0.23.0 (git version hash: 882639de109f0ecccf2a8522e2181a301145e19f, is dirty: false)

### Additional Context

Sample snippet
```rs
contract Foo {

    #[event]
    struct FooEvent {
        value: Field,
    }
}
```
### Would you like to submit a PR for this Issue?

Yes

**Comment by asterite** [comment]
Closing as invalid because the `#[event]` attribute doesn't cause LSP to panic anymore.
