### ISSUE TITLE
Document `BigInt` struct

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#4205]
Corresponding PRs:
- https://github.com/AztecProtocol/aztec-packages/pull/4050
- https://github.com/AztecProtocol/aztec-packages/pull/4198
- https://github.com/AztecProtocol/aztec-packages/pull/4415

Using code snippets (introduced in https://github.com/noir-lang/noir/pull/4164, [example](https://github.com/noir-lang/noir/blob/2ce89587980cf064baecab50ccf4db14b43bf5cd/docs/docs/noir/standard_library/cryptographic_primitives/hashes.mdx#L17)) to import code and CI test case(s) as examples is recommended.

P.S. As v0.24.0 is pre-released, reminder to copy doc changes into [version-v0.24.0](https://github.com/noir-lang/noir/tree/master/docs/versioned_docs/version-v0.24.0) when making them.

**Comment by Savio-Sou** [comment]
(Updated Issue body with additional context.)
