### ISSUE TITLE
Logical error in the documentation for `Unconstrained Functions`

### ISSUE THREAD

**Issue by KumaCrypto** [noir-lang/noir#4222]
Hey,
I noticed that in the documentation for `Unconstrained Functions`, there is a logical error, namely in [line 43](https://github.com/noir-lang/noir/blob/3af2a89826f7d9b6dcd1782b8b38417c64065293/docs/docs/noir/concepts/unconstrained.md?plain=1#L43).

```rust
 out[i] = (num >> (56 - (i * 8)) as u72 & 0xff) as u8;
```

The block code above deletes `AND` operator with value `0xff`, but the text says about `XOR`.

**Comment by signorecello** [comment]
thanks @KumaCrypto didn't run the code but it seems like there's a typo indeed, thanks for the heads-up!
