### ISSUE TITLE
`const` syntax possibly confusing to users

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#424]
# Background

`const` in noir currently means "known at compile-time." In this way it mostly matches with the rust usage of compile-time evaluation. Noir differs from rust here namely in that `const` can be attached to types, allowing functions to specify only certain parameters need be const. This is important because this is how array indices are typechecked currently - the index must be known at compile-time.

# Problem

With the introduction of "global consts" we now have 2 features with `const` in the name which do not relate to each other. This mostly matches rust, though users from other languages may still find it confusing. Users would also find writing `const FOO: const Field = 2;` confusing, even though both consts are semantically different. Currently to avoid this confusion the default behavior for global consts is to add an implicit `const` to any type annotation such that `const FOO: Field = 2;` is still valid and is identical to the previous example.

# Solution

To avoid this confusion, we likely need to break from rust syntactically. I have a few points here on aspects which could be clearer if we broke free from rust's syntax:
- Renaming `const` to `ct` (short for compile-time) would be a smaller change which would still keep us mostly compatible with rust. The new keyword `ct` is meant to indicate something must be known at compile-time and would replace `const` in types.
- `let` is a more natural choice to declare globals since there is no reason for a separate keyword to be required to separate global definitions from local ones (we do not share rust's distinction of `const` and `static` globals). Additionally, if we did want a separate keyword anyway, then `global` is the clearer choice over `const`.

# Alternatives considered

The following alternative names were also considered:
- `compiletime` is very descriptive but lengthy enough to discourage use.
- `ctime` is a possible middle-ground between `ct` and `compiletime`. Could be confused for `time` in the C programming language without additional context.
- `comptime` as used by Zig. Slightly longer/clearer than `ctime`.
- Arbitrary sigils like `$` are short but not easily memorized and make the language look like symbol-soup to unfamiliar readers.

**Comment by jfecher** [comment]
After an internal discussion we've decided to:
1. Change the keyword for const globals to `global`
2. Change the keyword for const types to `comptime`
3. Allow type inference for globals

**Comment by kevaundray** [comment]
Just to add some quick examples:

`global x = 5` is allowed

`global x : comptime Field = 5` is allowed

`fn foo(x : comptime Field)` is allowed

- `const Field` is replaced by `comptime Field`
-  `const FOO : Field = 10` is replaced by `global FOO : Field = 10`
