### ISSUE TITLE
Differentiate bigint structures per moduli

### ISSUE THREAD

**Issue by guipublic** [noir-lang/noir#4257]
### Problem

BB supports foreign field arithmetic (aka bigfield, or bigint in Noir context) but only for 6 different moduli.
In order to avoid mixing bigint operations between different moduli, we should use a different structure for each modulus.

### Happy Case

Remove specialised functions secpk1_...() and use instead a bigint_secpk1.. struct which implements the bigint trait.

### Would you like to submit a PR for this Issue?

Yes

**Comment by Savio-Sou** [comment]
Will be closed with https://github.com/noir-lang/noir/pull/4390.
