### ISSUE TITLE
Docs: Alternative install to older version

### ISSUE THREAD

**Issue by Complexlity** [noir-lang/noir#4271]
### Aim

The [Alternative Installation Docs](https://noir-lang.org/docs/getting_started/installation/other_install_methods) shows three ways other ways to install nargo on (mac and linux) but they all specify and older version or nargo (0.6.0) when the latest docs version if for 0.22.0

![image](https://github.com/noir-lang/noir/assets/105590967/3676155d-7264-41ab-8796-0cafc6e172ab)

### Expected Behavior

Should show the release link for 0.22.0

### Bug

Shows release link for 0.6.0

### To Reproduce

1. 
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
@noir-lang/developerrelations
