### ISSUE TITLE
Docs: Typo 

### ISSUE THREAD

**Issue by Complexlity** [noir-lang/noir#4272]
### Aim

The wrapping_add function expects two arguments. However it was supplied `x + y` rather than `x, y`

Page: [https://noir-lang.org/docs/noir/syntax/data_types/integers](https://noir-lang.org/docs/noir/syntax/data_types/integers)

![image](https://github.com/noir-lang/noir/assets/105590967/5918cf0c-a376-49f5-b4b8-62cf35920ebc)

### Expected Behavior

Should be 
`std::wrapping_add(x , y); `

### Bug

It currently is

`std::wrapping_add(x + y)`

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by joaolago1113** [comment]
hey, 
can confirm this is a typo
