### ISSUE TITLE
Cannot print variable sized arrays

### ISSUE THREAD

**Issue by Complexlity** [noir-lang/noir#4273]
### Aim

I tried to print a vector

```
fn main() {
    let message = "hello world";
    let message_bytes = message.as_bytes();
    let mut message_vec = message.as_bytes_vec();
    std::println(message); // hello world
    std::println(message_bytes); // [104, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100]
    std::println(message_vec); // Fails
}
```

### Expected Behavior

I should print the vector on the console

### Bug

Fails with message:

```
The application panicked (crashed).
Message:  Cannot print variable sized arrays
Location: compiler/noirc_frontend/src/hir_def/types.rs:1564
```

### To Reproduce

1.
2.
3.
4.

### Installation Method

None

### Would you like to submit a PR for this Issue?

No

**Comment by joaolago1113** [comment]
Hey,

It seems like the problem is because vectors are mutable and can change size at runtime, and `std::println` can't handle that because it needs to know the size of the array at compile time.

Here's something I tried:

```noir
    let message = "hello world";
    let message_bytes: [u8; 11] = message.as_bytes();
    let mut message_vec: Vec<u8> = message.as_bytes_vec();
    std::println(message); // hello world
    std::println(message_bytes); // [104, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100]
    //std::println(message_vec); // Fails
    
    let lght = message_vec.len() as u8;

    for i in 0..lght {
        std::print(message_vec.get(i as Field)); 
        std::print(", "); 
    } 
```

But got this error:

```
error: Could not determine loop bound at compile-time
   ┌─ /home/john/projects/hello_world/src/main.nr:16:17
   │
16 │     for i in 0..lght {
   │                 ----
   │
   = Call stack:
     1. /home/john/projects/hello_world/src/main.nr:16:17

Aborting due to 1 previous error
```

So seems to me that `std::println` needs the vector size at compile time, and that's not possible for vectors data type. I'm still learning however.

**Comment by Complexlity** [comment]
Oh wow. Thank you. 
I think maybe the error message could be updated to say 
`Can't print because variable sized array sizes are not known at compile time`

It currently says the generic:
`I think this is an issue that could be added in newer version .....`. Makes it look like a bug. 

Also if someone knows an alternative method to print variable length array or If a method could be added to the standard library, that'll be good

**Comment by asterite** [comment]
It seems the original snippet now runs fine, so maybe this was fixed at some point.
