### ISSUE TITLE
Typo: smart_contract verifier test

### ISSUE THREAD

**Issue by Complexlity** [noir-lang/noir#4307]
### Aim

![image](https://github.com/noir-lang/noir/assets/105590967/2c148aac-12db-4e0a-861b-e6b6aaad3f6b)
From my understanding, when verified is true, it means the proof passes. And from the current behaviour, if the verified would fail, the generateProof function will error and there will be no proof data. 

However the test comment says "Proof fails verification in JS". It confused me and I think it's a typo (as it's also expected to be true

Source: [https://github.com/noir-lang/noir/blob/master/compiler/integration-tests/test/node/smart_contract_verifier.test.ts](https://github.com/noir-lang/noir/blob/746b0c7587f3bd505c8edaa55a02083eac9fce77/compiler/integration-tests/test/node/smart_contract_verifier.test.ts#L54)

### Expected Behavior

It should say: 
 `expect(verified, 'Proof passes verification in JS').to.be.true;`

### Bug

It says: 
 `expect(verified, 'Proof fails verification in JS').to.be.true;`

### To Reproduce

1.
2.
3.
4.

### Project Impact

None

### Workaround

None

### Installation Method

None

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
This is an error to be printed if the test fails so is correct.
