### ISSUE TITLE
Misdiagnosed parse error

### ISSUE THREAD

**Issue by nventuro** [noir-lang/noir#4322]
### Aim

When importing multiple things from the same crate or module, it's typical to have a single `use` statement and use braces and a comma-separated list. When a comma is missing however (very common when copy-pasting imports or simply adding new things), the parser provides an unhelpful error message that points somewhere else.

### Expected Behavior

In the following minimal example, there's a comma missing between `map::Map` and `set::Set`.

```rust
contract ParserTest {
    use dep::aztec::{
        state_vars::{map::Map set::Set},
    };

    #[aztec(private)]
    fn constructor() {}
}
```

### Bug

The compiler emits the following error message:

```
error: Expected a Ident but found {
  ┌─ <...>/contracts/parser_test_contract/src/main.nr:2:21
  │
2 │     use dep::aztec::{
  │                     -

```

This led on a wild-goose check trying to find if I was using the `use` statement incorrectly, or trying to find grammar errors at some earlier line.

### To Reproduce

Compile the above code with the current `master` of `aztec-packages`. See [here](https://github.com/nventuro/aztec-packages/commit/7d707591567898de50d758bdac4d4ef96ed03588) for a minimal commit that adds this test contract to the monorepo.

### Project Impact

None

### Workaround

None

### Installation Method

Compiled from source

### Nargo Version

nargo version = 0.23.0 noirc version = 0.23.0+f1b91511124df89bbe9e059b87536901bdf0d6f3 (git version hash: f1b91511124df89bbe9e059b87536901bdf0d6f3, is dirty: false)

### Would you like to submit a PR for this Issue?

None

**Comment by asterite** [comment]
Here's the error message that the handwritter parser produces for this:

```
error: Expected a `,` separating these two use trees
  ┌─ src/main.nr:1:15
  │
1 │ use foo::{bar baz};
  │               ---
```
