### ISSUE TITLE
Remove sha256 opcode

### ISSUE THREAD

**Issue by guipublic** [noir-lang/noir#4330]
### Problem

Sha256 is implemented with the sha256compression opcode in PR https://github.com/AztecProtocol/aztec-packages/pull/4511
When this PR is merged, we no longer need the sha256 opcode

### Happy Case

Just remove the sha256 opcode. The implementation with sha256 compression is more performant and allows us to have a variable size sha256

### Project Impact

None

### Workaround

None

### Would you like to submit a PR for this Issue?

None

**Comment by Savio-Sou** [comment]
Pending for AVM's update to support SHA256 compression opcode, so we can safely deprecate this.

**Comment by Savio-Sou** [comment]
Doesn't look like it need any, but do create an Issue if any updates to the SHA256 section in docs is necessary, thanks!
https://noir-lang.org/docs/dev/noir/standard_library/cryptographic_primitives/hashes#sha256
