### ISSUE TITLE
Circuit compilation fail with wasm, if a dependency has no `dependencies` tag in `Nargo.toml`

### ISSUE THREAD

**Issue by KumaCrypto** [noir-lang/noir#4338]
Hey, I noticed a problem that during compilation if a library that is in a dependency for main project has no `[dependencies]` tag, then the [`Package.getDependencies`](https://github.com/noir-lang/noir/blob/be6e8eb366cbb09ce21b06ed9d9d37e696bd3600/compiler/wasm/src/noir/package.ts#L93) function will return `undefined` which eventually causes the program to crash when trying [`Object.entries(noirPackage.getDependencies()))`](https://github.com/noir-lang/noir/blob/be6e8eb366cbb09ce21b06ed9d9d37e696bd3600/compiler/wasm/src/noir/dependencies/dependency-manager.ts#L88C7-L88C84) with the error `Cannot convert undefined or null to object`.

I found a simple workaround to just add an empty [dependencies] tag to `Nargo.toml` of the library, which by this point is already copied to the local environment. But that adds a headache : )

I think you should add a check for `undefined` before the `for` loop, and if it is, just skip to the next iteration of the `while`.

**Comment by TomAFrench** [comment]
Thanks for making us aware of this. I've added a check so that we return an empty dependencies map rather than `undefined` here.
