### ISSUE TITLE
Panic during inlining

### ISSUE THREAD

**Issue by RajeshRk18** [noir-lang/noir#4361]
### Aim

I have tried to run the ECDH verifier from [here](https://github.com/RajeshRk18/ecdh_verifier/blob/d79680fa5a322c6cc89526a0ff317068ca619bde/src/ed25519.nr#L7).

### Expected Behavior

ECDH verifier should have run and produced the output. 

### Bug

I got an assertion failed in inlining as follows:

```
Message:  assertion failed: `(left == right)`
  left: `2`,
 right: `1`
Location: compiler/noirc_evaluator/src/ssa/opt/inlining.rs:173
```

### To Reproduce

1. Clone this  [repo](https://github.com/RajeshRk18/ecdh_verifier) locally.
2. Run `nargo test`.

### Project Impact

None

### Workaround

None

### Installation Method

Binary (`noirup` default)

### Nargo Version

nargo version = 0.22.0 noirc version = 0.22.0+3fae4a03fded4e3f5065e7461c563f7e39745604

### Would you like to submit a PR for this Issue?

None

**Comment by jfecher** [comment]
Testing this on current master I see error messages instead:
```
error: Expected type [u8], found type [u8; 32]
   ┌─ /home/user/Code/Noir/ecdh_verifier/src/ed25519.nr:17:37
   │
17 │     let secret_key = Fq::from_bytes(secret_key);
   │                                     ----------
   │

error: Expected type [u8], found type [u8; 32]
   ┌─ /home/user/Code/Noir/ecdh_verifier/src/ed25519.nr:37:39
   │
37 │     Point::from_affine(Fp::from_bytes(x), Fp::from_bytes(y))
   │                                       -
   │

error: Expected type [u8], found type [u8; 32]
   ┌─ /home/user/Code/Noir/ecdh_verifier/src/ed25519.nr:37:58
   │
37 │     Point::from_affine(Fp::from_bytes(x), Fp::from_bytes(y))
   │                                                          -
   │

error: Expected type [u8], found type [u8; 32]
   ┌─ /home/user/Code/Noir/ecdh_verifier/src/secp256k1.nr:17:37
   │
17 │     let secret_key = Fq::from_bytes(secret_key);
   │                                     ----------
   │

error: Expected type [u8], found type [u8; 32]
   ┌─ /home/user/Code/Noir/ecdh_verifier/src/secp256k1.nr:38:39
   │
38 │     Point::from_affine(Fp::from_bytes(x), Fp::from_bytes(y))
   │                                       -
   │

error: Expected type [u8], found type [u8; 32]
   ┌─ /home/user/Code/Noir/ecdh_verifier/src/secp256k1.nr:38:58
   │
38 │     Point::from_affine(Fp::from_bytes(x), Fp::from_bytes(y))
   │                                                          -
   │
```
This is likely related to the current panic you're seeing as well - you may want to try swapping out arrays for slices or vice-versa.
For now though, I can't reproduce this.

**Comment by RajeshRk18** [comment]
> Testing this on current master I see error messages instead:
> ```
> error: Expected type [u8], found type [u8; 32]
>    ┌─ /home/user/Code/Noir/ecdh_verifier/src/ed25519.nr:17:37
>    │
> 17 │     let secret_key = Fq::from_bytes(secret_key);
>    │                                     ----------
>    │
> 
> error: Expected type [u8], found type [u8; 32]
>    ┌─ /home/user/Code/Noir/ecdh_verifier/src/ed25519.nr:37:39
>    │
> 37 │     Point::from_affine(Fp::from_bytes(x), Fp::from_bytes(y))
>    │                                       -
>    │
> 
> error: Expected type [u8], found type [u8; 32]
>    ┌─ /home/user/Code/Noir/ecdh_verifier/src/ed25519.nr:37:58
>    │
> 37 │     Point::from_affine(Fp::from_bytes(x), Fp::from_bytes(y))
>    │                                                          -
>    │
> 
> error: Expected type [u8], found type [u8; 32]
>    ┌─ /home/user/Code/Noir/ecdh_verifier/src/secp256k1.nr:17:37
>    │
> 17 │     let secret_key = Fq::from_bytes(secret_key);
>    │                                     ----------
>    │
> 
> error: Expected type [u8], found type [u8; 32]
>    ┌─ /home/user/Code/Noir/ecdh_verifier/src/secp256k1.nr:38:39
>    │
> 38 │     Point::from_affine(Fp::from_bytes(x), Fp::from_bytes(y))
>    │                                       -
>    │
> 
> error: Expected type [u8], found type [u8; 32]
>    ┌─ /home/user/Code/Noir/ecdh_verifier/src/secp256k1.nr:38:58
>    │
> 38 │     Point::from_affine(Fp::from_bytes(x), Fp::from_bytes(y))
>    │                                                          -
>    │
> ```
> This is likely related to the current panic you're seeing as well - you may want to try updating nargo and swapping out arrays for slices (you can use `.as_slice()`) or vice-versa.
> For now though, I can't reproduce this.

Yeah, it's fine now. Closing this issue.
