### ISSUE TITLE
Global arrays

### ISSUE THREAD

**Issue by vezenovm** [noir-lang/noir#439]
# Problem

Many users are requesting the ability to have global arrays. This will allow users to specify lists of compile time values in a separate file that can be referenced throughout a Noir project.

For example even in our standard lib we could move out the `mimc` constants to a separate file that does not clutter up our `hash.nr` module: https://github.com/noir-lang/noir/blob/23c17040b19620bce9e392d5b8a3ea83746b5ea8/crates/std_lib/src/hash.nr#L37 This can be applied to many other cryptographic functionality that requires lists of primes and/or constants. 

# Solution

Allow Noir developers to use global arrays. Follow the current scheme of not allowing mutable globals. Keeping the same feature of not allowing mutable globals should make implementation simpler. Either way, moving to mutable globals would be a separate issue that should be discussed internally before implementation. 

# Alternatives considered

(Describe any alternative solutions you have considered.)

# Additional context

(If applicable.)

**Comment by kevaundray** [comment]
@vezenovm can we close this?

**Comment by vezenovm** [comment]
> @vezenovm can we close this?

I am helping @michaelneuder submit a PR for this as I think it is a good first issue. Should hopefully be able to close it soon.
