### ISSUE TITLE
Prover.toml (error)

### ISSUE THREAD

**Issue by CryptoRalph** [noir-lang/noir#4401]
### Aim

**While trying to build a proof for Identity verification that stores all account information a user could ever need , I provide the main source file structure, which is:**
### main.nr
 "fn main(
    name : Field,
    age : Field,
    nationality : Field,
    address : Field,
    email : Field,
    phone : Field,
    passport_number : Field,
    driver_license_number : Field,
    social_security_number : Field,
    bank_account_number : Field,
    credit_card_number : Field,
    employee_id : Field
) {
    assert(name != age);
    assert(age != nationality);
    assert(nationality != address);
    assert(address != email);
    assert(email != phone);
    assert(phone != passport_number);
    assert(passport_number != driver_license_number);
    assert(driver_license_number != social_security_number);
    assert(social_security_number != bank_account_number);
    assert(bank_account_number != credit_card_number);
    assert(credit_card_number != employee_id);
}
"  
 ### prover.toml 
**I am a bit confused as to what to put inside the Prover.toml file, if x is 1 or the "private" string and y is the Pub string. I've already tried this format, which is returning an error (Expected witness values to be integers)  :** 

name = "Alice"
age = "30"
nationality = "US"
address = "123 Main St"
email = "alice@example.com"
phone = "555-123-4567"
passport_number = "A1234567"
driver_license_number = "123456789"
social_security_number = "123-45-6789"
bank_account_number = "123456789"
credit_card_number = "1234-5678-9012-3456"
employee_id = "EMP123456"
]
}

**(I expect that x might = integers, since that is the private data and I might have to rewrite each and specify the pub strings, but I'm feeling a bit lazy right now)**

### Expected Behavior

**To clarify the expected behavior for building a proof for identity verification using the Noir language:**

### Source Code Structure (main.nr):
**The main.nr file defines a main function that takes several identity attributes as input parameters (name, age, nationality, etc.). It then uses assertions to ensure that these attributes are not equal to each other, enforcing uniqueness constraints.**

### Prover.toml File:

**The Prover.toml file is used to provide input values for the main function.
Each attribute (name, age, nationality, etc.) should be assigned a value that matches the expected data type.
If x and y are placeholders for private and public values, respectively, they should be assigned appropriate integer values.
Ensure that all values are properly formatted and match the expected data types to avoid errors.** 

### Bug

Expected witness values to be integers, provided value causes `cannot parse integer from empty string` error

### To Reproduce

1.
2.
3.
4.

### Project Impact

Blocker

### Workaround

None

### Installation Method

Binary (`noirup` default)

### Nargo Version

v0.23.0

### Would you like to submit a PR for this Issue?

Yes

**Comment by TomAFrench** [comment]
Hey, the issue you're running into is that you're trying to pass in invalid types as a Noir `Field`. You can't represent a postal address as a scalar field element directly so you need to encode it in a way so that the circuit can act on it sensibly (This could be as simple as just thestring's byte representation).

I'd recommend looking at the range of types which Noir supports at https://noir-lang.org/docs/noir/concepts/data_types/
