### ISSUE TITLE
Add support for custom modulus in the bigint opcode

### ISSUE THREAD

**Issue by joeandrews** [noir-lang/noir#4404]
### Problem

Currently the bigint opcode uses a fixed set of 6 templated modulus. This is not generic and prevents developers using the opcode for custom modulus e.g RSA signatures or Curve25519 which requires a custom value.

It also prevents Noir from having U256 integers.

### Happy Case

Barretenberg should support custom run time modulus definition.

### Project Impact

Nice-to-have

### Workaround

None

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
Let's add an issue for this in aztec-packages so crypto can see this @Savio-Sou

**Comment by Savio-Sou** [comment]
> Let's add an issue for this in aztec-packages
https://github.com/AztecProtocol/aztec-packages/issues/4676

**Comment by TomAFrench** [comment]
Closing this due to above issue + it seems like crypto isn't comfortable with this.
