### ISSUE TITLE
Type variables still bound from previous trait implementations

### ISSUE THREAD

**Issue by Thunkar** [noir-lang/noir#4436]
### Aim

Use (different) globals as generic parameters for trait implementations, in both libs and app code. This is a very common situation in aztec contracts, in which it's typical to have a contract that stores both standard `aztec-nr` notes and custom ones.

The project structure is as follows:
```
a_trait_lib/
├─ src/
│  ├─ lib.nr
├─ Nargo.toml
lib_struct/
├─ src/
│  ├─ lib.nr
├─ Nargo.toml
main/
├─ src/
│  ├─ custom_struct.nr
│  ├─ main.nr
├─ Nargo.toml
```
Where `a_trait_lib` exports:

```rust 
trait LibTrait<N> {
    fn broadcast();
    fn get_constant() -> Field;
}
```

`lib_struct`

```rust 
use dep::a_trait_lib::LibTrait;

global LIB_STRUCT_LEN: Field = 3; 

struct LibStruct {
}

impl LibTrait<LIB_STRUCT_LEN> for LibStruct {
    fn broadcast() {
        Self::get_constant();
    }

    fn get_constant() -> Field {
        1
    }
}

impl LibStruct {
    pub fn new() -> Self {
        LibStruct {}
    }
}
```

`custom_struct.nr`

```rust 
use dep::a_trait_lib::LibTrait;

global EVENTUALLY_CLASHES: Field = 5;

struct CustomStruct {

}

impl LibTrait<EVENTUALLY_CLASHES> for CustomStruct {
    fn broadcast() {
        Self::get_constant();
    }

    fn get_constant() -> Field {
        2
    }
}

impl CustomStruct {
    pub fn new() -> CustomStruct {
        CustomStruct {}
    }
}
```

`main` does nothing besides importing the `custom_struct` module. It is enough that dependencies are declared in `Nargo.toml` to trigger the bug.

```rust
mod custom_struct;

fn main() {}
```

```toml
[package]
name = "broken_globals"
type = "bin"
authors = [""]
compiler_version = ">=0.24.0"

[dependencies]
lib_struct = { path = "../lib_struct"}
a_trait_lib = { path = "../a_trait_lib"}
```

### Expected Behavior

It should be possible to use both library and custom app defined structs (implementing `LibTrait<N>`), in which `impl LibTrait<A_GLOBAL_VAR>` can be defined for each of them, without the compiler panicking.

### Bug

The compiler panics with: 

```
The application panicked (crashed).
Message:  internal error: entered unreachable code: TypeVariable::bind, cannot bind bound var 3 to 5
Location: compiler/noirc_frontend/src/hir_def/types.rs:472
```

Notice the values of the bindings, which correspond to `LIB_STRUCT_LEN` and `EVENTUALLY_CLASHES`. Altering those values change the error message.

It is very possible that there are several red herrings on the minimal reproduction, but I could not reduce it anymore without the problem disappearing. Specially baffling is that an apparently unrelated method `get_constant` that just returns a `Field` must be present and be called with `Self::` within the implementation (equivalent to `get_note_type_id()` and `broadcast()` in Aztec)

### To Reproduce

Use the provided minimal example:

[broken_globals.tgz](https://github.com/noir-lang/noir/files/14418612/broken_globals.tgz)

### Project Impact

Blocker

### Impact Context

It's a very common pattern in aztec contracts

### Workaround

Yes

### Workaround Description

It is possible to work around this issue by moving the library struct into the main crate, or commenting out the `Self::get_constant()` lines, using Field literals instead. In some cases this would trigger another error, but I couldn't get it to fail reliably.

### Installation Method

Compiled from source

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
Flattening this example down into a single module also fails

```rust
trait LibTrait<N> {
    fn broadcast();
    fn get_constant() -> Field;
}

global STRUCT_A_LEN: Field = 3;
global STRUCT_B_LEN: Field = 5;

struct StructA;
struct StructB;

impl LibTrait<STRUCT_A_LEN> for StructA {
    fn broadcast() {
        Self::get_constant();
    }

    fn get_constant() -> Field {
        1
    }
}
impl LibTrait<STRUCT_B_LEN> for StructB {
    fn broadcast() {
        Self::get_constant();
    }

    fn get_constant() -> Field {
        1
    }
}

fn main() {}

```

This gives the error
```
error: No matching impl found for `StructB: LibTrait<3>`
   ┌─ /home/tom/Programming/aztec/noir/tmep/src/main.nr:23:9
   │
23 │         Self::get_constant();
   │         ------------------ No impl for `StructB: LibTrait<3>`
   │
```

Swapping out `Self` for `LibTrait` results in us resolving the correct `get_constant` implementation.

**Comment by jfecher** [comment]
Updated the title since this is about previous variables still being bound in general, not specifically globals. The following still exhibits the bug:
```rs
trait LibTrait<N> {
    fn broadcast();
    fn get_constant() -> Field;
}

struct StructA;
struct StructB;

impl LibTrait<u32> for StructA {
    fn broadcast() {
        Self::get_constant();
    }

    fn get_constant() -> Field {
        1
    }
}
impl LibTrait<u64> for StructB {
    fn broadcast() {
        Self::get_constant();
    }

    fn get_constant() -> Field {
        1
    }
}

fn main() {}
```
