### ISSUE TITLE
nargo_cli: support user defined .nargo location for prover backends

### ISSUE THREAD

**Issue by veigajoao** [noir-lang/noir#4458]
### Problem

Currently the nargo_cli automatically defines a path in the user's machine where it stores a `.nargo` directory. Whenever Nargo is used for building proofs it fetches a Barrentenberg binary and saves it to the `.nargo` directory.

However, the location of the `.nargo` directory is defined by an environment variable in `nargo_cli` making it impossible for the user to redefine it, unless they recompile the cli.

### Happy Case

Ideally a command would be supplied in the CLI to define the location of the `.nargo` package:

```bash
nargo configure backend_directory ~/something/.nargo
```

### Project Impact

Nice-to-have

### Impact Context

I am building a prove bulding server, that is based on SGX enabled machines to allow faster server side proof generation without compromising user privacy.
SGX's configuration requires us to package all files in a directory so that it can be cryptographicaly signed. As the `.nargo` location cannot be changed it is outside of this file and SGX cannot sign to attest its version.

### Workaround

Yes

### Workaround Description

Currently remapping the signature structure in gramine to support different signed file location

### Would you like to submit a PR for this Issue?

Maybe

### Support Needs

Documentation on building nargo_cli locally to test changes

**Comment by TomAFrench** [comment]
We actually support using a backend at a custom path by using the `NARGO_BACKEND_PATH` environment variable.

https://github.com/noir-lang/noir/blob/cb4c1c5264b95d01f69d99f916ced71ad9cdc9d1/tooling/backend_interface/src/lib.rs#L65

You would have to download/move the backend binary into the directory you're loading into SGX yourself but this is possible currently.
