### ISSUE TITLE
Bump Noir toolings to use barretenberg v0.26.0

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#4468]
```[tasklist]
### Blockers
- [ ] https://github.com/AztecProtocol/aztec-packages/pull/4569
```

Useful for making features like e.g. Poseidon2 available.

**Comment by Savio-Sou** [comment]
@guipublic would you like to do the honor? See if this fixes the Poseidon2 auto-discarded issue due to missing backend implementation in the current version of barretenberg used.

**Comment by TomAFrench** [comment]
I can handle this.

**Comment by TomAFrench** [comment]
There's no 0.26.0 release of @aztec/bb.js on npm
