### ISSUE TITLE
Cannot use type aliases of structs in paths

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#4469]
### Aim

```rs
use std::{collections::map::HashMap, hash::{BuildHasherDefault, poseidon::PoseidonHasher}};

type Alias = HashMap<Field, Field, 10, BuildHasherDefault<PoseidonHasher>>;

fn main() {
    let map1 = HashMap::default();

    // panic here
    let map2 = Alias::default();
}
```

### Expected Behavior

To be able to use `Alias` anywhere `HashMap` is expected, including in paths

### Bug

```
The application panicked (crashed).
Message:  type aliases cannot be used in type namespace
Location: compiler/noirc_frontend/src/hir/resolution/import.rs:159

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml
exit 101
```

### To Reproduce

1.
2.
3.
4.

### Project Impact

None

### Workaround

Yes

### Workaround Description

The original type (`HashMap` in this case) must be used instead of the alias

### Installation Method

None

### Would you like to submit a PR for this Issue?

None

**Comment by asterite** [comment]
To be able to work on this we first need to implement #6000.

The reason is that we can solve the alias but it solves to a type that has concrete generics, and then we are calling a method on that... but we don't have code yet to support that, so we first need to implement that.
