### ISSUE TITLE
When executing codegen-verifier, the name used for the generated Solidity contracts is currently fixed

### ISSUE THREAD

**Issue by nicolasgarcia214** [noir-lang/noir#4477]
When executing the codegen-verifier across a workspace, all generated Solidity contracts receive the same name, creating organizational challenges. Additionally, the name "plonk_vk" can be misleading when the proving backend differs from PLONK scheme.

**Comment by TomAFrench** [comment]
Closing as `nargo` does not expose this feature anymore but leaves it to the backend.

**Comment by partylikeits1983** [comment]
A bit annoying that codegen-verifier used to work with nargo, now it doesn't in new versions. How to generate a verifier in solidity? The docs got worse.
