### ISSUE TITLE
Unreachable error for large circuits with NoirJS

### ISSUE THREAD

**Issue by madztheo** [noir-lang/noir#4481]
### Aim

I'm trying to generate proofs with NoirJS (v0.23.0) for a circuit with over 2 million constraints and consuming a fair amount of memory (over 30GB with nargo). But the proof generation fails with an `unreachable` error. I presume this error is because the proof generation consumes too much RAM, but the error fails to show that clearly, so in practice it's not possible to know for sure. 

Note that even when I split the circuit into multiple smaller circuits, the bigger ones with around 800k constraints (i.e. the RSA signature verifications) also fail with the same error (they consume around 8GB of RAM when executed with nargo), while the smaller ones with fewer constraints work just fine.

You can find the Noir code in question [here](https://github.com/ocelots-app/passport-verifier/blob/main/src/main.nr)

### Expected Behavior

Either succeed in generating the proof or fail with a descriptive message about the reason of the error.

### Bug

When trying to generate the proof with NoirJS, both with Node.js and in the browser, I run into the `unreachable` error.

Here's the stack trace with Node.js:
```
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error [RuntimeError]: unreachable
    at wasm://wasm/0177a776:wasm-function[14557]:0x58d9a8
    at wasm://wasm/0177a776:wasm-function[175]:0x242d6
    at wasm://wasm/0177a776:wasm-function[170]:0x2415f
    at wasm://wasm/0177a776:wasm-function[134]:0x2340b
    at BarretenbergWasmMain.call
``` 

And the stack trace when using NoirJS in the browser:
```
Uncaught (in promise) RuntimeError: unreachable
    at 017352ae:0x57f629
    at 017352ae:0x21ba6
    at 017352ae:0x21a2f
    at 017352ae:0x217ae
    at I.call (blob:http://localhost:3000/be17a5a3-1865-4fb9-8007-0eb7d84e1ec2:2:25102)
    at I.callWasmExport (blob:http://localhost:3000/be17a5a3-1865-4fb9-8007-0eb7d84e1ec2:2:27743)
    at a (blob:http://localhost:3000/be17a5a3-1865-4fb9-8007-0eb7d84e1ec2:2:8039)
```

### To Reproduce

1. Clone my repo `git clone https://github.com/ocelots-app/passport-verifier.git`
2. Make sure to use nargo 0.23.0 or at the very least 0.22.0
3. Run `nargo compile` to get the circuit bytecote 
4. Import the bytecode into a NoirJS project to generate the proof, either in Node.js or in the browser
5. Run the web app or Javascript file with node and wait to see the error show up after a few seconds

Note that the circuit above has a lot of inputs, so it might be tricky to test it out (and I haven't come up with mock inputs yet). But since the error seems to be linked to memory over-consumption, you could take any circuit with a lot of constraints (I'd say over 700k constraints). In my circuit, the RSA signature verification is the main culprit for the memory consumption, so a circuit using the RSA lib should be a good way to test it out.

### Project Impact

Nice-to-have

### Impact Context

I have no direct need at the moment to generate proofs in the browser or on a Node.js server, only to verify them. Note that I haven't tried proof verification with that same circuit in NoirJS yet. However, this could be nice to have a clearer error message when the proof generation fails, which seems to be linked to memory consumption here.

### Workaround

None

### Installation Method

Binary (`noirup` default)

### Nargo Version

nargo version = 0.23.0 noirc version = 0.23.0+5be9f9d7e2f39ca228df10e5a530474af0331704

### NoirJS Version

0.23.0

### Would you like to submit a PR for this Issue?

None

**Comment by Savio-Sou** [comment]
Thanks for submitting the detailed issue!

> the bigger ones with around 800k constraints (i.e. the RSA signature verifications) also fail with the same error (they consume around 8GB of RAM when executed with nargo)

NoirJS by default uses bb.js for proving under the hood, which is WASM-based and hence comes with WASM's 4GB memory limit.

That with UltraPlonk translates to a cap at 2^19 (~500k) constraints, which could explain why this is failing.

**Comment by TomAFrench** [comment]
I'm going to close this issue as noir_js no longer handles proving and users are expected to use the @aztec/bb.js package directly. As a result any issues related to proof generation should be opened on https://github.com/AztecProtocol/aztec-packages
