### ISSUE TITLE
Type aliases cannot be used in main function signature

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#4500]
### Aim

I'm trying to compile the program 

```rust
type Foo = u8;

fn main(x: Foo) {

}

```

### Expected Behavior

Should compile successfully

### Bug

Compilation fails with error

```
error: Only sized types may be used in the entry point to a program
  ┌─ /home/tom/Programming/aztec/noir/temp/src/main.nr:3:12
  │
3 │ fn main(x: Foo) {
  │            --- Slices, references, or any type containing them may not be used in main or a contract function
  │
```

### To Reproduce

1.
2.
3.
4.

### Project Impact

None

### Workaround

None

### Installation Method

None

### Would you like to submit a PR for this Issue?

None

**Comment by jfecher** [comment]
This is due to the check here: https://github.com/noir-lang/noir/blob/master/compiler/noirc_frontend/src/hir_def/types.rs#L706-L709
