### ISSUE TITLE
Cast to U128 Struct (or return native u128) for working with Wei values

### ISSUE THREAD

**Issue by n4ru** [noir-lang/noir#4524]
### Problem

Following up from discord discussion: https://discord.com/channels/1113924620781883405/1209863956122959892

Since the removal of integers above u64, it's incredibly cumbersome to work with any values meant to represent Wei which feels like a common pattern.

Since 2^64 is only ~18e18, we have to use Fields. This presents its own issues as the only operation we get is equality and `lt`, but in many cases one might want to sum or multiply, and there's no easy way to do that with Fields. So we can use the U128 struct, but...

The provided U128 struct doesn't allow casting from Fields, and is additionally more expensive than native integers. It would be really great to get back u128 or anything higher than u64 that could properly represent a Wei balance cheaply, or at least a way to cast into the U128 struct easily from a Field element.

### Happy Case

1. Have Field that represents a balance in Wei
2. Use magic function
3. Have u128 or equivalent that represents said balance in Wei
4. Do math on multiple u128 values

### Project Impact

Blocker

### Impact Context

There's no easy way to deal with wei balances currently that doesn't involve significant extra overhead compared to native support, and no easy way to cast from Fields to U128.

### Workaround

None

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
This should be possible using the `from_integer` function which also accepts fields.

https://github.com/noir-lang/noir/blob/b94adb92657e2b4a51dc7216a88e080aed1cf8b0/noir_stdlib/src/uint128.nr#L115-L122

**Comment by n4ru** [comment]
Thanks!

Suggesting an update to the docs as this wasn't clear.

https://github.com/noir-lang/noir/commit/7aff28ade7528f4bc78712bf30f6a7d623186731

**Comment by Savio-Sou** [comment]
Thanks @n4ru!

You should be able to create a PR on https://github.com/noir-lang/noir/pulls/, where typing `Resolves #4524` in the PR body should bind that to this Issue.
