### ISSUE TITLE
Brillig's `modulo_instruction` uses 254-bit integer multiplication

### ISSUE THREAD

**Issue by fcarreiro** [noir-lang/noir#4543]
### Aim

Transpile to AVM bytecode

### Expected Behavior

Should avoid using u254 integer ops, use Field instead or some other trick

### Bug

`modulo_instruction` uses 254-bit integer multiplication to implement `to_radix`. However, that will not be supported in the AVM. Discussed with @sirasistant.

### To Reproduce

1.
2.
3.
4.

### Project Impact

None

### Workaround

None

### Installation Method

None

### Would you like to submit a PR for this Issue?

None

**Comment by fcarreiro** [comment]
For the record, SUB is also used on 254 int

**Comment by sirasistant** [comment]
fixed in https://github.com/AztecProtocol/aztec-packages/pull/5208
