### ISSUE TITLE
Add error message when trying to use `&T` as a type or `&x` as an expression

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#4548]
### Problem

Noir doesn't have immutable references but due to its similarity with Rust, users may try to use them anyway.

### Happy Case

Users should get a nice error message indicating Noir doesn't have immutable references. Potentially with a link to docs or similar explaining why this is.

### Project Impact

None

### Workaround

None

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
Agreed, we can likely have this as just a warning similar to the rust lint.
