### ISSUE TITLE
Auto return doesn't work with arrays

### ISSUE THREAD

**Issue by Globallager** [noir-lang/noir#455]
# Description

## Aim

Auto returning the value of an array without the need to specify it in `Prover.toml` before proving.

The feature was introduced in https://github.com/noir-lang/noir/pull/360.

## Expected behavior

*main.nr*
```rust
fn main(x : Field, y : pub Field) -> pub [Field; 2] {
    [x + y, y]
}
```

*Prover.toml*
```toml
x = "1"
y = "2"
return = []
```

Expect Verifier.toml to be auto-filled as:

*Verifier.toml*
```toml
y = "0x0000000000000000000000000000000000000000000000000000000000000002"
return = [
    "0x0000000000000000000000000000000000000000000000000000000000000003",
    "0x0000000000000000000000000000000000000000000000000000000000000002",
]
```

## Bug

Instead, was prompted with the error below when proving:

```
The parameters in the main do not match the parameters in the Prover.toml file. 
Please check `return` parameter
```

# To reproduce

1. Fill *main.nr* as above
2. Run `nargo build`
3. Fill *Prover.toml* as above
4. Run `nargo prove p`

# Environment

- OS: Linux (x86_64-pc-linux-gnu)

For `nargo` users

- _noir-lang/noir_ commit cloned: [e885d42](https://github.com/noir-lang/noir/commit/e885d42634adfd7de69bd8bd166d82d8e3c0c8b2)
- Proving backend
  - [x] default
    - Clang: 10.0.0-4ubuntu1
  - [ ] wasm-base

**Comment by vezenovm** [comment]
I changed this to enhancement as this is not supported yet with the auto-return feature: https://github.com/noir-lang/noir/blob/1d1b592039fa73ce561d6b6886c36b02b36ada53/crates/nargo/src/cli/prove_cmd.rs#L96

The error makes sense as you did specify an empty return array.
