### ISSUE TITLE
Maybe `Driver`'s `check` method could be skipped given that now it is a pass through method

### ISSUE THREAD

**Issue by ilitteri** [noir-lang/noir#456]
> I think that this issue requires a discussion label

This issue is to track this [note](https://github.com/noir-lang/noir/blob/master/crates/noirc_driver/src/lib.rs#L121) and was requested [here](https://github.com/noir-lang/noir/pull/443#discussion_r1014644380).

# Problem

After #443 the `build` of the `Driver` is like a passthrough method.

# Solution

Make `analyze_crate` public and use it instead of `build` (removing it).

# Alternatives considered

- Move the `analyze_crate` logic into `build`.
- This could also stay like it is the idea of this issue is to discuss it.

# Additional context

N/A

**Comment by kevaundray** [comment]
Related to @jfecher issue about renaming build to check

**Comment by jfecher** [comment]
The test PR had to reorganize this slightly and I ended up just deleting the wrapper function entirely there. Once that PR is merged this issue can be closed
