### ISSUE TITLE
Please implement deflating heap arrays from foregin calls

### ISSUE THREAD

**Issue by LogvinovLeon** [noir-lang/noir#4561]
### Aim

I want to receive a two dimensional array from an oracle.

### Expected Behavior

It works

### Bug

```
Failed calling external resolver. JSON decode error: invalid type: map, expected a string at line 1 column 30
```

### To Reproduce

1. `git clone https://github.com/vlayer-xyz/noir-oracles-2d-arrays-repro.git`
2. `cd noir-oracles-2d-arrays-repro`
3. `rm -r target`
4. `yarn install`
5. `yarn start`
6. (In a separate terminal) `nargo prove --oracle-resolver http://localhost:5555`

Gets error:
```
Failed calling external resolver. JSON decode error: invalid type: map, expected a string at line 1 column 30
```

### Project Impact

Nice-to-have

### Impact Context

Without this - I need to linearise arrays and have serde logic in Noir

### Workaround

Yes

### Workaround Description

custom serde

### Installation Method

Binary (`noirup` default)

### Nargo Version

nargo version = 0.26.0
noirc version = 0.26.0+c46b164ce56e6a8f81255fb17eb6539bd040f336
(git version hash: c46b164ce56e6a8f81255fb17eb6539bd040f336, is dirty: false)

### Would you like to submit a PR for this Issue?

None

**Comment by LogvinovLeon** [comment]
Also - the type in `@noir-lang/acvm_js` doesn't support 2d arrays
```typescript
export type ForeignCallOutput = string | string[]
```
 For context: I'm trying to prove ethereum receipt inclusion. Receipts include arrays of logs. And each data is an array by itself, so would be really nice to have nested structures support in oracles

**Comment by marekkirejczyk** [comment]
@LogvinovLeon Would you add reproduce?

**Comment by LogvinovLeon** [comment]
Here is the repro: https://github.com/vlayer-xyz/noir-oracles-2d-arrays-repro

**Comment by LogvinovLeon** [comment]
Use cases for it:
* We want to ask an oracle to return us an array of storage proofs. Each storage proof is a struct containing arrays as it's fields.
* Because Option type is not supported in brillig we want to simulate option with a `struct Optional<T> { value: T, is_some: bool}`, but brillig does not support nested structs

**Comment by Savio-Sou** [comment]
Thanks @LogvinovLeon. Updated the Issue body with what I believe are the steps for reproduction, let us know if any of them is in conflict with your intention / experience 🙌
