### ISSUE TITLE
Add NoirJS error message when proving circuits compiled at an incompatible version

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#4571]
### Problem

During ETHGlobal London, some users were having a hard time debugging NoirJS Issues they had.

Turned out they were attempting to prove circuits compiled from a different incompatible version of Nargo(?) / noir_wasm(?).

Credit to @catmcgee @jzaki for reporting the problem.

### Happy Case

We have https://github.com/noir-lang/noir/issues/2712.

We can't achieve the same with NoirJS unless we bring noir_wasm into the package. That said, an incompatibility error message in the meantime would be a helpful addition.

### Project Impact

None

### Workaround

None

### Additional Context

We have `noir_version` in compiled circuits (.json files) that should help.

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
We currently have an error message for this during circuit execution.

https://github.com/noir-lang/noir/blob/6a9ea35c4f1578058179aa08eedf44eb18bad4a1/acvm-repo/acvm_js/src/execute.rs#L64-L65

**Comment by Savio-Sou** [comment]
> Failed to deserialize circuit. This is likely due to differing serialization formats between ACVM_JS and your compiler

@catmcgee @jzaki was that the error you get?

**Comment by TomAFrench** [comment]
Closing this as we have errors on noir packages which deserialize circuits.
