### ISSUE TITLE
Update EC docs with new public key function

### ISSUE THREAD

**Issue by michaeljklein** [noir-lang/noir#4574]
### Problem

`docs/docs/noir/standard_library/cryptographic_primitives/ec_primitives.md` currently lacks reference to `eddsa_to_pub` and instead defines a similar function in-line.

### Happy Case

Reference [`eddsa_to_pub`](https://github.com/noir-lang/noir/blob/master/noir_stdlib/src/eddsa.nr#L72C8-L72C20)

### Project Impact

Nice-to-have

### Workaround

None

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
Closing as this function is being removed in #6591
