### ISSUE TITLE
Cannot append slices

### ISSUE THREAD

**Issue by signorecello** [noir-lang/noir#4609]
### Aim

My goal is to append one slice to another

### Expected Behavior

I expected it to return a new slice with both slices concatenated

### Bug

I get an error in the form of:
`ICE: should have slice capacity set at address v45 being loaded into v112`

### To Reproduce

1. Use this snippet:
  ```rust
  fn main(a: Field, b: pub Field) {
      let sl = [a, 1, 2, 3].as_slice();
      let sl2 = [b, 5, 6].as_slice();
      let sl3 = sl.append(sl2);
  }
  ```
2. Run nargo test with something such as:

```rust
#[test]
fn test_main() {
    main(0, 4);
}
```

### Project Impact

None

### Workaround

None

### Installation Method

Binary (`noirup` default)

### Nargo Version

nargo version = 0.25.0 noirc version = 0.25.0+cba1bff95911a7a1d3ea714735786db595a435cf (git version hash: cba1bff95911a7a1d3ea714735786db595a435cf, is dirty: false)

### Would you like to submit a PR for this Issue?

None

**Comment by vezenovm** [comment]
As `as_slice` moved to a builtin we are not accurately handling it in the slice capacity tracker. Will push a fix soon.
