### ISSUE TITLE
"nargo test" taking forever on 0.25.0

### ISSUE THREAD

**Issue by harshnambiar** [noir-lang/noir#4636]
### Aim

I was making the necessary code changes to be able to adhere to 0.25.0 and the Noir add on shows no syntactic error. However on running "nargo test" , it just freezes (note: the terminal doesn't crash but the machine does heat up pretty hard).

### Expected Behavior

The tests should pass like before since the only change has been replacement of u84 with the more acceptable U128 as present in the standard Noir library. The tests should all pass. If they fail, that is also ok, but the tests should run.

### Bug

The tests just freeze at the beginning itself, and nothing changes in at least 7 mins (after which the command was manually terminated).

### To Reproduce

1. clone the [fraction](https://github.com/resurgencelabs/fraction) repository
2. cd fraction
3. nargo test

### Project Impact

None

### Workaround

None

### Installation Method

None

### Nargo Version

nargo 0.25.0

### Would you like to submit a PR for this Issue?

None

**Comment by jfecher** [comment]
I've confirmed on master I'm seeing the same. The program runs for about 3:30s for me until my computer runs out of memory and it is OOM killed.

**Comment by harshnambiar** [comment]
I tried the same after upgrading to 0.26.0. No changes.

**Comment by asterite** [comment]
I just tried this (after removing the `compiler_version` line in `Nargo.toml`) and the tests ran almost immediately, so something in the past might have fixed this. Please reopen if that's not the case for you.
