### ISSUE TITLE
Format and raw strings ignore escape characters

### ISSUE THREAD

**Issue by michaeljklein** [noir-lang/noir#4642]
### Aim

Attempted to use escape characters in format or raw strings

### Expected Behavior

1. reject invalid escape character `\999..`
2. convert escaped characters to expected values, e.g. `\n` becoming a newline
3. the same behavior between the different string types, besides exceptions for formatting and `#`'s

### Bug

Format strings `f".."` and raw strings `r".."` currently ignore `\n`, and other escaped characters.

For example:
```rust
    print(f"hello world!\n \0 \99999999");
    print(r#"hello world!\n \0 \99999999"#);
```

`nargo execute` gives:

```bash
hello world!\n \0 \99999999[name_of_program] Circuit witness successfully solved
```

### To Reproduce

1. put one of the `print`'s above into a test file
2. `nargo execute`

### Project Impact

None

### Workaround

Yes

### Workaround Description

use regular strings for escaped characters and format strings for formatting, like so:

```rust
  print(f"hi there, {name}!");
  print("\n");
```

### Installation Method

Binary (`noirup` default)

### NoirJS Version

0.24.0+722dc969e8b09e5a6fd56b094b6939e9330233f6

### Would you like to submit a PR for this Issue?

None

**Comment by asterite** [comment]
This will be fixed by #6703

I'm commenting this because it will only "fix" it for fmtstring. Raw strings seem to work well... or at least in Rust if you do "\n" inside a raw string, it prints "\n", not a newline, and it seems escape chars don't work inside raw strings.
