### ISSUE TITLE
Benchmarking each step of the compilation process

### ISSUE THREAD

**Issue by vezenovm** [noir-lang/noir#4658]
### Problem

Every so often we have bugs that arise such as https://github.com/noir-lang/noir/issues/4395 where users cannot compile certain valid code due to compile time blowup. 

It would be easier to nail down and debug these programs if we had an option to similar to `--show-ssa` that displayed how much time we are spending on each compilation pass. 

### Happy Case

We should be able to discern how much time is spent per compilation step.

Ideally after this is done, we could have a similar tool to the gate checks count that displays how compilation times increase/decrease on certain tests due to PRs.

### Project Impact

None

### Workaround

None

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
`NOIR_LOG=trace nargo compile` will currently display timings for all of the different SSA passes btw.

**Comment by vezenovm** [comment]
@TomAFrench Thank you good to know I forgot about that. I will change this issue to make a tool similar to gate counts check then.

**Comment by vezenovm** [comment]
I just ran that and it is slightly hard to discern exactly the timings as everything is just timestamped. Perhaps it would be worth to still have a command that pretty prints some benchmarking info.

**Comment by vezenovm** [comment]
Can we have the trace output the difference between enter and exit: 
```
2024-03-27T16:33:32.975201Z TRACE compile_no_check{function_name="main"}:create_circuit:ssa_generation:fold_constants: noirc_evaluator::ssa::opt::constant_folding: enter
2024-03-27T16:33:34.866814Z TRACE compile_no_check{function_name="main"}:create_circuit:ssa_generation:fold_constants: noirc_evaluator::ssa::opt::constant_folding: exit
After Constant Folding:: 1891
```
