### ISSUE TITLE
Incorrect compiler error when value returned after a code block uses unnecessary parentheses

### ISSUE THREAD

**Issue by pventuzelo** [noir-lang/noir#4677]
### Aim

We (https://github.com/FuzzingLabs) found that the compiler raises incorrectly an error when the value returned after a code block uses unnecessary parentheses.

### Expected Behavior

No error should be returned.

### Bug

When the returned value uses unnecessary parentheses and occurs right after a code block, the compiler will misinterpret the type as **`(type)`**. For example, if the returned value is a **`u32`**, the compiler will interpret it as a **`(u32)`**, which is not a valid type in the language.

The reason seems to be due to the presence of unnecessary parentheses, which are usually well ignored by the compiler but not in this specific situation, and end up distorting the type.

As demonstrated in the code example, the occurrence of this error does not depend on the type used or the content of the code block. The return statement can involve variables or multiple operations, as long as unnecessary parentheses are used somewhere, the error will occur.

The error occurs with the latest compiler version on the master branch. The error message is as follows:

```
error: expected type Field, found type (Field)
```

### To Reproduce

1. Create a Noir project with the following command: **`nargo new test_issue`**
2. Paste the code below into the file main.nr
3. Compile the project using the following command: **`nargo compile`**

```rust
// The return type is Field, but the compiler misinterprets the type of the returned value 
// when the return follows a block and unnecessary parentheses are used.
fn func1() -> Field {
    if true { // Just here to create a valid code block
    }
    (2*1)*(2*4) // Random operation that use unnecessary parentheses
}

// The return type and the content of the block are irrelevant.
//The usage of variables also doesn't matter.
fn func2() -> u32 {
    let mut var: u32 = 1;
    if true {
        var = 2; // Random instruction
    }
    (var + var)
}

// The error doesn't appear if there is an instruction between the code block and the return.
fn func3() -> Field {
    if true {
    }
    let var = 1; // Random instruction
    (1 + 2)
}

fn main() {
}

```

### Project Impact

None

### Workaround

None

### Installation Method

None

### Would you like to submit a PR for this Issue?

None

**Comment by asterite** [comment]
This no longer errors. I think it was fixed in the past where we made `if` parse as its own statement rather than only as an expression.
