### ISSUE TITLE
Compiler crashing when using constant derived from other constant

### ISSUE THREAD

**Issue by aajj999** [noir-lang/noir#4689]
### Aim

Create a global constant using another global constant and then use it to create an array:
```
global L1: u64 = 1;
global L2: u64 = L1 + 1;

type T = [u8; L2];
```

### Expected Behavior

Compiler shouldn't crash. Either should display it as an error in code, or accept this usage of globals.

### Bug

Compilation crashing with:
```
The application panicked (crashed).
Message:  ice: all globals should correspond to a let statement in the interner
Location: compiler/noirc_frontend/src/node_interner.rs:861
```

### To Reproduce

1.  Use https://github.com/vlayer-xyz/repro-derived-constant
2. Run `nargo compile` in the main folder in above repo

### Project Impact

Nice-to-have

### Workaround

Yes

### Workaround Description

Creating globals with hardcoded values without depending on other globals' values.

### Installation Method

Binary (`noirup` default)

### Nargo Version

nargo version = 0.26.0 noirc version = 0.26.0+c46b164ce56e6a8f81255fb17eb6539bd040f336

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
This compiles correctly on master.
