### ISSUE TITLE
OOM when reading from a single large constant array many times

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#4709]
See the linked repo here: https://github.com/AndreiCravtov/noir-crypto-kit/blob/d7db6bc93f60709abad4bda3b810e900b614d068/noir/src/main.nr

This program reads values from a large constant array at constant indices to calculate a constant value `acc`, however it crashes once we reach the loop unrolling phase.

My assumption is that we're creating many unnecessary duplicates of the array contents, we then get `P*P` copies of a `P*P` array which would take horrendous amounts of RAM to store. If this is the case then we should look at ways to deduplicate constant arrays similarly to how we handle constant numeric values.

**Comment by TomAFrench** [comment]
This is a blocker for using arrays as lookup tables of any considerable size.

**Comment by jfecher** [comment]
> My assumption is that we're creating many unnecessary duplicates of the array contents

Yeah, this is because globals are "inlined" during monomorphization when they're used. Maybe we can add a quick fix to remember the global's ID and cache its value per-function instead.
