### ISSUE TITLE
Remove `Location::dummy`

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#472]
# Problem

`Location::dummy` is a Location pointing to the beginning of whichever FileId happens to be assigned index 0. Its usage as a default Location introduced by PR #437 is thus not ideal as it is unlikely to point to the actual location of the error being issued.

# Solution

To remove this, one possible method is to add locations to ssa blocks. The only current user of Location::dummy is creating short-circuited blocks and adding a `Constrain` node with its location set to `None`, which eventually defaults to `Location::dummy`. The function that does this should at least have access to the current block and be able to pull a Location from there.

# Alternatives considered

Alternatively, we could store Locations on other instructions in the block, or on the condition of if statements. This could be more accurate and less confusing since users would not have to guess which condition within an entire block is the failing one.

**Comment by kevaundray** [comment]
@jfecher can this be closed?

**Comment by jfecher** [comment]
@kevaundray I think so, I can't find the method anymore.
