### ISSUE TITLE
Run verifier in CosmWasm

### ISSUE THREAD

**Issue by hu55a1n1** [noir-lang/noir#4727]
### Problem

I would like to run the Noir verifier in a CosmWasm smart contract. This is currently not possible because the barretenberg backend depends on FFI/C++ code. 

### Happy Case

I see three ways to solve this -
* Use the Marlin backend (assuming it is in pure Rust)
* Write a custom rust verifier from scratch based on the solidity verifier code
* Rewrite the barretenberg backend's verifier code in pure Rust (and adapt noir-rs to use it)

### Project Impact

Blocker

### Impact Context

This is a major blocker for us and the choice of Noir as a ZKP stack for our protocol depends on us being able to run the verifier in a CosmWasm smart contract. 

### Workaround

None

### Workaround Description

AFAICT there is no workaround to this currently. 

### Would you like to submit a PR for this Issue?

Maybe

### Support Needs

I would like to know the best way to implement this.

**Comment by Savio-Sou** [comment]
Thanks for creating the Issue!

> Write a custom rust verifier from scratch based on the solidity verifier code

> Rewrite the barretenberg backend's verifier code in pure Rust

Either one of these could be valid, where the [Marlin backend](https://github.com/noir-lang/marlin_arkworks_backend) for Noir is out of date.

The choice would be on which of reimplementing Solidity or C++ code is preferred.

For easy reference, the Solidity verifier logic for the default proving backend (barretenberg) is located here: https://github.com/AztecProtocol/aztec-packages/tree/a9a349db3902970a2b484b5e1509931423ac5775/barretenberg/sol

**Comment by TomAFrench** [comment]
I'm going to close this issue as proof verifiers are not developed in this repository. Please feel free to open an issue wrt to a lightweight wasm verifier in https://github.com/AztecProtocol/aztec-packages.
