### ISSUE TITLE
`nargo info` error: The backend encountered an error: "dyld[3537]: Library not loaded...

### ISSUE THREAD

**Issue by iAmMichaelConnor** [noir-lang/noir#4731]
### Aim

I just installed Noir fresh on my Mac (OS Sonoma 14.4.1).
Installed Noirup.
Ran `noirup`.
Then `nargo new my-project`

```
fn main(x: Field, y: pub Field) {
    assert(x != y);
}

#[test]
fn test_main() {
    main(1, 2);

    // Uncomment to make test fail
    // main(1, 1);
}
```
Figured I'd run `compile` and `info` to see if things were working.

`nargo info` resulted in this error.

```
$ nargo info

The backend encountered an error: "dyld[37922]: Library not loaded: 
/usr/local/opt/llvm@16/lib/libunwind.1.dylib\n  Referenced from: 
<D9AA1763-BA8F-34E5-B2A0-6A25305D5B13> 
/Users/mike/.nargo/backends/acvm-backend-barretenberg/backend_binary 
(built for macOS 13.6 which is newer than running OS)\n  
Reason: tried: '/usr/local/opt/llvm@16/lib/libunwind.1.dylib' (no such file),
'/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/llvm@16/lib/libunwind.1.dylib' (no such file),
'/usr/local/opt/llvm@16/lib/libunwind.1.dylib' (no such file)\n"
```

I saw this part in particular: `(built for macOS 13.6 which is newer than running OS)` and thought, "Ok, I guess I should finally install that new Mac OS update". So I did. Tried again and got this:

```
$ nargo info     

The backend encountered an error: "dyld[3537]: Library not loaded:
/usr/local/opt/llvm@16/lib/libunwind.1.dylib\n  Referenced from:
<D9AA1763-BA8F-34E5-B2A0-6A25305D5B13>
/Users/mike/.nargo/backends/acvm-backend-barretenberg/backend_binary\n 
Reason: tried: '/usr/local/opt/llvm@16/lib/libunwind.1.dylib' (no such file),
'/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/llvm@16/lib/libunwind.1.dylib' (no such file), 
'/usr/local/opt/llvm@16/lib/libunwind.1.dylib' (no such file)\n"
```

I guess I need to install some llvm stuff? But I didn't see a "prerequisites" section in the docs, so maybe this is an unexpected bug?

### Expected Behavior

.

### Bug

.

### To Reproduce

1.
2.
3.
4.

### Project Impact

None

### Workaround

None

### Installation Method

Binary (`noirup` default)

### Nargo Version

nargo version = 0.25.0 noirc version = 0.25.0+3f676051a6073d6eabdc7fee68e4b522334344f6

### Would you like to submit a PR for this Issue?

None

**Comment by iAmMichaelConnor** [comment]
Oh wow, in 2.5 years, it turns out I've never written code on this Mac (only on the mainframe), so I'd never installed command line tools or anything. Clean slate.

**Comment by iAmMichaelConnor** [comment]
Perhaps the docs need to mention this extra `brew install llvm@16` prerequisite? I'll let you close the issue in case you want to add something to the docs :)

**Comment by TomAFrench** [comment]
Did this only happen on `nargo info` and not `nargo compile`? If so it's likely a `bb` issue rather than nargo.

**Comment by iAmMichaelConnor** [comment]
Yeah it was just when I ran `nargo info` - `nargo compile` worked.
Fair enough!

**Comment by iAmMichaelConnor** [comment]
I wasn't sure whether `nargo test` actually used the underlying proving system, or whether it solves things solely within the acvm. E.g. the `assert(x != y)` function in my snippet is proving system agnostic, I'd imagine?

**Comment by TomAFrench** [comment]
Yep, `nargo test` should be entirely proving system agnostic, we don't ever speak to the backend for that as we can check for failed constraints within the ACVM.

**Comment by TomAFrench** [comment]
I'm gonna link this back to [the issue on bb installation](https://github.com/AztecProtocol/aztec-packages/issues/4190) and just close this in the meantime.
