### ISSUE TITLE
No `constraint is always false` error within if statement

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#474]
# Description

## Aim

Running the code in the `9_conditional` test

## Expected behavior

Expected a `constraint is always false` error to be issued on the line
```rs
fn must_be_zero(x: u8) {
    constrain x == 0;
}
```
As a result of this call:
```rust
must_be_zero(1);
```

## Bug

The current ssa pass does not seem to catch this error, it was found when it was caught by the partial evaluator pass in PR #462 .

# To reproduce

(Describe the steps to reproduce the behavior.)

1. `cd crates/nargo/tests/test_data/9_conditional`
2. `nargo prove p`
3. Observe that no error is issued

**Comment by guipublic** [comment]
The test `9_conditional` is not supposed to fail because the branch corresponding to `must_be_zero(1);` is not executed.
You would need to change `a ` to 1 in the prover .toml in order to trig the constrain is always false error.

**Comment by jfecher** [comment]
I would expect the error to still be issued because `a` is a private variable and the circuit should not change if the value of an input is changed

**Comment by guipublic** [comment]
Yes the circuit should not change and in fact we should never get the constrain is always false error in this example.
I tried again with the latest master and I can generate the proof with `a=0` and I get a `could not satisfy all constraints` with a=1, which is fine now. The issue must have been indirectly fixed by the recent fixes.

**Comment by jfecher** [comment]
This is a bug in ssa which inconsistently issues the "constraint is always false" error. With simpler code:
```
use dep::std;
fn main(a: u32) {
    if 29 as u32 == a {
        constrain false;
    }
}
```
(a = 0 in Prover.toml)
It does issue "error: Constraint is always false." The difference seems to be the lack of a function requiring inlining to see that it is always false here.

**Comment by guipublic** [comment]
This is something different, indeed it works with function because they get the conditional predicate. Without the function, we have a bug and it is related to my comment in the short-circuit PR where I say I will handle constant folding when we are under assumption in another PR.
