### ISSUE TITLE
Benchmark execution and proving performances in CI

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#4740]
### Problem

We do not currently have comprehensive and objective insights into what Noir's execution and (when paired with Barretenberg) proving performances are across PRs and versions.

### Happy Case

Extend the [`gates_report.yml`](https://github.com/noir-lang/noir/blob/dbb86acd43de5d34905c8e7cb47cff7afc8a6071/.github/workflows/gates_report.yml) action to also run and report [`zk_bench`](https://github.com/noir-lang/zk_bench)'s Noir portion of execution and proving benchmarks.

### Project Impact

None

### Workaround

None

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
> Extend the [gates_report.yml](https://github.com/noir-lang/noir/blob/dbb86acd43de5d34905c8e7cb47cff7afc8a6071/.github/workflows/gates_report.yml) action to also run and report [zk_bench](https://github.com/noir-lang/zk_bench)'s Noir portion of execution and proving benchmarks.

Small modification to this: We'll be wanting to move the source of truth on Noir benchmarks into this repository along with the suite of programs we're benchmarking.

**Comment by TomAFrench** [comment]
Superceded by https://github.com/AztecProtocol/aztec-packages/issues/6060
