### ISSUE TITLE
Compiler panic when you modify the value of an element of a slice

### ISSUE THREAD

**Issue by pventuzelo** [noir-lang/noir#4741]
### Aim

We (https://github.com/FuzzingLabs) found that the compiler panics when you modify the value of an element of a slice

### Expected Behavior

No panic should occur.

### Bug

The compiler panics whenever you modify the value of an element of a slice. This issue doesn't depend on the size of the slice or the values used; it only happens with the slice type.

The compiler still panics if you modify the entire slice, but the error message is different.

The issue occurs with the latest compiler version on the master branch. The error message is as follows:

```
The application panicked (crashed).
Message:  Found unexpected tree combination during SSA: (Branch([Leaf(Mutable(Id(5), Numeric(Unsigned { bit_size: 64 }))), Leaf(Mutable(Id(6), Slice([Numeric(Signed { bit_size: 32 })])))]), Leaf(Array([Numeric(Signed { bit_size: 32 })], 1)))
Location: compiler/noirc_evaluator/src/ssa/ssa_gen/value.rs:152
```

The error message obtained with modification of the entire slice is as follows:

```
The application panicked (crashed).
Message:  internal error: entered unreachable code: assign: Expected lhs and rhs values to match but found Branch([Leaf(Mutable(Id(5), Numeric(Unsigned { bit_size: 64 }))), Leaf(Mutable(Id(6), Slice([Numeric(Signed { bit_size: 32 })])))]) and Leaf(Normal(Id(8)))
Location: compiler/noirc_evaluator/src/ssa/ssa_gen/context.rs:1035
```

### To Reproduce

```rust
fn main() {
/* panic if you try to modify the value of an element of a slice */
let mut var: [i32] = [1];
var[0] = 3;

/* size or values doesn't matter */
let mut var: [i32] = [1, 2, 3, 4, 5, 99999999, 7, 8, 9];
var[5] = 6;

/* no panic with array */
let mut var: [i32; 1] = [1];
var[0] = 3;

/* another panic message appears when you modify the entire slice */
let mut var: [i32] = [1];
var = [3];
}
```

### Project Impact

None

### Workaround

None

### Installation Method

None

### Would you like to submit a PR for this Issue?

None

**Comment by jfecher** [comment]
This is related to the array to slice coercion which is being used here. The `[1]` literal is now an array literal, not a slice literal which would be `&[1]`. When an array is assigned to a slice variable however, it is coerced via an implicit call to `.as_slice()`. Showing the monomorphized output of the first two lines confirms this:

```rs
fn main$f0() -> () {
    let var$0 = as_slice$as_slice([1]);
    var$l0[0] = 3
}
```

Curiously, adding an explicit `.as_slice()` seems to produce the same monomorphized IR but does not lead to a panic:

```rs
fn main() {
    let mut var: [i32] = [1].as_slice();
    var[0] = 3;
```

Produces the same:

```rs
fn main$f0() -> () {
    let var$0 = as_slice$as_slice([1]);
    var$l0[0] = 3
}
```

Using an explicit slice literal `&[1]` to begin with also fixes the issue, but we should fix the panic regardless. Perhaps the types used in the `as_slice` expression when it is auto-generated are incorrect.

**Comment by asterite** [comment]
I can't reproduce this issue. It might be that this issue existed in the old resolver and the elaborator doesn't have this bug.

I'm closing this, but @vezenovm feel free to open if it reproduces on your side.
