### ISSUE TITLE
Compiler panic when you initialize a slice of composite type with as value, a slice with the exact same type.

### ISSUE THREAD

**Issue by pventuzelo** [noir-lang/noir#4742]
### Aim

We (https://github.com/FuzzingLabs) found that the compiler panics when you initialize a slice of composite type with as value, a slice with the exact same type.

### Expected Behavior

No panic should occur.

### Bug

The previous issue reported shows that modifying a slice causes the compiler to panic. However, this issue demonstrates that initializing a slice of a composite type with another slice of the same type as its value also triggers a compiler panic.

The specific composite type or values used are irrelevant. The issue arises only when assigning an existing slice as the value of the initialized slice. If the value is a slice created within the initialization statement, the panic does not occur.

The issue seems to be due to the compiler treating the slice as an array and attempting to call AsSlice on it. However, the slice doesn’t have a fixed size like an array.

The issue occurs with the latest compiler version on the master branch. The error message is as follows:

```
The application panicked (crashed).
Message:  ICE: Should be have an array length for AsSlice input
Location: compiler/noirc_evaluator/src/ssa/opt/flatten_cfg/capacity_tracker.rs:129
```

### To Reproduce

```rust
struct strct1 {
    elem1: Field,
}

fn main() {
/* Panic when you initialize a slice of arrays with a value of a slice with the exact same type */
let var1: [[i32; 1]] = [[0]];
let var2: [[i32; 1]] = var1;

/* Still panics with other composite types */
let var1: [(i32, u8)] = [(1, 2)];
let var2: [(i32, u8)] = var1;

let var3: [strct1] = [strct1 { elem1: 1321351 }];
let var4: [strct1] = var3;

/* No panic if the slice is created in this initialization sentence, even with an existing array */
let var1: [i32; 1] = [0];
let var2: [[i32; 1]] = [var1];
}
```

### Project Impact

None

### Workaround

None

### Installation Method

None

### Would you like to submit a PR for this Issue?

None

**Comment by vezenovm** [comment]
This looks to be due to incorrect array to slice coercion @jfecher

**Comment by jfecher** [comment]
> and are calling as_slice on a slice.

Looks like a result of `check_declaration` returning the `expr_type` instead of the annotated type again: https://github.com/noir-lang/noir/blob/master/compiler/noirc_frontend/src/hir/type_check/stmt.rs#L352.

IIRC this used to return the annotated type. I don't remember why it was changed a while back.

**Comment by vezenovm** [comment]
> IIRC this used to return the annotated type. I don't remember why it was changed a while back.

I'll test that out

**Comment by vezenovm** [comment]
Looks to be a part of this PR (https://github.com/noir-lang/noir/pull/4152). I'm assuming the simpler logic was fine until this case

**Comment by vezenovm** [comment]
Switching it back fixes the issue
