### ISSUE TITLE
`nargo fmt` panicked

### ISSUE THREAD

**Issue by aajj999** [noir-lang/noir#4746]
### Aim

Formatting code below:

```
fn fun(x: bool) -> (Field, Field) {
    let a = 0;
    let b = 0;

    if (x) {
    }

    (a, b)
}
```

### Expected Behavior

Should not panic, should format

### Bug

```
The application panicked (crashed).
Message:  assertion failed: end >= start
Location: /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/codespan-0.11.1/src/span.rs:21
```

### To Reproduce

1.
2.
3.
4.

### Project Impact

Nice-to-have

### Workaround

None

### Installation Method

Binary (`noirup` default)

### Nargo Version

nargo version = 0.26.0 noirc version = 0.26.0+c46b164ce56e6a8f81255fb17eb6539bd040f336

### Would you like to submit a PR for this Issue?

None

**Comment by ewynx** [comment]
I'm encountering the same issue, is there a workaround?
