### ISSUE TITLE
Add a diagnostic for unused imports in nargo language server

### ISSUE THREAD

**Issue by LogvinovLeon** [noir-lang/noir#4762]
### Problem

When refactoring Noir code, developers face the challenge of manually adjusting imports, as there is currently no automated way to generate required imports or remove unused ones. This manual process results in tedious and error-prone import management.

[Noir Docs](https://noir-lang.org/docs/)
[Example Noir Code with Modules](https://github.com/vlayer-xyz/noir-trie-proofs/tree/vlayer-main/lib/src)

### Happy Case

The Noir VSCode extension has the potential to alleviate this problem by communicating with the Nargo language server. This communication enables the extension to provide import-related diagnostics and actions, streamlining the import management process for developers.

### Project Impact

While not critical, integrating automated import management into the Noir VSCode extension would greatly enhance the development experience by reducing manual effort and improving code cleanliness.

### Impact Context

Without automated import management, developers must spend significant time and effort managing imports manually during refactoring, which hampers productivity and introduces the risk of errors.

### Workaround

None

### Additional Context

Noir already supports unused variables diagnostic and it's very useful

### Existing Functionality

Noir already has a language server implemented, residing in the repository under tooling/lsp. This server provides some functionality, such as reporting unused variables, which are highlighted in the IDE by the Noir extension. However, it currently does not report unused imports. Adding support for this functionality is the focus of this issue.

### Proposal for Resolution

Integrate automated import management features into the Noir VSCode extension, leveraging the capabilities of the existing Noir language server. This includes adding support for reporting and addressing unused imports, similar to the existing functionality for unused variables.

### Would you like to submit a PR for this Issue?

Maybe

### Support Needs

While the implementation of this feature is feasible, it may require collaboration with the community and feedback from project maintainers to ensure alignment with project goals and standards.

**Comment by Kapple14** [comment]
**Additional Context:**
Noir already implemented a language server, residing in the repository under `tooling/lsp`. This language server adheres to the Language Server Protocol (LSP), a standardized protocol for communication between code editors and language servers. While the Noir language server provides some functionality, such as reporting unused variables, currently it cannot report unused imports. This means that while unused variables are highlighted in the IDE by the Noir extension, unused imports are not flagged. Adding support for detecting and managing unused imports through the Noir language server is crucial for enhancing the refactoring experience within the Noir codebase.

**Comment by Savio-Sou** [comment]
This would be a great DevEx add 👍

If anyone is interested in contributing, feel free to create a PR / comment below.
Happy to provide support, answer questions and review works 💪
