### ISSUE TITLE
foreign call executor times out

### ISSUE THREAD

**Issue by drgorillamd** [noir-lang/noir#4772]
### Aim

Using an external RPC oracle resolver, while running multiple tests

### Expected Behavior

not to time-out

### Bug

default minreq timeout ([noir/noir-repo/tooling/nargo/src/ops/foreign_calls.rs ln165](https://github.com/noir-lang/noir/blob/f3eee6c00a9b1ea939c5757d91faac693e909301/tooling/nargo/src/ops/foreign_calls.rs#L165)) is 12 seconds. This is fine for most of the single foreign calls to resolve but, since tests have been parallelised in #4484 , if there is a lot of calls to make with potential lock on the resolver side (awaiting offchain data for instance), it is too short

### To Reproduce

1. Follow the guide to use an external express json rpc server as oracle resolver
2. create an endpoint which sleeps 15 seconds
3. call this oracle from within a noir test

### Project Impact

None

### Impact Context

I've increased it myself in a project conducted on Aztec (integration test ran from within Noir) as our tests were timing-out.

### Workaround

Yes

### Workaround Description

manually increase the timeout when creating a new minreq Builder, as in
https://github.com/defi-wonderland/aztec-packages/blob/b3b7fb3b50498b1b2f45e1dc473109e37f087256/noir/noir-repo/tooling/nargo/src/ops/foreign_calls.rs#L167

This is hacky tho, and should rather rely on an environment variable (minreq `MINREQ_TIMEOUT` isn't working for Builders, if I'm correct)

### Installation Method

Compiled from source

### Nargo Version

0.26.0 (aztec)

### Would you like to submit a PR for this Issue?

Maybe

### Support Needs

Validation of the fix suggested, ie no unforeseen side-effect?

**Comment by Savio-Sou** [comment]
Approach aside, do you have a recommended timeout duration / what's the minimal timeout duration you're seeing with your project?

**Comment by drgorillamd** [comment]
I don't know how representative to "classic" use-case it is @Savio-Sou , right now, I'm timing out if I set it under 40sec (I'm having some Aztec sandbox interactions in these foreign calls, so lots of async calls to resolve from within my rpc server before getting back to the minreq request).

On the other hand, wouldn't it be more flexible with an env variable (thinking of linear homomorphic encryption as it was recently mentioned on Aztec forum by Rahul - baby step giant step or pollard's rho could be run within an oracle call no? So pretty slow then), and leave it at minreq default if not defined?

**Comment by TomAFrench** [comment]
Agreed on having an environment variable is the best solution for this for the time being.
