### ISSUE TITLE
Unexpected ABIError from benign code change

### ISSUE THREAD

**Issue by alexghr** [noir-lang/noir#4778]
### Aim

I've encountered this issue doing two different things:

1. I've added an `if` statement in aztec-packages in order to update a field on a struct
2. I ran an "empty" transaction in aztec (a `new BatchCall([])`). Internally this uses `if` statements to only execute non-empty function calls

### Expected Behavior

It should work (field should be updated in the first case/the tx should be valid in the second case)

### Bug

In both instances aztec's `private_kernel_init` fails with an `ABIError`.

The first code change is [here](https://github.com/AztecProtocol/aztec-packages/commit/31d58d1bbd7506c9c35c6d4e304dec1df46abf88#diff-bd52146f662c026254653247904835e7f90b38dc7fbdd18752403abcafb837a8R364-R371) and leads to this [error in CI](https://app.circleci.com/pipelines/github/AztecProtocol/aztec-packages/33494/workflows/f91ddacf-9c4f-4251-8ecd-a64dac9aaa7f/jobs/1576024)

In the second case here's [a minimal example](https://github.com/AztecProtocol/aztec-packages/pull/5666) and here's the [CI run for it](https://app.circleci.com/pipelines/github/AztecProtocol/aztec-packages/34013/workflows/0db818e1-618b-4b58-b434-6462a61e581f/jobs/1598649)

In the first case we were able to find a workaround where we replaced the `if` statement with a "max" function and that has fixed the problem. I haven't looked for a workaround for the empty BatchCall example.

### To Reproduce

Run the test in AztecProtocol/aztec-packages#5666

### Project Impact

Blocker

### Impact Context

A workaround was found for the first case. The second case, with the BatchCall, is contrived but realistically it should work since there's nothing wrong with it.

It's unclear what triggers the bug and what other (valid) use cases could lead to it.

### Workaround

None

### Workaround Description

We found [this workaround](https://github.com/AztecProtocol/aztec-packages/pull/5624/files#diff-bd52146f662c026254653247904835e7f90b38dc7fbdd18752403abcafb837a8R350) for the first use case.

### Installation Method

Compiled from source

### Would you like to submit a PR for this Issue?

Maybe

**Comment by TomAFrench** [comment]
My understanding was that Aztec was using their own abi encoder though? Is that not correct?

**Comment by TomAFrench** [comment]
@alexghr I've pushed a change which will highlight exactly which input is breaking type checks during abi encoding. Looks like your counter for note hash read requests is not a valid u32.

```
2024-04-12 16:42:37 end-to-end_1  |     Received promise rejected instead of resolved
2024-04-12 16:42:37 end-to-end_1  |     Rejected to value: [Error: (JSON-RPC PROPAGATED) The value passed for parameter `input.private_call.call_stack_item.public_inputs.note_hash_read_requests[0].counter` does not match the specified type:
2024-04-12 16:42:37 end-to-end_1  |     Value Field(11425886363827509554056097664977951424140858054424059518964806857959181738141) does not fall within range of allowable values for a Integer { sign: Unsigned, width: 32 }]
```

**Comment by alexghr** [comment]
Thanks @TomAFrench, I think this could this be related to #4600 where we were seeing corruption of the `note_hash_read_requests`. I'll retest the flow now that #4600 has been fixed.

**Comment by alexghr** [comment]
Can confirm the latest changes in Noir have fixed this issue https://github.com/AztecProtocol/aztec-packages/actions/runs/8701866086/job/23865456943
