### ISSUE TITLE
Application panicked impl From

### ISSUE THREAD

**Issue by aajj999** [noir-lang/noir#4801]
### Aim

Implement From for structure:

```Rust
 struct A { 
    data: u8
}

impl From<u8> for A { 
    fn from(data: u8) -> A { 
        A{data}
    }
}

fn main() {
    let _: A = Into::into(3);
}
```

### Expected Behavior

Implement from for a structure and then allow to use into.

### Bug

The application panicked (crashed).
Message:  internal error: entered unreachable code: Failed to find trait impl during monomorphization. The failed constraint(s) are:
  A: From
Location: compiler/noirc_frontend/src/monomorphization/mod.rs:1022

### To Reproduce

1.
2.
3.
4.

### Project Impact

Blocker

### Workaround

None

### Installation Method

Binary (`noirup` default)

### Nargo Version

nargo version = 0.26.0 noirc version = 0.26.0+c46b164ce56e6a8f81255fb17eb6539bd040f336

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
This doesn't panic for me on master. We should perhaps be automatically casting `3` into a `u8` but there's existing issues open for this.

```
$ nargo compile
error: No matching impl found for `A: From<Field>`
   ┌─ /home/tom/Programming/aztec/noir/temp/src/main.nr:12:16
   │
12 │     let _: A = Into::into(3);
   │                ---------- No impl for `A: From<Field>`
   │
   = Required by `Field: Into<A>`

Aborting due to 1 previous error
```
