### ISSUE TITLE
Multi-line where clauses fail to parse with low-level error

### ISSUE THREAD

**Issue by michaeljklein** [noir-lang/noir#4809]
### Aim

Attempted to separate `where` clause to multiple lines as is commonly found in Rust

### Expected Behavior

It to either fail with an informative error or be accepted as equivalent to a single-line where clause, i.e. `impl<A, B> Default for Foo<A, B> where A: Default, B: Default`

### Bug

Compiling the following:
```rust
struct Foo<A, B> { }

impl<A, B> Default for Foo<A, B>
where
    A: Default,
    B: Default,
{
    fn default() -> Self { Foo { } }
}
```

fails with:
```bash
error: Unexpected {, expected one of bool, comptime, crate, dep, Field, fn, fmtstr, impl, str, &, (, [, integer type, Ident
   ┌─ /Users/michaelklein/Coding/rust/noir/test_programs/compile_success_empty/name_shadowing_template/binary/src/local_module.nr:19:1
   │
19 │ {
   │ -
   │
```

### To Reproduce

1. `nargo compile` the test program as `main.nr`
2.
3.
4.

### Project Impact

Nice-to-have

### Workaround

None

### Installation Method

None

### Would you like to submit a PR for this Issue?

None

**Comment by jfecher** [comment]
The error here is a result of the ending comma, removing it results in no errors:
```rs
struct Foo<A, B> { }

impl<A, B> Default for Foo<A, B>
where
    A: Default,
    B: Default
{
    fn default() -> Self { Foo { } }
}
```
The `where_clause` parser in the parser looks like it is missing an `.allow_trailing()` call.
