### ISSUE TITLE
to_bytes in stdlib

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#482]
# Problem

It's currently inconvenient to convert a `Field` element into `[u8]`. This seems like a common use case, e.g. when incorporating a `Field` element into a message for signature checks, or into the input of various hash functions.

# Solution

Define `to_bytes` as part of the stdlib.

# Alternatives considered

Document a convenient and recommended snippet for writing the above function directly into your circuit.

**Comment by guipublic** [comment]
what is the specification for converting a field to a [u8]?

**Comment by vezenovm** [comment]
This would definitely be a useful enhancement. Specifically, converting a `Field` element to a `[u8]` message for signature checks has been requested a few times, and I have needed to perform this conversion myself. For example if one wanted to use the result of a pedersen hash as the message of a signature:
```
    // Check signature.
    let message = std::hash::pedersen(
        [
            alias_hash,
            account_public_key[0],
            new_account_public_key[0],
            spending_public_key_1[0],
            spending_public_key_2[0],
            nullifier_1,
            nullifier_2
        ]
    )[0];
    constrain message != 0;
    let message_byte_array = utils::half_of_field_to_bytes(message);
    let sig_res = std::schnorr::verify_signature(signer[0], signer[1], signature, message_byte_array);
    constrain sig_res == 1;
```
I have been getting around it by writing methods such as below where I convert half of a Field to a byte array:
```
fn half_of_field_to_bytes(input: Field) -> [u8; 16] {
    let bit_size: comptime Field = 128;
    let input_bits = std::to_bits(input, bit_size as u32); // Bit size must be 253 or less as this is restricted in Noir for safety

    let mut byte_array: [u8; 16] = [0; 16];
    for i in 0..(bit_size/8) {
        let index = i * 8;
        let mut byte: u8 = 0;
        for j in 0..8 {
            byte = (byte << 1) | (input_bits[index+(7-j)] as u8);
        };
        byte_array[i] = byte;
    };
    byte_array
}
```
We could add `to_byte` methods written directly in Noir that use the whole field, however, it would probably be faster within the compiler itself. It is also important to note that right now we also only convert the first 253 bits of a Field when doing bit decomposition for safety, so by whole Field I mean first 253 bits on the Field. This can be seen [here](https://github.com/noir-lang/noir/blob/bc80c85a4725d9a1bb5a328c05493881c6c510d0/crates/noirc_evaluator/src/ssa/acir_gen.rs#L636). This requires truncating the field some amount of bits if you are a developer (the max `bit_size` I can use in the snippet above is 253 not 254). I think it may be worth it to switch this check to the max size of our `NativeField` as to avoid any developer confusion.

**Comment by kevaundray** [comment]
We can generalise `to_bits` and `to_bytes` in the acir by adding a `to_radix` directive.

So for to_bits it would call `to_radix(2)` so its a bit decomposition, and to to_bytes it would `to_radix(8)`  which is a byte decomposition

**Comment by guipublic** [comment]
There is no confusion right now, as you need to specify a maximum number of bits. If you use more than we support, you have an error because we do not support this. If the field does not fit on the supplied number of bits, it will also fail, so this if fine for me. Of course we can also support more, but then the operation will be more costly without the user knowing it.

So I suggest we do a to_radix(f,a,b)-> [T]; which generates an array of ua, corresponding to the field f being b or less bits.
n.b. I am not sure generics will allow to do this, alternatively we could return [Field], or just have to_bytes(f,b).

**Comment by vezenovm** [comment]
> There is no confusion right now, as you need to specify a maximum number of bits. If you use more than we support, you have an error because we do not support this. If the field does not fit on the supplied number of bits, it will also fail, so this if fine for me. Of course we can also support more, but then the operation will be more costly without the user knowing it.

It is true a developer will get an error that we simply do support that size of bits, I just meant a developer calculating inputs to their circuit, such as a signature, will have to be aware that the message used should use a truncated Field by some amount of bits (one bit, one byte, half the field, etc). 

> So I suggest we do a to_radix(f,a,b)-> [T]; which generates an array of ua, corresponding to the field f being b or less bits. n.b. I am not sure generics will allow to do this, alternatively we could return [Field], or just have to_bytes(f,b).

I think this suggestion is good. `to_radix` with the bit size will give Noir devs the most control.

**Comment by guipublic** [comment]
Do you think it is important to have a to_bytes that uses all the 254 bits?

**Comment by jfecher** [comment]
I believe Joss' original usecase was converting all 254 bits to a byte array so they may all be hashed, so I'd say yes.

**Comment by vezenovm** [comment]
> We can generalise `to_bits` and `to_bytes` in the acir by adding a `to_radix` directive.
> 
> So for to_bits it would call `to_radix(2)` so its a bit decomposition, and to to_bytes it would `to_radix(8)` which is a byte decomposition

I'm looking at switching to using `to_radix` as part of my `to_bytes` PR. One thing we should note though, is that we are referring to the term radix here differently than how it is normally used. When I hear radix I usually think of the unique number of digits used to represent a number. For radix 2 we represent using 0s and 1s, for radix 10 we use the digits 0-9, for radix 16 we use the digits 0-F. 

However, here we are saying `to_radix(8)` is a byte decomposition into a list of u8s. Every byte is then represented as a hexadecimal, not a base 8 number. We should settle on whether `to_radix` refers to the size of the integer type in the output array (`[u1; 256]` or `[u8; 32]` or `[u16; 16]`), or the base of the numerical system we are converting into as this may be confusing to developers.

**Comment by guipublic** [comment]
I am not sure I understand the difference between size of the integer type and base of the numerical system, may be one is log of the other?
If you have a better name or think log is better/worse, feel free to propose what you think is best, as long as we have the feature to do to_bytes and to_bits with the same opcode, it is ok for me.
