### ISSUE TITLE
Generated gate count regression test in CI

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#483]
# Problem

Changes to the compiler could accidentally change the number of gates produced by given code samples. It could be useful to have an automatic test for each PR to test that they do not accidentally increase gate count. It should not automatically decline the PR since it can be intentional, but it should make the change more visible that it happened.

# Solution

A CI step to record the amount of gates produced by a PR and issue a message (where?) if it is more gates for a given test compared to master.

# Alternatives considered

Alternatively, we could have a nightly script that runs and records changes to this over time. We wouldn't catch this before a PR is merged this way, but we would know the day after and could manually check the pull requests that were merged that day. It would also give us a recorded history so that we can better see how the compiler has improved over time.

**Comment by kevaundray** [comment]
This has been completed by @TomAFrench so closing
