### ISSUE TITLE
Allow importing definitions from parent module using `super`.

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#4835]
Rust has the concept of [super](https://doc.rust-lang.org/reference/paths.html#super) which allows importing from the parent module. Noir doesn't have this so all imports from non-descendant modules within the same crate must specify a full `crate::` import.

This is especially useful for when writing tests and grouping them within a submodule

**Comment by LogvinovLeon** [comment]
This would be awesome. Also - being able to do `super::*` in tests would be a big help
