### ISSUE TITLE
nargo fmt infinitely prepends plain:: to type name

### ISSUE THREAD

**Issue by LogvinovLeon** [noir-lang/noir#4846]
### Aim

Nargo fmt should be idemponent. Running it 2, 3, 4 times should produce the same results as running it once.

### Expected Behavior

nargo fmt does not change it's own output

### Bug

It infinitely prepends `plain::` to type name in this code:
```rust
fn strict_if<T>(pred: bool, x: T, y: T) -> T {
    let pred_f = pred as plain::plain::plain::T;
    pred_f * x + (1 - pred_f) * y
}
```

### To Reproduce

1. https://github.com/vlayer-xyz/plain-repro

### Project Impact

Nice-to-have

### Impact Context

Sometime we need to write code without generics to avoid this bug

### Workaround

Yes

### Workaround Description

Don't use generics when this happens

### Installation Method

None

### Nargo Version

noirc version = 0.26.0+c46b164ce56e6a8f81255fb17eb6539bd040f336

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
Hmm, that's odd. We can take a look but in the meantime you can use a `// noir-fmt:ignore` comment to disable the formatter on the next line.
