### ISSUE TITLE
Allow querying the gates in a `Program` in a single request to the backend.

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#4851]
We've taken on some tech debt here as part of the folding epic as we need to pass a separate program to the backend for each function within a program.

https://github.com/noir-lang/noir/blob/4dfd7f03bc1b9cf57f5829c435a560bed53b7f46/tooling/nargo_cli/src/cli/info_cmd.rs#L281-L306

**Comment by vezenovm** [comment]
Closing in favor of https://github.com/noir-lang/noir/issues/4962

**Comment by TomAFrench** [comment]
I've opened https://github.com/AztecProtocol/aztec-packages/issues/6168 to track the changes we need to make to `bb`
