### ISSUE TITLE
Cannot assign a generic to a concrete type

### ISSUE THREAD

**Issue by guipublic** [noir-lang/noir#486]
# Description

## Aim

```
fn foo(a: [u32]) -> [u32] {
    a
}

let mut a=[3,4];
a= foo([1,2]);

```

## Expected behavior

The code snippet above should change a into [1,2]

## Bug

Instead it creates an error: error: `Cannot assign an expression of type [u32] to a value of type [u32; 2]`
# To reproduce

try to prove the provided snippet

# Environment

- OS: mainframe

For `nargo` users

- _noir-lang/noir_ commit cloned: latest master
- Proving backend
  - [X] default
  - [ ] wasm-base

**Comment by kevaundray** [comment]
This gets fixed by doing the following:

```
fn foo<N>(a: [u32;N]) -> [u32;N] {
    a
}

fn main() {
    let mut a = [3,4];
    a = foo([1,2]);
}
```

The issue here being the use of slices. I changed it to `[u32;N]`
