### ISSUE TITLE
Cannot call a function returning a value

### ISSUE THREAD

**Issue by guipublic** [noir-lang/noir#487]
# Description

## Aim

Trying to call a function like this:

```
fn bar() -> bool {
    true
}

fn main() -> pub bool {
   bar();
   true
}
```

## Expected behavior

no error

## Bug

I get an error: error: `Expected type (), found type bool`

# To reproduce

try to nargo prove the provided snippet

# Environment

- OS: mainframe

For `nargo` users

- _noir-lang/noir_ commit cloned: latest master
- Proving backend
  - [X] default
  - [ ] wasm-base

**Comment by TomAFrench** [comment]
Still exists in 0.3.2

**Comment by kevaundray** [comment]
This is correct behaviour; the `bar` function returns a boolean but it is not being used. This can be fixed by:

```
fn bar() -> bool {
    true
}

fn main() -> pub bool {
   let _k = bar();
   true
}
```
