### ISSUE TITLE
Cannot compare arrays

### ISSUE THREAD

**Issue by guipublic** [noir-lang/noir#488]
# Description

## Aim

```
fn foo(a: [u8]) -> [u8] {
  a
}

fn main() {
  let b= foo([1,2]);
  constrain b == [1,2];
}
```

## Expected behavior

no error

## Bug

I get an error: `error: Can only compare arrays of the same length. Here LHS is of length _, and RHS is 2 `

# To reproduce

Nargo prove the provided snippet

# Environment

- OS: mainframe

For `nargo` users

- _noir-lang/noir_ commit cloned: latest master
- Proving backend
  - [X] default

  - [ ] wasm-base

**Comment by kevaundray** [comment]
Noting from meeting that we will go with instead of ordering the functions:

```
fn main() {
  let b= foo([1,2]);
  constrain b == [1,2];
}

fn foo<N>(a: [u8; N]) -> [u8; N] {
  a
}
```
