### ISSUE TITLE
Add SHA256 support for variable `message_size` to be hashed

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#4909]
### Problem

The [SHA256](https://github.com/noir-lang/noir/blob/e7057674f81e24fe05f35c3e7c8fc2b05198232a/noir_stdlib/src/sha256.nr#L19) hash function in the stdlib doesn't currently support hashing of variable actual lengths of inputs.

This hinders use cases that rely on:
- **One** circuit (and by extension one e.g. verification key / verifier smart contract) for hashing different input sizes 
- **Hash matching** with established services (i.e. customized input-padding that results in different hashes isn't useful)

### Happy Case

Extend the SHA256 library to support an additional `message_size` argument, similar to Keccak256: https://github.com/noir-lang/acvm/issues/313

### Project Impact

Blocker

### Impact Context

For projects verifying passport ownerships, sizes of data to hash varies from passport to passport.

### Workaround

None

### Additional Context

Credit to @madztheo @michaelelliot for flagging.

### Would you like to submit a PR for this Issue?

None

**Comment by Savio-Sou** [comment]
@guipublic mentioned this should be approachable to implement in pure Noir now with the `sha256compression` opcode https://github.com/AztecProtocol/aztec-packages/pull/4511.

@michaelelliot you mentioned attempting to implement this in pure Noir some while ago? Was that before or already using `sha256compression`?

**Comment by guipublic** [comment]
Since I said it would be easy, I figured that I might just implement it. I confirm that the performance is good, the cost is the same as if you would hash the full message.
