### ISSUE TITLE
Align experimental feature disclaimers in docs

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#4935]
## Problem
We currently have different versions of experimental feature disclaimers in our docs:
- https://noir-lang.org/docs/dev/noir/concepts/oracles/
- https://noir-lang.org/docs/dev/noir/standard_library/containers/vec/
- https://noir-lang.org/docs/dev/noir/concepts/data_bus/
- https://noir-lang.org/docs/dev/noir/concepts/data_types/slices/

## Happy case
We should create one disclaimer module, then update the pages to link to it instead.

The disclaimer should specify:
- The feature is experimental
- Documentation of the feature is incomplete and could be out of date
- Documentation contributions are welcome: https://github.com/noir-lang/noir

**Comment by emmz3230** [comment]
ok will love to do it

**Comment by Savio-Sou** [comment]
🫡 Docusaurus's docs if it helps: https://docusaurus.io/docs/

PR welcome!

**Comment by emmz3230** [comment]
Yes, I even know how to use Docusaurus, so there won't be a problem with that.
What you want me to do is remove where their are two disclaimer modules, right?

**Comment by emmz3230** [comment]
like a reusable component that will be imported in the  doc page
