### ISSUE TITLE
Proof generation for various sizes and master verification key

### ISSUE THREAD

**Issue by marekkirejczyk** [noir-lang/noir#4938]
### Problem

An important limitation inherited by Noir from PLONK is that arrays and loops are of fixed length.
On the other hand, input data comes in various sizes.
Creating one big circuit that can handle all sizes is very inefficient.

An example distribution of input data from users could look something like:

- 80% is S or smaller, proving time 10 sec
- 18% is M or smaller, proving time 1min
- 2% is L or smaller, proving time 10min

So, I definitely don't want use L-sized prover for S-sized input data.

Hence, I need to generate 3 provers and the only way to do this now is to create a lib with core functionality with generic parameters and 3 projects with `main` function, with a single line calling a generic functionalities with various generic parameters.

Lib:
```rust
fn do_stuff<MAX_INPUT_LEN>(input:[u8; MAX_INPUT_LEN]>Ń {
    ...
}
```

Main 1:
```rust
fn main(input: [u8; 1000])
    do_json_stuff<1000>(input);
}
```

Main 2:
```rust
fn main(input: [u8; 10000])
    do_json_stuff<10000>(input);
}
```

Main 3:
```rust
fn main(input: [u8; 100000])
    do_json_stuff<100000>(input);
}
```

### Happy Case

We propose to implement an external tool in the near future, with hope to be later  adopted by the language tooling. It would allow to  generate multiple provers in a simple way. It would leverage custom attributes to generate multiple subprojects. Here is an example:

```rust
#[prover(MAX_INPUT_LEN=1000]
#[prover(MAX_INPUT_LEN=10000]
#[prover(MAX_INPUT_LEN=100000]
fn do_stuff<MAX_INPUT_LEN>(input: [u8; MAX_INPUT_LEN]) {
    ...
}
```

Note: There are many different methods that can be annotated with `#[prover]` attribute. Each will generate one sub-project with a single main.

### Project Impact

Nice-to-have

### Impact Context

Manual generation of provers is error-prone, obfuscates project and adds noise to the repository.
Additionally, generating multiple projects is also useful for recursive proofs, which suffers the same problems as generating multiple proofs for various sizes.

### Workaround

Yes

### Workaround Description

A typical workaround is to generate multiple main projects as described in problem description.

### Additional Context

**Mater verification key**
There is an additional consideration. Once multiple provers are generated for various sizes of input parameters, developer need to manage multiple verification keys. Ideally, we would be able to merge those keys into one master key.

That seems to be possible via recursive proofs, with one master circuit accepting max size of and argument and switching between one of the slaves subordinate circuits, with various input sizes.

Other ideas are welcome.

### Would you like to submit a PR for this Issue?

Maybe

**Comment by Savio-Sou** [comment]
Thanks for submitting the Issue!

As this is oriented more around an external tooling (at least for the short term), I'll close this as not-planned for now to keep Issues in this repo focused on the language.

Looking forward to the work nonetheless, and feel free to post the idea in the Noir Discord / Twitter to engage with the bigger Noir community!
