### ISSUE TITLE
Distinguish between internal and external imports with `::` prefix

### ISSUE THREAD

**Issue by michaeljklein** [noir-lang/noir#4947]
### Problem

We can have a crate with a dependency `foo` but also a submodule `foo`. Rust disambiguates these with `::foo` to select the dependency rather the submodule (or vice versa). We should have a test for this case in any case.

### Happy Case

- Add `::` prefix to parser
- Override case [here](https://github.com/noir-lang/noir/blob/master/compiler/noirc_frontend/src/hir/resolution/import.rs#L141) to resolve externally when `::` prefix is present
- Test [here](https://github.com/noir-lang/noir/pull/4946#issuecomment-2086523124)

### Project Impact

Nice-to-have

### Workaround

None

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
Removing deep isn't important imo
