### ISSUE TITLE
evaluator for array size does not work in function argument

### ISSUE THREAD

**Issue by guipublic** [noir-lang/noir#495]
# Description

## Aim

```
fn bar(a: [u8;2*2]) {
  constrain a[0]>1;
}

bar([1,2,3,4]);
```

## Expected behavior

No error

## Bug

`error: Expected a ] but found *`

# To reproduce

Nargo prove the provided snippet

# Environment

- OS: mainframe

For `nargo` users

- _noir-lang/noir_ commit cloned: lastest master
- Proving backend
  - [X] default
  - [ ] wasm-base

**Comment by jfecher** [comment]
Good catch. We only run the mini evaluator for array expressions and not array types. I think this was a simple oversight and should be easy enough to add
