### ISSUE TITLE
Expand the Solidity verifier (Barretenberg) compatibility section in docs to cover Top 10 EVMs and how to contribute compatibility tests

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#4964]
### Problem

We know Barretenberg, Noir's default proving backend loaded, generates Solidity verifiers for programs that are deployable on Ethereum.

It is however not directly clear with the same applies to other EVMs which might miss certain precompiles or specific EVM features.

### Happy Case

Expand the [current list we have](https://noir-lang.org/docs/how_to/how-to-solidity-verifier#a-note-on-evm-chains) in the Noir docs to cover:
1. :white_check_mark: and :x: for the top 10 EVMs measured by TVL (reference: [DefiLlama](https://defillama.com/chains/EVM))
2. Guide on how to test compatibility for other EVMs
3. List known EVM precompiles and features required for a EVM to be "Noir-ready" (simply cover gaps discovered when testing (1) is a win)
4. Encourage community to submit PRs for updating / add EVMs to the list

### Project Impact

Nice-to-have

### Impact Context

Great reference for:
- Developers interested in deploying Noir applications on non-Ethereum EVMs
- EVM development teams interested in supporting Noir / ZK applications

### Workaround

None

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
I'd recommend just linking off to https://www.evmdiff.com/features?feature=precompiles and just telling people it needs to support ec_add, ec_mul, ec_pairing. This avoids us from having to explicitly enumerate every single EVM network which wants a shoutout in our docs or gatekeeping this along with the inevitable arguments about which networks are deserving (i.e. if it's notable enough for inclusion in noir docs then it should be notable enough for evm.diff)

**Comment by jzaki** [comment]
Once we have the subset to test, these come in handy for [chainids](https://github.com/ethereum-lists/chains) and [rpc providers](https://rpc.info/#ethereum). Faucets still likely a manual process though :/

**Comment by signorecello** [comment]
[] - BSC ✅ [TX](https://bscscan.com/address/0xa2c2794b90a67e6633ad47653bff4f177f70f4a5)

**Comment by critesjosh** [comment]
> * [x]  BSC ✅ [TX](https://bscscan.com/address/0xa2c2794b90a67e6633ad47653bff4f177f70f4a5)

This just looks like a contract creation tx. Don't you need to send a tx that calls `verify` on that contract to fully test it?

**Comment by signorecello** [comment]
yes I'm on it, just working on making noir-starter easier to "attach" to a deployed contract
