### ISSUE TITLE
Move `GrumpkinScalar` out of std

### ISSUE THREAD

**Issue by benesjan** [noir-lang/noir#4968]
### Problem

We have a `GrumpkinScalar` type in std but it is no longer used in anywhere in std and it's only used in aztec-packages. Since the type doesn't do much I think it makes sense to move it out of std (to aztec noir protocol circuits).

Note: There is also `GrumpkinPrivateKey` in aztec protocol circuits which is basically the same thing.

### Happy Case

`GrumpkinScalar` not cluttering std.

### Project Impact

Nice-to-have

### Workaround

None

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
Part of #4845
