### ISSUE TITLE
`Could not satisfy all constraints` error when running reduce 9_conditional test

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#497]
# Description

Backend issues the message `could not satisfy all constraints` and fails when proving a reduced version of the 9_conditional test.

## Aim

Compiling the following code:
```rs
use dep::std;

fn main(a: u32, mut c: [u32; 4]){
    //Issue reported in #421
    //test 1
    let mut x: u32 = a - a;
    //test2: loops!
    for i in 0..4 {
        if c[i] == 0 {
            x = i as u32 +2;
        }
    };
    constrain x == 0;
}
```
With the Prover.toml:
```
c=[2, 4, 3, 0, ]
a=0
```

## Expected behavior

Expected the test to pass

## Bug

Test fails while proving with the message `could not satisfy all constraints`.

I am not sure why this is failing, I only removed lines from the 9_conditional test and did not add/change any existing ones.

**Comment by guipublic** [comment]
This is failing because x is equal to 5 when it reaches the  `constrain x == 0;`
So this is not a bug and failure is the expected behavior.

**Comment by jfecher** [comment]
Ah, indeed I had overlooked this

**Comment by jfecher** [comment]
How about this example, modified slightly:
```rs
fn main(a: u32, mut c: [u32; 4]){
    constrain c[0]==0;

    //test 1
    let mut x: u32 = 0;
    if a == 0 {
        c[0] = 12;
        if a != 0 {
            x = 6;
        } else {
            x = 2;
        }
    }

    //test2: loops!
    x = 0;//a - a;
    if c[0] == 0 {
        x = 2;
    }
    constrain x == 0;
}
```
with prover:
```
c=[0, 2, 3, 4]
a=0
```
I would expect `c = [12, 2, 3, 4]` by the end and for the last `if c[0] == 0` to thus not be triggered, yet it seems it is. Upon further inspection it seems ssa is re-using the same NodeId from the first `c[0] == 0` check on the first line before `c[0]` is stored to.
