### ISSUE TITLE
Get different contract-method name on `codegen-verifier`

### ISSUE THREAD

**Issue by hpmaxi** [noir-lang/noir#4977]
### Problem

When trying to deploy a contract generated by codegen-verifier, if more than one was generated for different verification tasks, the next command fails because of [this](https://hardhat.org/hardhat-runner/docs/advanced/artifacts#reading-artifacts)
 
```
await viem.deployContract('UltraVerifier');
```

I think, that in case of receiving an argument, should be interpolated [here](https://github.com/AztecProtocol/barretenberg/blob/master/cpp/src/barretenberg/dsl/acir_proofs/contract.hpp).

### Happy Case

Have a way to rename the target contract/method

### Project Impact

Nice-to-have

### Workaround

Yes

### Workaround Description

Use the fully qualified path/name
```
await viem.deployContract('contract/folder/plonk_vk.sol:UltraVerifier');
```

### Would you like to submit a PR for this Issue?

None

**Comment by Savio-Sou** [comment]
Thanks for submitting the Issue!

As `codegen-verifier` is largely a proving backend / barretenberg binary feature which we're moving towards [unwrapping it from Nargo](https://github.com/noir-lang/noir/issues/4960), I'd recommend recreating this Issue in the Barrtenberg repo: https://github.com/AztecProtocol/barretenberg
