### ISSUE TITLE
Can't prove range check constraints

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#498]
# Description

## Aim

Generate a proof that includes a range check constraint.

## Expected behavior

That my proof could be generated successfully for a valid input.

## Bug

Attempting to prove for a circuit containing a `Field` range check fails:

> thread 'main' panicked at 'not implemented: Field comparison is not implemented yet, try to cast arguments to integer type', crates/noirc_evaluator/src/ssa/acir_gen.rs:339:29

Attempting to prove  for a circuit containing a `u8` range check progresses further, but still fails:

```
ACIR gates generated : 15
Loading noir code from: "/var/folders/n4/d6xwpnvd3mb6vrsqh0k9rv9h0000gn/T/.tmp8bm2iQ"
panicked at 'called `Result::unwrap()` on an `Err` value: Syntax("invalid type: sequence, expected u32")', crates/acir/src/circuit/mod.rs:30:9

Stack:

Error
    at module.exports.__wbg_new_693216e109162396 (/Users/aztec/.nvm/versions/node/v16.13.0/lib/node_modules/@noir-lang/noir-cli/node_modules/@noir-lang/noir_wasm/noir_wasm.js:200:17)
    at wasm://wasm/009f874a:wasm-function[1148]:0x232fd6
    at wasm://wasm/009f874a:wasm-function[2431]:0x266915
    at wasm://wasm/009f874a:wasm-function[1674]:0x258cc7
    at wasm://wasm/009f874a:wasm-function[1752]:0x25c228
    at wasm://wasm/009f874a:wasm-function[2162]:0x2651bc
    at wasm://wasm/009f874a:wasm-function[1991]:0x26268b
    at wasm://wasm/009f874a:wasm-function[2100]:0x26456c
    at wasm://wasm/009f874a:wasm-function[1800]:0x25db79
    at wasm://wasm/009f874a:wasm-function[1324]:0x243434


Error thrown: RuntimeError: unreachable
thread 'main' panicked at 'range start index 32 out of range for slice of length 0', library/core/src/slice/index.rs:52:5
```

# To reproduce

## `Field` range bug

1. `nargo build` the follow circuit:
```
fn main(x : Field, y : pub Field) {
    constrain x < y;
}
```
2.  `nargo prove proof` with inputs
```
# Verifier.toml
x = 1
y = 2
```

## `u8` range bug

As above, but with circuit:
```
fn main(x : u8, y : pub u8) {
    constrain x < y;
}
```

# Environment

(Specify your setup and versions of dependencies.)

- OS: macOS 12.4 Intel

For `nargo` users

- _noir-lang/noir_ commit cloned: b3eb4c13192cb940d9d8a39bc8eb68e80d3284fa
- Proving backend
  - [ ] default
    - Clang: (run `clang --version`)
  - [x] wasm-base

**Comment by jfecher** [comment]
Your second example with `u8` successfully proves and verifies for me on the same commit

**Comment by guipublic** [comment]
`u8` example works for me as well.

**Comment by joss-aztec** [comment]
Can confirm this bug goes away if I build barretenberg instead of using wasm-base. Here's a fully stack trace attempting the same u8 comparison on linux.

```
RUST_BACKTRACE=1 nargo prove proof
ACIR gates generated : 15
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/mnt/user-data/joss/.nvm/versions/node/v14.18.1/lib/node_modules/@noir-lang/noir-cli/dest/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
thread 'main' panicked at 'range start index 32 out of range for slice of length 0', /mnt/user-data/joss/.cargo/git/checkouts/aztec_backend-a697fb631cbad807/8dc5b28/src/acvm_interop/proof_system.rs:205:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::slice::index::slice_start_index_len_fail_rt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/slice/index.rs:53:5
   3: core::slice::index::slice_start_index_len_fail
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/slice/index.rs:42:9
   4: aztec_backend::acvm_interop::proof_system::remove_public_inputs
   5: aztec_backend::acvm_interop::proof_system::<impl acvm::ProofSystemCompiler for aztec_backend::acvm_interop::Plonk>::prove_with_meta
   6: nargo::cli::prove_cmd::run
   7: nargo::cli::start_cli
```

**Comment by vezenovm** [comment]
This looks to be a Noir issue that was fixed (however I cannot find an original issue if there was one), but the `wasm-base` is missing the updated version of Noir. Using the `barretenberg.wasm` file directly allows us to access the most recent Noir changes without having to push updates to the noir-cli. This work has yet to be merged into the `aztec_backend`, but installing nargo with the backend below should result in successful proving and verification: 
`aztec_backend = { optional = true, package = "barretenberg_wasm", git = "https://github.com/noir-lang/aztec_backend", branch = "mv/fix-static-lib" }`

**Comment by joss-aztec** [comment]
Just tested - confirmed fixed
