### ISSUE TITLE
Expression type is ambiguous

### ISSUE THREAD

**Issue by LogvinovLeon** [noir-lang/noir#4994]
### Aim

Getting this code to compile:
```rust
fn main() {
    let a: [u8; 10] = [1; 10];
    let b: [Field; 10] = a.map(|x| x as Field);
}

```

### Expected Behavior

Compiles

### Bug

Does not compile:
```
error: Expression type is ambiguous
  ┌─ /Users/leonidlogvinov/Dev/ZK/plain-repro/src/main.nr:3:36
  │
3 │     let b: [Field; 10] = a.map(|x| x as Field);
  │                                    ---------- Type must be known at this point
  │

Aborting due to 1 previous error
```

### To Reproduce

1. Try to compile

### Project Impact

Nice-to-have

### Workaround

Yes

### Workaround Description

I can write a loop instead, but it's uglier & more verbose. Ideally - would like to be able to cast whole arrays

### Installation Method

Binary (`noirup` default)

### Nargo Version

nargo version = 0.28.0

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
A type hint fixes this for now.

```rust
fn main() {
    let a: [u8; 10] = [1; 10];
    let b: [Field; 10] = a.map(|x: u8| x as Field);
}

```
