### ISSUE TITLE
Avoid `O(N^2)` scan through globals during name resolution

### ISSUE THREAD

**Issue by michaeljklein** [noir-lang/noir#5001]
### Problem

the following [code](https://github.com/noir-lang/noir/blob/master/compiler/noirc_frontend/src/hir/resolution/resolver.rs#L418)
in the resolver scans through all previous global's whenever a global is added, resulting in `O(num_globals^2)`:

```rust
        // This check is necessary to maintain the same definition ids in the interner. Currently, each function uses a new resolver that has its own ScopeForest and thus global scope.
        // We must first check whether an existing definition ID has been inserted as otherwise there will be multiple definitions for the same global statement.
        // This leads to an error in evaluation where the wrong definition ID is selected when evaluating a statement using the global. The check below prevents this error.
        let mut global_id = None;
        let global = self.interner.get_all_globals();
        for global_info in global {
            if global_info.ident == name
                && global_info.local_id == self.path_resolver.local_module_id()
            {
                global_id = Some(global_info.id);
            }
        }
```

### Happy Case

Store global variables in a set or (hash)map to allow looking them up quickly

### Project Impact

Nice-to-have

### Workaround

None

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
This code still exists in the elaborator [here](https://github.com/noir-lang/noir/blob/a30814f1f767bf874cd7e2969f5061c68f16b9a7/compiler/noirc_frontend/src/elaborator/patterns.rs#L323-L332)

**Comment by jfecher** [comment]
@TomAFrench we should be able to remove that check I believe. As long as globals are present in the def_maps.
