### ISSUE TITLE
Performance dropping low when pushing arrays to BoundedVec

### ISSUE THREAD

**Issue by Pasifaee** [noir-lang/noir#5013]
### Aim

Getting this code to compile considerably fast:
```rust
global COUNT = 400;

fn main() -> pub BoundedVec<[Field; 1], COUNT> {
    let mut result = BoundedVec::new();
    let mut x = 0;

    for _ in 0..COUNT {
        if (x < 1) {
            result.push([0]);
        }
    }

    result
}
```

### Expected Behavior

The code compiles fast.

### Bug

The code takes 30 seconds to compile on my machine.

### To Reproduce

1. Compile the code

### Project Impact

Nice-to-have

### Workaround

Yes

### Installation Method

None

### Nargo Version

nargo version = 0.28.0 noirc version = 0.28.0+7dfa151da95c7ca9e1aaa752347b62f9fafe2c2c

### Would you like to submit a PR for this Issue?

None

**Comment by jfecher** [comment]
This runs in under half a second running with `nargo e` on master.

Are you just compiling, or are you executing, proving, verifying, etc?
