### ISSUE TITLE
Usage of `Trait::method` syntax on globals results in monomorphisation ICE.

### ISSUE THREAD

**Issue by Pasifaee** [noir-lang/noir#5029]
### Aim

I wanted to have a structure with multiple trait From implementations and use `From::from(...)` syntax to create a global variable.

### Expected Behavior

This code compiles:
```rust
struct Struct {
    field: Field
}

impl From<Field> for Struct {
    fn from(field: Field) -> Self {
        Struct { field }
    }
}

impl From<u64> for Struct {
    fn from(num: u64) -> Self {
        Struct { field: num as Field }
    }
}

global s: Struct = From::from(0);

fn main() {
    println(s);
}
```

### Bug

The code above causes compilation panic. I also can't use `Struct::from(...)` syntax because it causes compiler error: 'Could not resolve 'from' in path'.

### To Reproduce

1. Try to compile the code above.

### Project Impact

Nice-to-have

### Workaround

None

### Installation Method

Binary (`noirup` default)

### Nargo Version

nargo version = 0.29.0 noirc version = 0.29.0+2da28997dbedce4a00d2162eddb57564bdb23546

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
This is unrelated to multiple implementations of the same trait as I get the same ICE when commenting out either of the trait impls.

`Struct::from` issue is due to https://github.com/noir-lang/noir/issues/4943#issuecomment-2083486013

**Comment by TomAFrench** [comment]
For completeness the error is

```
% nargo compile                                                                                                        ~/aztec-packages/noir/noir-repo/temp tf/native-recursion tom-box
The application panicked (crashed).
Message:  ICE: missing trait impl - should be caught during type checking
Location: compiler/noirc_frontend/src/monomorphization/mod.rs:1027
```

**Comment by asterite** [comment]
This program:

```rust
global s: BoundedVec<Field, 2> = From::from([0]);

fn main() {
    println(s);
}
```

now gives this error:

```
error: No impl found due to prior type error
  ┌─ src/main.nr:1:34
  │
1 │ global s: BoundedVec<Field, 2> = From::from([0]);
  │                                  ----------
  │
  = Call stack:
    1. src/main.nr:1:34
```

So at least no panic, but I think it should compile so I'll take a look at this.
