### ISSUE TITLE
Allow to specify the file name for the proof

### ISSUE THREAD

**Issue by LogvinovLeon** [noir-lang/noir#5037]
### Problem

Currently `nargo` always generates a proof in `${monorepoRoot}/proofs/${packageName}.proof`.
This does not work for server side applications that generate multiple proofs in parallel as they can override each other.
`nargo prove` command already allows to specify `Prover.toml` & `Verifier.toml` names. Proof name should also be configurable

### Happy Case

`nargo prove --proof-path ../custom_proofs/uuid.proof`

### Project Impact

Blocker

### Impact Context

Without it - each proof needs to be generated in a separate file system or all proofs need to be generated sequentially

### Workaround

Yes

### Workaround Description

Kinda. As described above

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
Proving functionality is being removed from nargo as part of #4960 to instead use `bb` directly which does support this.

**Comment by LogvinovLeon** [comment]
@TomAFrench is there any documentation on how to use `bb` directly to achieve that? As of now - nargo is still the recommended way of doing things even on dev version of nargo docs: https://noir-lang.org/docs/getting_started/hello_noir/
