### ISSUE TITLE
Barretenberg compilation error

### ISSUE THREAD

**Issue by huitseeker** [noir-lang/noir#505]
# Description

Compilation error in the dependencies of the barretenberg wrapper.

## Aim

Following the guide:
https://noir-lang.github.io/book/getting_started/nargo/installation.html
Step 5 in `crates/nargo`, for an otherwise unmodified master at 16ce5b208bc15d448c7e1a4bc628cf48c4321f43:
`cargo install --locked --path=.`

## Bug
```
  /Users/huitseeker/tmp/noir/target/release/build/barretenberg_wrapper-5e68d2a5868c1d46/out/build/_deps/leveldb-src/util/cache.cc:129:14: error: variable 'count' set but not used [-Werror,-Wunused-but-set-variable]
      uint32_t count = 0;
               ^
```

See full output:
https://gist.github.com/acdc4a9e5533ff126dc9d96d0d82b17e

# Environment
- OS: OSX Monterey
- clang:
```
huitseeker@dapple.local➜noir/crates/nargo(master)» clang --version                                                                           [14:42:51]
Homebrew clang version 16.0.0 (https://github.com/llvm/llvm-project.git 5d1ae6346b15539421d055d3dfc94fabe0d7c558)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm/bin
```

**Comment by phated** [comment]
This should be fixed on the `master` branch. Please let us know if it is still broken.
