### ISSUE TITLE
Type inference fails without intermediate variable

### ISSUE THREAD

**Issue by nventuro** [noir-lang/noir#5065]
### Aim

I want to rely on type inference, but in some cases it only works if I have unnecessary intermediate variables.

### Bug

In the following program, `concise_but_does_not_compile` errors out with `Expression type is ambiguous`. This is fixed in `verbose_but_compiles`, which introduces an intermediate variable `a`. I'm providing zero new type information, so this looks like a bug.

```rust
struct Wrapper<T> {
    _value: T,
}

impl<T> Wrapper<T> {
    fn new(value: T) -> Self {
        Self { _value: value }
    }

    fn unwrap(self) -> T {
        self._value
    }
}

trait MyTrait {
    fn new() -> Self;
}

struct MyType {

}

impl MyTrait for MyType {
    fn new() -> Self {
        MyType {}
    }
}

fn foo<T>() -> T where T: MyTrait {
    MyTrait::new()
}

fn verbose_but_compiles() -> MyType {
    let a = Wrapper::new(foo());
    a.unwrap()
}

fn concise_but_does_not_compile() -> MyType {
    Wrapper::new(foo()).unwrap()
}

fn main() {
    let _ = verbose_but_compiles();
    let _ = concise_but_does_not_compile();
}
```

**Comment by sirasistant** [comment]
Could be related to https://github.com/noir-lang/noir/issues/4732 ?

**Comment by nventuro** [comment]
Yes, it is definitely the same thing. I didn't see that issue before, sorry. However this is likely a better example as the code sample does not rely on external libraies to trigger the bug.

**Comment by vezenovm** [comment]
Another workaround is to use turbofish now that Noir has the operator:
```rust
fn concise_but_does_not_compile() -> MyType {
    Wrapper::new(foo::<MyType>()).unwrap()
}
```

**Comment by vezenovm** [comment]
This is resolved if you want to try https://github.com/noir-lang/noir/issues/4732 @sirasistant
