### ISSUE TITLE
Can not produce a value of a struct in its impl

### ISSUE THREAD

**Issue by gnull** [noir-lang/noir#5067]
### Aim

I wanted to implement a `new` method that creates default values of my struct like so:

```rust
struct Hey {}

impl Hey {
  fn new() -> Hey {
    Hey()
  }
}
```

### Expected Behavior

I expect the code to compile and the `new` method to produce the specified value.

### Bug

The compiler fails with an error:

```rust
$ nargo build
error: cannot find `Hey` in this scope
  ┌─ /tmp/test/src/main.nr:5:5
  │
5 │     Hey()
  │     --- not found in this scope
  │

Aborting due to 1 previous error
```

### To Reproduce

1. `nargo new ./test`.
2. `cd test`.
3. Put the following in src/main.nr
   ```rust
   struct Hey {}
   
   impl Hey {
     fn new() -> Hey {
       Hey()
     }
   }
   ```
4. Run `nargo build`.

### Project Impact

None

### Workaround

None

### Installation Method

Binary (`noirup` default)

### Nargo Version

nargo version = 0.28.0 noirc version = 0.28.0+7dfa151da95c7ca9e1aaa752347b62f9fafe2c2c (git version hash: 7dfa151da95c7ca9e1aaa752347b62f9fafe2c2c, is dirty: false)

### Would you like to submit a PR for this Issue?

None

**Comment by jfecher** [comment]
We could look into having a better error message in this case. Since `Hey` is a type it wasn't found in the value scope but perhaps we could check for this and add a help message like "did you mean to construct this type with curly braces?"
