### ISSUE TITLE
Add usize for array indexing

### ISSUE THREAD

**Issue by guipublic** [noir-lang/noir#507]
# Problem

We currently use comptime Field for array indexing, but field arithmetic differs from integer arithmetic so something like `for i in ..  a[i/5]`  will not work as expected. With dynamic array indexes, comparison will also not work because we do not support it for Field type.

# Solution

We should introduce a `usize ` type which will be required for array indexes.
This is something that already exists for several programming languages, including rust, so users already expect this type.
usize should implement unsigned integer arithmetic and should not overflow.

One possibility is to define it as X bits integer, where X would be a bit less than the number of bits required for the field modulus. 
- Having a lot of bits should avoid overflows as usize indexes should be either known at compile time or reasonably bounded.
- Having the bit number depending on the compilation target is also expected for usize.
- Having it strictly less than modulus size yields to more effective comparisons.

# Alternatives considered

We could also implement overflow and use X/2 bit size instead of X. This would make the type may be easier to use (it will basically behaves like u128) although less efficient. I think no overflow for a type accessing indexes is fine.

Another alternative would be to use a small size, such as u16, to limit array size as large arrays can lead to circuits which would be too big to be handled in practice.

**Comment by kevaundray** [comment]
We are going to use a Polymorphic integer for this, so closing as not planned
