### ISSUE TITLE
Turbofish operator does not work

### ISSUE THREAD

**Issue by LogvinovLeon** [noir-lang/noir#5077]
### Aim

Use turbofish on a simple method

### Expected Behavior

Compiles

### Bug

```sh
error: expected type Field, found type ()
  ┌─ /Users/leonidlogvinov/Dev/ZK/trait_repro/src/main.nr:3:18
  │
3 │   fn main() -> pub Field {
  │                    ----- expected Field because of return type
  │ ╭────────────────────────'
4 │ │     fun::<2>()
5 │ │ }
  │ ╰─' () returned here
  │

error: Unexpected ::, expected one of binary operator, Ident
  ┌─ /Users/leonidlogvinov/Dev/ZK/trait_repro/src/main.nr:4:8
  │
4 │     fun::<2>()
  │        ---
  │

Aborting due to 2 previous errors
```

### To Reproduce

```rs
fn main() -> pub Field {
    fun::<2>()
}

fn fun<N>() -> Field {
    0
}

```

### Project Impact

Nice-to-have

### Workaround

Yes

### Workaround Description

Not use turbofish

### Installation Method

None

### Nargo Version

nargo version = 0.30.0

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
https://github.com/noir-lang/noir/pull/3542#issuecomment-2125081381
