### ISSUE TITLE
Push `noir_js_backend_barretenberg` into bb.js

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#5079]
We currently have `@noir-lang/backend_barretenberg` which is a wrapper around `bbjs` in order to make it more user-friendly. We should push these UX improvements into `@aztec/bb.js` so we can be a pure consumer of barretenberg.

**Comment by TomAFrench** [comment]
One difficulty is that the logic in `@noir-lang/backend_barretenberg` depends on `'noir-lang/types` which is a bit awkward as it results in a circular dependency between `noir-lang/noir` and `aztecprotocol/aztec-packages` so this will need to be resolved.

**Comment by Savio-Sou** [comment]
Might have to address https://github.com/noir-lang/noir/issues/5106 before / alongside this Issue.

**Comment by TomAFrench** [comment]
how are these two issues related?

**Comment by Savio-Sou** [comment]
In case https://github.com/noir-lang/noir/issues/5106 is a `@noir-lang/backend_barretenberg` bug instead of `@aztec/bb.js`, might be best to resolve that before this Issue (on the basis of cross-team expectations, rather than anything technical).

Simply flagging and will take your + Cody's lead.
