### ISSUE TITLE
Document `std::as_witness`

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#5086]
Implementation PR: https://github.com/noir-lang/noir/pull/4641

Document:
- Why is it useful
- What is it
- How to use (i.e. examples)

@TomAFrench any specific thought on when to consider it graduated from being an experimental feature (other than e.g. 2 releases from merge)?

**Comment by TomAFrench** [comment]
We shouldn't document this as it's a hack to unblock a particular usecase and it's not meaningfully usable by outside devs without knowing way too much of the compiler internals than we want Noir devs to worry about. I worry that if we push this on external devs we're going to end up with some form of cargo cult optimisation spring up around this.

The aim is to delete this function so if we push external devs to use it then that's going to become much harder to do.

**Comment by Savio-Sou** [comment]
> The aim is to delete this function

As in there is a better-but-takes-more-time alternative path?
