### ISSUE TITLE
Non-const loops and while expressions

### ISSUE THREAD

**Issue by guipublic** [noir-lang/noir#509]
# Problem

It is not possible to use while expressions or for loops with non-comptime range.

# Solution

One way to do this is to have a sugar syntax for while loops which would be:
 `while e {..} ` becomes:
```
let exit = false;
  for i in 0..M { 
    if e {...} else {
    exit = true;
  }
}
constrain exit;
```

for loops with non-const range can now be implemented using a while expression:
`for i in a..b {..}`   becomes:
```
let i =a;
while {i < b; i++}{
    ..
}

```

# Additional context

The value `M` will be simply hard-coded at the beginning (e.g M=10000), but this should be improved in the future with a `M` that depends on the loop.

**Comment by jfecher** [comment]
The solution here seems potentially confusing for users who do not expect a hidden maximum number of iterations M to be inserted into their code. I think an ideal solution would make this explicit in the code.

Another option is including a function in the stdlib to do the looping:
```rs
fn do_while<T>(max_iters: comptime u64, body: fn() -> (bool, T)) -> T {
    let mut (continue, ret) = body();
    for i in 1 .. max_iters { 
        if continue {
            let (c, r) = body();
            continue = c;
            ret = r;
        }
    }
    constrain !continue;
    ret
}
```
This has the advantage of making the `max_iters` parameter explicit for the user and easily discoverable and editable without requiring extra compiler features on our part.
Returning a tuple of `(continue, ret)` here is somewhat awkward. In other languages this would be a sum type, but that would require adding more features to noir.

**Comment by kevaundray** [comment]
I think this is confusing to use while loops and have an implicit max bound. Lets close and open if we deem it useful in the future
