### ISSUE TITLE
Error when exporting noir code to Typescript

### ISSUE THREAD

**Issue by MBelegris** [noir-lang/noir#5099]
### Aim

Compile my noir code to TS to be able to test within Jest.

### Expected Behavior

Should be able to test with Jest and return the correct assertion

### Bug

It returns the following error: `failed to deserilialize circuit`

![image](https://github.com/noir-lang/noir/assets/35403627/e1275088-2320-4816-8899-f28aed0f7912)

### To Reproduce

Following this tutorial: [https://noir-lang.org/docs/getting_started/tooling/noir_codegen](https://noir-lang.org/docs/getting_started/tooling/noir_codegen)
1. Create a new pnpm project with `pnpm init`
2. Create a ts config: `pnpm add typescript -D` and then `npx tsc --init`
3. Add noir-codegen `pnpm add @noir-lang/noir_codegen -D` and add noir js `pnpm add @noir-lang/noir_js`
4. Create a new noir lib `mkdir circuits && cd circuits` then `nargo new --lib myNoirLib`
5. Add #[export] to my function: `not_equal`
6. Call `nargo export`
7. Call `pnpm noir-codegen $JSONPATH`
8. Setup jest environment and write the following test:
```js
import { not_equal } from "../codegen";

describe("Test not equal", () => {
    expect(not_equal("1","1")).toBe(false)
})
```
9. Run `pnpm t` to test and it returns this error

### Project Impact

None

### Workaround

None

### Installation Method

Binary (`noirup` default)

### Nargo Version

nargo version = 0.26.0 noirc version = 0.26.0+c46b164ce56e6a8f81255fb17eb6539bd040f336

### NoirJS Version

0.29.0

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
> **Nargo Version**
> nargo version = 0.26.0 noirc version = 0.26.0+c46b164ce56e6a8f81255fb17eb6539bd040f336
>
> **NoirJS Version**
> 0.29.0

This is the cause of the issue as mentioned in the error message. You need to use the same versions of the compiler and JS packages to guarantee that they use the same serialization format.

**Comment by MBelegris** [comment]
I have updated noir to have version:
nargo version = 0.29.0
noirc version = 0.29.0+2da28997dbedce4a00d2162eddb57564bdb23546
The error still gets returned.

**Comment by TomAFrench** [comment]
Can you create a repository with a reproduction of this issue for me to look at? This should use a locally installed version (rather than global) of  any JS dependencies to ensure we're using the same versions.

**Comment by MBelegris** [comment]
I have just created one here: [https://github.com/MBelegris/noir-ts-jest/tree/main](https://github.com/MBelegris/noir-ts-jest/tree/main)

**Comment by TomAFrench** [comment]
https://github.com/MBelegris/noir-ts-jest/blob/main/circuits/myNoirLib/export/not_equal.json

This artifact still uses nargo 0.26.0, you need to rebuild the artifacts with the correct version of the compiler.
