### ISSUE TITLE
noir.js cannot prove on input a circuit of size 2^19

### ISSUE THREAD

**Issue by codygunton** [noir-lang/noir#5106]
This was uncovered by https://github.com/AztecProtocol/aztec-packages/pull/6391, which pushed the size of the UltraPlonk verifier circuit to size 2^19. The failure is that the prover runs out of memory while creating the proving key. It was subsequently verified that proving fails for other circuits of size 2^19 (e.g., the test program called hashmap) while it succeeds for a circuit of size 2^18 (the test program ecdsa_secp256r1_3x).

**Comment by Savio-Sou** [comment]
Was this happening with NoirJS specifically? As in bb.js works, but not when going through NoirJS?

**Comment by TomAFrench** [comment]
Closing as this is a BB.js concern
