### ISSUE TITLE
ICE encountered when calling a function marked with `#[fold]` from brillig

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#5130]
See PR https://github.com/noir-lang/noir/pull/5128

Most of the test cases for folding fail to compile if we force it to be compiled into brillig with an ICE. See below:

```
tom at tom-desktop in ~/Programming/aztec/noir/test_programs/execution_success/fold_fibonacci on tf/enforce-testing-in-brillig [$]
$ nargo compile --force-brillig
error: Internal Consistency Evaluators Errors: 

                    This is likely a bug. Consider opening an issue at https://github.com/noir-lang/noir/issues
  ┌─ std/aes128.nr:1:1
  │
1 │ #[foreign(aes128_encrypt)]
  │ - ICE: "Cannot find linked fn f1"
  │

Aborting due to 1 previous error
```

If we're compiling in brillig can make a call to a `#[fold]` function we should be able to just ignore that and treat it as a regular brillig function.

Also this diagnostic is quite odd, not sure why this is pointing at aes128.

**Comment by asterite** [comment]
I can't seem to reproduce this. I tried `nargo compile --force-brillig` in some of the fold programs and all compile file.

**Comment by TomAFrench** [comment]
Looks like we can close this then.
