### ISSUE TITLE
Unsatisfied constraint feedback

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#515]
# Problem

Presently when testing or debugging a complex circuit it is difficult to identify which constraints weren't satisfied for a given input. Working around this is cumbersome, and can involve commenting out large parts of the circuit to isolate the failed constraint.

This is the current feedback provided for a failed proof:
```
could not satisfy all constraints
```

# Solution

Provide semantics for annotating constraints akin to an assert or require statement. The associated message should then be listed when proving fails. E.g.

```
require(x < 5, "x is too high");
```

```
could not satisfy all constraints:
  - x is too high
```

# Alternatives considered

A simpler compromise would be to provide line numbers for the failed constraints. Note however this would insufficient when authoring failure case unit tests, which would want to test for a specific failure message.

**Comment by kevaundray** [comment]
Partially resolved by https://github.com/noir-lang/noir/pull/1864, opened a separate issue for assert messages: https://github.com/noir-lang/noir/issues/1939
