### ISSUE TITLE
Abstract away array bounds for variably sized main inputs

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#516]
# Problem

Array arguments to `main` have to be a fixed size, but you can imitate a variably sized input as such:

```
fn main(arr: [Field; 10], arr_len: u4) {
  for i in 0..std::array::len(arr) {
    if i as u4 < arr_len {
      // Perform some iteration
    }
  }
}
```
(Elements at `arr_len` and beyond are just padding)

However, in a large program it is cumbersome to forward an array's length down through the call stack. Also, supporting this pattern in a hypothetical library of array functions would require both bounded and unbounded versions of each function to be implemented.

# Solution

Introduce a compile time concept of max-sized arrays, such that the compiler can automatically infer when to inject an `if i < arr_len` statment. E.g.
```
fn main(arr: [Field; <=10], arr_len: u4) { // Note the <= in the array size
  for i in 0..std::array::len(arr) {
    // Perform some iteration
  }
}
```
Could evaluate to the compiled equivalent of:
```
fn main(arr: [Field; 10], arr_len: u4) {
  for i in 0..10 {
    if i as u4 < arr_len {
      // Perform some iteration
    }
  }
}
```
All array functions would then be compatible for free.

# Alternatives considered

None come to mind. (This suggestion is merely a nice to have.)

**Comment by guipublic** [comment]
I think the right way to implement variable sized array inputs for main would be to simply allow it in main, so the code will be:
```
fn main(arr: [Field]) {
  for i in 0..std::array::len(arr) {
      // Perform some iteration
  }
}
```
array::len(arr) should then work because we know the array len from the input. We would need to parse the inputs before compiling.

**Comment by joss-aztec** [comment]
Wouldn't compiling the array length into the circuit leak information? And it wouldn't it also make proof verification needlessly complicated - i.e. I imagine a verifier smart contract would need to store as many verifications keys as the circuit has length permutations. This number could quadratic, cubic, etc depending how many array inputs you have.

**Comment by guipublic** [comment]
Yes good points;
it leak the size which is also the case when you have a fixed size array, although the later is more visible.
Proof verification would work with nargo verify
You will not be able to generate a smart contract with variable array-size, which is good. Since it does not use the prover.toml, it will not be able to figure out the array size. If you really need variable size array for a smart contract, it can be done as you suggested.

**Comment by jfecher** [comment]
> However, in a large program it is cumbersome to forward an array's length down through the call stack. Also, supporting this pattern in a hypothetical library of array functions would require both bounded and unbounded versions of each function to be implemented.

@joss-aztec can you elaborate on this part? You shouldn't need to manually forward an array's length down a callsite in noir since you can use a polymorphic array size instead on any function except main:

```rs
fn main(input: [Field; 10]) {
    foo(input);
    foo([1, 2, 3]);
}

fn foo(array: [Field]) {
    constrain array[0] < array[1];
}
```

**Comment by joss-aztec** [comment]
Sorry - inconsistent wording. In that sentence by "array's length" what I really meant was the length of the segment of an array that I'm interested in.

Recap: If I want to hide the number input elements I'm using, the main function needs to take a fixed-size array where not all the elements are used. E.g. If my app uses a circuit that can take a maximum of 10 elements, but I only want to use 3 of them, I would fill the other 7 with padding.

Reasons you might want a variable length input:
- hiding how many actions you took in your turn of a game
- hiding how many UTXOs you're using in a payment
- hiding the number of candidates you included in your ballot

In my original example I've implied the start of the padding with a length argument. However, it's a cumbersome pattern in a large code base, or in one that wants to draw on libraries. Here's a slightly more expanded example:

```
use dep::std;

fn foo(arr: [Field], virtual_length: u8) {
    for i in 0..std::array::len(arr) {
        if (i as u8 < virtual_length) {
            // Iterate on this element
        }
    };
}

fn bar(arr: [Field], virtual_length: u8) {
    // Let's forward that extra arg again
    foo(arr, virtual_length);
}

fn baz(arr: [Field], virtual_length: u8) {
    // Would be nice if the concept of virtual length wasn't
    // narrowing the utility of my function signatures...
    bar(arr, virtual_length);
}

fn main(arr: [Field; 10], virtual_length: u8) {
    baz(arr, virtual_length);
    // Functions that don't understand the concept
    // or padding can't be safely used.
    std::array::sort(arr); // Unsafe
}
```
I mentioned in https://github.com/noir-lang/noir/issues/374 that there's some overlap in intent.

**Comment by kevaundray** [comment]
Closing as I don't think we will implement this and there has been no apetite for it since the issue was opened
