### ISSUE TITLE
`acir_field`'s `FieldElement::is_negative` invalid in some cases

### ISSUE THREAD

**Issue by michaeljklein** [noir-lang/noir#5174]
### Aim

`FieldElement::is_negative` should be correct in all cases

### Expected Behavior

I expect `FieldElement::is_negative` to be correct in all cases

### Bug

[acvm-repo/acir_field/src/field_element.rs](https://github.com/noir-lang/noir/pull/5115/files/8acf0295758bc3aaa23aab4581867384c1062ece#diff-f3ab60ad94e3965ff9b8b695dcd3294eaccf0b2d9eafcdb0220c710891f7bcf2)

```
    fn is_negative(&self) -> bool {
        self.neg().num_bits() < self.num_bits()
```

As far as I can tell, this will be incorrect when the field element is in the middle of its range.

Instead, I believe we should compare without `num_bits`, i.e. `self.neg() < self`

### Project Impact

None

### Workaround

None

### Installation Method

None

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
I've had a little look into this and the logic of this function is correct for how we're using it.

The only place we're using it is when converting a field element into an i128 and so we're going to have values in the ranges 0..2^127-1 (representing positive integers) and p-2^127..p (representing negative integers). If we were to use field elements outside of this range we would get invalid results anyway.

That said, this method is devoid of any context as it is which opens it up to being misused in future. We should just inline it into `to_i128` as a result.
