### ISSUE TITLE
Support type wildcards (`_`)

### ISSUE THREAD

**Issue by michaeljklein** [noir-lang/noir#5183]
### Problem

Currently,

1. When using turbofish with multiple arguments, e.g.

```rust
foo<A, B, 3, 12>
```

4. When the return type is underconstrained, e.g. when deserializing from an array of `Field`'s:

```rust
let deserialized: Vec<MyStruct> = input.deserialize();
```
(i.e. `collect::<Vec<_>>()`)

This can require a lot of duplication when functions/traits have several generic arguments and makes the resulting code more fragile.

### Happy Case

Support a type wildcard (`_`) that's equivalent to an unbound type variable and errors at monomorphization if still unbound:

1.

```rust
foo<_, _, 3, 12>
```

4. 

```rust
let deserialized: Vec<_> = input.deserialize();
```

### Project Impact

Nice-to-have

### Workaround

Yes

### Workaround Description

Specify all of the arguments and types explicitly

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
See #4664
