### ISSUE TITLE
Clean up Elaborator hacks

### ISSUE THREAD

**Issue by vezenovm** [noir-lang/noir#5231]
### Problem

The elaborator and the old resolution/type checking passes re-use certain types and the same CI flow. This can lead to some hacks in the codebase to get certain types working in both the old pass as well as the new elaborator. We should remove all these hacks once we fully move over to the elaborator.

E.g. in https://github.com/noir-lang/noir/pull/5155 we added a test for explicit numeric generic that only works with the elaborator.

### Happy Case

Link this issue anywhere there is elaborator tech debt and clean up the respective tech debt. 

### Project Impact

Nice-to-have

### Workaround

None

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
@vezenovm Was this all suitably cleared up once we removed the old flow?

**Comment by vezenovm** [comment]
Yes I believe so, I cannot find the issue linked anywhere in the code base either so any new hacks can be linked in a new issue.
