### ISSUE TITLE
Support array lengths inferred from compile time arithmetic

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#528]
# Problem

It is not possible to infer the fixed length of an array if it is to be determined by compile time arithmetic. E.g. the following won't compile:
```
use dep::std;

fn append(arr: [u8], elem: u8) -> [u8] {
    let out_length = std::array::len(arr) + 1;
    let mut out = [0; out_length];
    for i in 0..std::array::len(arr) {
        out[i] = arr[i];
    };
    out[std::array::len(arr)] = elem;
    out
}

fn main(x : [u8; 10]) -> pub [u8; 11] {
    append(x, 1)
}
```
Error:
```
aztec@Aztecs-MBP fixed_length % nargo build
error: Expression invalid in an array-length context
  ┌─ /Users/aztec/Desktop/fixed_length/src/main.nr:5:23
  │
5 │     let mut out = [0; out_length];
  │                       ---------- Array-length expressions can only have simple integer operations and any variables used must be global constants
```
Aside: What does "simple integer operations" refer to in this error message? Any operation like addition or multiplication doesn't seems to be supported.

In order to make this example compile you are forced to redefine the function in terms of globals or literals, which greatly impacts the reusability of the function:
```
global in_length = 10;
global out_length = 11;

fn append(arr: [u8; in_length], elem: u8) -> [u8; out_length] {
    let mut out = [0; out_length];
    for i in 0..std::array::len(arr) {
        out[i] = arr[i];
    };
    out[std::array::len(arr)] = elem;
    out
}
```

# Solution

Add support for compile time expressions as array lengths.

**Comment by joss-aztec** [comment]
I messed up my testing before - can confirm that the compiler accepts `let mut arr = [0; some_global + 1];`. But yes, `comptime` support would be great, since what I really want is `let mut arr2 = [0; std::array::len(arr1) + 1];`.

**Comment by jfecher** [comment]
Hi @rahulghangas, no progress on this specifically, but we have figured out a scheme for implementing slices into Noir such that users can use them and not have to worry about the array size being inferred in the type system. It's worth noting the array size is still tracked, but this happens at a later step of compilation once more information is known.

The `[0; out_length]` with a `comptime` (but not a constant-integer) `out_length` still won't be supported by that change unfortunately. I do think the addition of slices will allow this one to be more easily supported later on.

**Comment by LogvinovLeon** [comment]
Currently oracles don't support nested arrays and I've hit this issue trying to implement `flatten` for oracle args.
So just bumping this up as it makes it impossible to pass arbitrary structures to oracles.

I would like to do something like this:
```rust
pub fn flatten<T, M>(array: [[T; 32]; M]) -> [T; 32 * M] {
    let mut result = [0; 32 * M];
    for i in 0..M {
        for j in 0..32 {
            result[i * 32 + j] = array[i][j];
        }
    }
    result
}
```

**Comment by TomAFrench** [comment]
Closing this as we can now support this through static assertions + explicit numeric generics. This can be made more user-friendly with the usage of macros also.
