### ISSUE TITLE
`use dep::{foo, bar}` is formatted into `use {foo, bar}` which is invalid

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#5299]
See commit https://github.com/AztecProtocol/aztec-packages/pull/7134/commits/d2b452927ca844d687b69f94aa65a4d9bf6cf10e which was required workaround for this issue

**Comment by asterite** [comment]
I think this was introduced in https://github.com/noir-lang/noir/pull/4946, see https://github.com/noir-lang/noir/pull/4946/files#r1666774807

**Comment by TomAFrench** [comment]
Solved by new formatter right? @asterite

**Comment by asterite** [comment]
It seems so! :-)
