### ISSUE TITLE
Add test vectors for pedersen commitments/hashes with non-zero separators

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#5315]
We recently ran into an issue during the [Noir sync](https://github.com/AztecProtocol/aztec-packages/pull/7134) which slipped through due to a lack of tests for non-zero separators.

We should generate some test vectors using an old version of Noir prior to the removal of pedersen blackbox functions, port over the changes from [this commit](https://github.com/AztecProtocol/aztec-packages/pull/7134/commits/b77204a75c0bbe0850994e37e6f6ab21c9478446) and ensure that the new implementation matches these values.

**Comment by guipublic** [comment]
I added test vector in PR #5431
