### ISSUE TITLE
Terminology: ACIR gates -> ACIR opcodes

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#536]
# Description

## Aim

Use standard terminology.

## Expected behavior

The term "ACIR opcodes" should be used in place of "ACIR gates"

## Bug

When proving, ACIR opcodes are instead referred to as ACIR gates:
```
...
ac8f20451d553902fcc99b82bb87589077f0549bad5bdbd6734191ac
Proof successfully created and located at proofs/p.proof
Ok("/Users/aztec/Desktop/range_test/proofs/p.proof")
ACIR gates generated : 47
```

# To reproduce

Prove any circuit.

**Comment by guipublic** [comment]
I think ACIR gates is correct, while an ACIR opcode refers to the opcode of an ACIR custom gates.

**Comment by joss-aztec** [comment]
(@kevaundray put me up to this)

**Comment by vezenovm** [comment]
This was changed in the new `acvm` repo. This can be seen in the [CHANGELOG](https://github.com/noir-lang/acvm/blob/master/CHANGELOG.md) under 0.3.0
