### ISSUE TITLE
`Option<[u8]>::none()` panics at SSA

### ISSUE THREAD

**Issue by michaeljklein** [noir-lang/noir#5429]
### Aim

Ran `nargo compile` on:

```rust
fn main() {
    let _: Option<[u8]> = Option::none();
}
```

### Expected Behavior

The program to compile without errors

### Bug

```bash
❯ nargo compile
The application panicked (crashed).
Message:  internal error: entered unreachable code: ICE: unexpected array literal type, got [u8]
Location: compiler/noirc_evaluator/src/ssa/ssa_gen/mod.rs:203
```

### To Reproduce

1.
2.
3.
4.

### Project Impact

None

### Workaround

None

### Installation Method

None

### Nargo Version

nargo version = 0.31.0 noirc version = 0.31.0+7b77bbfc19c51829814149e623257a3424d8e8c2 (git version hash: 7b77bbfc19c51829814149e623257a3424d8e8c2, is dirty: true)

### Would you like to submit a PR for this Issue?

None

**Comment by asterite** [comment]
This also reproduces the same issue:

```rust
fn main() {
    let _: [u8] = std::unsafe::zeroed();
}
```

@noir-lang/core Is there a way for `zeroed` to work on slices? Maybe it's just a tuple `(0, 0)`?

**Comment by jfecher** [comment]
@asterite should just be an empty slice `&[]`. IIRC we already do this as well.
