### ISSUE TITLE
Numeric generic struct parameter panics when accessed uninitialized

### ISSUE THREAD

**Issue by michaeljklein** [noir-lang/noir#5436]
### Aim

Attempted to compile the following program:

```rust
struct Foo<let N: u32> { }

impl<let N: u32> Foo<N> {
    fn size(self) -> u32 {
        N
    }
}

fn main() {
    let foo = Foo { };
    assert(foo.size() == 0);
}
```

### Expected Behavior

Expected the program to either compile successfully (having defaulted `N = 0`) or fail with a user error because `N` is uninitialized when declaring `foo`.

### Bug

```bash
The application panicked (crashed).
Message:  Non-numeric type variable used in expression expecting a value
Location: compiler/noirc_frontend/src/monomorphization/mod.rs:909
```

### To Reproduce

1.
2.
3.
4.

### Project Impact

None

### Workaround

None

### Installation Method

None

### Would you like to submit a PR for this Issue?

None

**Comment by vezenovm** [comment]
> fail with a user error because `N` is uninitialized when declaring `foo`.

Yeah I think we should fail with that a type annotation is needed here.

**Comment by asterite** [comment]
@noir-lang/core Rust gives an error whenever a type's generic can't be deduced. For example:

```rust
struct Foo<const N: u32> {}

impl<const N: u32> Foo<N> {
    fn size(self) -> u32 {
        N
    }
}

fn main() {
    let foo = Foo {}; // type annotations needed for `Foo<N>`
    let x = foo.size();
}
```

That said, the error happens regardless of `size()` being called or not. This produces the same error:

```rust
fn main() {
    let foo = Foo {}; // type annotations needed for `Foo<N>`
}
```

However in Noir we don't error in that case. Here's a Noir program that compiles fine:

```rust
struct Foo<N> { }

fn main() {
    let foo = Foo {}; // No error here, `foo` is deduced to be `Foo<_>`
}
```

But maybe the above program should give an error similar to Rust? What do you think?

**Comment by michaeljklein** [comment]
I would prefer to error whenever a type's generic can't be deduced.

Consider the following code:

```rust
fn copy_from_slice<let N: u32>(xs: [u8]) -> [u8; N] {
  let mut inp = xs;
  let mut out = [0; N];
  for i in 0..N {
    let (x, rest) = inp.pop_front();
    inp = rest;
    out[i] = x;
  }
}

let my_slice: [u8] = [0; 8].as_slice();
let output_array = copy_from_slice(my_slice);
```

If we default `N`, `output_array` will have `length == 0` and nothing will be copied/output.

**Comment by jfecher** [comment]
We should error in this case - I'm surprised we don't. Perhaps we treat these numeric generics as TypeVariableKind::Integers and thus default them instead?
