### ISSUE TITLE
Wrong Failed Constraint Error

### ISSUE THREAD

**Issue by LukiMueller** [noir-lang/noir#5463]
### Aim

I experimented with the language and found a weird behavior.
When executing the following code with `nargo execute`:

main.nr:
```rust
pub fn main(x : Field) -> pub Field {
    let mut y : Field = 0;
    if (!(6.lt(x)) | !(6.lt(x)))
    {
        y = x;
    }
    else
    {
        y = 1;
    }
    assert(((x == y) | true), "assertion");
    y
}
```

Prover.toml:
```
x = "10"
```

I receive a failed constraint error for the expression inside of the `assert` statement.
I am unsure why I receive this error in this particular case.
if I remove one of the `!(6.lt(x))` expressions of the condition everything executes as expected, which seems even weirder to me.

### Expected Behavior

I expect to run `nargo execute` without receiving an error and to receive following expected output:

```
[playground] Circuit witness successfully solved
[playground] Circuit output: Field(1)
```

### Bug

This is the error message I receive from executing `nargo execute`:

```
error: Failed constraint
   ┌─ /app/src/main.nr:11:14
   │
11 │     assert(((x == y) | true), "assertion");
   │              -----------
   │
   = Call stack:
     1. /app/src/main.nr:11:14
```

### To Reproduce

1. create a project with the provided `main.nr` and `Prover.toml`
2. `nargo execute`
3.
4.

### Project Impact

None

### Workaround

None

### Installation Method

Binary (`noirup` default)

### Would you like to submit a PR for this Issue?

None

**Comment by jfecher** [comment]
What compiler version are you using?

I can't reproduce this on latest master (82a67a0e)

**Comment by LukiMueller** [comment]
Hey, thank you for the quick reply.

```
> nargo --version
nargo version = 0.30.0
noirc version = 0.30.0+af57471035e4fa7eaffa71693219df6d029dbcde
(git version hash: af57471035e4fa7eaffa71693219df6d029dbcde, is dirty: false)
```
I am using the default install when executing `noirup`.

**Comment by jfecher** [comment]
I've confirmed it's failing on your commit and not failing on master - so this bug has been fixed. You should see the fix in a future update. Alternatively, if this is blocking you can download nargo nightly via noirup as well to see this fix today.

**Comment by LukiMueller** [comment]
Seems like this was the fixing commit:
  * https://github.com/noir-lang/noir/pull/5100/commits/91e6e5319c648122d10d0b8af41782190243829d
