### ISSUE TITLE
Trait with superfluous generic argument panics

### ISSUE THREAD

**Issue by michaeljklein** [noir-lang/noir#5542]
### Aim

Attempted to compile the following program:

```rust
impl std::ops::Add<()> for () {
    fn add(self, other: ()) -> () { }
}

fn main() { }
```

### Expected Behavior

The program to compile successfully

### Bug

Compilation panics with:

```bash
❯ nargo compile
The application panicked (crashed).
Message:  assertion `left == right` failed
  left: 0
 right: 1
Location: compiler/noirc_frontend/src/elaborator/mod.rs:1526
```

### To Reproduce

1.
2.
3.
4.

### Project Impact

None

### Workaround

None

### Installation Method

Binary (`noirup` default)

### Nargo Version

nargo version = 0.31.0 noirc version = 0.31.0+45e82a672b9ba7f7326e8d9f8800e2489013e2e8 (git version hash: 45e82a672b9ba7f7326e8d9f8800e2489013e2e8, is dirty: false)

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
Note this is because the `Add` trait is not generic.

https://github.com/noir-lang/noir/blob/5bbce7977f72b07336bc8ef09f6acff687f1644a/compiler/noirc_frontend/src/elaborator/mod.rs#L1527
