### ISSUE TITLE
Blackbox `AND` function fails identity tests

### ISSUE THREAD

**Issue by michaeljklein** [noir-lang/noir#5597]
### Aim

Attempted to test that `ONES` (max-bit-size `11111..` in binary) is a left/right identity of the `AND` function

### Expected Behavior

Expected that `AND(ONES, x) == AND(x, ONES) == x`

### Bug

Both tests fail: https://github.com/noir-lang/noir/pull/5484/files#diff-6c685a553939db8389f16b6cf06d7d4caae94f46d64e327233fe02c7b4f8dbafR883

(Even when restricted values `<= ONES`)

### To Reproduce

1.
2.
3.
4.

### Project Impact

None

### Workaround

None

### Installation Method

Compiled from source

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
This is an issue in the testing code as discussed here: https://github.com/noir-lang/noir/pull/5484#discussion_r1690139207
