### ISSUE TITLE
Add tests for noir-bignum and noir-rsa in `external-repo-checks`

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#5627]
### Problem

[noir-bignum](https://github.com/noir-lang/noir-bignum) and [noir_rsa](https://github.com/noir-lang/noir_rsa) are receiving and making growing attention and impact to community projects.

We should maintain the libraries well, but they are not currently tested against Noir master to flag related breaking changes.

### Happy Case

Add tests for the libraries in [`external-repo-checks`](https://github.com/noir-lang/noir/blob/28211a397b810c661204b45b7da06f7cad345278/.github/workflows/test-js-packages.yml#L512-L528) to proactively flag Noir changes that will break the libraries, prompting library updates necessary to work with new Noir versions.

### Project Impact

Nice-to-have

### Would you like to submit a PR for this Issue?

None

**Comment by vezenovm** [comment]
> We should maintain the libraries well, but they are not currently tested against Noir master to flag related breaking changes.

We had turned off the `external_repo_checks` as any breaking changes would give a big red X on our PRs that are actually valid and pass our CI. I think these types of checks against Noir nightlies should be done on the libraries themselves.
