### ISSUE TITLE
Generic unsupported u64 type

### ISSUE THREAD

**Issue by LesterEvSe** [noir-lang/noir#5632]
### Aim

Why is the u64 type not supported? Is this how it should be, or is it a bug?
nargo - 0.32.0
bb - 0.46.1

### Expected Behavior

Expected to use u64 type

### Bug

![image](https://github.com/user-attachments/assets/1f943afd-316d-424d-8261-56f124ca6ce8)

error: The only supported numeric generic types are `u1`, `u8`, `u16`, and `u32`
    ┌─ /home/user/nargo/github.com/noir-lang/noir-bignumv0.2.2/src/lib.nr:296:6
    │
296 │ impl<let N: u64, Params> std::ops::Mul for BigNum<N, Params> where Params: BigNumParamsTrait<N> + RuntimeBigNumParamsTrait<N>  {
    │      ----------
    │

error: The only supported numeric generic types are `u1`, `u8`, `u16`, and `u32`
    ┌─ /home/user/nargo/github.com/noir-lang/noir-bignumv0.2.2/src/lib.nr:306:6
    │
306 │ impl<let N: u64, Params> std::ops::Div for BigNum<N, Params> where Params: BigNumParamsTrait<N> + RuntimeBigNumParamsTrait<N>  {
    │      ----------
    │

error: The only supported numeric generic types are `u1`, `u8`, `u16`, and `u32`
    ┌─ /home/user/nargo/github.com/noir-lang/noir-bignumv0.2.2/src/lib.nr:313:6
    │
313 │ impl<let N: u64, Params> std::cmp::Eq for BigNum<N, Params> where Params: BigNumParamsTrait<N> + RuntimeBigNumParamsTrait<N>  {
    │      ----------
   

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Workaround Description

None

### Additional Context

None

### Project Impact

None

### Blocker Context

None

### Would you like to submit a PR for this Issue?

None

**Comment by jfecher** [comment]
`u64` is mainly only unsupported due to internal implementation details that can be changed.
The other reason is that there's not much of a use case for it currently since the index & length type in Noir is `u32` not `u64`.

Looks like the bignum library was just updated to use `u32` - it was a bit out of date.
