### ISSUE TITLE
Bump bb to 0.47.1

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#5636]
### Problem

Noir master is currently compatible against Barretenberg v0.46.1, but not v0.47.1.

The new Barretenberg v0.47.1 offers the ability to generate Honk Solidity verifiers, which could be useful for Noir devs.

### Happy Case

Update Noir / Barretenberg to make Noir master compatible with Barretenberg v0.47.1.

### Workaround

None

### Additional Context

Previous bump PRs for reference:

### Project Impact

None

### Would you like to submit a PR for this Issue?

None

**Comment by Savio-Sou** [comment]
@TomAFrench why are we closing?

**Comment by TomAFrench** [comment]
Dupe of https://github.com/noir-lang/noir/issues/5637
