### ISSUE TITLE
Calling function defined in struct needs let binding

### ISSUE THREAD

**Issue by michaeljklein** [noir-lang/noir#5644]
### Aim

Attempted to call a function defined in a struct:

```rust
struct Foo {
    wrapped: fn(Field) -> bool,
}

impl Foo {
    fn call(self, x: Field) -> bool {
        // This works:
        // let f = self.wrapped;
        // f(x)

        self.wrapped(x)
    }
}

fn main() { }
```

### Expected Behavior

Expected the function call to work: `struct_object.fn_in_struct_field_name(input)`

### Bug

The function call fails unless the function is first pulled out into a `let` binding:

```rust
error: No method named 'wrapped' found for type 'Foo'
  ┌─ /Users/michaelklein/Coding/rust/noir/tmp2/src/main.nr:7:9
  │
7 │         self.wrapped(x)
  │         ---------------
  │
```

### To Reproduce

1.
2.
3.
4.

### Workaround

Yes

### Workaround Description

Use a let binding as above

### Project Impact

Nice-to-have

### Would you like to submit a PR for this Issue?

None

**Comment by asterite** [comment]
I was about to start working on this, but I checked if Rust worked in this case. It turns out it doesn't!  Here's the error I get:

```rust
error[E0599]: no method named `wrapped` found for struct `Foo` in the current scope
 --> src/main.rs:7:14
  |
1 | struct Foo {
  | ---------- method `wrapped` not found for this struct
...
7 |         self.wrapped(x)
  |              ^^^^^^^ field, not a method
  |
help: to call the function stored in `wrapped`, surround the field access with parentheses
  |
7 |         (self.wrapped)(x)
  |         +            +
```

I was surprised this was the case. But maybe the reason is that if I later go and define a `wrapped()` function in `Foo`, the meaning of the code will suddenly change.

I guess we can still keep this issue open and improve the error message here?

**Comment by jfecher** [comment]
This is expected behavior - `foo.bar(baz)` is always a method call in Rust and Noir. To call a field you must use parenthesis or a separate let binding. If we want to improve the error message I think we can have a second issue for that.
