### ISSUE TITLE
`Keccak256` returns constant output instead of error on invalid length

### ISSUE THREAD

**Issue by michaeljklein** [noir-lang/noir#5689]
### Aim

Attempted to test the [following comment](https://github.com/noir-lang/noir/blob/2b18151168b4fa0b1a4173b11f047ff2fc338d28/acvm-repo/acir/src/circuit/opcodes/black_box_function_call.rs#L144) on the `Keccak256` blackbox instruction:

```rust
        /// This is the number of bytes to take
        /// from the input. Note: if `var_message_size`
        /// is more than the number of bytes in the input,
        /// then an error is returned.
        var_message_size: FunctionInput<F>,
```

By solving a simple circuit with the instruction that has a `var_message_size` that's `1` greater than the actual number of bytes in the input.

### Expected Behavior

Expected a user error or panic

### Bug

The function fails this [injectivity test](https://github.com/noir-lang/noir/pull/5614/files#diff-6c685a553939db8389f16b6cf06d7d4caae94f46d64e327233fe02c7b4f8dbafR1377), but does not fail with an error indicating `var_message_size` is wrong. 

Note that the injectivity test with the correct `var_message_size` passes.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Project Impact

None

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
Closing as we no longer have a `keccak256` opcode
