### ISSUE TITLE
`Keccak256` blackbox instruction injectivity test fails

### ISSUE THREAD

**Issue by michaeljklein** [noir-lang/noir#5690]
### Aim

Attempted to test that the `Keccak256` blackbox instruction is injective as part of https://github.com/noir-lang/noir/pull/5614

### Expected Behavior

Expected to find that solving the `Keccak256` blackbox function on different inputs resolves to different outputs, i.e.

```haskell
forall x, y. x != y -> f x != f y
```

### Bug

The following test passes:

```rust
#[test]
fn keccak256_injective_regression() {
    // 2⁸×61916068613087029720904767285796661
    let x = FieldElement::from(15850513564950279608551620425163945216u128);

    // 2⁸×220343640628484768581538005104492351
    let y = FieldElement::from(56407972000892100756873729306750041856u128);
    assert!(x != y);

    let inputs = vec![(x, false)];
    let distinct_inputs = vec![(y, false)];
    let num_outputs = 32;

    assert_eq!(
        solve_array_input_blackbox_call(inputs, num_outputs, keccak256_op),
        solve_array_input_blackbox_call(distinct_inputs, num_outputs, keccak256_op));

    assert!(result, "{}", message);
}
```

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Project Impact

None

### Would you like to submit a PR for this Issue?

None

**Comment by michaeljklein** [comment]
I am still looking into this, but @vezenovm suggested that `keccak256` could silently require the `num_bits` of the `FunctionInput` to be `8`.

**Comment by TomAFrench** [comment]
Closing as we no longer have a `keccak256` opcode
