### ISSUE TITLE
Large input in Prover.toml

### ISSUE THREAD

**Issue by okuyiga** [noir-lang/noir#570]
# Description

## Aim

Inputs in `Prover.toml` cannot accept values larger than `2^63 - 1` (`9223372036854775807`). 

## Expected behavior

Any valid Field element should be allowed.

## Bug

If I have a private input `x` of type `u124`
```rs
fn main(x : u124) {
    constrain x != 0;
}
```
With the following `Prover.toml`
```toml
# Fails
x=9223372036854775808

# Succeeds
# x=9223372036854775807
```

Proving fails with the following message

```
Error: input.toml file is badly formed, could not parse, invalid number at line 1 column 3
```

**Comment by TomAFrench** [comment]
toml treats all numbers as i64s so this is expected. If you wrap the value in quotes then it should be read correctly though.

**Comment by okuyiga** [comment]
That makes sense - my mistake!
