### ISSUE TITLE
Request for improvements to contract verifier how-to

### ISSUE THREAD

**Issue by partylikeits1983** [noir-lang/noir#5711]
### Problem

I used Noir 3 months ago, the running `nargo codegen-verifier` created a solidity verifier. Now this feature was removed. 

### Happy Case

`nargo codegen-verifier` should result in a solidity verifier. Why move it to some npm package?? Now my project needs a forge.toml, cargo.toml, and a package.json??? Additionally the docs got worse, they assume developers who use noir will use remixIDE? 

### Workaround

Yes

### Workaround Description

Search for 30 minutes how to generate a solidity verifier. 

### Project Impact

Blocker

### Blocker Context

Why remove useful features?

### Would you like to submit a PR for this Issue?

Maybe

**Comment by partylikeits1983** [comment]
Please add this to your docs: https://github.com/AztecProtocol/aztec-packages/blob/ss/doc-bb-honk/barretenberg/cpp/src/barretenberg/bb/readme.md#usage-with-ultrahonk

These docs are very misleading: https://noir-lang.org/docs/how_to/how-to-solidity-verifier

**Comment by TomAFrench** [comment]
This command was removed as the verifier contract is specific to a particular proving backend. Nargo no longer handles communication with the proving backend in order to make it easier to use 3rd party backends, and so the contract must be generated on the backend directly.

**Comment by TomAFrench** [comment]
We do link to the BB docs when we introduce usage of bb in our documentation. https://noir-lang.org/docs/dev/getting_started/hello_noir/#proving-backend

cc @developerrelations on issues with contract verifier tutorial.

**Comment by partylikeits1983** [comment]
Yes, I found how to generate a proving contract, this is at the bottom of `Creating a project` in the docs. The `Generate a Solidity verifier` should also have the same info on how to use `bb` for people who don't use RemixIDE. 

@TomAFrench Also how to pass the a proof to the generated contract to verify? There used to be a file with a `.proof` extension, what is the new equivalent?

**Comment by TomAFrench** [comment]
https://noir-lang.org/docs/how_to/how-to-solidity-verifier#step-4---verifying

**Comment by critesjosh** [comment]
@partylikeits1983 from what i understand, the info that you are looking for is included in [Step 1](https://noir-lang.org/docs/how_to/how-to-solidity-verifier#step-1---generate-a-contract) of the page. The information that follows is meant to demonstrate how you could interact with the verifier. I opened a [PR](https://github.com/noir-lang/noir/pull/5754) to make it easier to find more info about `bb` from the Solidity Verifier page. Just want to check that these edits address your issue.

@Savio-Sou do we want to add instructions for generating solidity verifiers with ultrahonk yet?

**Comment by Savio-Sou** [comment]
@critesjosh I haven't personally figured out how to extract public inputs from Honk proofs yet, but we are clear to document it is expected to work from Noir v0.33.0 + bb v0.47.1 onwards.

Will defer to your team on is updating the Noir docs page sustainably feasible (i.e. if we need to consider migrating content to bb's README).
