### ISSUE TITLE
Optimise away predicates which are always true

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#573]
# Problem

The following program:

```rust
 fn main( y: Field, z: Field) {
    let x = y + z;
    constrain x == 20;
}
```

Will generate the following opcodes:

```
1x1 + 1x2 + -1x3 + -20 = 0
x4=1/x3, or 0
1x3*x4 + -1x5 + 0 = 0
1x3*x5 + -1x3 + 0x5 + 0 = 0
1x5 + 0 = 0
```

Note that there is an inversion being done here, when the original code should not require it. This is because the predicate is not being optimised away

# Solution

Add optimisation to remove this extra overhead.

# Alternatives considered

(Describe any alternative solutions you have considered.)

# Additional context

**Comment by jfecher** [comment]
Looks like the Acir generated for this is now:
```
EXPR [ (1, _3, _4) (1, _5) -1 ]
EXPR [ (1, _3, _5) 0 ]
EXPR [ (1, _5) -1 ]
```
