### ISSUE TITLE
Struct assignment occurs in if branch when predicate is false

### ISSUE THREAD

**Issue by okuyiga** [noir-lang/noir#579]
# Description

## Aim

Struct assignment in an if statement

## Expected behavior

The assignment should not occur when the statement is false

## Bug

The assignment always occurs

# To reproduce

[Snippet](https://gist.github.com/okuyiga/268aaf8f510c75c4fa753fc8c50f23c7)

# Environment

- OS: Debian

For `nargo` users

- _noir-lang/noir_ commit cloned: Nightly build from 2022-12-09

**Comment by Globallager** [comment]
Thanks 🙌 Extracted a condensed reproduction snippet from your example for others' easy reference:
```rust
struct MyStruct {
    array_param: [u32; 8]
}

impl MyStruct {
    fn new(array_param: [u32; 8]) -> MyStruct {
        MyStruct {
            array_param: array_param
        }
    }
}

fn test(flag: bool) -> MyStruct {
    let mut my_struct = MyStruct::new([4; 8]);
    if flag {
        my_struct = MyStruct::new([3; 8]);
    }
    my_struct
}

fn main() {
    let result1_true = test(true);
    constrain result1_true.array_param[0] == 3;
    let result1_false = test(false);
    constrain result1_false.array_param[0] == 3; // Somehow it still went in the if-statement.
    // constrain result1_false.array_param[0] == 4; // Error: Constraint is always false
}
```

A more through reproduction can be found in OP's snippet.
