### ISSUE TITLE
Check for correct bit-size in ACVM solver

### ISSUE THREAD

**Issue by michaeljklein** [noir-lang/noir#5793]
### Problem

Several of the blackbox functions fail in a variety of ways on inputs with too many bits. See https://github.com/noir-lang/noir/pull/5614/ for examples.

NOTE: this is currently causing non-deterministic failures, see [Maxim's comment](https://github.com/noir-lang/noir/issues/5793#issuecomment-2313294089) below

### Happy Case

As per [Maxim's comments](https://github.com/noir-lang/noir/pull/5614/#discussion_r1710410959) on https://github.com/noir-lang/noir/pull/5614:

- We should have a clearer ban on the bit size for these functions so this isn't possible at all.
- Let's make sure we are setting up the input bits correctly here and update the issue accordingly.
- At a minimum we should panic if the incorrect bit size is provided (e.g. 254 instead of 8 for keccak256) so that we know codegen is incorrect.
- We could probably just return an `OpcodeResolutionError<F>::BlackBoxFunctionFailed`

### Workaround

None

### Project Impact

Nice-to-have

### Blocker Context

It's similar to overflow checks for blackbox function _inputs_

### Would you like to submit a PR for this Issue?

None

**Comment by vezenovm** [comment]
This is causing non-deterministic failures  https://github.com/noir-lang/noir/actions/runs/10582178394/job/29321514166?pr=5838.
