### ISSUE TITLE
`Quoted::as_...` doesn't consume all tokens

### ISSUE THREAD

**Issue by asterite** [noir-lang/noir#5803]
### Aim

When turning Quoted into something else, it seems once tokens were consumed to form the target type, the rest of the tokens are discarded. Maybe in that case it should error with "expecting EOF" or something like that.

For example:

```rust
fn main() {
    comptime
    {
        let expr = quote { x = hello world ([{}]) }.as_expr().unwrap();
        println(expr);
    }
}
```

Output:

```
x
``` 

### Expected Behavior

The above program errors because the entire token stream doesn't parse to an expression.

### Bug

Remaining tokens are silently discarded.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Project Impact

None

### Would you like to submit a PR for this Issue?

None

**Comment by asterite** [comment]
I'm also thinking, given that `as_expr()` can actually wrap a statement, an LValue, eventually a Pattern... maybe `as_expr()` would try to parse each of those things in turn, right? So you could do `quote { a = 1; }.as_expr()` instead of having to wrap that in a block expression.

**Comment by jfecher** [comment]
Yeah. I do wonder if that could be problematic though. If there's ever when you'd parse a variable but you wanted an lvalue variable or a pattern variable or something. Not sure but if that's ever the case we'd have to split Expr into the actual 2-4 types it wraps.
