### ISSUE TITLE
Invalid Proof Verification: `bb` verification key does nothing?

### ISSUE THREAD

**Issue by lamafab** [noir-lang/noir#5805]
### Aim

I tried to make sure that verifying a proof of a Noir program fails when specifying the verification key of the **different** Noir program. But it doesn't.

### Expected Behavior

The proof should be linked to a specific Noir program. Verifying said proof should fail when verifying against a verification key of a different Noir program. Or am I misunderstanding this step?

### Bug

Setup:

```bash
$ nargo --version
nargo version = 0.31.0
noirc version = 0.31.0+540bef3597bd3e5775c83ec2ee3c0d4463084b4c
(git version hash: 540bef3597bd3e5775c83ec2ee3c0d4463084b4c, is dirty: false)
$ bb --version
0.41.0
```

Prover input:

```console
$ cat Prover.toml 
key = "2"
```

Demonstration:

```console
# Init program...
cat <<EOL > src/main.nr
fn main(key: Field) {
    assert(key == 2);
}
EOL

# Create proof
nargo execute witness
bb prove -b ./target/noir.json -w ./target/witness.gz -o ./target/proof

# Modify program (note that `key = "2" != 3`)...
cat <<EOL > src/main.nr
fn main(key: Field) {
    assert(key == 3);
}
EOL

# Create new `noir.json`
nargo compile

# Verify proof
bb write_vk -b ./target/noir.json -o ./target/vk
bb verify -k ./target/vk -p ./target/proof 

# This verifies happily... why?
```

### Workaround

None

### Project Impact

Nice-to-have

### Nargo Version

nargo version = 0.31.0 noirc version = 0.31.0+540bef3597bd3e5775c83ec2ee3c0d4463084b4c (git version hash: 540bef3597bd3e5775c83ec2ee3c0d4463084b4c, is dirty: false)

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
`bb` returns whether the proof is valid or not using its exit code (0 for successful proofs, 1 for unsuccessful proofs). If you run `echo $?` after the steps listed you can see that `bb` exited unsuccessfully and so the proof was rejected.

I agree that this isn't flagging up potential failures to a user on the CLI very clearly. Can you create an issue over on https://github.com/AztecProtocol/aztec-packages?

**Comment by lamafab** [comment]
Yes, you're right. Running `echo $?` shows the error code correctly, as expected. But simply being quiet like this is very dangerous, imo... Anyway I guess we can close this. Thanks for the quick response.
