### ISSUE TITLE
Add `Module::add_item`

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#5875]
### Problem

(From a slack request)

Given just a `Module` metaprogramming object, there is no way to add additional functions or types to the module.

### Happy Case

We add the function:
```
impl Module {
    fn add_item(self, item: Quoted) {}
}
```
To add a top-level item to the module.

### Workaround

None

### Project Impact

None

### Would you like to submit a PR for this Issue?

None

**Comment by asterite** [comment]
I was actually wondering if this should be the only way to add new items to a program.

For example, if you have two annotations on a module:

```rust
#[one]
mod foo {
  #![two]
}
```

if there are functions `one` and `two` that return a `Quoted` value, where do they get inserted? I think right now for `one` it's inserted in `foo`'s parent, but for `two` it's inserted in `foo`... but maybe that's expected?

**Comment by jfecher** [comment]
@asterite I think I would expect both to be inserted within `foo`. We should have inner attributes just be a syntax thing that are otherwise equivalent to being on the module itself.

**Comment by asterite** [comment]
Sounds good, I'll capture an issue for this and likely work on it today.
