### ISSUE TITLE
Types on numeric generics are not respected

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#5886]
```
fn main() -> pub [u8; BAZ] {
    Foo::bar()
}

struct Foo;

trait Bar<let N: u1> {
    fn bar() -> [u8; N];
}

global BAZ: Field = 8;

impl Bar<BAZ> for Foo {
    fn bar() -> [u8; BAZ] {
        [0; BAZ]
    }

}

```
Consider the above program. I've specified that the `Bar` trait has a numeric generic parameter which is of the type `u1`. I'm then allowed to implement this trait using a `Field` of value 8. This then allows me to have `Foo::bar()` return a `[u8; 8]` whereas reading the trait definition this should not be allowed.

**Comment by vezenovm** [comment]
I made an issue for this here (https://github.com/noir-lang/noir/issues/5447). This is easier to implement as part of https://github.com/noir-lang/noir/issues/5156
