### ISSUE TITLE
Load backends dynamically

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#595]
# Problem

Currently backends are pulled in at compile time, which means we cannot use the same strategy as rustup which loads backends and switches them out at runtime.

# Solution

Dynamically load libraries

# Alternatives considered

(Describe any alternative solutions you have considered.)

# Additional context

(If applicable.)

**Comment by kevaundray** [comment]
This begs the question as to whether we need a Proving system trait in acvm or a c header that specifies the methods needed

**Comment by kobyhallx** [comment]
`Dynamically load libraries` requires number of considerations. 
Those to be have once dynamic backend invocation gets completed.
