### ISSUE TITLE
Switch to crates.io version of acvm

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#596]
# Problem

ACVM has been moved out of this repo and noir should depend on it by using version and github path. Preferably just the crates.io version and the github version can be used as an unstable tag.

# Solution

Switch the acvm dependencies for crates.io version

# Alternatives considered

(Describe any alternative solutions you have considered.)

# Additional context

(If applicable.)

**Comment by phated** [comment]
Completed by #647
