### ISSUE TITLE
Solidity: "Arithmetic operation underflow" in `compute_public_input_delta` function

### ISSUE THREAD

**Issue by kathodler** [noir-lang/noir#598]
# Description

When compiling a simple noir program with the nightly release on (25/12/22) (assume a4da7740c44ea92a548af518cbaf6d5de87444fb) upon running the verify function on the smart contract I get an underflow operation. Verifying by other means works as expected. 

## Aim

I want to compile this circuit and use solidity to verify the generated proof with the inputs `(3,111) -> 333`

```rust
fn main(x: u32, y: pub u32) -> pub u32 {
    let z = x * y;
    z
}
```

After `nargo compile p && nargo contract` I have to edit the contract pragma to remove the `<0.8.0` so I can deploy as suggested in [this discord post](https://discord.com/channels/563037431604183070/1051151566171820032) - if this is the issue would love to hear work arounds and example hardhat configs.

Then using ethers I call the `verify` contract method with public values for `y` and the `return` value like so:

```ts
async function loadAndVerifyWithSolidity() {
  const acir = await getAcirFromAcirFile(
    resolve(__dirname, "../circuits/build/p.acir")
  );

  const proof = await createProof(acir, {
    x: 3,
    y: 111,
    return: 333,
  });

  const provider = new ethers.providers.JsonRpcProvider();
  const signer = provider.getSigner();
  const abiCoder = new ethers.utils.AbiCoder();
  const encodedPubInputs = abiCoder.encode(
    ["uint256", "uint256"],
    ["111", "333"]
  );
  const pubInputs = Buffer.from(encodedPubInputs.slice(2), "hex");
  const verified = await submitProofTx(signer, proof, pubInputs);
}

async function submitProofTx(
  signer: ethers.providers.JsonRpcSigner,
  proof: Buffer,
  pubInputs: Buffer
) {
  const verifierContract = new ethers.Contract(
    FIRST_CONTRACT_DEPLOYMENT_ADDRESS,
    new ethers.utils.Interface([
      "function verify(bytes calldata, bytes calldata) public view returns (bool)",
    ]),
    signer
  );

  // Takes a byte array!
  const verifiedResult = await verifierContract.verify(proof, pubInputs);
  return verifiedResult;
}
```

When this is executed I get what looks like an underflow error.

## Expected behavior

Proof would be valid and the function would not error.

## Bug

After calling the contract `verify()` method the error in the hardhat console looks like this:

```bash
 eth_call
[0]   Contract call:       TurboVerifier#verify
[0]   From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
[0]   To:                  0x5fbdb2315678afecb367f032d93f642f64180aa3
[0] 
[0]   Error: VM Exception while processing transaction: reverted with panic code 0x11 (Arithmetic operation underflowed or overflowed outside of an unchecked block)
[0]       at TurboVerifier.compute_public_input_delta (contracts/TurboVerifier.sol:1238)
[0]       at TurboVerifier.evalaute_field_operations (contracts/TurboVerifier.sol:188)
[0]       at TurboVerifier.verify (contracts/TurboVerifier.sol:66)
[0]       at processTicksAndRejections (node:internal/process/task_queues:95:5)
[0]       at async HardhatNode.runCall (/workspaces/noir/node_modules/.pnpm/hardhat@2.12.4_z6wznmtyb6ovnulj6iujpct7um/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:652:20)
[0]       at async EthModule._callAction (/workspaces/noir/node_modules/.pnpm/hardhat@2.12.4_z6wznmtyb6ovnulj6iujpct7um/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:354:9)
[0]       at async HardhatNetworkProvider._sendWithLogging (/workspaces/noir/node_modules/.pnpm/hardhat@2.12.4_z6wznmtyb6ovnulj6iujpct7um/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:139:22)
[0]       at async HardhatNetworkProvider.request (/workspaces/noir/node_modules/.pnpm/hardhat@2.12.4_z6wznmtyb6ovnulj6iujpct7um/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:116:18)
[0]       at async JsonRpcHandler._handleRequest (/workspaces/noir/node_modules/.pnpm/hardhat@2.12.4_z6wznmtyb6ovnulj6iujpct7um/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:188:20)
[0]       at async JsonRpcHandler._handleSingleRequest (/workspaces/noir/node_modules/.pnpm/hardhat@2.12.4_z6wznmtyb6ovnulj6iujpct7um/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:167:17)
```

Investigating the code suggested by the error the error occurs here:

![image](https://user-images.githubusercontent.com/93621943/209459261-fc546923-f201-4e1d-b73b-f0a82c9b636d.png)

Looking at the verification key code generated by nargo it appears the `vk.num_inputs` field is set to `2` 

![image](https://user-images.githubusercontent.com/93621943/209459375-a5c33201-aa69-4adb-8cb8-6ee11af322bd.png)

I am guessing that since `0x2 * 0x20 - 0x60 = -0x20` that we are getting an underflow error because the type is uint256? Could this be attempted pointer arithmetic gone bad? 

Creating and verifying a proof with both typescript and nargo works fine so I assume the issue is purely with the solidity compilation.

# To reproduce

1. Create a simple nargo project with `nargo --version` being `0.1` 
2. `nargo compile p` to compile the acir file.
3. `nargo contract` to create the solidity contract
4. Remove the pragma `<0.8.0`
5. Create a hardhat project and deploy the contract eg.:
  ```ts
  const Verify = await ethers.getContractFactory("TurboVerifier");
  const contract = await Verify.deploy();
  await contract.deployed();
  ```
7. Use code similar to the above to call the `verify` method 

# Environment

- OS:Linux (NixOS)

For `nargo` users

- _noir-lang/noir_ commit cloned: a4da7740c44ea92a548af518cbaf6d5de87444fb
- Proving backend
  - [ ] default
  - [x] wasm-base

For TypeScript users

- Node.js: v18.12.1
- @noir-lang/noir_wasm: 0.10.0
- @noir-lang/barretenberg: 2.19.0
- @noir-lang/aztec_backend: 0.11.0

Environment is built using the following docker file:

```
ARG VARIANT=16-bullseye
FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:0-${VARIANT}
USER root
RUN mkdir -p /home/node/.config && chown -R node:node /home/node/.config
USER node
RUN curl -L https://foundry.paradigm.xyz | bash
RUN /home/node/.foundry/bin/foundryup
RUN npm install --location=global pnpm 
RUN mkdir -p $HOME/.nargo/bin && \
  curl -o $HOME/.nargo/bin/nargo-x86_64-unknown-linux-gnu.tar.gz -L https://github.com/noir-lang/noir/releases/download/nightly/nargo-x86_64-unknown-linux-gnu.tar.gz && \
  tar -xvf $HOME/.nargo/bin/nargo-x86_64-unknown-linux-gnu.tar.gz -C $HOME/.nargo/bin/ && \
  mkdir -p $HOME/.config/noir-lang
RUN cp -r $HOME/.nargo/bin/noir-lang/* "$HOME/.config/noir-lang/"
RUN echo '\nexport PATH=$PATH:$HOME/.nargo/bin' >> ~/.bashrc && \
  . ~/.bashrc
```

**Comment by kathodler** [comment]
Further information/workaround. It appears that when I build using TS/JS the contract works as expected:

```ts
export async function getAcirFromAcirFile(
  location = "../circuits/build/p.acir"
): Promise<Acir> {
  const buffer = await readFile(location);
  return acir_from_bytes(new Uint8Array(buffer));
}

export async function createSmartContract(acir: Acir) {
  let [, verifier] = await setupGenericProverAndVerifier(acir);
  return verifier.SmartContract();
}
```

```ts
import { createSmartContract, getAcirFromAcirFile } from "../sdk/lib";
import { resolve } from "path";
import { writeFileSync } from "fs";

async function main() {
  const acir = await getAcirFromAcirFile(
    resolve(__dirname, "../circuits/build/p.acir")
  );
  const sc = await createSmartContract(acir);

  writeFileSync(resolve(__dirname, "../contracts/TurboVerifier.sol"), sc);
}
main()
  .then(() => process.exit())
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
```

What appears to be at issue here is using `nargo contract` to create a verifier.

**Comment by kathodler** [comment]
Can confirm this occurs with:
```
@noir-lang/noir_wasm: next
@noir-lang/barretenberg: next
@noir-lang/aztec_backend: next
```

**Comment by kevaundray** [comment]
This seems to now be fixed in the latest contracts as no-one has opened up an issue regarding this and dev-rel have been running tests. If this issue pops up again, feel free to re-open!
