### ISSUE TITLE
Types in scope are not recognised via `quoted.as_type()`

### ISSUE THREAD

**Issue by Thunkar** [noir-lang/noir#6011]
### Aim

Rewrite fields inside a struct so that they include a generic the user omitted:

Given

```noir
#[storage]
struct Storage {
    counters: Map<AztecAddress, EasyPrivateUint>, // Both Map and EasyPrivateUint take Context as generic
}
```

I want to write: 

```noir
comptime fn add_context_generic(typ: Type, context_generic: Type) -> Type {
    assert(
        typ.as_struct().is_some(), "Storage containers must be generic structs of the form `Container<..., Context>`"
    );
    if is_storage_map(typ) {
        let (def, mut generics) = typ.as_struct().unwrap();
        let name = def.name();
        generics[generics.len() - 2] = add_context_generic(generics[1], context_generic);
        generics[generics.len() - 1] = context_generic;
        let generics = generics.map(|typ: Type| quote{$typ}).join(quote{,});
        quote { $name<$generics> }.as_type()
    } else {
        let (def, mut generics) = typ.as_struct().unwrap();
        let name = def.name();
        generics[generics.len() - 1] = context_generic;
        let generics = generics.map(|typ: Type| quote{$typ}).join(quote{,});
        quote { $name<$generics> }.as_type()
    }
}

pub comptime fn storage(s: StructDefinition) -> Quoted {
    let mut new_storage_fields = &[];
    let context_generic = s.add_generic("Context");
    for field in s.fields() {
        let (name, typ) = field;
        let with_context_generic = add_context_generic(typ, context_generic);
        new_storage_fields = new_storage_fields.push_back((name,  with_context_generic ));
    }

    s.set_fields(new_storage_fields);
}
```

So that the final (unquoted) code is:

```noir
struct Storage<Context> {
    counters: Map<AztecAddress, EasyPrivateUint<Context>, Context>,
}
```

### Expected Behavior

The above example works

### Bug

Compiler fails with: 

![Screenshot 2024-09-12 at 12 04 02](https://github.com/user-attachments/assets/85342ac1-aa95-4a25-91a7-2b9f9ab54b2f)

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Project Impact

None

### Would you like to submit a PR for this Issue?

None

**Comment by Thunkar** [comment]
> Are you sure the types are within scope?

I think so, since it works if I don't try to mess with the generics:

![Screenshot 2024-09-12 at 17 21 39](https://github.com/user-attachments/assets/5826e8bf-cf4f-43bb-a575-ef884a322e66)

**Comment by jfecher** [comment]
I can't seem to reproduce this. When adding the given code snippets to a file I get too many other unrelated errors. Fixing them would require me to add things.

I still think this issue could be because you are using `as_type()` which resolves types in the same scope as the attribute function (not the item the attribute is on). So the type may not be in scope there. I'm adding `#[use_callers_scope]` in a PR which would fix this issue if that guess was right. If not, it is still a useful attribute to have but wouldn't fix this issue.

**Comment by Thunkar** [comment]
The attribute solved the first issue and seems very useful overall. Now encountering a different one but unrelated, will repro that one and report. 

Feel free to close! @TomAFrench
