### ISSUE TITLE
Trait where clause isn't type-checked

### ISSUE THREAD

**Issue by asterite** [noir-lang/noir#6023]
### Aim

This program:

```noir
trait Foo<U> where U: Uknown<U> {}

fn main( ) {}
```

doesn't give an error.

### Expected Behavior

The compiler should say that it can't find `Unknown`.

### Bug

The compiler doesn't error.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Project Impact

None

### Would you like to submit a PR for this Issue?

None

**Comment by asterite** [comment]
@noir-lang/core Actually, it seems a trait's where clause is completely ignored. "Find all references" of `NoirTrait.where_clause` gives no results (except when it's created from parsing).

**Comment by jfecher** [comment]
I didn't know we allowed where clauses in this position at all. Checking these is somewhat similar to trait inheritance (which we also don't support) where we'd need to check/assume it everywhere the trait is used.
