### ISSUE TITLE
Docs for `Field` methods are out of date and fail to compile

### ISSUE THREAD

**Issue by michaeljklein** [noir-lang/noir#6070]
### Aim

Attempted to learn how `to_le_bytes` and `to_be_bytes` worked from their [`noir-lang.org/docs` page](https://noir-lang.org/docs/noir/concepts/data_types/fields#methods)

### Expected Behavior

Expected to find how those methods worked, including each parameter, along with working example code

### Bug

- The docs are out of date, as those methods (and several others) no longer return slices: https://github.com/noir-lang/noir/blob/master/noir_stdlib/src/field/mod.nr#L81
- The code in the docs isn't being run because it's failing on `nargo` nightly, e.g.

```noir
fn main() {
    let field = 2;
    let bytes = field.to_le_bytes(4);
}
```

```bash
warning: unused variable bytes
  ┌─ src/main.nr:3:9
  │
3 │     let bytes = field.to_le_bytes(4);
  │         ----- unused variable 
  │

error: Function expects 1 parameter but 2 were given
  ┌─ src/main.nr:3:17
  │
3 │     let bytes = field.to_le_bytes(4);
  │                 --------------------
  │

Aborting due to 1 previous error
```

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Project Impact

None

### Nargo Version

nargo version = 0.33.0 noirc version = 0.33.0+e84f7d2e81c1f59e9af015f38c2d477607a9c558 (git version hash: e84f7d2e81c1f59e9af015f38c2d477607a9c558, is dirty: false)

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
This is expected as those are the docs for the version 0.33.0 which is from before these changes. The latest docs are correct.
