### ISSUE TITLE
Downloading the SRS for Barretenberg is slow

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#61]
There should be a way to only download the necessary amount of the SRS

**Comment by codygunton** [comment]
Suggestion: it may be that the chunk size is not optimal.

**Comment by kevaundray** [comment]
Giving justification for the suggestion from our slack conversation:

Cody noticed that if you download the SRS using the AWS link in Firefox, it takes seconds to download. However, when we download it using reqwest, it is really slow.
