### ISSUE TITLE
Methods on primitive integers get mixed

### ISSUE THREAD

**Issue by asterite** [noir-lang/noir#6106]
### Aim

The following code:

```noir
trait Read {
    fn read(data: [Field; 1]) -> Self;
}

impl Read for Field {
    fn read(data: [Field; 1]) -> Self {
        data[0]
    }
}

impl Read for u32 {
    fn read(data: [Field; 1]) -> Self {
        data[0] as u32
    }
}

fn main() {
    let data = [1];
    let _: u32 = u32::read(data);
}
```

doesn't compile because the compiler thinks `u32::read` returns a `Field`.

### Expected Behavior

The above code compiles without error.

### Bug

The code above errors. I think it's because we store all integer-and-field methods in a single bucket (not sure!)

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Project Impact

None

### Would you like to submit a PR for this Issue?

None

**Comment by jfecher** [comment]
> doesn't compile because the compiler thinks u32::read returns a Field.

This is because of TypeMethodKey in the node interner. All integer types share the same method key with fields so that we can still call methods on polymorphic integer literals.
