### ISSUE TITLE
Stop storing ArrayIds in ObjectTypes

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#612]
# Problem

ObjectTypes are meant to be the type of an object, but ArrayIds refer to the value of a specific array instead. This makes the system as a whole less consistent and means we can not convert directly from a monomorphised Type into an ObjectType because we would not know which specific array value a given array type refers to.

# Solution

Arrays should likely be NodeObjs in our IR like other interned items are. More investigation is needed on the impacts of this decision and what other decisions may lead to a cleaner implementation of this change.

**Comment by jfecher** [comment]
Related is the TODO on line 306 of function.rs (once the first class functions PR is merged):

```rs
// TODO: There is a mismatch between intrinsics and normal function calls:
// Normal functions returning arrays have 1 ArrayId on the function itself
// Intrinsics generate a new Id on every call
```
These both point to a need to refactor ArrayIds in some way for more consistent handling of them.

**Comment by kevaundray** [comment]
Noting here since its about reworking arrays: calling `to_node_ids` on an expression which was an array can be a bit footgunny since it returns a single node_id and not a node_id per element.

You need to deref the node_id to get an array_id and then fetch all of the elements using the array_id

**Comment by kevaundray** [comment]
Closing, since this is about the old ssa
