### ISSUE TITLE
BB Prover Error in 'MemBn254CrsFactory'

### ISSUE THREAD

**Issue by MarkCampbell90** [noir-lang/noir#6147]
### Aim

I tried to execute and prove following toy noir program and input using the `bb`-prover:

~~~
// main.nr
pub fn main(input : Field) -> pub Field {
    let mut output : Field = 0;
    output = input;
    let zero = 0;
    let b1 : [u8; 32] = zero.to_be_bytes();
    let b2 : [u8; 32] = input.to_be_bytes();
    let mut b3 : [u8; 32] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
    for i in 0..32 {
        b3[i] = (b1[i] | b2[i]);
    }
    assert(!(0 == std::field::bytes32_to_field(b3)), "example assertion");
    output
}
~~~

~~~
// Prover.toml
input="1"
~~~

I used following commands and got following output:
~~~
$> nargo execute --force witness --expression-width 4
[Test] Circuit witness successfully solved
[Test] Circuit output: Field(1)
[Test] Witness saved to /app/noir-example/target/witness.gz

$> bb prove -b target/Test.json -w target/witness.gz -o proof
prover trying to get too many points in MemBn254CrsFactory! 205 vs 257
~~~

i used `nargo version 0.34.0` and `bb version 0.55.0`

### Expected Behavior

Since the program was accepted by `nargo`, I expected it to be also accepted by the `bb` prover. 

### Bug

`bb` gave me following error message

~~~
prover trying to get too many points in MemBn254CrsFactory! 205 vs 257
~~~

and exit code `1`. 

### To Reproduce

1. create a new `noir` / `nargo` project and create the files as mentioned above.
2. `nargo execute --force witness --expression-width 4`
3. `bb prove -b target/Test.json -w target/witness.gz -o proof`

### Workaround

None

### Project Impact

None

### Nargo Version

nargo version = 0.34.0 noirc version = 0.34.0+e3cdebe515e4dc4ee6e16e01bd8af25135939798 (git version hash: e3cdebe515e4dc4ee6e16e01bd8af25135939798, is dirty: false)

### Proving Backend Tooling & Version

0.55.0

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
Huh this is very odd, I can reproduce this and a more minimal reproduction is 

```noir
pub fn main(input : Field) -> pub Field {
    let b2 : [u8; 32] = input.to_be_bytes();
    let b2_f = std::field::bytes32_to_field(b2); 
    assert(0 != b2_f, "example assertion");
    0
}
```

Could you open an issue on https://github.com/AztecProtocol/aztec-packages?  `bb` isn't developed in this repository so it would be easier to get help on this over there.

**Comment by MarkCampbell90** [comment]
Thank you for looking into this!
The new issue can be found [here](https://github.com/AztecProtocol/aztec-packages/issues/8745)

**Comment by TomAFrench** [comment]
Thanks for reporting this! I'm going to close this issue in favour of the one linked.
