### ISSUE TITLE
CLI nargo prove fails on Apple Silicon

### ISSUE THREAD

**Issue by harshadptl** [noir-lang/noir#615]
# Description
Tried to generate proof of the Hello World circuit described 
## Aim
I am trying to build a proof with the nargo CLI

## Expected behavior

`nargo prove` should generate a proof

## Bug

It throws a panic in CRS

# To reproduce

(Describe the steps to reproduce the behavior.)

1. Install CLI from binaries on Apple Silicon https://noir-lang.github.io/book/getting_started/nargo/installation.html#option-1-binaries
2. Follow steps to generate a project and a proof https://noir-lang.github.io/book/getting_started/hello_world.html
3. It throws an error at proof generation step
4.

# Environment

- OS: mac OS Monterey Version 12.6

For `nargo` users

- _noir-lang/noir_ commit cloned:
- Proving backend
  - [ ] default
    - Clang: (run `clang --version`)
  - [ ] wasm-base

For TypeScript users

- Node.js: (run `node --version`)
- @noir-lang/noir_wasm: (from `yarn.lock`)
- @noir-lang/barretenberg: (from `yarn.lock`)
- @noir-lang/aztec_backend: (from `yarn.lock`)

# Additional context

(If applicable.)

**Comment by vezenovm** [comment]
Could you post the error that is outputted? The CRS may not have been fully downloaded causing an error. You could try deleting your `noir_cache` and running it again. The `noir_cache` is under your machine's $HOME dir

**Comment by jrocco2** [comment]
I'm getting the same issue
`
$ nargo prove p

Downloading the Ignite SRS (340MB)

[00:04:56] ######################################## 322560348/322560348 
Downloaded the SRS successfully!
Time Elapsed: 4 minutes

SRS is located at : "/Users/username/noir_cache/ignition/transcript00.dat"

Downloading the Ignite SRS (340MB)

[00:04:56] ######################################## 322560348/322560348 
Downloaded the SRS successfully!
Time Elapsed: 4 minutes

SRS is located at : "/Users/username/noir_cache/ignition/transcript00.dat"
The application panicked (crashed).
Message:  range end index 322560156 out of range for slice of length 74486912
Location: /Users/runner/.cargo/git/checkouts/aztec_backend-a697fb631cbad807/74b4d8d/common/src/crs.rs:37

This is a bug. Consider opening an issue at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.md`

**Comment by jfecher** [comment]
> Message:  range end index 322560156 out of range for slice of length 74486912

This usually means something went wrong while downloading the SRS - and it is a bit odd it took 4 minutes to download.

You can try to remove the `~/noir_cache` directory and `nargo prove` again afterward

**Comment by jrocco2** [comment]
@jfecher @vezenovm  I have tried removing the `~/noir_cache` and I can confirm that the error still persists on my mac M1.

**Comment by vezenovm** [comment]
> @jfecher @vezenovm I have tried removing the `~/noir_cache` and I can confirm that the error still persists on my mac M1.

Is your transcript00.dat file in the /home/aybehrouz/noir_cache/ignition/ folder of size ~300MB?

If not it's likely corrupted during the download process. See if downloading and replacing it using an alternative method (e.g. via browser, curl) gives you any luck?

The CRS is hosted here: http://aztec-ignition.s3.amazonaws.com/MAIN%20IGNITION/sealed/transcript00.dat

**Comment by jrocco2** [comment]
@vezenovm Amazing my transcript00.dat file was only 64MB so that worked like a charm thanks so much to yourself and @jfecher for the prompt replies

**Comment by ruizehung** [comment]
I have the same problem and downloading from http://aztec-ignition.s3.amazonaws.com/MAIN%20IGNITION/sealed/transcript00.dat works! Thank you so much!

**Comment by zf0x00** [comment]
also got the same problem delete the transcript00.dat file download from http://aztec-ignition.s3.amazonaws.com/MAIN%20IGNITION/sealed/transcript00.dat and put it in the noir_cache folder

**Comment by TomAFrench** [comment]
We [replaced the dependency](https://github.com/noir-lang/aztec_backend/pull/114) used to download the CRS a little while back as it was flakey on apple silicon for some reason (the underlying cause of this issue).

We haven't seen any new reports of this issue so I'm going to close it. Feel free to reopen if you experience this in future.
