### ISSUE TITLE
Compiler doesn't infer generics on `Field::from_be_bytes` correctly

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#6188]
https://github.com/noir-lang/noir/pull/6084 added the `Field::from_be_bytes` and `Field::from_le_bytes` functions. These are generic in their inputs however the compiler doesn't seem to be able to determine the value of `N` from the passed array.

This is likely due to the fact that it's an impl on a primitive type, so we should check for inconsistencies between how we handle these relative to struct impls.

**Comment by asterite** [comment]
I thought about working on this next but this program:

```noir
fn main() {
    let bytes = [1, 2, 3];
    let field = Field::from_be_bytes(bytes);
}
```

crashes with the same error a recent PR tried to fix:

```noir
The application panicked (crashed).
Message:  while substituting (unbound): expected kind of unbound TypeVariable (Numeric(u32)) to match the kind of its binding (Normal)
Location: compiler/noirc_frontend/src/hir_def/types.rs:2003
```

so there might be other cases where `Kind::Normal` is used instead of `Kind::Any` (I wonder if `Kind::Normal` is the same as `Kind::Any` and only Any should remain).
