### ISSUE TITLE
Issue compiling with aztec-nargo

### ISSUE THREAD

**Issue by brunolune** [noir-lang/noir#6196]
### Aim

new to Aztek ... Interested to use the sandbox 0.56.0. Launching the aztec and ethereum networks containers worked fine. Aztek-wallet worked fine but aztec-nargo doesn't. I also tried 0.55.1, same problem. 

### Expected Behavior

I tested with counter contract, or appbox contract, cannot compile with aztec-nargo

### Bug

(base) bruno@AORUS:~/Documents/ZKAndScaling/Aztec/my-aztec-box$ yarn dev
The application panicked (crashed).
Message:  could not create the `target` directory
Location: tooling/nargo_cli/src/cli/fs/mod.rs:13

This is a bug. We may have already fixed this in newer versions of Nargo so try searching for similar issues at https://github.com/noir-lang/noir/issues/.
If there isn't an open issue for this bug, consider opening one at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.yml

### To Reproduce

1.I followed normal steps given in the doc
2.
3.
4.

### Workaround

None

### Project Impact

Blocker

### Nargo Version

(base) bruno@AORUS:~/Documents/ZKAndScaling/Aztec/my-aztec-box$ aztec-nargo --version nargo version = 0.34.0 noirc version = 0.34.0+02fea6abe8637b9fb8f9535d1709b367d5e1da5c (git version hash: 02fea6abe8637b9fb8f9535d1709b367d5e1da5c, is dirty: false)

### NoirJS Version

0.34.0

### Proving Backend Tooling & Version

0.47.1

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
Hey, aztec-nargo and the boxes aren't developed by the Noir team so we can't really help on this. These are instead developed in https://github.com/AztecProtocol/aztec-packages.

cc @signorecello as he will know more on this.

**Comment by brunolune** [comment]
Thanks!

**Comment by TomAFrench** [comment]
Closing in favour of https://github.com/AztecProtocol/aztec-packages/issues/8937
