### ISSUE TITLE
Improve misleading error messages for struct typos

### ISSUE THREAD

**Issue by iAmMichaelConnor** [noir-lang/noir#6215]
### Problem

Not sure if it's possible to easily identify this, but occasionally I've mistyped instantiations of structs. Maybe a `=` instead of a `:`, or a missing `,`. The errors I get are misleading and don't help me find the typo.

Take this code:

```noir
struct Foo {
    a: Field,
    b: Field,
}

fn main() -> pub Field {
    let foo = Foo { a: 12, b: 32 }; // Here's the instantiation we care about.
    foo.a * foo.b
}

#[test]
fn test_main() {
    let x = main();
}
```

Suppose I put `=` instead of `:`:

```noir
struct Foo {
    a: Field,
    b: Field,
}

fn main() -> pub Field {
    let foo = Foo { a = 12, b: 32 }; // typo here
    foo.a * foo.b
}

#[test]
fn test_main() {
    let x = main();
}
```

I get errors: `Cannot find Foo in this scope` and `Expected a ; separating these two statements`.

Suppose I forget a `,`:

```noir
struct Foo {
    a: Field,
    b: Field,
}

fn main() -> pub Field {
    let foo = Foo { a: 12 b: 32 }; // Missing comma. It's harder to spot with big structs that span lines.
    foo.a * foo.b
}

#[test]
fn test_main() {
    let x = main();
}
```
I get errors: `Cannot find Foo in this scope` and `Expected a ; separating these two statements`, `Expected a binary operator but found :`.

### Happy Case

I have no idea how complicated it is to identify, so you might decide to simply close this issue. But it would be cool if it could infer: "Hey, you might be missing a comma, you plonker" or "Hey, use a colon instead of a `=` inside a struct, you plonker".

### Workaround

None

### Project Impact

None

### Would you like to submit a PR for this Issue?

None

**Comment by iAmMichaelConnor** [comment]
@asterite @jfecher thanks for resolving the first part of this issue.
It looks like this issue got auto-closed, but I suspect 2nd part of this issue (an accidentally-missing comma) is still unresolved. :)

**Comment by asterite** [comment]
It seems it's solved too, but let me know otherwise:

![Image](https://github.com/user-attachments/assets/2f6e33ab-f139-4c5d-ac59-c4434824222a)
