### ISSUE TITLE
Ability to multiply points not on a curve

### ISSUE THREAD

**Issue by jewelofchaos9** [noir-lang/noir#6217]
## Problem

Ability to multiply points not on a curve can cause invalid curve attack. Works for tecurve, swcurve and montcurve. 

## Expected Behavior
Exception when multiplying or adding points not from curve.

## Bug
```noir
use dep::std;
use std::ec::tecurve::affine::{Curve, Point};


fn main(
) {
}


#[test]
fn test_main() {
    let gen = Point::new(995203441582195749578291179787384436505546430278305826713579947235728471134,5472060717959818805561601436314318772137091100104008585924551046643952123905);
    let bjj = Curve::new(168700, 168696, gen);
    let priv_key = 13378;
    let base_pt = Point::new(2, 2);

    assert(bjj.contains(gen));
    assert(!bjj.contains(base_pt));
    let res = bjj.mul(priv_key,base_pt);
    assert(!bjj.contains(res));
}
```

`base_pt` is not on curve, but we still can multiply it.

## To Reproduce
1. Create Noir project for program written in bug section.
2. Run `nargo test`

## Possible fix
`assert(curve.contains(point))` for every operation with points

## Environment
```
nargo version = 0.35.0 
noirc version = 0.35.0+2a0d211b92d002fa75855d4ba27267f8892dd52c (git version hash: 2a0d211b92d002fa75855d4ba27267f8892dd52c, is dirty: false)
```

**Comment by TomAFrench** [comment]
I discussed this issue with Kev a while back and came to the conclusion that we should not enforce this on every EC operation as this would be overly expensive in terms of constraints. Instead any user input should be asserted to be on the curve and then we can do unsafe operations

In any case, I'm going to mark this as `wontfix` as this portion of the stdlib is deprecated in favour of https://github.com/noir-lang/noir-edwards and https://github.com/noir-lang/noir_bigcurve.
