### ISSUE TITLE
Copy how to install and use `bbup` into Noir Docs

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#6223]
### Problem

The current "Install Proving Backend" page describes how proving backends work with Noir programs from a high level, then merely links out to Barretenberg's README as an example and leaves developers on their own to figure out how to install a proving backend.

This means developers not only have to read through instructions in the Noir Docs, but also have to hop out and read Barretenberg's documentations just to create their first Noir project.

### Happy Case

1. Copy instructions of [how to install and use `bbup` in Barretenberg's README](https://github.com/AztecProtocol/aztec-packages/blob/86afa81d744bcf0c3ffd732663a24234b26e8aa8/barretenberg/cpp/src/barretenberg/bb/readme.md#installation) into the "Install Proving Backend" page (or the "Getting Started" page if https://github.com/noir-lang/noir/issues/6222 is completed) of the Noir Docs
2. Add a note highlighting that this is only for reference, refer to Barretenberg's documentations for the latest instructions and details

#### Alternative solution

We can create and establish an external-facing documentation site for Barretenberg, and link to that from the Noir Docs.

This would be nicer to search, read, consume, etc. than the current README, but it wouldn't resolve the friction of needing to hop out and back into the Noir Docs during onboarding.

### Workaround

None

### Additional Context

This comes at the cost of needing to manually check and update this section before each Noir release.

This Issue is broken out from https://github.com/noir-lang/noir/pull/6175 and related discussions.

### Project Impact

Nice-to-have

**Comment by TomAFrench** [comment]
I don't see how this is necessary tbh as we show examples of usage of `bb` in the noir docs already when relevant.

> This comes at the cost of needing to manually check and update this section before each Noir release.

I guarantee that this won't end up happening and this will quickly fall out of date tbh.

**Comment by Savio-Sou** [comment]
cc @noir-lang/developerrelations would love to hear your thoughts and/or suggestions
