### ISSUE TITLE
`nargo execute` generates a witness at `./target/witness.gz` by default

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#6240]
### Problem

Running `nargo execute` currently executes the Noir program without generating a witness file.

Devs have to manually specify a witness path and file name if they want to generate a witness, which adds development friction.

### Happy Case

Running `nargo execute` generates a witness at `./target/witness.gz` by default.

### Project Impact

Nice-to-have

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
Nargo already outputs a default witness file so I'm going to close this issue.
