### ISSUE TITLE
Warn on items more private than others

### ISSUE THREAD

**Issue by asterite** [noir-lang/noir#6248]
### Problem

For example in this Rust code:

```rust
struct Foo {}

pub fn bar() -> Foo {
    Foo {}
}
```

Rust says that `Foo` is more private than `bar`.

We should do the same in Noir and also in similar cases (for example when defining a struct with fields that are more visible than the struct).

### Happy Case

Noir warns/errors in the above snippet and similar ones.

### Workaround

None

### Project Impact

None

### Would you like to submit a PR for this Issue?

None

**Comment by asterite** [comment]
No, I didn't start yet, so feel free to assign it to Akosh :-)

**Comment by aakoshh** [comment]
Tests can go into compiler/noirc_frontend/src/tests/visibility.rs
