### ISSUE TITLE
Exported structs and globals are marked as unused

### ISSUE THREAD

**Issue by Thunkar** [noir-lang/noir#6250]
### Aim

```noir
#[abi(notes)]
global note_export: (Field, Field) = (123, 124);

#[abi(functions)] 
struct MyFnAbi {
    parameters: MyFnParameters,
    return_value: Field,
}
```

This code generates warnings for unused structs and globals

### Expected Behavior

Being able to generate the exports without warnings being emitted

### Bug

Warnings are generated

### To Reproduce

Use the example above

### Workaround

None

### Project Impact

None

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
@asterite Are we marking structs as unused before macros run?

**Comment by TomAFrench** [comment]
Ah, nvm. This is a different kind of exported.

**Comment by asterite** [comment]
So is the rule that if there's #[abi(...)]` on top of a struct then it shouldn't warn if it's unused?

**Comment by TomAFrench** [comment]
Yeah, this annotation marks that we should create a template for that struct type in the ABI. Similarly for globals, it puts the value of those in the ABI.

**Comment by Thunkar** [comment]
> So is the rule that if there's #[abi(...)]` on top of a struct then it shouldn't warn if it's unused?

I think it should be, kinda the same as if you did `pub use` on it?

**Comment by asterite** [comment]
In the example above, I guess `MyFnParameters` would also be considered used because it's inside a struct that's marked with `#[abi]`?

**Comment by TomAFrench** [comment]
Yeah, we should mark anything reachable from these structs as used.
