### ISSUE TITLE
Return an error when trying to compare arrays of two different sizes in SSA

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#627]
# Problem

[This line](https://github.com/noir-lang/noir/blob/master/crates/noirc_evaluator/src/ssa/acir_gen.rs#L416) will return true in SSA when we try to compare two arrays which have two different lengths.

# Solution

Given that the array sizes are known at compile time, we should not allow this. It should be caught on the frontend and be a compiler error in the SSA.

# Alternatives considered

(Describe any alternative solutions you have considered.)

# Additional context

(If applicable.)

**Comment by guipublic** [comment]
I don't understand why saying arrays of different sizes are different is a bug.

**Comment by kevaundray** [comment]
Generally we compare types which are the same, and two arrays which have different sizes are different types

**Comment by jfecher** [comment]
Arrays of different sizes being compared was a type system bug that is fixed as part of the numeric generics PR since it was also impacting that PR's features: https://github.com/noir-lang/noir/pull/620/files#diff-de963a8d675cb22753e6a2ae32b7e56c1755f581da58828165136d8b699c1560L704 .

I can split it out into a separate PR if we want that fix merged early.

**Comment by kevaundray** [comment]
> Arrays of different sizes being compared was a type system bug that is fixed as part of the numeric generics PR since it was also impacting that PR's features: https://github.com/noir-lang/noir/pull/620/files#diff-de963a8d675cb22753e6a2ae32b7e56c1755f581da58828165136d8b699c1560L704 . After that diff, the type system will correctly issue an error when arrays of different lengths are compared.
> 
> I can split it out into a separate PR if we want that fix merged early.

If it's not a hassle, then that would be easier to review. We would also want to modify that line in SSA to make it an ice(internal compiler error) if we do get arrays of different sizes due to something going wrong in the frontend

**Comment by kevaundray** [comment]
@jfecher Can you confirm that this now gets caught on the frontend, I'm adding an internal compiler error into SSA for this.

**Comment by jfecher** [comment]
```rs
fn main() {
    let arr1 = [1, 2, 3];
    let arr2 = [1, 2];
    constrain arr1 == arr2;
}
```
Output:
```
error: Can only compare arrays of the same length. Here LHS is of length 3, and RHS is 2
   ┌─ /.../src/main.nr:4:20
   │
11 │     constrain arr1 == arr2;
   │                    --
```

**Comment by kevaundray** [comment]
Closing since this is now caught on the frontend
