### ISSUE TITLE
Setup `bash`/`zsh` command-line completion for `nargo`

### ISSUE THREAD

**Issue by michaeljklein** [noir-lang/noir#6284]
### Problem

Tab-completion in [bash](https://www.gnu.org/software/gnuastro/manual/html_node/Bash-TAB-completion-tutorial.html) and zsh for `nargo` would be helpful so that typing partial commands like `nargo co<TAB>` or `nargo n<TAB>`, the commands are completed to `nargo compile`, `nargo new`, respectively.

### Happy Case

Setup tab completion for the commonly used shells `bash` and `zsh`

### Workaround

Yes

### Workaround Description

1. Use "short" versions of commands where available (e.g. `check`, `execute`) or else enable them for other commands
2. Type the whole command

### Project Impact

Nice-to-have

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
Kev mentioned there are some addons we can use for clap to improve the CLI experience: https://github.com/noir-lang/noir/issues/3159

Specific to this issue there is [clap_complete](https://github.com/clap-rs/clap/blob/master/clap_complete/README.md).
