### ISSUE TITLE
Use workspace inheritance for common items across crates

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#629]
# Problem

Some dependencies are copied across different crates.

# Solution

Declare dependencies at the workspace root and inherit them from the root  

# Alternatives considered

(Describe any alternative solutions you have considered.)

# Additional context

See [here](https://betterprogramming.pub/workspace-inheritance-in-rust-65d0bb8f9424) or rust docs for more information

**Comment by phated** [comment]
Completed by #632
