### ISSUE TITLE
Unused `self` in trait impl generates warning

### ISSUE THREAD

**Issue by aakoshh** [noir-lang/noir#6297]
### Aim

On my machine `tests::execution_success::test_trait_impl_base_type` failed with the following error:

```
command=`"/Users/aakoshh/Work/aztec/noir/target/debug/nargo" "--program-dir" "/Users/aakoshh/Work/aztec/noir/test_programs/execution_success/trait_impl_base_type" "execute" "--force"`
code=1
stdout=""
stderr=```
warning: unused variable self
   ┌─ /Users/aakoshh/Work/aztec/noir/test_programs/execution_success/trait_impl_base_type/src/main.nr:38:17
   │
38 │     fn to_field(self) -> Field {
   │                 ---- unused variable 
```

### Expected Behavior

The test should compile without warning.

### Bug

The method is an implementation of `Fieldable::to_field`. We can't use `_self` to silence this, and Rust does not warn about it.

### To Reproduce

```
cargo test -p nargo_cli test_trait_impl_base_type
```

### Workaround

Yes

### Workaround Description

Add `let _ = self;` to the method body.

### Project Impact

None

### Would you like to submit a PR for this Issue?

Yes

**Comment by jfecher** [comment]
> The method is an implementation of Fieldable::to_field. We can't use _self to silence this, and Rust does not warn about it.

Why can't we use `_self: Self`?

**Comment by aakoshh** [comment]
You're right, if we specify the type as `: Self` we can use `_self`, I haven't tried that.

I meant that if I just try to use `_self` , the compiler says: 
```
`Fieldable::to_field` expects 1 parameter, but this method has 0`.
```

NB the Rust compiler doesn't seem to like `_self: Self`: 
```
method `to_field` has a `self` declaration in the trait, but not in the impl
expected `self` in impl`
```

**Comment by jfecher** [comment]
> NB the Rust compiler doesn't seem to like _self: Self:

Yep, this is a difference between Rust and Noir. Noir is a bit more permissive with methods, you don't need a `self` parameter to call something as a method. Just an impl and the first type must match.
