### ISSUE TITLE
Compiling a function returning an unknown numeric generic panics

### ISSUE THREAD

**Issue by michaeljklein** [noir-lang/noir#6379]
### Aim

Attempted to compile the following program with a function that outputs a numeric generic:

```noir
// Using "[(); N]" as a parameter compiles and executes successfully
//
// Using "struct W<N> {}" as a parameter also panics if "foo" is called on "W {}",
// but not if "foo" is called on "let w_1: W<1> = W {};"
fn foo<let N: u32>() -> u32 {
    N
}

fn main() {
    foo();
}
```

### Expected Behavior

The program to compile successfully or fail with a user error

### Bug

Compiling the program panics with the following message:

```bash
The application panicked (crashed).
Message:  Non-numeric type variable used in expression expecting a value
Location: compiler/noirc_frontend/src/monomorphization/mod.rs:934
```

### To Reproduce

1.
2.
3.
4.

### Workaround

Yes

### Workaround Description

Use turbofish (e.g. `foo::<3>()`) to specify numeric generics when they can't be derived from a parameter's type

### Project Impact

None

### Nargo Version

nargo version = 0.36.0 noirc version = 0.36.0+2f376100d3ee7ab519d6ea30153395bb3e7af7b1 (git version hash: 2f376100d3ee7ab519d6ea30153395bb3e7af7b1, is dirty: false)

### Would you like to submit a PR for this Issue?

None

**Comment by michaeljklein** [comment]
Could be related to https://github.com/noir-lang/noir/issues/6126

**Comment by jfecher** [comment]
Hmm I had thought we had a check for this case already but it looks like what was added was a slightly different check: https://github.com/noir-lang/noir/pull/5840. I would've still expected `main` to error that the generic in the call to `foo` wasn't known however.
