### ISSUE TITLE
Run entire test suite with multiple values for `inliner_aggressiveness`

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#6390]
We recently updated the test suite to run the stdlib tests with a range of potential inliner aggressiveness settings. In https://github.com/noir-lang/noir/pull/6378 I've updated the default aggressiveness to 0 however this has resulted in a number of compilation failures.

We should update the test suite so that we run it with a range of inliner aggressiveness settings to match how we do it in the stdlib.

**Comment by aakoshh** [comment]
You mean literally the entire test suite, with a [Github Workflow matrix strategy](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow#using-a-matrix-strategy)?
Or should we somehow identify tests that run the nargo cli? 

I suppose it would help to add support for that value to [come from an env](https://docs.rs/clap/latest/clap/struct.Arg.html#method.env) var.

**Comment by aakoshh** [comment]
I'll look at the test failures, I see there are some tests which might work similarly to how the stdlib is decorated.

**Comment by TomAFrench** [comment]
By "entire test suite" I meant everything in `test_programs`. We codegen the tests in [this file](https://github.com/noir-lang/noir/blob/master/tooling/nargo_cli/build.rs) which we can modify to pass different values for the `inliner_aggressiveness` CLI option.

**Comment by aakoshh** [comment]
I thought I saw some other kinds of test failures, can't find them now 🙈
