### ISSUE TITLE
Don't fmt `unsafe` blocks to span multiple lines.

### ISSUE THREAD

**Issue by iAmMichaelConnor** [noir-lang/noir#6459]
### Problem

A subjective one for you.

Say you have this code:

`let a = my_unconstrained_fn();`

And then the compiler warns you to wrap it in an unsafe block:

`let a = unsafe {  my_unconstrained_fn() };`

This is nice and still on one line.

But then the formatter spills it over 3 lines, and I can understand why, but I feel like it hurts readability when these `unsafe` blocks span lines when they don't need to.

```
let a = unsafe {
    my_unconstrained_fn()
};
```

**Comment by TomAFrench** [comment]
As I've seen a lot of one line unsafe blocks. Feel free to reopen if you can provide a test case for the formatter which displays this behavior
