### ISSUE TITLE
Arithmetic generics cannot simplify `[Field; (N-1) + 1]` to `[Field; N]`

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#6495]
On the [latest sync](https://github.com/AztecProtocol/aztec-packages/pull/9769) we've started getting errors of the form

```
  ./noir-projects+build-mock-protocol-circuits *failed* | error: expected type [Field; N], found type [Field; ((N - 1) + 1)]
  ./noir-projects+build-mock-protocol-circuits *failed* |    ┌─ /usr/src/noir-projects/noir-protocol-circuits/crates/types/src/abis/side_effect.nr:78:27
  ./noir-projects+build-mock-protocol-circuits *failed* |    │
  ./noir-projects+build-mock-protocol-circuits *failed* | 78 │     fn serialize(self) -> [Field; N] {
  ./noir-projects+build-mock-protocol-circuits *failed* |    │                           ---------- expected [Field; N] because of return type
  ./noir-projects+build-mock-protocol-circuits *failed* | 79 │         array_concat(self.inner.serialize(), [self.counter as Field])
  ./noir-projects+build-mock-protocol-circuits *failed* |    │         ------------------------------------------------------------- [Field; ((N - 1) + 1)] returned here
  ./noir-projects+build-mock-protocol-circuits *failed* |    │
```

In https://github.com/noir-lang/noir/pull/6494 I've added a unit test showing how we fail to canonicalize the length of these arrays.

We should update the canonicalization logic such that the `solves_n_plus_one_minus_one_array_length` test passes.

**Comment by TomAFrench** [comment]
@michaeljklein potentially related to your recent changes?

**Comment by jfecher** [comment]
Hmm, it's possible the new CheckedCast variant is messing with recursive matches when we try to check for  `Infix(Infix(N, -, 1), +, 1)` since it now could be `Infix(CheckedCast(Infix(N, -, 1)), +, 1)` or another variant with CheckedCast wrapping the constants as well.
