### ISSUE TITLE
Circuit output is not printed after successful execution

### ISSUE THREAD

**Issue by LukiMueller** [noir-lang/noir#6516]
### Aim

I want to check the result of my program executions but for some special cases the results are not shown although the witness is generated.
Here are some examples when this is the case.

**Examples NOT showing the** `Circuit output:`

~~~rust
pub fn main(in0 : Field) -> pub (Field, Field) {
    let out0 = (in0 * in0);
    let out1 = (in0 * in0);
    (out0, out1)
}

// OR

pub fn main(in0 : Field) -> pub (Field, Field) {
    let out0 = (in0 * in0);
    let out1 = out0;
    (out0, out1)
}
~~~

**Example showing the** `Circuit output:`

~~~rust
pub fn main(in0 : Field) -> pub (Field, Field) {
    let out0 = (in0 * in0);
    let out1 =  (in0 + in0);
    (out0, out1)
}

// OR

pub fn main(in0 : Field) -> pub (Field, Field) {
    let out0 = (in0 * in0);
    let out1 = 0;
    (out0, out1)
}
~~~

In all cases I get `Circuit witness successfully solved`. Older versions seem to give me the expected `Circuit output:` for all of the provided test cases.
Was there a change that removed this for some special cases, do I have to provide a flag now, or is this a bug?

### Expected Behavior

I expected to receive the circuit output `Circuit output: ...`  after the message `Circuit witness successfully solved`

### Bug

For some programs I do no longer receive a `Circuit output: ...`  although `nargo execute` prints  `Circuit witness successfully solved`.

### To Reproduce

1. Create a new `nargo` project
2. Create a file `main.nr` with the content from above and a `Prover.toml` (with e.g. in0="1") 
3. `nargo execute`
3.
4.

### Workaround

None

### Project Impact

None

### Nargo Version

nargo version = 0.38.0 noirc version = 0.38.0+35408ab303f1018c1e2c38e6ea55430a2c89dc4c (git version hash: 35408ab303f1018c1e2c38e6ea55430a2c89dc4c, is dirty: false)

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
Hmm, this is odd. I've confirmed that this exists in master.

I think that this is likely caused by the `MergeExpressionOptimizer` doing something it shouldn't as the issue pops up when a single witness is returned twice.
