### ISSUE TITLE
Deduplicate intrinsics with side effects when they're under the same predicate

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#6533]
We currently do not deduplicate any intrinics which have side effects. This results in us not deduplicating instrinsics which we should be able to (example given in #6527 where we do not deduplicate `Intrinsic::ToRadix` calls of the same variable in the same block).

We essentially need to make deduplication of these instructions aware of `deduplicate_with_predicate` similarly to how we do for other instructions.

**Comment by jfecher** [comment]
We can add the `&& deduplicate_with_predicate` clause but we also need to actually match on them more closely in that case since we still wouldn't want to deduplicate e.g. `println(1)`

**Comment by TomAFrench** [comment]
I don't think we have any intrinsics which result in foreign calls afaik but agreed in general that we should be careful when deduplicating these.
