### ISSUE TITLE
test disallowed on impl methods seems to throw on structs

### ISSUE THREAD

**Issue by signorecello** [noir-lang/noir#6535]
### Aim

Trying to use the [bignum library](https://github.com/noir-lang/noir-bignum/blob/d81d5fac5e2ea919bd93e513644d0edc5630261c/src/tests/runtime_bignum_test.nr#L515)

### Expected Behavior

I expect tests to not be executed or at least not throw errors

### Bug

I get an error:

```noir
error: The `#[test]` attribute is disallowed on `impl` methods
```

### To Reproduce

1. Start a new project
2. Import the bignum library
3. Compile

### Workaround

Yes

### Workaround Description

Manually removing the make_tests macros makes it stop

### Project Impact

None

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
This is expected behaviour and the library has been updated to not use these anymore.
