### ISSUE TITLE
Input to brillig function is in a separate subgraph to output

### ISSUE THREAD

**Issue by signorecello** [noir-lang/noir#6536]
### Aim

Trying to use the [plume](https://github.com/distributed-lab/noir-plume) library

### Expected Behavior

I expect it to work normally

### Bug

I get an error:

```noir
bug: Input to brillig function is in a separate subgraph to output
    ┌─ /Users/zpedro/nargo/github.com/noir-lang/noir-bignumv0.4.1/src/fns/constrained_ops.nr:302:43
    │
302 │     let (result, borrow_flags) = unsafe { __neg_with_flags(params, val) };
    │                                           ----------------------------- There is no path from the output of this brillig call to either return values or inputs of the circuit, which creates an independent subgraph. This is quite likely a soundness vulnerability
```

### To Reproduce

1. Start a new project
2. Import and use the PLUME library
3. Compile without the --silence-warnings flag

### Workaround

Yes

### Workaround Description

Using --silence-warnings makes it go away

### Project Impact

None

### Would you like to submit a PR for this Issue?

None

**Comment by signorecello** [comment]
Can we check if it's a duplicate before closing this? Should I reopen it in the bignum library? I'd be wary of closing an issue if it's unclear whether this will persist after fixing #5518

**Comment by TomAFrench** [comment]
This is #5518.
