### ISSUE TITLE
Discrepancy Between Verification Keys Generated Using @aztec/bb.js and BB CLI Tool

### ISSUE THREAD

**Issue by beastmode2306** [noir-lang/noir#6567]
### Aim

Tried to get circuit verification key to use in app.

### Expected Behavior

@aztec/bb.js js package to return same verification key as returned from bb cli binary.

### Bug

```
const generator = new UltraPlonkBackend(depositCompiledCircuit.bytecode);
const vkUintArray = await generator.getVerificationKey();
const nodeJsVk = Buffer.from(vkUintArray).toString("hex");
```

 does not return the same result as 

```
bb write_vk -b ./target/deposit.json -o ./target/vk ->
const importedFromFileVk = fs
  .readFileSync("circuits/deposit/target/vk")
  .toString("hex");
```

The ending of the VK is the only difference between them.

Actual returned VK in the first case: 000000020001000000000005000000170000000449445f311826deef630ad0d8463944bdb7b0839e5e5759505673749d4e762279f880785304351145b80164d641681d9c366fe85ff6363b64a1ca9deb127afb838cd080970000000449445f3212a105423d73c7150f31c4ee86e73a6bfcca701446ccdaabdafb759838cb300d24418c567ab4fe47a13ee4bc003176cd5782382c9dff47e6f0b5c60c3562d1de0000000449445f3300fa51ad1641003dd30ca5ecee0de9ec8a1976dbaf2a9c36c9c66c1877fc110f1c77fdea20ec1bd9d0572a3a19e6d6c1efead36714b6740d3ba41bd58defebdd0000000449445f341aa1aa9f5446daced93f03e51a85fda159cd304d06dc77b11fff1908b59dbb530bea2aa352ed1cf68b138a252dca63499a693fd2e7ed654e9950aac9b397530800000003515f3120a117b7c279d81efd881c757802e9a8e90e6e6f7b38a1e5a20917754ffddf25028b02b9c481c71e73399186751daf706264f7095c81e5287f83035d7a93268200000003515f322de02d202e58bcf7705600a87b4096af3e84d3eb9fb385a2e674ee0b3f86f76a2a709747a12189082a5466a25756c0820560b58c3137d7e245c2189c2a3bbb9500000003515f332b1888181447b4a0896441661588284a0dc9151e337a6c053a648a9656788f241332252a7568bac4d4e2afc29640bf478792ed5b92f69a5b7532fbad1559063b00000003515f34143f9d48cfed2940d9b51665504e2fd25d5716ce89b74f64fd0e7d7b9f9e146311f5356ee60f8b70489410cb9b2b0b36cfe2ba932a81840cd7e183f4fc87a90c0000000c515f41524954484d4554494318b223529fd52c6595e34dba272cecb283afa2085830affaec68abd6c6b57643113eef12020512845ba285c9d3367e35d02d21cf321fba4a2e1be3d892b168dd00000005515f415558115de6b2de5250feddeb29f7d9571ea43631dd0fe18e33930ab5adff69ef35a81dc944cfbf06e0d9626ebd636118f55a9e68d2cabe3b5f4d120c9cd9170285f800000003515f431412efddcf0f27870f7e67914ede0c948160e648a1c48afa084cfd1a97ae4252123cb113631b07f09daf8a6a1251741755b52cb762c3014529c16b406a51b8f60000000a515f454c4c49505449431568fe007d810c1201e3556ec81f437536b646a471d87a989c754fff07b88f69011bb497d54eee968569df7efb24db7879dcdc1b4258662126d398d0b37914b200000003515f4d00f8c18652c8122c4a16c1c3c13a1b5b52cad6b5b3b1270f2dc9f67f1dd60fe82dca95cba85a9046acce574a0f7255d2cb0a481c16c526a63f69b4d9b74fd0fe00000006515f534f52540b0407c4c65240777873fbab391bffc17a751ed9cafedb7bce527ddd56dc882216b93cae1c0ba469e457df5a0baa50b8259e502121434b77f90afc853152004c000000075349474d415f3109a762e38e0884583419721fac7ee2361e1407035c8b7d7a4a673e28c13b4c39051b6633a04f172975ea61f73aa99fde84f97f8831abd29b29505eb8b151f736000000075349474d415f320bc026328b1a953ff1acc938d1fd189cbabeb4b17834bc6f3c728bf891d08bbe187090ee18a98536bef25e7b10ba73d76d1bf553b512141130d725f85078376b000000075349474d415f331f80b4a5ec942364f262af4fa483b90b650a6bc6eedd133834286f4dcfc220481b4cfb751312b2fb30cccbecbc6e8d815a44c6f9a8e8c4295045d754254724b3000000075349474d415f342a362dc85e3e9a8c468d975dedbe9d08110b1dce7d5238f8cbffe997d59244ec221cf7709c8ea6c594f6f10fe4d52edd6c744de6fed9b746b8506bf7886c7b2f000000075441424c455f31138c2f5e3fd1228e915c151690b2eb796bc33156f2923d689525f0c497014bce0be85de8976f8fec0ad349778e206b8aaddf792b14a5dccd435e97bbc93bcace000000075441424c455f320ed87af976c50be820eb4f5ea0c527ce51e72f1a5dfb05356650ec788be9b3b108af0b20f80fe572de2f990dd6176b3ffed42494d8a331095eff8a2943c63bb3000000075441424c455f332832fbb1b93ead5801aa4b196942a14323ce60c38aa5ed53547574f09038d2f901403b05d9723bcfbf5bed8f44ac099f986d4417e0a3b1a0d8d76959ed976952000000075441424c455f3416cc5ccf3d71031db63b44d57bdc8f8b622d5ff4a41ab2a36f4c9e486b4e13281b812a62c41e800ff958c93d6f602840309b850409e207a5d34368ddc6eb8d650000000a5441424c455f5459504521ee0d7d3360a40a593025419674c29153bcbe1f3003fc02bd0d110d94510e720a6efb2bddbd2826e3f32159591b19e2ebabeeab1130bb6b751e34e327ce1b9e000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 

Actual returned VK in the second case: 000000020001000000000005000000170000000449445f311826deef630ad0d8463944bdb7b0839e5e5759505673749d4e762279f880785304351145b80164d641681d9c366fe85ff6363b64a1ca9deb127afb838cd080970000000449445f3212a105423d73c7150f31c4ee86e73a6bfcca701446ccdaabdafb759838cb300d24418c567ab4fe47a13ee4bc003176cd5782382c9dff47e6f0b5c60c3562d1de0000000449445f3300fa51ad1641003dd30ca5ecee0de9ec8a1976dbaf2a9c36c9c66c1877fc110f1c77fdea20ec1bd9d0572a3a19e6d6c1efead36714b6740d3ba41bd58defebdd0000000449445f341aa1aa9f5446daced93f03e51a85fda159cd304d06dc77b11fff1908b59dbb530bea2aa352ed1cf68b138a252dca63499a693fd2e7ed654e9950aac9b397530800000003515f3120a117b7c279d81efd881c757802e9a8e90e6e6f7b38a1e5a20917754ffddf25028b02b9c481c71e73399186751daf706264f7095c81e5287f83035d7a93268200000003515f322de02d202e58bcf7705600a87b4096af3e84d3eb9fb385a2e674ee0b3f86f76a2a709747a12189082a5466a25756c0820560b58c3137d7e245c2189c2a3bbb9500000003515f332b1888181447b4a0896441661588284a0dc9151e337a6c053a648a9656788f241332252a7568bac4d4e2afc29640bf478792ed5b92f69a5b7532fbad1559063b00000003515f34143f9d48cfed2940d9b51665504e2fd25d5716ce89b74f64fd0e7d7b9f9e146311f5356ee60f8b70489410cb9b2b0b36cfe2ba932a81840cd7e183f4fc87a90c0000000c515f41524954484d4554494318b223529fd52c6595e34dba272cecb283afa2085830affaec68abd6c6b57643113eef12020512845ba285c9d3367e35d02d21cf321fba4a2e1be3d892b168dd00000005515f415558115de6b2de5250feddeb29f7d9571ea43631dd0fe18e33930ab5adff69ef35a81dc944cfbf06e0d9626ebd636118f55a9e68d2cabe3b5f4d120c9cd9170285f800000003515f431412efddcf0f27870f7e67914ede0c948160e648a1c48afa084cfd1a97ae4252123cb113631b07f09daf8a6a1251741755b52cb762c3014529c16b406a51b8f60000000a515f454c4c49505449431568fe007d810c1201e3556ec81f437536b646a471d87a989c754fff07b88f69011bb497d54eee968569df7efb24db7879dcdc1b4258662126d398d0b37914b200000003515f4d00f8c18652c8122c4a16c1c3c13a1b5b52cad6b5b3b1270f2dc9f67f1dd60fe82dca95cba85a9046acce574a0f7255d2cb0a481c16c526a63f69b4d9b74fd0fe00000006515f534f52540b0407c4c65240777873fbab391bffc17a751ed9cafedb7bce527ddd56dc882216b93cae1c0ba469e457df5a0baa50b8259e502121434b77f90afc853152004c000000075349474d415f3109a762e38e0884583419721fac7ee2361e1407035c8b7d7a4a673e28c13b4c39051b6633a04f172975ea61f73aa99fde84f97f8831abd29b29505eb8b151f736000000075349474d415f320bc026328b1a953ff1acc938d1fd189cbabeb4b17834bc6f3c728bf891d08bbe187090ee18a98536bef25e7b10ba73d76d1bf553b512141130d725f85078376b000000075349474d415f331f80b4a5ec942364f262af4fa483b90b650a6bc6eedd133834286f4dcfc220481b4cfb751312b2fb30cccbecbc6e8d815a44c6f9a8e8c4295045d754254724b3000000075349474d415f342a362dc85e3e9a8c468d975dedbe9d08110b1dce7d5238f8cbffe997d59244ec221cf7709c8ea6c594f6f10fe4d52edd6c744de6fed9b746b8506bf7886c7b2f000000075441424c455f31138c2f5e3fd1228e915c151690b2eb796bc33156f2923d689525f0c497014bce0be85de8976f8fec0ad349778e206b8aaddf792b14a5dccd435e97bbc93bcace000000075441424c455f320ed87af976c50be820eb4f5ea0c527ce51e72f1a5dfb05356650ec788be9b3b108af0b20f80fe572de2f990dd6176b3ffed42494d8a331095eff8a2943c63bb3000000075441424c455f332832fbb1b93ead5801aa4b196942a14323ce60c38aa5ed53547574f09038d2f901403b05d9723bcfbf5bed8f44ac099f986d4417e0a3b1a0d8d76959ed976952000000075441424c455f3416cc5ccf3d71031db63b44d57bdc8f8b622d5ff4a41ab2a36f4c9e486b4e13281b812a62c41e800ff958c93d6f602840309b850409e207a5d34368ddc6eb8d650000000a5441424c455f5459504521ee0d7d3360a40a593025419674c29153bcbe1f3003fc02bd0d110d94510e720a6efb2bddbd2826e3f32159591b19e2ebabeeab1130bb6b751e34e327ce1b9e000579f3c00000002400384770006de190000000130000000000000000000000000000000000000000ffffffff000000000000000000000000000000000000000000

### To Reproduce

1.Clone https://github.com/beastmode2306/noir-deposit
2.Run npm run install
3.Run npm run start
4.Wait for logs to appear

### Workaround

Yes

### Workaround Description

Use verification key returned from bb cli binary

### Project Impact

Blocker

### Blocker Context

Verification key dapp consumer is reverting key returned from @aztec/bb.js library 

### Nargo Version

nargo version = 0.38.0 noirc version = 0.38.0+e784523a15c0c233a5a794f28498635b7ce86325 (git version hash: e784523a15c0c233a5a794f28498635b7ce86325, is dirty: false)

### NoirJS Version

0.38.0

### Proving Backend Tooling & Version

0.61.0

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
Hey can you open this issue on https://github.com/AztecProtocol/aztec-packages? We don't develop `bb.js` in this repository.

**Comment by TomAFrench** [comment]
Closing as we don't develop `bb` and `bb.js`.
