### ISSUE TITLE
Incorrect `%` (modulo) operator behavior for negative divisors

### ISSUE THREAD

**Issue by Aristotelis2002** [noir-lang/noir#6609]
### Aim

Attempted to create a simple program which does the modulo operation between a positive and a negative number.

The following main.nr:
```rust
fn main(x: i16, y: i16) {
    println(x % -13);
    println(x % y);
}
```
with Prover.toml:
```toml
x = "169"
y = "-13"
```
Outputs
```
169
169
```

This output is unexpected. It should be
```
0
0
```

Another example is the following main.nr:
```rust
fn main(x: i16, y: i16) {
    println(x % -107);
    println(x % y);
}
```
with Prover.toml:
```toml
x = "769"
y = "-107"
```
Outputs
```
769
769
```
In Rust the same program would have the output 20. In some other programming languages the output would be -20

### Expected Behavior

Consisted behavior of the modulo operator. Currently the modulo operation between negative constants fails to compile but it has undefined behavior for negative integer parameters.

### Bug

The modulo operator produces an incorrect value when working with negative values passed as parameters.

### To Reproduce

1. Create a Noir project with the provided code
2. `nargo check`
3. Insert the provided values into the `Prover.toml`
4. `nargo execute`

### Workaround

None

### Project Impact

None

### Nargo Version

nargo version = 0.39.0 noirc version = 0.39.0+45eb7568d56b2d254453b85f236d554232aa5df9 (git version hash: 45eb7568d56b2d254453b85f236d554232aa5df9, is dirty: false)

### Would you like to submit a PR for this Issue?

None

**Comment by Subway2023** [comment]
Is this really a bug? I get the same result in the circom compiler as well.
```circom
template Multiplier() {
    signal input x;
    signal input y;

    log("x%-13: ",x%-13);
    log("x % y: ",x % y);
}

component main = Multiplier();
```
```
x%-13:  169
x % y:  169
```
