### ISSUE TITLE
Hash to field panics in ssa module

### ISSUE THREAD

**Issue by LHerskind** [noir-lang/noir#662]
# Description

## Aim

Produce proof for a noir program using the `hash_to_field` function from the standard library:
```rust
use dep::std;
fn main(secret: [Field; 12]) -> pub Field {
    std::hash::hash_to_field(secret)
}
```

## Expected behavior

Produce proof

## Bug

```bash
➜  nargo prove p
thread 'main' panicked at 'not yet implemented: max value must be implemented for opcode hash_to_field ', crates/noirc_evaluator/src/ssa/integer.rs:494:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by vezenovm** [comment]
This is fixed on Noir source. I believe we just need to update our binaries to not have users run into this error any longer. @phated @kobyhallx

**Comment by LHerskind** [comment]
After updating binaries:

Running `nargo check` create `PROVER.toml` and `VERIFIER.toml` so it is not just a check. 

When running `nargo prove p` it will not execute, but the return is not updated, will just leave empty when `return = ""` set before, this worked before. Might just be that it is never updated in the toml.

Generated proofs are invalid. Generating proof with `0x01` and `0x02` as the field elements going into secret (updated to be length 2 insetead of 12),
