### ISSUE TITLE
The `compile_file` function of Driver should not panic if file extension is not `.nr`

### ISSUE THREAD

**Issue by phated** [noir-lang/noir#663]
# Description

Currently, calling `noirc_driver::Driver::compile_file` with a `root_file` that doesn't have `.nr` as the extension panics due to unwrapping an option from the call to `FileManager::add_file`. The extension to the file shouldn't be a hard requirement to be `.nr` (I naively tried naming my file `.noir` and was freaking out about the crash).

## Aim

`compile_file` should allow any file extension. We can still use `.nr` throughout the codebase when we need to generate file extensions.

## Expected behavior

`compile_file` should not panic if a file doesn't use the `.nr` extension.

## Bug

`compile_file` panics if a file doesn't use the `.nr` extension.

# To reproduce

1. Create a noir file named `hello.noir`
2. Try to call `compile_file` on it (easiest to do through the noir_wasm package)
3. See the crash

# Environment

- OS: MacOS

For TypeScript users

- Node.js: (run `node --version`) 18.13.0
- @noir-lang/noir_wasm: (from `yarn.lock`) latest
- @noir-lang/barretenberg: (from `yarn.lock`) latest
- @noir-lang/aztec_backend: (from `yarn.lock`) latest

# Additional context

**Comment by kevaundray** [comment]
Can you clarify whether you are suggesting that:

- it should not panic, but disallow .nr

- it should not panic and allow files with any extension

**Comment by phated** [comment]
I think it should allow any file extension. Is there a reason the file extension is hardcoded? Note that this is only when `compile_file` is called because it doesn't build a workspace like nargo does.

**Comment by kevaundray** [comment]
The file extension was hardcoded because I wanted the compiler to only recognise .nr files and it became a standard that Noir files have .nr as their file extension.

What was the reason to wanting to use .noir as an extension and is this conventional for the compiler to ignore the file extension? 

I'm on mobile, so can't check; one way to check is by using rustc on a file which doesn't have the .rs extension and seeing what it says -- cargo will probably prompt you to add the .rs extension

**Comment by phated** [comment]
> What was the reason to wanting to use .noir as an extension and is this conventional for the compiler to ignore the file extension?

The primary reason is that I didn't take the time to figure out what the common extension was supposed to be and just slapped a `.noir` file onto my filesystem and `noir_wasm` panicked without a good error message explaining the problem. I'm fairly certain that I'm not unique in my non-research here, which is the reason I don't think we should disallow other file extensions.

I view this `compile_file` call to be similar to `rustc`, which I just tested with a `.rust` filename and it works. e.g. `rustc barretenberg_wrapper/build.rust` attempted to compile the file. However, `nargo` is similar to `cargo` which can enforce the `.nr` convention. Nargo currently does this through the `resolve_path` function with looks up modules via appending `.nr` to the module name.

**Comment by kevaundray** [comment]
Thanks for checking this for me. I think it's fine to remove it then
