### ISSUE TITLE
Ability for a Noir program to choose to use it's nearest Nargo.toml file

### ISSUE THREAD

**Issue by jzaki** [noir-lang/noir#6671]
### Problem

A lib has a Nargo.toml file in the root, any supplementary circuits in sub-directories (eg benchmarking and examples beyond atomic tests) also have their Nargo.toml file.

For these subdirectories to be compiled, the lib would have to be aware of the contents of the subdirectories.
Ideally they would be associated with the lib and be updated if the lib changes, but sufficiently decoupled so that the lib needn't be aware of ancillary sub-directories.

### Happy Case

The ability to indicate to `nargo` to not search for a Nargo.toml file beyond the one in the current directory, or specify where to find the nargo file.

`nargo compile --nargo-path .`

### Workaround

Yes

### Workaround Description

Keep examples/benchmarking manually in sync with lib whether in lib repo or separate.

### Additional Context

Cargo searches up parent paths until the first Cargo.toml file it finds, Nargo ascends to the top-most Nargo.toml file

### Project Impact

None

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
We wanting to change this so that we don't keep traversing up to the highest nargo.toml file but this isn't considered a high priority ATM.

See https://github.com/noir-lang/noir/issues/2606

**Comment by TomAFrench** [comment]
You mention this is going to be used for example and benchmarking. I don't think it's good practice for examples to be created a separate binaries, these should be created as tests.

We also have a workflow for benchmarking that allows the benchmarks functions to be placed within the library. https://github.com/noir-lang/noir-library-starter/pull/7
