### ISSUE TITLE
Hide Nightly releases from the GitHub Releases page

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#6702]
### Problem

Noir's GitHub Releases page is current populated by all Noir releases, including nightlies: https://github.com/noir-lang/noir/releases

While this is very informative, it could be too informative and makes pre-releases and releases less visible + more difficult to search for.

Which by extension complicates readers' efforts to catch up on release changes.

### Happy Case

Nightlies are installable with noirup still, but not visible on https://github.com/noir-lang/noir/releases (at least by default).

### Project Impact

Nice-to-have

### Workaround

Yes

### Workaround Description

Refer people to less intuitively read https://github.com/noir-lang/noir/blob/master/CHANGELOG.md instead

### Would you like to submit a PR for this Issue?

No

**Comment by TomAFrench** [comment]
This isn't possible without just entirely deleting all the nightly releases which would be too much of a regression in terms of devex.

**Comment by Savio-Sou** [comment]
How does Rust do nightlies while hidden? 🤔 https://github.com/rust-lang/rust/releases

Or are they not on Release Please

**Comment by TomAFrench** [comment]
Rust doesn't use github releases for distributing their binaries. You can see that they don't have any binaries attached to their releases.
