### ISSUE TITLE
NextJs build issue with noirjs 0.38.0

### ISSUE THREAD

**Issue by peter0x2** [noir-lang/noir#6708]
### Aim

No error when building a NextJs project with NoirJS 0.38.0

### Expected Behavior

No error when building a NextJs project with NoirJS 0.38.0

### Bug

info  - Collecting page data .Error: ENOENT: no such file or directory, open '/workspace/newdarkpoolv1/darkpool-v1-dapp-ui-zkverify/.next/server/chunks/../../barretenberg-threads.wasm'
    at async open (node:internal/fs/promises:639:25)
    at async readFile (node:internal/fs/promises:1242:14)
    at async fetchCode (/workspace/newdarkpoolv1/darkpool-v1-dapp-ui-zkverify/.next/server/chunks/8.js:1705:12)
    at async fetchModuleAndThreads (/workspace/newdarkpoolv1/darkpool-v1-dapp-ui-zkverify/.next/server/chunks/8.js:1724:18)
    at async BarretenbergSync.new (/workspace/newdarkpoolv1/darkpool-v1-dapp-ui-zkverify/.next/server/chunks/8.js:432:37)
    at async /workspace/newdarkpoolv1/darkpool-v1-dapp-ui-zkverify/.next/server/chunks/8.js:456:1 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/workspace/newdarkpoolv1/darkpool-v1-dapp-ui-zkverify/.next/server/chunks/../../barretenberg-threads.wasm'
}

> Build error occurred
Error: Failed to collect page data for /depositwithdraw
    at /workspace/newdarkpoolv1/darkpool-v1-dapp-ui-zkverify/node_modules/next/dist/build/utils.js:1130:15 {
  type: 'Error'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### To Reproduce

1.
2.
3.
4.

### Workaround

None

### Project Impact

None

### NoirJS Version

0.38.0

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
cc @noir-lang/developerrelations

**Comment by saleel** [comment]
Hi @peter0x2 
Can you try adding [this](https://github.com/saleel/stealthnote/blob/main/app/next.config.mjs#L8-L19) to your NextJs config

**Comment by TomAFrench** [comment]
Closing this issue as it's not an issue with noir but instead with bb.js. The devrel team are best placed to help with this and I recommend asking in the Aztec discord
