### ISSUE TITLE
`aztec-nargo new --contract` should add contract dependencies and template a contract

### ISSUE THREAD

**Issue by critesjosh** [noir-lang/noir#6717]
### Problem

`aztec-nargo new --contract` doesn't add all of the setup that it could to help devs get set up with writing contracts.

### Happy Case

running `aztec-nargo new --contract` should include the following in main.nr

```noir
use dep::aztec::macros::aztec;

#[aztec]
```
and add the latest `aztec` dependency to Nargo.toml
```toml
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.65.2", directory = "noir-projects/aztec-nr/aztec" }
```

### Workaround

Yes

### Workaround Description

Do it manually.

### Project Impact

Nice-to-have

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
I don't think that nargo should be injecting Aztec dependencies in the default templates, this is going to add a whole new level of dependency hell between noir and Aztec.

This could be put in aztec-nargo but that's not developed in this repository or maintained by the noir team.
