### ISSUE TITLE
Q: Should this duplicate variable name declaration be allowed?

### ISSUE THREAD

**Issue by iAmMichaelConnor** [noir-lang/noir#6718]
![Image](https://github.com/user-attachments/assets/8c0f804e-8070-4358-80a8-9a8df165550f)

The same name is being used for two different types in the same function. That seems quite jarring to me, and I was surprised to see it allowed.

Further Q: even if there was a duplicate declaration of the same type, shouldn't that also be disallowed?

**Comment by TomAFrench** [comment]
This is expected to be allowed and is how it's done in rust. The second let statement redefines the variable shared_secret.
