### ISSUE TITLE
Restrict the number of tests being run in parallel for `nargo test`

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#6724]
We're currently unable to run the tests for https://github.com/noir-lang/noir-bignum due to `nargo test` attempting to run all of the tests in parallel, resulting in it just running out of memory and the process being killed.

As a short term fix, we should restrict the number of threads which `nargo test` will use so that we can run these tests in github CI. We can set the `RAYON_NUM_THREADS` environment variable internally to set the max number of threads.

**Comment by asterite** [comment]
Regarding this, it seems Rust runs tests in parallel for each package, but each package tests (as groups) run sequentially. Do we want to do the same? Right now that's not the case... though I feel that the current way is probably fine.

**Comment by TomAFrench** [comment]
Yeah, I think that running packages serially makes sense.

**Comment by TomAFrench** [comment]
This websites all the tests for a single package will be printed together which is what we want tbh.
