### ISSUE TITLE
Track the time taken to run test functions in `nargo test` and print beside the test output

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#6727]
Pretty much clear from the title. We currently have no real good way to determine which tests in a package are particularly slow to compile so it would be helpful to have a readout of the time taken for each one.

This would be useful for tracking potential regressions in compilation speed in the noir compiler or when it would be sensible to split up a test into smaller components.

**Comment by asterite** [comment]
Do we want to always show the times, or just when a flag is passed?

Also, with many tests it can be hard to spot the slowest ones, so we could list the 10 slowest at the end of the run (maybe if they take more than a threshold, for example 1 second).

**Comment by TomAFrench** [comment]
I think with a naked `nargo test` we should only show times for tests which take more than 30s-1min to avoid flooding the console.
