### ISSUE TITLE
`Illegal instruction (core dumped)` when proving circuits through CLI

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#675]
# Description

## Aim

I'm trying to run `nargo prove` on circuits to generate a proof for one of the circuits in `test_data`.

## Expected behavior

`nargo prove` should exit successfully after writing the proof to a file.

## Bug

Nargo fails to prove the circuit in `8_integration` with the following error:

```
$ nargo prove test
ACIR opcodes generated : 22804
Illegal instruction (core dumped)
```

This seems to occur when we call into `aztec_backend` as we can see that this is thrown inside the `backend.prove_with_meta` function. If we attempt to prove a circuit with blackbox functions such as `simple_shield` however, then we get the same error within `backend.solve`.

# To reproduce

1. Install nargo on Ubuntu 22.04
2. Run `nargo prove` on one of the test case circuits

# Environment

- [x] Using `nargo`:

  - [ ] Binary: (issue doesn't exist in binaries as these are from last year)
  - [x] Compiled from source: [5d29fbc](https://github.com/noir-lang/noir/commit/5d29fbc7370fd794307c04bf670eb65378104ff9)

# Additional context

**Comment by vezenovm** [comment]
I was seeing similar complaints about `backend.prove_with_meta` and `backend.solve` after I made `acvm` changes and was using different versions of `acvm` in `aztec_backend` and in Noir. Would you be able to try a cargo clean and cargo update and running it again?

**Comment by TomAFrench** [comment]
Hey, sorry I must have forgotten to reply here. I've done a clean install of everything and get the same behaviour.

It's something to do with release builds as I can run nargo through `cargo run` but `cargo run --release` fails, most likely some optimisation which has gone awry.

**Comment by aybehrouz** [comment]
I get the exact same error on Ubuntu 20.04.5 LTS on a vmware virtual machine, when I try to prove the hello_world example.

**Comment by kevaundray** [comment]
Closing as #792 has been merged
