### ISSUE TITLE
`noir-lang/big_curve` test `test_secp256r1_offset_generators` fails after #6685

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#6763]
While fixing the dead canary @kashbrti found in https://github.com/noir-lang/noir_bigcurve/pull/22 that the `test_secp256r1_offset_generators` would fail with the error

```
error: Failed to solve program: 'Failed to solve brillig function'
   ┌─ /mnt/user-data/tom/nargo/github.com/noir-lang/noir-bignumv0.4.2/src/fns/expressions.nr:74:12
   │
74 │     assert(remainder == [0; N]);
   │            -------------------
   │
   = Call stack:
     1. src/bigcurve_test.nr:534:17
     2. src/lib.nr:331:9
     3. src/lib.nr:772:13
     4. src/lib.nr:380:9
     5. /mnt/user-data/tom/nargo/github.com/noir-lang/noir-bignumv0.4.2/src/bignum.nr:264:9
     6. /mnt/user-data/tom/nargo/github.com/noir-lang/noir-bignumv0.4.2/src/fns/expressions.nr:279:9
     7. /mnt/user-data/tom/nargo/github.com/noir-lang/noir-bignumv0.4.2/src/fns/expressions.nr:74:12
```

I've bisected this down to passing on fc11b631a2a1c0054b3b2a9e9fd2b7fa3a285076 and failing on 24cc19ed9f29792c7b056124b2adf87fc6c18e42 so it seems like the root cause is due to us not copying arrays when we should due to the changes made in https://github.com/noir-lang/noir/pull/6685.

We didn't catch this at the time as the tests in `noir_bignum` were already failing in CI due to being too heavy for the github runner to run in parallel.

**Comment by TomAFrench** [comment]
@jfecher Can you take a look at whether we can salvage #6685 or if it needs to be reverted?

**Comment by jfecher** [comment]
Looking into this now
