### ISSUE TITLE
Noir "Getting Started" link to "Setting up shell completions" is broken

### ISSUE THREAD

**Issue by michaeljklein** [noir-lang/noir#6779]
### Aim

Attempted to setup shell completions according to the guide in the `Setting up shell completions` section [here](https://github.com/noir-lang/noir/blob/13856a121125b1ccca15919942081a5d157d280e/docs/docs/getting_started/noir_installation.md)

### Expected Behavior

Expected to reach the following page: https://github.com/noir-lang/noir/blob/13856a121125b1ccca15919942081a5d157d280e/docs/docs/getting_started/setting_up_shell_completions.md

### Bug

There's a typo in the link so [it returns a 404](https://github.com/noir-lang/noir/blob/13856a121125b1ccca15919942081a5d157d280e/docs/docs/getting_started/setting_up_shell_completions)

### To Reproduce

1.
2.
3.
4.

### Workaround

Yes

### Workaround Description

Navigate [here](https://github.com/noir-lang/noir/blob/13856a121125b1ccca15919942081a5d157d280e/docs/docs/getting_started/setting_up_shell_completions.md)

### Project Impact

Nice-to-have

### Would you like to submit a PR for this Issue?

None

**Comment by asterite** [comment]
It seems to work in the actual docs, just not in GitHub. I'm not sure how this can be fixed.
