### ISSUE TITLE
Example of an unexpectedly-huge contract artifact.

### ISSUE THREAD

**Issue by iAmMichaelConnor** [noir-lang/noir#6786]
https://github.com/AztecProtocol/aztec-packages/issues/10546

In particular, `create_note` and `create_note_no_init_check`

https://github.com/AztecProtocol/aztec-packages/blob/6f209fb69fcce868c6e0fe9b79b5ac3f3a1e5c48/noir-projects/noir-contracts/contracts/stateful_test_contract/src/main.nr#L45

**Comment by iAmMichaelConnor** [comment]
https://aztecprotocol.slack.com/archives/C02M7VC7TN0/p1733953786902059

**Comment by TomAFrench** [comment]
@aakoshh Do you have bandwidth for this?

**Comment by aakoshh** [comment]
The first jump I found in the size was https://github.com/AztecProtocol/aztec-packages/commit/3304046704e257902e32b86baf1aafc8b23bcaf6 where the `create_note_no_init_check` goes from 164,516 bytes in the previous commit up all the way to 13,815,792, or if we consider the entire `stateful_test_contract-StatefulTest.json` then it goes from 3.3M to 42M. This is not the final size, but it's something worth intestigating. 

Commands to check:

```shell
PROGRAM_DIR=$pwd/noir-projects/noir-contracts 
git checkout 3304046704e257902e32b86baf1aafc8b23bcaf6
cd noir/noir-repo
cargo run --release -p nargo_cli -- --program-dir $PROGRAM_DIR compile --package stateful_test_contract
jq '.functions | sort_by(.name) | .[] | {name: .name, size: .bytecode | length }' $PROGRAM_DIR/target/stateful_test_contract-StatefulTest.json
```

**Comment by aakoshh** [comment]
Within the syncing PR https://github.com/AztecProtocol/aztec-packages/pull/10307 that backs the above squashed commit, the two commits where there are significant bytecode size increases are:
* https://github.com/AztecProtocol/aztec-packages/commit/369ea54 the size goes from 213,180 to 4,802,664
* https://github.com/AztecProtocol/aztec-packages/commit/70cf870f the size goes from 4,331,388 to 15,129,080

**Comment by aakoshh** [comment]
The following is the printout of the number of lines in the SSA in https://github.com/AztecProtocol/aztec-packages/commit/369ea54 

```
COMPILING CONTRACT FUNCTION create_note_no_init_check
Initial SSA:: 7661
After Defunctionalization:: 7693
After Removing Paired rc_inc & rc_decs:: 7693
After Runtime Separation:: 8136
After Resolving IsUnconstrained:: 8136
After Inlining (1st):: 12098
After Mem2Reg (1st):: 8727
After Simplifying (1st):: 7953
After `as_slice` optimization: 7953
After `static_assert` and `assert_constant`:: 7953
After Loop Invariant Code Motion:: 7953
After Unrolling:: 40728
After Simplifying (2nd):: 38161
After Flattening:: 58927
After Removing Bit Shifts:: 58927
After Mem2Reg (2nd):: 33335
After Inlining (2nd):: 33813
After Remove IfElse:: 1287564
After Constant Folding:: 967623
After EnableSideEffectsIf removal:: 965798
After Constraint Folding:: 963258
After Dead Instruction Elimination:: 958799
After Simplifying:: 958797
After Array Set Optimizations:: 958797
After Constant Folding with Brillig:: 958478
After Dead Instruction Elimination:: 958458
```

We can see that there is a dramatic increase in the `Remove IfElse` step, going from 33,813 to 1,287,564

Compare it with the same in its parent commit https://github.com/AztecProtocol/aztec-packages/commit/0577c1a 

```
COMPILING CONTRACT FUNCTION create_note_no_init_check
Initial SSA:: 8009
After Defunctionalization:: 8041
After Removing Paired rc_inc & rc_decs:: 7861
After Runtime Separation:: 8342
After Resolving IsUnconstrained:: 8342
After Inlining (1st):: 13330
After Mem2Reg (1st):: 11720
After Simplifying (1st):: 10834
After `as_slice` optimization: 10834
After `static_assert` and `assert_constant`:: 10834
After Loop Invariant Code Motion:: 10834
After Unrolling:: 44343
After Simplifying (2nd):: 41738
After Flattening:: 71721
After Removing Bit Shifts:: 71721
After Mem2Reg (2nd):: 35739
After Inlining (2nd):: 35277
After Remove IfElse:: 39020
After Constant Folding:: 31940
After EnableSideEffectsIf removal:: 30111
After Constraint Folding:: 27518
After Dead Instruction Elimination:: 19253
After Simplifying:: 19251
After Array Set Optimizations:: 19251
After Constant Folding with Brillig:: 18969
After Dead Instruction Elimination:: 18944
```

In this version `RemoveIfElse` adds less than 4,000 lines.

**Comment by aakoshh** [comment]
Looking at what is causing the following:

> https://github.com/AztecProtocol/aztec-packages/commit/70cf870f the size goes from 4,331,388 to 15,129,080 compared to feef655

Printing SSA sizes does not reveal any smoking gun, the numbers are similar to above. 
Actually in this case, commit feef655 looks bigger on paper than what follows:
```
Dead Instruction Elimination (2nd): 874,549 lines, 36,977,266 chars
f0: 874,081 instructions
ACIR OPCODES BEFORE TRANS: 298,782
ACIR OPCODES AFTER TRANS: 299,471
```
Whereas in 70cf870f we have a smaller SSA, but the final ACIR opcode count is 5x larger:
```
Dead Instruction Elimination (2nd): 641,474 lines, 28,936,683 chars
f0: 640,942 instructions
OPCODES BEFORE TRANS: 1,580,140
OPCODES AFTER TRANS: 1,580,497
```

**Comment by aakoshh** [comment]
The next larger change to the overall size shown by `ls -lh ./target/stateful_test_contract-StatefulTest.json` is https://github.com/AztecProtocol/aztec-packages/commit/31665296c94a221098a473426e3686e56b4b9e96 which is the squashed commit of https://github.com/AztecProtocol/aztec-packages/pull/10483

I'll update the comment if I find anything.

**Comment by benesjan** [comment]
@aakoshh I don't know if you've seen [my comment](https://aztecprotocol.slack.com/archives/C0183F0V42V/p1733945470447529) but there the cause of blowup is pretty clear. Might make sense to investigate that first as the cause of the blowup of the stateful contract seems hard to point down (might be the same issue).
