### ISSUE TITLE
Slow downloading project deps with nargo

### ISSUE THREAD

**Issue by jzaki** [noir-lang/noir#6833]
### Problem

Downloads entire git history, when a shallow clone might suffice.
Important example deps from aztec-packages.

### Happy Case

Reduce friction / entry barriers when using deps with long git histories like aztec-packages.
Suggestion [here](https://discord.com/channels/1113924620781883405/1316807516818247680) `git clone --depth 1`

### Workaround

Yes

### Workaround Description

Being patient and accepting unnecessary(?) download and disk use

### Project Impact

Nice-to-have

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
https://github.com/noir-lang/noir/blob/f037c36f6bfcb8efb1950e444b50bc3eff28ffc4/tooling/nargo_toml/src/git.rs#L49

Closing as this had been the default behaviour for a long time.
