### ISSUE TITLE
assert_max_bit_size() causes panic

### ISSUE THREAD

**Issue by calummoore** [noir-lang/noir#6839]
### Aim

Verify that the the sum of two fields is less than the bit size, to prevent overflow attack.

### Expected Behavior

Constraint is applied.

### Bug

The application panicked (crashed).
Message:  Non-numeric type variable used in expression expecting a value
Location: compiler/noirc_frontend/src/monomorphization/mod.rs:934

I also note in the docs that this field takes a parameter (`field.assert_max_bit_size(32);`), but it doesn't seem to in the Noir validation. I get an error if I try to use a parameter.

```
error: Function expects 1 parameter but 2 were given
   ┌─ src/main.nr:15:5
   │
15 │     output_value.assert_max_bit_size(32);
   │     ------------------------------------
   │
```

### To Reproduce

```rust
#[recursive]
fn main(field1: Field, field2: Field) {
    let output_value = field1 + field2;

    // Contrain the output value
    output_value.assert_max_bit_size();
}

#[test]
fn test_main() {
    main(1, 2)
}
```

### Workaround

None

### Project Impact

Blocker

### Nargo Version

nargo version = 0.36.0 noirc version = 0.36.0+801c71880ecf8386a26737a5d8bb5b4cb164b2ab (git version hash: 801c71880ecf8386a26737a5d8bb5b4cb164b2ab, is dirty: false)

### NoirJS Version

n/a

### Would you like to submit a PR for this Issue?

None

**Comment by TomAFrench** [comment]
Hey, thanks for opening this. Looks like the example in the docs is stale so I've opened #6840 to address this.

Due to \*reasons\*, we've moved the argument of this function into a numeric generic so to constrain `output_value` to fit in 32 bits you would need to modify your example as below.

```
#[recursive]
fn main(field1: Field, field2: Field) {
    let output_value = field1 + field2;

    // Contrain the output value
    output_value.assert_max_bit_size::<32>(); // See turbofish usage.
}

#[test]
fn test_main() {
    main(1, 2)
}
```

**Comment by calummoore** [comment]
Ok, sounds good, it worked with specifying a value using the turbofish syntax. 

Should it also work with ` output_value.assert_max_bit_size();` - i.e. no parameter? Currently that triggers an error.

**Comment by TomAFrench** [comment]
There's no way for the compiler to know how many bits you want to constrain the field to if you don't use the turbofish syntax.

**Comment by calummoore** [comment]
Ah okay, I thought it would be the max Field size looking at the code.
