### ISSUE TITLE
Readme - hello world example not working

### ISSUE THREAD

**Issue by nikkolasg** [noir-lang/noir#70]
Hi there,

I wanted to try out Noir - I installed it correctly, created a hello world example with `nargo new hello_world`, cd into it, `nargo build` correctly but `nargo prove my_proof`simply fails:
```
thread 'main' panicked at 'Expected witness values to be integers: ParseIntError { kind: Empty }', crates/noirc_abi/src/input_parser/toml.rs:91:14
```
What am I missing ? It seems I need to give the witness but there's no indication on how in the CLI.

**Comment by nikkolasg** [comment]
Ok found it - I need to replace the x and y value in `Prove.toml`- this should be added to the documentation I believe it's missing.

**Comment by kevaundray** [comment]
Hi @nikkolasg , 

Sorry about that, there is a tracking issue here: https://github.com/noir-lang/book/issues/5 for this problem.

Let me know if there is anything else lacking in the documentation.
