### ISSUE TITLE
Rename `noir gates` command

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#714]
# Problem

Noir has no concept of a `gate`, we compile down to an ACIR circuit which holds opcodes.

# Solution

I think `noir opcodes` is the most intuitive solution. However, this implies that we are printing out all of the opcodes. This was a problem with `noir gates` too, so we can fix that in another issue.

# Alternatives considered

# Additional context

**Comment by vezenovm** [comment]
> noir opcodes

`nargo gates` outputs the number of ACIR opcodes but it also prints the final number of gates in the circuit used by the proving system. `noir opcodes` seems not entirely intuitive. Perhaps just `nargo info`? Or we should split the functionality for outputting the number of ACIR opcodes and the true size of a circuit.

**Comment by kevaundray** [comment]
> tputs the number of ACIR opcodes but it also prints the final number of gates in the circuit used by the proving system. `n`

`nargo info` does sound closer to what we want, its probably lower effort than splitting up the functionality, so I'd opt for renaming at least for now

**Comment by kevaundray** [comment]
@vezenovm whats the status of this issue?

**Comment by TomAFrench** [comment]
I think we can hold off on this until we implement https://github.com/noir-lang/noir/issues/1381.

**Comment by vezenovm** [comment]
@kevaundray I can submit a PR to rename the command to `nargo info` for the time being as it is a pretty simple change. @TomAFrench Are you good with the name `nargo info`? Then we can do a full refactor of the command at some later date?
