### ISSUE TITLE
Remove catch_unwind in nargo tests

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#716]
# Problem

Currently the test code uses `catch_unwind` to catch panics. [See here](https://github.com/noir-lang/noir/blob/master/crates/nargo/tests/prove_and_verify.rs#L47)
# Solution

It should come as a suprise that user input can crash the compiler, so any case where this happens should be converted to an error and or fixed.

With this assumption, the test case should not `catch_unwind`. This is a part of a larger issue where for tests we should instead be using something closer to `compiletest` that Rust uses.

# Alternatives considered

# Additional context

**Comment by jfecher** [comment]
I agree that we do not want user input to ever crash the compiler, but I think this `catch_unwind` is still necessary for catching unexpected crashes as well so that we can print out the failing test name before re-crashing.

Using `compiletest` like rust or `goldentests` like ante both run the program externally which has the same effect of catching panics, just at the shell level now.

**Comment by kevaundray** [comment]
> I agree that we do not want user input to ever crash the compiler, but I think this `catch_unwind` is still necessary for catching unexpected crashes as well so that we can print out the failing test name before re-crashing.
> 
> Using `compiletest` like rust or `goldentests` like ante both run the program externally which has the same effect of catching panics, just at the shell level now.

Fair point, I think then this issue is blocked until we have a setup closer to `compiletest` or `goldentest` which I think may be necessary for us to move nargo out of this repository. Since we probably want to run nargo in the CI whenever we modify the compiler on a directory full of test cases

**Comment by kevaundray** [comment]
Closing this in favour of https://github.com/noir-lang/noir/issues/2013
