### ISSUE TITLE
Add nargo command to both prove and verify

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#719]
# Problem

Proving and immediately verifying afterward is a common usecase but has no single command to do both. It would also be nice if there were an option to do so without writing to the file system between the two steps.

# Solution

Add a `nargo run` command to prove and verify.

# Alternatives considered

# Additional context

**Comment by kevaundray** [comment]
@TomAFrench what are your thoughts on this?

**Comment by TomAFrench** [comment]
I'd question whether this is/should be a common action for users other than us. Noir devs trust that Nargo/backends are implemented correctly and so will properly create a valid proof as long as that their circuit the witness can be solved, after that point it's out of their hands.

It feels like we'd be the main users of this action for e2e testing so this might be better to have as a flag on `nargo prove` rather than a full-fledged command i.e. `nargo prove --checked`.

Happy to be corrected if I'm missing something though.

**Comment by phated** [comment]
I might be mistaken, but I believe snarkjs has `fullProve` which is a prove and verify and everyone I've seen uses this (Dark Forest, etc) so I think it is pretty common 🤔

**Comment by TomAFrench** [comment]
> I might be mistaken, but I believe snarkjs has `fullProve` which is a prove and verify and everyone I've seen uses this (Dark Forest, etc) so I think it is pretty common thinking

https://github.com/iden3/snarkjs/blob/b478e44e9ffb6270b51e24c38158730a39b27b02/cli.js#L1059-L1077

Looks like their `fullProve` is roughly equivalent to our `nargo prove` (i.e. solve witness and prove) and doesn't verify.

**Comment by phated** [comment]
👍 That's what I get for not checking before I opened my mouth. Thanks for looking.

**Comment by kevaundray** [comment]
> I'd question whether this is/should be a common action for users other than us. Noir devs trust that Nargo/backends are implemented correctly and so will properly create a valid proof as long as that the witness for their circuit can be solved, after that point it's out of their hands. Anything after solving the witness is wasted CPU time then surely unless you're actually creating a proof which will be used for anything other than testing? (#626)
> 
> It feels like we'd be the main users of this action for e2e testing (as we'll be mucking around in the guts of nargo and so could break how we interact with the backend, etc.) so this might be better to have as a flag on `nargo prove` rather than a full-fledged command i.e. `nargo prove --checked`.
> 
> Happy to be corrected if I'm missing something though.

The --checked flag seems like a good trade-off, I'd imagine that we move towards using @jfecher 's testing framework as time goes by.
