### ISSUE TITLE
Nargo prove cause RuntimeError

### ISSUE THREAD

**Issue by Syhawk** [noir-lang/noir#723]
# Description

## Aim

Generate proof.

## Expected behavior
Run `nargo prove p` to generate proof.
```
ACIR opcodes generated : 102
Total Proving time (Rust + WASM) : 14516569125ns ~ 14seconds
Proof successfully created and located at proofs/p.proof
```

## Bug
Get a runtimeError
```
ACIR opcodes generated : 102
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RuntimeError { source: Trap(UnreachableCodeReached), wasm_trace: [], native_trace:    0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
 }', /Users/xxx/.cargo/git/checkouts/aztec_backend-a697fb631cbad807/c673a14/barretenberg_wasm/src/lib.rs:90:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

# To reproduce

1. use this code
`main.nr`
```
use dep::std;
fn main(x: pub [u8; 64], result: pub u8) {
    let mut digest = std::hash::sha256(x);
    let N = 31;
    for i in 0..N {
        if (i >= 0) {
            digest = std::hash::sha256(x);
        }
    }
    constrain digest[0] == result;
}
```
`Prover.toml`
```
x = [
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00
]
result = 0xf5
```

2. `nargo prove p`

# Environment

- [x] Using `nargo`:

  - [x] Binary: [0.1 ](https://github.com/noir-lang/noir/releases/download/nightly/nargo-aarch64-apple-darwin.tar.gz)
  - [ ] Compiled from source: 

- [ ] Using TypeScript:

  - @noir-lang/noir_wasm: 
  - @noir-lang/barretenberg: 
  - @noir-lang/aztec_backend: 

# Additional context
`Macbook Pro (2021 14-inch M1 Max) 16G`

**Comment by jfecher** [comment]
Hmm, just tested this and it proved correctly for me on my M1 Pro. I'm on commit 506feace379f5de7e6805052283057b00f2d8e1a for reference.

Issue may be specific to the wasm backend

**Comment by Syhawk** [comment]
You can increase the value of N and try again, maybe it can be reproduced.

**Comment by Syhawk** [comment]
Thank you, using `aztec_backend` does not have this error.

**Comment by phated** [comment]
I'm going to re-open because the wasm backend is the backend that most people get by default and we need to fix it.

**Comment by kevaundray** [comment]
@phated whats the status of this issue?

**Comment by kevaundray** [comment]
Closing this and we can re-open if the issue arises again
