### ISSUE TITLE
Remove uses of `std::process::exit`

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#729]
# Problem

`std::process::exit` prevents drops from running which has the potential to be problematic for e.g. open files or other IO relying on being closed cleanly.

# Solution

Remove each use of `std::process::exit`, instead percolating the error up to nargo's main function and returning an error there.

# Additional context

The `nargo test` PR brings us a bit closer in percolating up errors more to be caught by testing, but also adds more `std::process::exit` instances in doing so.

**Comment by phated** [comment]
This is also important for things that get compiled to wasm, as `std::process::exit` causes a force exit in all WASI runtimes and breaks a lot of tooling (I had to deal with this in Circom).

**Comment by kevaundray** [comment]
Assigning this to @Ethan-000
