### ISSUE TITLE
Add type aliases

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#735]
# Problem

Noir has no way to abbreviate types which can be problematic especially for generic or function types which tend to be larger.

# Solution

Add type aliases using the same syntax as rust - noir has no need to innovate here.

```rs
type Point = (Field, Field);
type Eq<T> = fn(T, T) -> bool;
type Index = comptime Field;

// Aliases can then be used anywhere a type is expected
fn array_eq<Elem>(array1: [Elem], array2: [Elem], elem_eq: Eq<Elem>) -> bool {
    let len = std::array::len(array1);
    if len != std::array::len(array2) {
        false
    } else {
        let mut eq = true;
        for i in 0 .. len {
            eq &= elem_eq(array1[i], array2[i]);
        }
        eq
    }
}
```

# Alternatives considered

# Additional context

**Comment by jfecher** [comment]
@Ethan-000 good catch. Not sure why I didn't catch that when searching beforehand. I've closed the older issue since this one has slightly more detail.

**Comment by kevaundray** [comment]
@jfecher and @Ethan-000 what was the status of PR 817?
