### ISSUE TITLE
Tracking issue: Merge queues

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#748]
# Problem

When multiple PRs pass the CI individually, it is not certain that they will all pass the CI when merged into the master branch. To mitigate this, whenever a PR is merged into master, the other PRs will need to update their branch and have the CI run again against the new state of master and their branch.

Ideally this process is automated when there are no merge conflicts.

# Solution

Add Github merge queues which will allow us "Add PR to queue" and github will deal with the reconsolidation.

# Alternatives considered

- There is also https://github.com/marketplace/mergify
- We can also do nothing

# Additional context

**Comment by phated** [comment]
When GitHub rolled out merge queues, they only supported merging, not squashing (and thus not linear history). I'm not sure if that has changed yet.

**Comment by kevaundray** [comment]
Leaving here as a TODO: we have a bors.toml file in the root directory, that we should remove now or once we fully add github merge queues.

**Comment by kevaundray** [comment]
bors.toml is getting removed in #937 so closing this as the original merge queue functionality is being used
