### ISSUE TITLE
Remove `todo` to generate a witness when resolving a `NodeId`

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#758]
See this line: https://github.com/noir-lang/noir/blob/b8c582f2a958bb27fb7218fb8f40c36d49601afb/crates/noirc_evaluator/src/ssa/acir_gen.rs#L608

**Comment by TomAFrench** [comment]
There's been some churn on where this todo lives however [it still exists](https://github.com/noir-lang/noir/blob/3891faf4ac0212aed63a2c0e2cfcdeafa6a68d37/crates/noirc_evaluator/src/ssa/acir_gen/operations/intrinsics.rs#L176)
