### ISSUE TITLE
Nargo refuses to proceed when Executing / Proving with unfilled `return`

### ISSUE THREAD

**Issue by Globallager** [noir-lang/noir#767]
# Description

## Aim

Computes an unknown Pedersen hash value.

## Expected behavior

Running `nargo execute` / `nargo prove` on the following should auto-compute the return value and fills it in Verifier.toml:

**main.nr**
```rust
use dep::std;

fn main(a : Field) -> pub Field {
    std::hash::pedersen([a])[0]
}
```

**Prover.toml**
```rust
a = "1"
return = ""
```

## Bug

Was prompted with this error instead:
```
Received parameters not expected by ABI: ["return"]
```

# Environment

- [x] Using `nargo`:

  - [x] Binary:  nargo 0.1.1 (git:[0c16089](https://github.com/noir-lang/noir/commit/0c16089f73b64ee489a5c2fa065238421247168b))
  - [ ] Compiled from source:

**Comment by kevaundray** [comment]
What happens if you remove the return parameter from Prover.toml ? 

There was a PR to remove this about two weeks ago

**Comment by Globallager** [comment]
Ah wasn't aware of that being the cause. Thanks Kev.
