### ISSUE TITLE
Using modulus on comptime values within a for-loop always returns 0

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#774]
# Description

## Aim

I'd like to use the modulus operator on array indices which are defined at compilation time.
 
## Expected behavior

Using the modulus operator (%) on comptime values should correctly calculate the modulus of these values at compile time.

## Bug

Instead of the expected index, I always access the 0'th element of the array. I've checked and the only usage of `%` in noir code today I can see is `2_div` makes use of it on non-comptime values. This implies the issue is specific to comptime values and I've confirmed this with the test case below.

# To reproduce

Run the following Noir program

```
fn main() {
    // x % y should always return x for 0 <= x < y.
    let y = 25;
    for i in 0..y {
        let t: Field = ((i as u64) % (y as u64)) as Field;
        // This constraint fails
        constrain t == i;
        // This constraint passes
        // constrain t == 0;
    }  
}

// Compare with this circuit which uses non-comptime values

fn main(z: Field) {
    let y = 25;
    constrain z > y;
    for i in 0..y {
        let t: Field = ((i as u64) % (z as u64)) as Field;
        constrain t == i;
    }  
}


```

# Environment

- [x] Using `nargo`:
  - [x] Binary: `nargo 0.1.1 (git:c072150)`
  - [ ] Compiled from source: 

- [ ] Using TypeScript:

  - @noir-lang/noir_wasm: 
  - @noir-lang/barretenberg: 
  - @noir-lang/aztec_backend: 

# Additional context

**Comment by pierg** [comment]
I have experienced the same problems. Here's a small example to reproduce the problem:

`fn main() -> pub [u8;4] {
    let mut result = [0;4];
    for i in 0..4{
        // WORKS: result=[0,1,2,3]
        result[i] = i as u8;

        // DOES NOT WORK: result=[0,0,0,0]
        result[i] = i as u8 % 2 as u8;
    }
    result
} 
`
