### ISSUE TITLE
Apply correct typing to return values of black box functions

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#775]
# Problem

Functions like `merkle_check_membership` will return a `Field` whereas we ideally want it to return a `bool`

# Solution

- The easiest solution would be to wrap the function in another function which does the correct typing using `as`.
-  Another solution is to change the types of those functions to be `bool` for example and then enforce that they are in the compiler 

# Alternatives considered

# Additional context

**Comment by TomAFrench** [comment]
Weren't we planning on avoiding passing in a root all together? (https://github.com/noir-lang/acvm/issues/66)

**Comment by kevaundray** [comment]
> Weren't we planning on avoiding passing in a root all together? ([noir-lang/acvm#66](https://github.com/noir-lang/acvm/issues/66))

Yep you are correct; issue may have not been clear -- This is for all blackbox functions that we have implemented in Noir that should return booleans, but we've typed them as `Field`. So this would apply for signature verification functions too.
