### ISSUE TITLE
Comptime soundness issue in `if` expressions

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#793]
# Description

## Aim

```rs
fn main(x: bool) {
    let foo = if x { 1 } else { 2 };
    ...
}
```

## Expected behavior

Expected `foo` to be a `Field` rather than a `comptime Field` since its value depends on a private input to the circuit.

## Bug

`foo` is incorrectly typed as a `comptime Field` which can cause compiler panics when later attempting to use it as an array index.

**Comment by kevaundray** [comment]
@jfecher whats the status of this issue?

**Comment by jfecher** [comment]
@kevaundray still open and unchanged. I haven't worked on it in case we wanted to remove comptime after dynamic indexing is enabled.
