### ISSUE TITLE
Add some simple form of workspace file

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#794]
# Problem

I would like to be able to have several noir crates in a repository and interact with them from the repository root.

# Solution

We should add some form of workspace file similar to this repository's [Cargo.toml](https://github.com/noir-lang/noir/blob/master/Cargo.toml). This would specify the paths of each of the Noir crates in the repository so Nargo can find them easily.

Using this we could perform actions such as 
- running all the tests in a single command from the repository root
- prove against a circuit in a different directory by specifying `-p crate_name`
- specify a default crate to interact with (similarly to how we have `nargo` as the default crate in this repository).

# Alternatives considered

We could either maintain that the user has to cd into each crate themselves (this isn't particularly nice from a CI perspective).

Alternatively we could search all subdirectories of the current directory for Noir crates, but this seems needlessly complicated.

# Additional context

**Comment by f01dab1e** [comment]
In the initial phase, I aim to investigate the extension of the manifest, akin to Rust's approach:

```toml
[workspace]
members = [
    "path/to/first_member", 
    "path/to/second_member"
]
```
..and a command to run tests

One of the prominent features is the ability to consolidate all components into a single target folder when executing the build process. If anyone has any suggestions or tips regarding this aspect, your insights would be greatly appreciated.

**Comment by kevaundray** [comment]
Linking here but we can put it in another issue, it was noted internally that it would be good to generate ABIs for not only this contract, but also the contract's dependencies. Our tooling around dependencies is not that mature so I think we can brainstorm around that at a later point while we mature the dependency tooling

**Comment by f01dab1e** [comment]
cargo checks the workspace, ensuring that a number of invariants are met:
1. A workspace only has one root.
2. All workspace members agree on this one root as the root.
3. Unique package names in the workspace.

It probably makes sense to support that as well.
