### ISSUE TITLE
Consider whether we should have openssl dependency in nix file

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#795]
https://github.com/noir-lang/noir/blob/846a24af0c3ed5cc1d35d0630b8fbe3faca33b8a/default.nix#L5

Seems like with https://github.com/noir-lang/noir/pull/691, this is no longer necessary but I want to be able to build from this nix file before I start removing things from it.

**Comment by kobyhallx** [comment]
Now that we have moved on to rust_tls this won't be needed. It won't hurt either.

**Comment by kevaundray** [comment]
@TomAFrench whats the status of this issue?

**Comment by TomAFrench** [comment]
This line can be removed now. Will make a quick pr for it.

**Comment by TomAFrench** [comment]
Relevant file no longer exists
