### ISSUE TITLE
Rename `HirFunction::unsafe_from_expr` to `HirFunction::from_expr_unchecked`

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#812]
# Problem

The word `unsafe` here is being used to mean `unchecked`. Since `unsafe` has a particular meaning in Rust, we should be careful not to cause confusion when using it.

# Solution

Change `unsafe` word to `unchecked`

Thoughts welcome on bikeshedding, ie we could do `HirFunction::from_expr_unchecked` or `HirFunction::unchecked_from_expr` or something else; the core of this issue is to remove the `unsafe` keyword

# Alternatives considered

# Additional context

**Comment by DreamerChaserHAH** [comment]
![Three Result](https://user-images.githubusercontent.com/109950820/218290753-beab0bef-d830-4b7c-9060-136eac5e5531.png)

Found three result to replace. I will replace it

**Comment by kevaundray** [comment]
> ![Three Result](https://user-images.githubusercontent.com/109950820/218290753-beab0bef-d830-4b7c-9060-136eac5e5531.png)
> 
> Found three results to replace. May I replace it?

Thanks for tentatively opening up the PR for this :)
