### ISSUE TITLE
Tracking issue: libtest-mimic crate as a test harness

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#815]
# Context

This is an issue to track discussions around the [libtest-mimic crate](https://github.com/LukasKalbertodt/libtest-mimic) which is meant to look like the usual rust test-harness. 

We may or may not want to use this in the future, depending on how advanced our test harness gets and other factors.

**Comment by TomAFrench** [comment]
Closing in favour of [4489](https://github.com/noir-lang/noir/issues/4489)
