### ISSUE TITLE
Tracking issue: Add human readable panic messages for end-users

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#818]
# Problem

When a user encounters a compiler error, we ideally don't want them to see the stack trace, but instead a call-to-action, telling them how to report the error (creating an issue, or emailling)

# Solution

One crate which provides a solution is human-panic [here](https://github.com/rust-cli/human-panic)

There may be other crates out there, I honestly did not look past this one. If there are better alternatives would be great to hear about them too.

# Alternatives considered

# Additional context

**Comment by phated** [comment]
It seems weird that'd we'd "panic" instead of propagating the errors to the root and letting rust crash itself with the error properly. This seems to be a symptom of `unwrap` calls instead of judicious use of `?` and Option/Result return types. 

Generally, you want to avoid `panic` and `exit` calls because those are very hard/impossible to handle from the wasm.

**Comment by jfecher** [comment]
Panics are supposed to be impossible to run into if our assumptions writing the program are correct so I'm unsure this is needed. I think for the cases that we do have a compiler bug our users are themselves programmers and know how to read a panic message and know that they should submit a bug report if they care about the project.

**Comment by kevaundray** [comment]
@Blaine I think for cases that should never happen, it makes sense to panic or we _could_ create a CompilerError error variant, but I think the norm would be to panic on impossible cases/compiler errors. For WASM, we can have a panic_hook which catches that nasty case. See [here](https://github.com/rustwasm/console_error_panic_hook)


@jfecher I agree that our userbase will be developers however its not clear that they will be Rust developers, so seeing a stack unwinding may not be the best UX. 

To clarify, this does not affect any code in the library itself, you just add a method in your main function in main.rs and it will catch panics that are brought up over the lifetime of the program.


[You can see Rust doing something similar on its ICEs](https://github.com/rust-lang/rust/issues/107440)

**Comment by blaine** [comment]
I was accidentally tagged (hi @phated!) and have no context here (noir looks cool!) but I may as well bring something to the party while I'm here. ;-)

This post from Joe Duffy on error handling does a great job of talking through why panic makes more sense than propagating an error up the stack in the case you're talking about: https://joeduffyblog.com/2016/02/07/the-error-model/ 😊

**Comment by 0xYYY** [comment]
> There may be other crates out there, I honestly did not look past this one. If there are better alternatives would be great to hear about them too.

Another option may be using [`color_eyre` panic hook](https://docs.rs/color-eyre/latest/color_eyre/config/struct.HookBuilder.html).

```rust
use anyhow::{bail, Context, Result};
use color_eyre;

fn f3() -> Result<()> {
    bail!("something went wrong in f3")
}

fn f2() -> Result<()> {
    f3().context("failed to run f3")
}

fn f1() -> Result<()> {
    f2().context("failed to run f2")
}

fn main() {
    let (panic_hook, _) = color_eyre::config::HookBuilder::default()
        .display_env_section(false)
        .panic_section("This is a bug. Consider raising an issue at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.md")
        .into_hooks();
    panic_hook.install();
    f1().unwrap();
}
```

And the output looks like
<img width="1047" alt="Screenshot 2023-02-15 at 00 43 54" src="https://user-images.githubusercontent.com/86655648/218801654-64497bd5-01ca-4fe9-bf9c-d6773a8b45a6.png">

Which is, imho, clearer than `human_panic`'s (uncustomizable) output
<img width="1438" alt="Screenshot 2023-02-15 at 00 48 41" src="https://user-images.githubusercontent.com/86655648/218802905-28baad40-e9ab-4841-ac55-057a7fe838cb.png">

**Comment by kevaundray** [comment]
> > There may be other crates out there, I honestly did not look past this one. If there are better alternatives would be great to hear about them too.
> 
> Another option may be using [`color_eyre` panic hook](https://docs.rs/color-eyre/latest/color_eyre/config/struct.HookBuilder.html).
> 
> ```rust
> use anyhow::{bail, Context, Result};
> use color_eyre;
> 
> fn f3() -> Result<()> {
>     bail!("something went wrong in f3")
> }
> 
> fn f2() -> Result<()> {
>     f3().context("failed to run f3")
> }
> 
> fn f1() -> Result<()> {
>     f2().context("failed to run f2")
> }
> 
> fn main() {
>     let (panic_hook, _) = color_eyre::config::HookBuilder::default()
>         .display_env_section(false)
>         .panic_section("This is a bug. Consider raising an issue at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.md")
>         .into_hooks();
>     panic_hook.install();
>     f1().unwrap();
> }
> ```
> 
> And the output looks like <img alt="Screenshot 2023-02-15 at 00 43 54" width="1047" src="https://user-images.githubusercontent.com/86655648/218801654-64497bd5-01ca-4fe9-bf9c-d6773a8b45a6.png">
> 
> Which is, imho, clearer than `human_panic`'s (uncustomizable) output <img alt="Screenshot 2023-02-15 at 00 48 41" width="1438" src="https://user-images.githubusercontent.com/86655648/218802905-28baad40-e9ab-4841-ac55-057a7fe838cb.png">

Yeah `color_eyre` does print the trace in a nicer way imo

**Comment by 0xYYY** [comment]
Absolutely, would be happy to take this one.

**Comment by TomAFrench** [comment]
Closing this as it seems like it's been addressed.
