### ISSUE TITLE
Replace `thiserror` in `nargo` with `anyhow`

### ISSUE THREAD

**Issue by Ethan-000** [noir-lang/noir#819]
# Problem

It seems `thiserror` is usually used in libraries and `anyhow` is used more in binaries. 

Since `nargo` is a binary, it might be better for it to adopt `anyhow` for errors

# Solution

replace `thiserror` in `nargo` with `anyhow`

# Alternatives considered

alternatively, we can keep using `thiserror` for `nargo`

# Additional context

**Comment by TomAFrench** [comment]
I think we can let them run in parallel quite happily. We should keep `thisError` in place in the internals of `nargo` for now (this is important as we break off components into various libraries) but when we bubble up an error to `main` it should be wrapped in `anyhow::Result` to avoid us leaking `CliError`.
