### ISSUE TITLE
Report errors in the stdlib

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#834]
# Description

@jfecher noted that when there is an error in the stdlib, it fails to compile and thus the program simply states that the stdlib cannot be found.

Copying the exact error from Jake:

```
thread 'main' panicked at 'error reporter: could not find crate std', crates/noirc_frontend/src/hir/resolution/import.rs:163:28
```

# Solution

We should report errors in the stdlib just like how we report errors in the local crate.

# Note

We should check if this is a problem with the stdlib or just a problem with dependencies

**Comment by kevaundray** [comment]
For reference, to reproduce this one just needs to make a syntactic error in the stdlib.

@phated since you have made changes in the context of the lsp, can you check if this is still an issue?

**Comment by phated** [comment]
I'll take a look into this

**Comment by jfecher** [comment]
Could not reproduce. As far as I can tell, all errors in the stdlib are reported, including parser, name resolution, and type errors.
