### ISSUE TITLE
Switch to clap's derived CLI interface

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#841]
# Problem

We're currently using claps builder API which causes us a few issues

- Command definitions are verbose and separate from the actual code they're running
- Argument decoding is verbose and repeated across each command (e.g. `allow_warnings`, `show_ssa`, `program_dir`)
- We don't get the benefits of defining structure between different arguments (e.g. `allow_warnings` and `show_ssa` could be grouped into a `CompilationOptions` struct and passed around as a unit)
  - This means that the current format isn't going to scale well as we add more options

https://docs.rs/clap/latest/clap/_faq/index.html#when-should-i-use-the-builder-vs-derive-apis

# Solution

We should switch over to using [clap's derived API](https://docs.rs/clap/latest/clap/_derive/_tutorial/index.html) so we can begin to simplify the CLI code and group flags which naturally go together.

# Alternatives considered

# Additional context

**Comment by jfecher** [comment]
We should absolutely switch over to the derived API. I did the same for my other compiler project when clap 4.0 originally came out and the improvement to argument handling ergonomics was considerable.
