### ISSUE TITLE
Remove chumsky fork

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#853]
# Problem

We have been using a fork of chumsky for some time for the added parser `.recover_via` for custom recovery strategies. Chumsky 0.9.0 has now been released with the parser `skip_parser` which will do the same thing.

# Solution

We should abandon the fork, change our chumsky version to 0.9.0, and test with the new version. We should also test #791 again with the new version to see if there have been any performance improvements.

**Comment by pczarn** [comment]
I started working on this issue.

**Comment by kevaundray** [comment]
@jfecher wants the status on this issue? Would be good to get this closed once and for all (given the problem is tractable)

**Comment by jfecher** [comment]
@kevaundray we're still using the fork. I suppose we can try to revisit using chumsky again, but last time there was an issue with the parser recovery from it.

**Comment by jfecher** [comment]
According to https://github.com/zesterer/chumsky/releases it looks like the first alpha version for the zero-copy update of chumsky released March 2nd. Instead of migrating over to 0.9.0 now, I think we should wait until 1.0.0 is eventually finalized and released since it sounds like it'll come with many new features, performance improvements, and changes.
