### ISSUE TITLE
Consider making ABI non-optional on `CompiledProgram`

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#855]
# Problem

In order to access the ABI for a compiled program we need to use `compiled_program.abi.as_ref().unwrap().clone()` which is pretty verbose considering how often we need it.
# Solution

We don't seem to be making use of the optionality of this field (as shown by all the unwrapping we do) and considering that there's never a situation in which a `CompiledProgram` doesn't have an ABI, we should just make it a required field on the struct. We'd then be able to remove the `.as_ref().unwrap()`.

# Alternatives considered

# Additional context

**Comment by kevaundray** [comment]
This was an oversight on my part, as I thought we could compile libraries into circuits which would then facilitate us not having an Abi
