### ISSUE TITLE
Tracking issue: Adding noir stdlib to npm

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#859]
# Problem

Currently to compile noir code in the browser using the stdlib, you need to bring a copy of the stdlib and add it to the dependency graph. This is what nargo is doing.
 
# Solution

I was looking at grain and they allow you to install the grain stdlib from npm. This seems like a possible solution for us also, where we publish the stdlib on every new noir version to keep it in sync.

See here: https://github.com/grain-lang/grain/tree/main/stdlib#installation

# Alternatives considered

# Additional context

**Comment by kevaundray** [comment]
One disadvantage/deal breaker that Blaine mentioned was that it is easy to then have the compiler version and the stdlib be out of sync, since one does not need to update the npm package.

**Comment by TomAFrench** [comment]
This isn't needed after #973
