### ISSUE TITLE
Cannot index array coming out of pedersen hash

### ISSUE THREAD

**Issue by signorecello** [noir-lang/noir#864]
# Description

## Aim

Tried to run a simple program:

```

use dep::std;

fn main(coords : [Field; 2], solutionHash : pub Field) {
    constrain std::hash::pedersen(coords)[0] == solutionHash;
}
```

## Expected behavior

It should be compiled by `@noir-lang/noir_wasm` npm lib

## Bug

I get

```
panicked at 'not yet implemented: Array indexing with an lhs of 'Call(HirCallExpression { func_id: FuncId(Index { index: 6, generation: 0 }), arguments: [ExprId(Index { index: 31, generation: 0 })] })' is unimplemented, you must use an expression in the form `identifier[expression]` for now.', crates/noirc_evaluator/src/ssa/code_gen.rs:640:30
```

# To reproduce

Run the code using any ts script like:

```
import { compile, acir_to_bytes } from '@noir-lang/noir_wasm';    
const compiled = compile(
      resolve(__dirname, `../src/main.nr`)
  );
```

# Environment

- [ x] Using TypeScript:

  - @noir-lang/noir_wasm: 0.10.0
  - @noir-lang/barretenberg: 2.19.0

# Additional context

Program worked by putting the result on a var and indexing that var:

```
use dep::std;

fn main(coords : [Field; 2], solutionHash : pub Field) {
    let hash = std::hash::pedersen(coords);
    constrain hash[0] == solutionHash;
}

```

**Comment by phated** [comment]
The `@noir-lang/noir_wasm` you were using was the wrong version. I've just fixed the publishing now. You'll want to use https://www.npmjs.com/package/@noir-lang/noir_wasm/v/0.2.0-ca986a4 if you are using v0.2.0 of Noir. We're also looking into changes that happened for `@noir-lang/barretenberg` since those probably also require publishing.

**Comment by kevaundray** [comment]
Closing as this seems to be fixed. Feel free to re-open if this issue occurs again!
