### ISSUE TITLE
feat(cli): limit output for nargo prove

### ISSUE THREAD

**Issue by cheethas** [noir-lang/noir#873]
# Problem

I've thought about building a foundry library for noir that uses ffi calls to read proof outputs, passing them to a smart contract verifier. Currently such a workflow is a bit tricky as the proof includes "Proof Successfully Created".  

# Solution
Add a cli flag that will output the hex string proof output directly to stdout, without extra output. Possibly named `-s` | `--silent`?
```bash
nargo prove -s | --silent
```
# Additional context

N/A

**Comment by kevaundray** [comment]
This is an interesting usecase. 

I guess right now you are piping the output and editting out the extra fluff with something like `sed` ?

Re your suggestion, I'd like to hear what @TomAFrench thinks about it

**Comment by TomAFrench** [comment]
Initial thoughts are that if we're going down that route then it would be better in the longer-term to define a general machine readable output, e.g. https://rust-cli.github.io/book/in-depth/machine-communication.html

**Comment by jfecher** [comment]
Instead of using `nargo prove`, would it be easier to save the proof to a file so that you can ignore all of nargo's output?

```sh
nargo prove p >/dev/null
my_proof=`cat proofs/p.proof`
```

**Comment by cheethas** [comment]
> Instead of using `nargo prove`, would it be easier to save the proof to a file so that you can ignore all of nargo's output?
> 
> ```shell
> nargo prove p >/dev/null
> my_proof=`cat proofs/p.proof`
> ```

This is what I have been doing, however I'd like to avoid IO operations.

**Comment by jfecher** [comment]
Going forward, I think silent by default would actually be a better option. It follows the unix philosophy of "no news is good news," and matches better with the behavior of other compilers.
