### ISSUE TITLE
`acir_from_bytes` result does not work with `setup_generic_prover_and_verifier`

### ISSUE THREAD

**Issue by siosw** [noir-lang/noir#888]
# Description

## Aim

I would like to use the TS bindings to load the acir of my compiled proof and create a prover and verifier.

## Expected behavior

I expect this code to successfully setup the prover and verifier.

```
const acirByteArray = path_to_uint8array(resolve(__dirname, '../circuits/target/p.acir'));
const acir = acir_from_bytes(acirByteArray);
const [prover, verifier] = await setup_generic_prover_and_verifier(acir);
```

## Bug

The `acir` object returned by `acir_from_bytes(acirByteArray)` does not include the field `gates`.
Terminal output:
```
panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `gates`", line: 1, column: 1189)', src/lib.rs:81:28
```

# To reproduce

This [repo](https://github.com/siosw/noir-ts-acir-bug) contains a minimal example of the bug. To reproduce it run `npm test`.

# Environment

- [x] Using `nargo`:

  - [x] Binary: `nargo 0.2.0 (git version hash: 5186ab97a0fc087413f6d217b87c77f693c574ac, is dirty: false)`

- [x] Using TypeScript:

  - @noir-lang/noir_wasm: `0.2.0-ca986a4`
  - @noir-lang/barretenberg: `2.19.0`
  - @noir-lang/aztec_backend: `0.9.0-287d42d`

**Comment by siosw** [comment]
I was able to get this to work with this `acir = { ...acir, gates: acir.opcodes };` 
and downgrading to `nargo 0.1.0 (git:126ca26a)`

As far as I understand gates were renamed to opcodes (https://github.com/noir-lang/noir/issues/536)

However I'm not sure if this has unintended side effects.

**Comment by vezenovm** [comment]
This is due to an outdated aztec_backend dependency. We recently just fixed some discrepancies between the packages, however, they have not been pushed to npm yet. Could you try using the dependencies under this project's package.json: https://github.com/noir-lang/noir-cra?

**Comment by siosw** [comment]
Thanks for helping with this.

I was able to compile + verify the proof from a TS script using these versions:
```
"@noir-lang/aztec_backend": "github:kobyhallx/aztec-backend#1bcdd4bf67dad1ab977867f1d655bcab7085a518",
"@noir-lang/barretenberg": "github:noir-lang/barretenberg#39a1547875f941ef6640217a42d8f34972425c97",
"@noir-lang/noir_wasm": "0.2.0-ca986a4"
```

Unfortunately the compilation fails when I'm trying to make use of the stdlib.
```
panicked at 'error reporter: could not find crate std', crates/noirc_frontend/src/hir/resolution/import.rs:163:28
```

Loading an `acir` from a TS script fails with:
```
panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: "corrupt deflate stream" }', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/acir-0.4.1/src/circuit/mod.rs:35:9
```
It's compiled with `nargo 0.2.0 (git version hash: e51ff01b426c7f91422a53e691b6aaf9bb4b4a86, is dirty: false)`

All of the circuits I tested this with compile and verify correctly using the `nargo` CLI.

Do you have a suggestion what my next steps should be here?

**Comment by kobyhallx** [comment]
@siosw Thanks for the detailed report. JavaScript packages currently do not allow stdlib or any other "non-local" dependency. Basic support for it should land early next week.

**Comment by kobyhallx** [comment]
Closing as outdated
