### ISSUE TITLE
Save Noir ABI to disk

### ISSUE THREAD

**Issue by joss-aztec** [noir-lang/noir#897]
# Problem

It is not convenient to arrange the initial witness for a precompiled ACIR. At present, the Noir ABI is recompiled from source and held in memory for all nargo commands that require it.

# Solution

Save the Noir ABI to disk when compiling from source, such that it can be used as a resource in a dApp. (Whether it is saved as a separate resource or incorporated into another is up for discussion.)

# Alternatives considered

None, access to the Noir ABI is a must have for any sort of e2e system.

**Comment by TomAFrench** [comment]
Following discussion in slack, this will be bundled along with the acir.
