### ISSUE TITLE
Unusually long padding of vector output of `to_le_bytes`.

### ISSUE THREAD

**Issue by Ethan-000** [noir-lang/noir#916]
# Description

Unusually long padding of vector output of `to_le_bytes`.

## Expected behavior

I'm not sure if this is intended or a bug. I think the expected length of the `output vector` should be `31` or as specified, but its`254` at the moment.

## Bug

# To reproduce

see [here](https://github.com/Ethan-000/unusally_long_padding)

# Environment

- [x] Using `nargo`:

  - [ ] Binary: 
  - [x] Compiled from source: 

- [ ] Using TypeScript:

  - @noir-lang/noir_wasm: 
  - @noir-lang/barretenberg: 
  - @noir-lang/aztec_backend: 

# Additional context

**Comment by kevaundray** [comment]
@Ethan-000 is this still an issue?

**Comment by kevaundray** [comment]
@guipublic assigning this issue to you

**Comment by kevaundray** [comment]
As a side-task in this issue, I think we should document `to_be_bytes` and to_le_bytes`, so users know what the `10` is meant to indicate.  In general, documenting the stdlib as we go along is a good idea.

**Comment by kevaundray** [comment]
@Ethan-000 re what we should do, can I leave that to you to create a rationale as to what you think is the most reasonable and non-suprising output?

**Comment by vezenovm** [comment]
Following https://github.com/noir-lang/noir/pull/2479 and https://github.com/noir-lang/noir/pull/2350 padding has been removed and we simply return the specified byte size. I believe this issue can be closed @Ethan-000 correct?
