### ISSUE TITLE
cargo crashes

### ISSUE THREAD

**Issue by jordan-public** [noir-lang/noir#929]
# Description

nargo crashes on "prove" command

## Aim

I tried to create a hello_world proof with nargo

## Expected behavior

nargo prove p 
is supposed to create a proof

## Bug

cargo crashes on "nargo prove"
# To reproduce

jordan@a20 aztec % nargo -V 
nargo 0.2.0 (git version hash: c7303294763c485644ebaa87e81aaab567995283, is dirty: false)
jordan@a20 aztec % nargo new hello_world
Project successfully created! Binary located at /Users/jordan/Downloads/aztec/hello_world
jordan@a20 aztec % cd hello_world 
jordan@a20 hello_world % nargo check
Constraint system successfully built!
jordan@a20 hello_world % vi Prover.toml 

# Here I edit: 
# x = "1" 
# y = "2"

jordan@a20 hello_world % nargo prove p

Downloading the Ignite SRS (340MB)

[00:04:59] ######################################## 322560348/322560348 
Downloaded the SRS successfully!
Time Elapsed: 4 minutes

SRS is located at : "/Users/jordan/noir_cache/ignition/transcript00.dat"
The application panicked (crashed).
Message:  range end index 322560156 out of range for slice of length 94011429
Location: /Users/jordan/.cargo/git/checkouts/aztec_backend-a697fb631cbad807/74b4d8d/common/src/crs.rs:37

This is a bug. Consider opening an issue at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.md
jordan@a20 hello_world % 

# Environment

jordan@a20 hello_world % uname -a
Darwin a20.local 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103 arm64

# Additional context

I tried with the binary install from the instructions as well as by rebuilding nargo for WASM. Both crash.

**Comment by TomAFrench** [comment]
Closing this as a duplicate
