### ISSUE TITLE
Nested structs in return value crash the compiler

### ISSUE THREAD

**Issue by sirasistant** [noir-lang/noir#942]
### Aim

Tried to make a proof in a circuit that returns a nested struct

### Expected behavior

It expected that the prover would be able to generate the proof 

### Bug

When running `nargo prove test` i get:
```console
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: crates/noirc_abi/src/lib.rs:354
```

### To reproduce

Using this circuit:
```rust
struct Inner {
    bar: Field,
}

struct Outer {
    arr: [Field; 1],
    inner: Inner,
}

fn main(foo: Field) -> pub Outer {
    let inner = Inner {
        bar: foo + 1,
    };

    let outer = Outer {
        arr: [foo + 2],
        inner,
    };

    outer
}
```

with this Prover.toml
```toml
foo = "2"
```

### Installation method

Compiled from source

### Nargo version

ba947a7c22720d90676422f9c29bd55f047e9edb

### Additional context

Using nested structs in arguments does work

**Comment by TomAFrench** [comment]
@sirasistant I'm closing this issue as this is fixed in nargo 0.4.0. Feel free to reopen if you're still running into this issue on that release.
