### ISSUE TITLE
Rename `nargo contract` command

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#945]
As we add Noir contracts, there's going to become confusion around the `nargo contract` command. Does it create a solidity verifier contract or does it do something else related to noir contracts?

We should then update the name to avoid any confusion. One option is:

> `nargo generate-verifier --solidity` perhaps? We could then extend it to other languages, etc.

_Originally posted by @TomAFrench in https://github.com/noir-lang/noir/issues/944#issuecomment-1454160836_

**Comment by kevaundray** [comment]
Think we want to get this in quite quickly as its an annoying breaking change that is in a lot of places. 

```sh
$ nargo generate-verifier --solidity
```

@noir-lang/tooling what do you think about the above change? Any suggestions for something better?

**Comment by joss-aztec** [comment]
I like your suggestion
