### ISSUE TITLE
Revisit usage of noirpacker.py

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#951]
### Problem

In the past, we had the problem of the noir-wasm not being able to read multiple files in the browser without a file-read host function. 

A file-read host function was then added, however we also desired the stdlib to be added automatically without the file-read host function. Since the stdlib spanned multiple files, this was not possible and so Jake created noirpacker which allowed us to pack the stdlib into one file by inlining each module declaration.

This functionality is actually still quite useful and is close to what javascript minify does.

This issue is left as a tracker to decide on whether we still need it for the original problem. 

CC @Ko

### Proposed solution

A solution would detail a narrative on how the stdlib will be loaded in the browser.

### Additional context

We can also bring it back for the web context in the future, so that users can minify their source code. We would need t add compression and whitespace removal etc

**Comment by TomAFrench** [comment]
Looks like this isn't necessary after #973. I'd say that we can delete it for now and resurrect it for the minifier usecase down the line if we need it.
