### ISSUE TITLE
"The application panicked (crashed)."

### ISSUE THREAD

**Issue by AleksanderMisztal** [noir-lang/noir#969]
While running `nargo prove` I got 

The application panicked (crashed).
Message:  assertion failed: `(left == right)`
  left: `1`,
 right: `0`
Location: crates/noirc_frontend/src/hir_def/types.rs:114

This is a bug. Consider opening an issue at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.md

Reproduction here https://github.com/AleksanderMisztal/noir-experiments/commit/9952b5ee402c503468340487f0e5309e9631c501

**Comment by AleksanderMisztal** [comment]
Another one:

The application panicked (crashed).
Message:  no entry found for key
Location: crates/noirc_abi/src/input_parser/toml.rs:26

This is a bug. Consider opening an issue at https://github.com/noir-lang/noir/issues/new?labels=bug&template=bug_report.md

Reproduction: https://github.com/AleksanderMisztal/noir-experiments/commit/f2178d501102dcf815ac8d5a7d671e48af832dc8

**Comment by jfecher** [comment]
Looking at the first examples real quick, I think the error is from this line:
```rs
impl DensePolynomial {
```
Which should be
```rs
impl<N> DensePolynomial<N> {
```
Since DensePolynomial is a generic type.

I'll work on verifying this is the actual error and adding a real error message for this if so, instead of crashing the compiler.

**Comment by TomAFrench** [comment]
The second issue is due to you having an entry in your `Prover.toml` which doesn't exist in the ABI for your program. I'll add a better error message for this.

**Comment by TomAFrench** [comment]
Closing this as we've added proper error types rather than panicking for these errors.
