### ISSUE TITLE
`publish-wasm` job fails due to insufficient permissions

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#979]
### Aim

This happened during performing the 0.3.0 Noir release.

### Expected behavior

The `publish-wasm` job should succeed and link the new commit in `noir-lang/noir_wasm` to the commit of the release.

### Bug

The job fails due to `Resource not accessible by personal access token`.

https://github.com/noir-lang/noir/actions/runs/4408358082/jobs/7723270706

### Installation method

None

**Comment by kevaundray** [comment]
Modified permissions and re-ran the job, so this should now be fixed. The issue was that the token was scoped to only noir-lang and noirup.

See [here](https://github.com/noir-lang/noir/actions/runs/4408358082/jobs/7725724347) for job succeeding
