### ISSUE TITLE
Add tests to check that fs loader functions will recover values saved by writers

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#995]
### Problem

We recently had an issue where the function to save an ACIR checksum was using a different extension to the function which was reading this when loading the circuit's keys: https://github.com/noir-lang/noir/issues/993

This is all easily testable so there's no excuse for not checking that these functions work together as expected (this was part of the original reasoning between factoring these into the `fs` module in the first place).

### Proposed solution

We should add unit tests for each function to check that if a value is written to file then it will be successfully read again by the appropriate function if we pass the correct arguments into it. For an example of this see https://github.com/noir-lang/noir/pull/994

**Comment by kevaundray** [comment]
@TomAFrench What is the status of this issue?

**Comment by TomAFrench** [comment]
This is not really an issue now that we have a single artifact for circuits.
